### ISSUE TITLE
Prerender service returns blank page

### ISSUE THREAD

**Issue by junajan** [prerender/prerender#106]
I have tried our app directly on your service and it runs great:
http://service.prerender.io/https://hearth-net-topmonks-staging.herokuapp.com/app/?_escaped_fragment_=/ad/537c4deda5a5570200000e4d

but when I call your service through ruby middleware on address:
https://hearth-net-topmonks-staging.herokuapp.com/app/?_escaped_fragment_=/ad/537c4deda5a5570200000e4d

it will end after 10 seconds with blank page:
<html><head></head><body></body></html>

I tried it also on local prerender server and there were same URLs to render in console.
Maybe some static assets may cause problem while fetching page?

**Comment by Ditchou** [comment]
Hello,

I am getting the same issue. Any help for that?

**Comment by junajan** [comment]
For us, the error was (as @thoop said) because of RoR server which was using only one thread so it ended in deadlock (client requested page on ruby, ruby made request to prerender and prerender made request back to ruby to scrape the page, but it was already waiting for prerender's result so it timeouted every time) 

We used nginx proxy to handle request from robots and transfer it to prerender and it works fine.. Or you can use some service like DivShot to host your frontend app - it has already prerender support in it.

**Comment by Ditchou** [comment]
Ok, but I also tried with unicorn and it does not work, always white page but without any error.

**Comment by thoop** [comment]
How many threads did you use with Unicorn? Do you have a public URL that I can test and make sure PhantomJS isn't crashing? Feel free to email me at todd@prerender.io

**Comment by christianseptimo** [comment]
We are experiencing this but in wordpress site. Do you have any thoughts about why am I experiencing this on wordpress?

**Comment by christianseptimo** [comment]
Found the issue, we are using intercom plugin and that's where the conflict is. Do you have any suggestion how can I fix this? Do we have to get rid on that plugin?

**Comment by thoop** [comment]
Shouldn't have any issues with intercom. Feel free to create a new issue with some more information so we can look into it. Thanks!
