### ISSUE TITLE
fetch and render in google webmaster tools not working

### ISSUE THREAD

**Issue by raviada** [prerender/prerender#120]
I implemented prerender node on one our ec2 instances and configured our `nginx` middleware to route the pages with `<meta name="fragment" content="!">` in the header. Everything is working fine, I am able to see `?_escaped_fragment_=` appended to all URLs with googlebot useragent. I can also view both backbone app and html in the browser when I view the pretty and ugly URLs in the browser.

But the problem is when I fetched and rendered the site in webmaster tools, I see the following error messages. It is also not consistent, sometimes complains about images, sometimes css and other times js files. I really want to know how googlebot is fetching these pages. Apparently it was finding the inner links and started crawling the links now, before it was not even doing that because all the links were not even visible to bots. 

![2014-10-05_1523](https://cloud.githubusercontent.com/assets/819292/4519889/30e17b2a-4ccf-11e4-844a-626da69ff11e.png)

**Comment by huevoncito** [comment]
I'm having a different issue but it falls under the same heading. When I fetch a patch using `_escaped_fragment_=`, it hits my prerender server and works perfectly. (Thanks, BTW! ) However when I try to do a fetch and render from the Google search console, I get a different result. The request doesn't seem to be hitting my prerender server at all. Any ideas?

**Comment by thoop** [comment]
When you do the fetch and render, are you also using a URL with the `_escaped_fragment_` query parameter? If you are, it shouldn't be any different.

**Comment by huevoncito** [comment]
Hey there. I'm not using the query param. My understanding was that the crawler adds this but it seems I may be mistaken. Are you saying that asking Google to index _escaped_fragment_ is no different to having it index the "normal" url? If so then I think we're good.

Thanks, Todd.
db

**Comment by thoop** [comment]
The crawlers do access the `_escaped_fragment_` URLs, but Fetch as Google has a bug where they don't. So you have to manually enter the `?_escaped_fragment_=` query parameter when using Fetch as Google, but the normal Googlebot does not have that issue.

**Comment by huevoncito** [comment]
@thoop That makes sense. This can probably be closed. Thanks for your help.

**Comment by arjunmat** [comment]
Adding `googlebot` to the nginx prerender script solved this for me.

`if ($http_user_agent ~* "googlebot|facebot|redditbot|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator|bingbot|msnbot|BingPreview|slurp|duckduckbot|YandexBot") {
                    set $prerender 1;
            }`
