### ISSUE TITLE
Intercept requests for domains we don't want

### ISSUE THREAD

**Issue by ernestoalejo** [prerender/prerender#130]
I would like to stop prerender from loading things from Google Maps and some widgets from several domains. There is anyway to add custom hosts to this list?

https://github.com/prerender/prerender/blob/master/lib/server.js#L187

**Comment by jshado1** [comment]
Bump

We're running our own server and would like to be able to add to this list, preferably by reading from a conf.js file of our own so the lib itself doesn't have to be modified. (Disqus' js is very slow and crashing Phantom about 80% of the time)

**Comment by thoop** [comment]
Some discussion is currently happening on #154 

If everything looks good there, we should have this functionality soon.

**Comment by jshado1** [comment]
w00t, thanks!

**Comment by thoop** [comment]
merged a while back. closing this issue.
