### ISSUE TITLE
(possible issue) window.prerenderReady

### ISSUE THREAD

**Issue by Student007** [prerender/prerender#138]
## Problem:
Using `window.prerenderReady = false;` doesn't force to wait for caching. 

## System-Logic:
I use two instances of express, one on port 80 and one on 3000 
The 80 is what should be cached and delivers an index.html.
The mainController is using a factury what is asking the instance 3000 using a different route for a JSON response. Instance 3000 then is asking a CORS allowed webservice and get the value. The factury has a timeout of 5 sec. When this response is noticed I set the `window.prerenderReady = true;` (yes: I checked the value is false)
I would expect to get a cached version of the existing page after setting `window.prerenderReady = true;`
Also tried to put the `window.prerenderReady = false;` outside/inside the document.ready area.

## Wrong behavior:
I got a plain `<html></html>` also with all angular controlled {{title}} {{description}} within `<head></head>` what works fine by calling the normal way by browser. I use prerender.io to cache.

## other possibilities (mistakes because of learning phase):
I am using both: `$locationProvider.hashPrefix('!');` and `$locationProvider.html5Mode(true);` within the app.config(...)

I wrote a comment to issue #30 because it seams similar. But now it looks for me like an issue (or wrong understanding - sorry if so)

**Comment by watsontom100** [comment]
I'm also having issues with this. Have emailed you @thoop
