### ISSUE TITLE
how install   prerender-phantomjs2

### ISSUE THREAD

**Issue by soitun** [prerender/prerender#148]
i have download  prerender-phantomjs2 ,when type npm install , it show 

> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-i686.tar.bz2
Saving to /home/soitun/prerender-phantomjs2/node_modules/phantomjs/phantomjs/phantomjs-2.0.0-linux-i686.tar.bz2
Receiving...
  [========================================] 100% 0.0s

Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-i686.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.5.10",
  "date": "Wed, 10 Dec 2014 01:51:24 GMT",
  "content-type": "text/html; charset=utf-8",
  "content-length": "32562",
  "connection": "keep-alive",
  "vary": "Accept-Language, Cookie",
  "x-render-time": "0.0439438819885",
  "content-language": "en",
  "etag": "\"8b793d634d70e0c5cf0f3ba4f8f2bb14\"",
  "x-request-count": "437",
  "x-served-by": "app22",
  "x-frame-options": "SAMEORIGIN",
  "x-static-version": "6580bb2d7ce5",
  "x-version": "1106bcab00f8"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs

npm ERR! phantomjs@2.0.0-0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.0.0-0 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.18-400.el5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/soitun/prerender-phantomjs2
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by dugainet** [comment]
If you compile it from source, you should package it in the same way they package phantomjs 1.9.8 and then host it somewhere yourself -> could you be more specific, I am fairly new to npm/node stuff..

**Comment by dugainet** [comment]
The link to binary version of phantomjs have been updated by some "stupid" guy. I have fixed it by : 
- open package.json, replace    
 "phantomjs": "git+something"  
by
 "phantomjs": "git+https://github.com/dugainet/phantomjs.git",
