### ISSUE TITLE
Angularjs SEO Optimization with prerender.io

### ISSUE THREAD

**Issue by geolyth** [prerender/prerender#151]
In my angularjs site I have insert prerender.io module and after testing (like prerender.io says) everything goes well.
Now I would like to know how I can index every single page generated? Is a good practise having a sitemap?
I have tested search and for me doesn't work well because in google, when I try to find my site I'm not able to see a result inside pages, I see only the main result (name of my web site).
Why this happens?

Thanks in advance

**Comment by geolyth** [comment]
Hi another time Todd, I have waited such as you say to me...now I have another problem with prerender...could you try to search in google:
1) arrray mario
2) arrray marvel

Until a few days ago only works fine (http://arrray.com/short), by now when I try to search one of them I see a URL like http://arrray.com/short/short. Why in you opinion?

Thanks in advance

**Comment by geolyth** [comment]
No help to understand why this happens?

**Comment by thoop** [comment]
Sorry about the delayed response!

I'm seeing results for both of those searches. What were you expecting to see there?

If you are seeing weird URLs like /short/short, that usually means that you have a relative link somewhere that is making the crawlers think that they can continue to add onto the URL. That's usually fixed by changing the relative URL to "/short" to have the "/" in the front to make it absolute.

Let me know how I can help.

**Comment by geolyth** [comment]
I'm apologize for my insistence, I thought my post was gone unnoticed.
Your idea is right, I use relative links. I'll fix such as you suggest changing relative to absolute path.

Waiting a few days so I tell you if it works.

Thanks you so much for your time.

**Comment by geolyth** [comment]
Thank you so much Todd, it seems go well!!! Now one of the most clicked link, http://arrray.com/XkiACb84, works very well!

**Comment by thoop** [comment]
Great! Please let me know if there's any other way I can help.

Thanks!

**Comment by ankitict** [comment]
Hello 
In my site i have inserted Prerende.io but not woking can you please check it 
site : https://www.mobintouch.com

some of it page not cached , Below is my error log file please check it 
https://pastebin.com/yc8TN11i
