### ISSUE TITLE
?_escaped_fragment_= redirecting to unknown site

### ISSUE THREAD

**Issue by dottodot** [prerender/prerender#155]
I have installed prerender on server and using the prerender-node middleware when I use ?_escaped_fragment_=  it redirects me to some site I have nothing to do with. How is this possible?

**Comment by dottodot** [comment]
The first redirect is going to shopping./com and I just downloaded all the files that have installed and found a reference to it in aws-sdk > xml2js > sax module

**Comment by thoop** [comment]
Can you send me the URL you are testing? todd@prerender.io

**Comment by dottodot** [comment]
test.boxxerworld.com/?_escaped_fragment_

**Comment by thoop** [comment]
I don't see the redirect when accessing our service directly:

```
➜  ~  curl -I http://service.prerender.io/http://test.boxxerworld.com/
HTTP/1.1 200 OK
Content-Length: 19031
Content-Type: text/html;charset=UTF-8
Date: Mon, 09 Feb 2015 16:04:47 GMT
Server: nginx/1.4.7
X-Powered-By: Express
Connection: keep-alive
```

Which middleware are you using?

**Comment by dottodot** [comment]
I'm using the express middleware setup as

```
var prerender = require('prerender-node');
prerender.set('prerenderServiceUrl', 'http://prerender.boxxerworld.com:3000');

module.exports ={
  http: {
    customMiddleware: function(app) {
      app.use(prerender);
    }
  }
};
```

but I'm wondering if it's something to do with my nginx setup as the problem goes away when not using the proxy. i.e http://test.boxxerworld.com:10002/?_escaped_fragment_=

Still baffled as to why is redirecting to random sites though.

**Comment by thoop** [comment]
Are you using nginx middleware at all? Nginx is known to cache IP addresses which is why you might be pointing at a random site. You could have cached an IP address that is no longer owned by the Prerender server. See the resolver part of our official nginx config: https://gist.github.com/thoop/8165802

**Comment by thoop** [comment]
I also think that's the problem with your other issue as well (https://github.com/prerender/prerender-node/issues/60)

**Comment by dottodot** [comment]
It was due to the JXCore plesk extension for nginx that I'm using and the upstream conf it uses, as per this issue.

https://github.com/Nubisa/jxdocs/issues/172#issuecomment-73547692
