### ISSUE TITLE
Posting to Facebook requires posting twice

### ISSUE THREAD

**Issue by dottodot** [prerender/prerender#156]
On my site have it set up so that when a piece of content is added or updated it makes a request to generate the cache in prerender which works fine. When i then go to paste the link on Facebook is shows all the information apart from the image. If I then refresh Facebook and post the link again it display everything including the image.

I've included below screenshots of the first post the the second attempt.

Not sure that giving you links is going to help in this scenario.

![screen shot 2015-02-10 at 21 15 51](https://cloud.githubusercontent.com/assets/811652/6136643/5d4ed2d4-b16a-11e4-84d2-054ca0cc70e1.png)

![screen shot 2015-02-10 at 21 18 14](https://cloud.githubusercontent.com/assets/811652/6136648/61d6a8ea-b16a-11e4-8f93-8b6ad388ab80.png)

**Comment by vkartaviy** [comment]
I have the same issue, do you think that is prerender related? Because event if you post without loaded image it will be shown in your feed as well but not in dialog.

**Comment by dottodot** [comment]
I've only come across this issue while using prerender, so can only assume it has something to do with it. Never had any problem with non javascript sites.

**Comment by thoop** [comment]
Does it only happen with new URLs? I'll look into it. Thanks for letting me know!

**Comment by dottodot** [comment]
Yes it's the first time URL is posted on Facebook, but the link has already been cached. After the second attempt displays the image it will aways show on Facebook correctly.

**Comment by gytisgreitai** [comment]
I'm having exatly same issue.. need to post twice to make it work.

**Comment by gytisgreitai** [comment]
Well, this is not a Prerender problem. See FB bug: https://developers.facebook.com/bugs/657696104321030/

We've added og:image:width and og:image:height and it shows the image instantly.

**Comment by thoop** [comment]
Interesting. @dottodot and @vkartaviy

**Comment by dottodot** [comment]
Yes it's seems to work, thanks for that.

**Comment by dasAnderl** [comment]
i think its not a prerender issue, since its working fine with google sharing.
