### ISSUE TITLE
TypeError: pid must be a number

### ISSUE THREAD

**Issue by tuhoojabotti** [prerender/prerender#157]
I'm getting this error after updating to the latest version:

```
prerender-3 (err): /srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:42
prerender-3 (err):         if (err.code !== 'ESRCH') throw err;
prerender-3 (err):                                         ^
prerender-3 (err): TypeError: pid must be a number
prerender-3 (err):     at process.kill (node.js:637:15)
prerender-3 (err):     at killPid (/srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:39:17)
prerender-3 (err):     at /srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:31:13
prerender-3 (err):     at Array.forEach (native)
prerender-3 (err):     at killAll (/srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:23:23)
prerender-3 (err):     at /srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:16:13
prerender-3 (err):     at ChildProcess.<anonymous> (/srv/www/prerender/node_modules/prerender/node_modules/tree-kill/index.js:60:17)
prerender-3 (err):     at ChildProcess.<anonymous> (/srv/www/prerender/node_modules/prerender/node_modules/tree-kill/node_modules/once/once.js:17:15)
prerender-3 (err):     at ChildProcess.emit (events.js:110:17)
prerender-3 (err):     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
```

**Comment by tuhoojabotti** [comment]
After debugging, it seems to be an issue with tree-kill. I don't know why, but it gets some pid as a strings while some are numbers. I added type coercion to number and it works now. I will post an issue to the tree-kill repo.

**Comment by thoop** [comment]
Hmm interesting. Were you seeing it every time? Or only once in a while?

What version of node are you on? Just curious in case this crops up again.

Thanks!

**Comment by tuhoojabotti** [comment]
@thoop It happens every time, as you can see from the PR https://github.com/pkrumins/node-tree-kill/pull/4 it is caused by error in the tree-kill code, not in Node.

I'm using Node v0.11.14, I guess they added a check to make sure that process.kill pid is a number, which caused this error to crop up.

**Comment by thoop** [comment]
Ah interesting. Yeah we haven't upgraded to the latest stable version of node yet (0.12)

**Comment by tuhoojabotti** [comment]
It has been a month since I submitted a PR and the repo does not seem active so I'm re-opening this issue because I feel that node-tree-kill is not a good dependency.

**Comment by thoop** [comment]
Can you upgrade to node 0.12.0 and see if this is still an issue? We currently support the previous stable version of node and haven't tried upgrading past version 0.10.31

**Comment by tuhoojabotti** [comment]
I will try to find time to upgrade it. I study full time and work part time so there's always something more important to do. I will update when I have tried it.

**Comment by thoop** [comment]
I totally understand! Have you tried pinging the tree-kill team again? Using that did seem to alleviate our problems with PhantomJS hanging around after it should. Maybe we can find a more elegant way to kill PhantomJS and then call worker.kill() than we were before.

**Comment by tuhoojabotti** [comment]
@thoop This module might be a good replacement for tree-kill, https://github.com/indexzero/ps-tree it doesn't offer a kill function, but the readme displays how to use it to kill a process tree.

**Comment by thoop** [comment]
Interesting. Thanks!

**Comment by wmhilton** [comment]
@tuhoojabotti Funny. So I tested process.kill() in 0.10.x and 0.12.x and could not reproduce it. It accepts a string PID without issue. But in 0.11.14 this error happens. In 0.11.16, again, accepts string without complaining. How unfortunate and bizarre.

As node-tree-kill's new co-maintainer, I think I will add this coercion, simply because I would hate a future change in Node or iojs to break this module again.

**Comment by thoop** [comment]
Thanks @wmhilton  :)

**Comment by thoop** [comment]
Shouldn't be a problem in our latest version of Prerender (v4.0.3). Feel free to reopen if you run into the same issue.
