### ISSUE TITLE
Bind prerender server on 0.0.0.0 using an ENV variable

### ISSUE THREAD

**Issue by mrgamer** [prerender/prerender#164]
Seems to me a good precaution against port sniffers, to let _backend servers_ (the ones that are somewhat protected by a _frontend_ one, like nginx) be bound to `0.0.0.0`, so they only listen to localhost.

It could be done simply adding `process.env.NODE_HOSTNAME || 127.0.0.1` in [the `.listen()` call](https://github.com/prerender/prerender/blob/master/lib/index.js#L38-L40)
Is that an use-case you are interested to?

**Comment by thoop** [comment]
Yeah that seems like a nice addition. Want to send a pull request?

**Comment by thoop** [comment]
Merged. Thanks!
