### ISSUE TITLE
angularjs prerender wont snapshot the url after hashbang?

### ISSUE THREAD

**Issue by em0xi0nx** [prerender/prerender#166]
im currently working on a project and this is my first time using angularjs and i think its pretty powerful but there's a problem. 
**SEO** problem. When i first use Angular i didn't know that its not visible to **SEARCH ENGINES**.

Right now im hosting my own Prerender Service. but whenever i request for a url after a #! 

http-:// -->> http://  ------ because i have limited links

http-://prerender.host.com/http-://host.com/#!/

something it always renders the http-://host.com/ route and not the http-://host.com/#!/something.

please help me!! i dont really know whats happening. i also tried html5mode with a fragment meta but still the same. 

**SETUP**
**HASHBANG**

> http-://host.com/#!/

**ROUTES**

i do have hashprefix and explicitly turning off html5mode knowing its off by default. --- i thought it was the problem :))

    $routeProvider
        .when('/', {
            templateUrl: '../views/tutorials.html',
            controller: 'TutorialController',

        })
        .when('/tutorial/:id', {
            templateUrl: '../views/tutorial_detail.html',
            controller: 'TutorialDetailController',

        })
        .when('/add-tutorial', {
            templateUrl: '../views/tutorial_add.html',
            controller: 'TutorialAddController',

        })

    .otherwise('/');
    $locationProvider.hashPrefix('!');
    $locationProvider.html5Mode(false);

**APACHE**

im using the settings from prerender apache guide.

    <IfModule mod_rewrite.c>
    RewriteEngine On

    <IfModule mod_proxy_http.c>
        # Enable prerendering for .html and directory index files
        RewriteCond %{HTTP_USER_AGENT} Googlebot|bingbot|Googlebot-Mobile|Baiduspider|Yahoo|YahooSeeker [NC,OR]
        RewriteCond %{QUERY_STRING} _escaped_fragment_
        RewriteRule ^ http://prerender.em0xi0nx.com/http://tutorial.em0xi0nx.com/%{REQUEST_URI} [P,L]
    </IfModule>
    </IfModule>

Do i need to do something else or is there anything wrong with my setup?? i've figuring out this for 3 days and now i really need help.

any suggestions?? i really need to finish this for our defense.

**Comment by aymone** [comment]
```
angular.module('myApp', [])
.config(['$location', function($location) {
  $location.hashPrefix('!');
}]);
```

Other tips...
http://www.ng-newsletter.com/posts/serious-angular-seo.html

**Comment by thoop** [comment]
Anything after the hash is not sent to the server so you should use the `_escaped_fragment_` protocol like this:

`http://prerender.host.com/http://host.com/?_escaped_fragment_=/something`

The Prerender middleware will detect the escaped fragment parameter and route it to the Prerender server. The Prerender server will then transform that URL back to the hash bang URL and request it from your site like `http://host.com/#!/something`

Let me know if that doesn't work when you try it. Feel free to email me at todd@prerender.io if you want to give me the link you're testing.

**Comment by em0xi0nx** [comment]
@aymone  I have that set on my config and its $locationProvider.hashPrefix('!')

@thoop yes i try it like that but it seems its still not working.. its just returning http://host.com/#!/   contents

**Comment by thoop** [comment]
What URL are you trying to access? What is the real address for host.com/#!/ ? Feel free to email me if you want to keep it private, but I'll need that to test why it would only be returning the homepage. todd@prerender.io

**Comment by paislee** [comment]
I'm having this same issue with my site http://backstory.io.

The escaped_fragment version of a URL returns the correct page when sent directly to my private prerender server. For example http://private.prerender.io/http://backstory.io/?_escaped_fragment_=/name/a3b8f9fb-3c3e-45a4-80e3-1aa65e6bc797

But if I send the hash bang version, http://private.prerender.io/http://backstory.io/#!/name/a3b8f9fb-3c3e-45a4-80e3-1aa65e6bc797, it returns the homepage.

I am sending these directly to the prerender service via the web browser, so I'm downstream of my nginx middleware. Does the prerender service itself rewrite hash bang requests? @thoop @em0xi0nx did you learn anything?

**Comment by thoop** [comment]
Anything after the # isn't sent to the server from your browser so that's why you're just seeing the homepage. You have to send the escaped fragment URL to the prerender server and the prerender server will translate it to the #! for you.

**Comment by paislee** [comment]
@thoop ok I see. I'm primarily interested in being able to embed my links in apps like Twitter, FB that can read the meta tags. So I'm pretty much relying on them to send the actual complete URL or use escaped_fragment when their bot makes the request?

**Comment by thoop** [comment]
If you share a URL with the hashbang on twitter, what URL makes it to your Prerender server after going through your nginx middleware?

**Comment by dalelotts** [comment]
My girlfriend just read the above reply from @thoop and she said it's Jabberwocky!  LOL - you should have heard her (try to) pronounce the words and then rant about how it makes no sense!  Made my day!

**Comment by thoop** [comment]
:)

**Comment by verishal** [comment]
when i hit url:
http://example.com/?_escaped_fragment_=
but
only In https request time not working .
https://example.com/?_escaped_fragment_=

that time page is not render. how can resolve this issue.
please help

my .htacesss file
RewriteEngine On
RewriteCond %{HTTPS} !=on

RewriteRule ^(.)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# Tried for SSR -Verishal
Options +FollowSymLinks
RewriteCond %{REQUEST_URI} ^/$
RewriteCond %{QUERY_STRING} ^escaped_fragment=/?(.)$
#RewriteCond %{QUERY_STRING} escaped_fragment=/([^&])
RewriteRule ^/(.) http://example.com:9090/$1 [R,L]
ProxyPassReverse / http://example.com:9090/
Options Indexes FollowSymLinks MultiViews

Production envirment url:
phantomjs --disk-cache=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /opt/bitnami/apache-tomcat/staging/ROOT/js/angular-seo-server.js 9090 https://example..com/

**Comment by thoop** [comment]
I'm not sure if PhantomJS might just have trouble with your javascript, or what angular-seo-server.js is. So I'm not sure if you're even using Prerender there. Please create a new issue if you end up using Prerender and still have trouble.
