### ISSUE TITLE
"Connection reset by peer" error

### ISSUE THREAD

**Issue by theking-laptop** [prerender/prerender#167]
I wrote a dummy plugin as a cache manager instead of `inMemoryHtmlCache` like this:

```
// lib/plugins/myCache.js

module.exports = {
    beforePhantomRequest: function(req, res, next) {
        res.send(200, 'result');
    },

    afterPhantomRequest: function(req, res, next) {
        next();
    }
};
```

```
// server.js

...
server.use(prerender.myCache());
...
```

I thought prerender runs very fast in that case and I test in normal browser with correct URL, the result is returned in 1ms (very fast). Then I benchmark it using ab and siege, but both of them raise `Connection reset by peer` error.

```
ab -t 5 "http://localhost:3000/URL"

...
Benchmarking localhost (be patient)
apr_socket_recv: Connection reset by peer (104)
Total of 59 requests completed
```

```
siege "http://localhost:3000/URL" -b -c 10 -t 5s

...
[error] socket: read error Connection reset by peer sock.c:460: Connection reset by peer
...

Lifting the server siege...      done.
Transactions:		         339 hits
Availability:		       82.28 %
Elapsed time:		        4.28 secs
Data transferred:	        0.01 MB
Response time:		        0.10 secs
Transaction rate:	       79.21 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        8.20
Successful transactions:         339
Failed transactions:	          73
Longest transaction:	        0.30
Shortest transaction:	        0.00
```

Error and low performance. Can you recheck this issue? Thanks!

**Comment by gokceyalcin** [comment]
I think it's mainly related to the NUM_ITERATIONS https://github.com/prerender/prerender/blob/master/lib/server.js

for a temporary solution, I increased NUM_ITERATIONS then put multiple prerender instances behind a load balancer so I could let one server restart while others can keep serving htmls.

**Comment by theking-laptop** [comment]
@gokceyalcin I increased NUM_ITERATIONS but no improvement.
```
export NUM_ITERATIONS=1000
node server.js
```

Output is the same.

**Comment by theking-laptop** [comment]
@gokceyalcin Aha, I increased `PHANTOM_WORKER_ITERATIONS` and the performance is great. Thanks for your advise.

**Comment by thoop** [comment]
Interesting. Thanks @gokceyalcin!
