### ISSUE TITLE
prerender doesn't work correctly with $http

### ISSUE THREAD

**Issue by theking-laptop** [prerender/prerender#169]
I use AngularJS and I wrote the code like this:

```
$http.get('external-resource-url').then(function (data) {
    $scope.data = data;
});
```
In html, I render it via binding. But when I get html from prerender, it's not rendered. I replace `$http.get` by `$.get` (jQuery) and surprisingly, it's rendered. I don't want to use `$.get` in my application. What can I do?

**Comment by thoop** [comment]
Weird. Are you seeing any errors? We use `$http({method:'GET'...}).success(function(){})` in our application without any problems. Feel free to send me the URL (todd@prerender.io) and I'll test it out.

**Comment by theking-laptop** [comment]
@thoop I sent. Additional information: I don't see any errors and if I don't use `removeScriptTags` plugin, after raw html is rendered, data from external resource is fetched and rendered.

**Comment by stewones** [comment]
+1

**Comment by thoop** [comment]
Hi @stewones. Can you send me an email with the URL that you're seeing issues with? I'm happy to help make sure things are working. todd@prerender.io

**Comment by stewones** [comment]
@thoop email sent. thx

**Comment by thoop** [comment]
Should be working in our latest version of Prerender (v4.0.3). Feel free to reopen if not.
