### ISSUE TITLE
Getting only 504 after a random timeframe

### ISSUE THREAD

**Issue by m3kka** [prerender/prerender#172]
Hello,

recently testing this service for production (the PhantomJS2 branch to be specific), and it is kinda amazing.

The problem we are experiencing is that after a couple minutes / hours / days (the amount of time changes quite a bit) we're getting only:

    got 504 in 333ms for https://www.travelrepublic.ie/v2/hotels/united_kingdom/swindon_swindon/cheap_rates_marriott_swindon_hotel_hotel.html

While on the mobile version of the site this is not happening (only 200 so far).
What could be the reason?

**Comment by m3kka** [comment]
Uhm... during the timeframes with 504 a curl request gives back:

    curl: (52) Empty reply from server

I think I am being throttled by the server. 
Just trying to rule prerender out prerender from this issue

**Comment by thoop** [comment]
Hmm, that's weird. What do you have the number of `workers` and `iterations` set to? If you restart the server, does it fix it?

**Comment by m3kka** [comment]
10 workers and 10 iterators.

Usually a restart does not work. I just get bursts of 504 every now and then - even for a couple minutes - even if the non-prerendered site is still functional.

**Comment by thoop** [comment]
wow that's weird. Can you see the requests come through to your site when it starts getting 504s? Or is it not sending anything at all? Haven't experienced this.

**Comment by m3kka** [comment]
Sorry for the late response.

I am still getting a lot of 504 from our main website (a test page could be https://www.travelrepublic.ie/v2/hotels/hotels_spain.html)

Right now I am running on 2 aws servers with this configuration:

    var prerender = require('./lib');

    var server = prerender({
        workers: 2,
        iterations: 5,
        phantomBasePort: 20000,
        messageTimeout: process.env.PHANTOM_CLUSTER_MESSAGE_TIMEOUT,
        port: 4000,
    });


    // server.use(prerender.basicAuth());
    // server.use(prerender.whitelist());
    // server.use(prerender.blacklist());
    // server.use(prerender.logger());
    server.use(prerender.removeScriptTags());
    // server.use(prerender.httpHeaders());
    // server.use(prerender.inMemoryHtmlCache());
    server.use(prerender.s3HtmlCache());

    server.start();

Each server is running 4 instances of prerender (branch `phantomjs2` running `phatomjs v 2.0.1-development`).

After a week or more of no `504` error they started appearing again when we added another site to the prerendered ones.
So I thought that splitting the load between more servers would solve the issue, but even balancing between a gran total of 8 servers apparently is not doing the trick.

CPUs are always around 40% - 60% so normal load.

Is there something horribly wrong with my conf?

**Comment by m3kka** [comment]
Ah forgot a detail, the `504`s are generated from the failure of `req.prerender.page.open`, the status returned from phantomjs is `fail`.

I've tried the log methods suggested in this article https://newspaint.wordpress.com/2013/04/25/getting-to-the-bottom-of-why-a-phantomjs-page-load-fails/ but I wasn't able to get anymore informations (I did this tests on the `master` branch)

**Comment by thoop** [comment]
Interesting. There's nothing wrong with your Prerender config. 5 iterations is pretty low. We usually go with something like 30-40 and it works fine.

The failure from the phantomjs open command sounds like the real problem. I'm also unsure of how they calculate that but, in my experience, it's usually right. Once they start failing, are you getting 504s for all URLs? Or just certain URLs? And is it still random or do you get only failures after that?

**Comment by m3kka** [comment]
After the 504s start I only get failures with every URL

**Comment by thoop** [comment]
Did you compile your own PhantomJS 2?

**Comment by m3kka** [comment]
Yes I did, on the same machine I'm currently executing it

**Comment by thoop** [comment]
Do you know which commit you compiled from? I haven't seen that problem with our version of PhantomJS 2 that we compiled. Sorry, I'm not sure how much I'd be able to help since that seems like something going on with PhantomJS :(

You could try using an AWS health check to load a page and replace a server if it starts failing a bunch.

**Comment by m3kka** [comment]
Ugh not sure I know which commit was, can you tell me from which one did you compile?
So I can use that same executable, maybe this will fix my problem :)

(Thank you for your help by the way)

**Comment by thoop** [comment]
I'll have to see if I wrote it down somewhere. I'd suggest trying to recompile from master if possible, just in case.

**Comment by m3kka** [comment]
Ok compiled and started in production right now. 
Everything seems fine, I the 2.0.1 version should not be used, my bad.
Thank you again for your help!

**Comment by m3kka** [comment]
Uhm started the 2.0.0 version now and after a couple minutes of stability the 504s started again :/

I used the source at this page http://phantomjs.org/download.html

**Comment by thoop** [comment]
Did you compile your own on linux from the source they have on that page? Can you try an older version from the beginning of September (compile from git) or something and see if it's any different? See if you can set up a health check on AWS. We use those to rotate servers that start to have issues.

**Comment by m3kka** [comment]
Yes I compiled on my own, rebooted (my process-stuck-senses were tingling so I went for the  windows way) and started all the 8 instances again, seeing the error on all of them (both my prerender servers).

I'll try the older version and let you now.

**Comment by thoop** [comment]
How many CPUs does your server have?

**Comment by m3kka** [comment]
Working on an c4.xlarge with 4 vCPU

**Comment by m3kka** [comment]
Used this commit https://github.com/ariya/phantomjs/commit/3274001e079d3a7255167162d4f4fb2c8ef8c22a

same problem :/

**Comment by thoop** [comment]
Hmm, that's really weird. Can you try medium servers with 1 instance on each? Seems really weird that it starts to happen so quickly. We definitely don't experience that. You compiled it on your c4.xlarge, right? And when you start getting the 504s, even if you try http://yourPrerenderServer/https://www.google.com it still gives you a 504? Can you ssh into your instance when that's happening and look at the CPU usage, memory usage, and anything else to see if there's a problem with opening a new page?

**Comment by m3kka** [comment]
I will use some time today to configure 2 medium instance with 2 vCPU each, I'll configure the instance from scratch.

I did compile on my c4.xlarge.
Yes I do see the 504 even if I skip the middleware and use the URL
CPU and memory usage are under alerts (60%), the never spiked over that limit.

Unitil now I worked on Ubuntu 14, I'll switch distro to Amazon Linux and see how it goes

**Comment by m3kka** [comment]
Started 4 loadbalanced c4large with a single instance of prerender each (2 `workers` 5 `iterations`).

Right now this setup seems to work ok.

**Comment by m3kka** [comment]
The system is holding up quite well (still using `2.0.1-development` as PhantomJS version), the main change was moving from ubuntu to Amazon Linux and reducing the number of concurrent prerender process to 1.

**Comment by thoop** [comment]
Interesting! I wonder if it was Ubuntu or the numbers of processes that caused the issue. Weird!

**Comment by m3kka** [comment]
I did have the same problem also while running a single process.

I am tempted to say it's Ubuntu, but I don't have much proof to be honest.

**Comment by thoop** [comment]
Yeah I use the Amazon Linux AMI and never have any issues. Let me know if you see anything else!
