### ISSUE TITLE
Error in parsing multiple hash parameters

### ISSUE THREAD

**Issue by rabihsyw** [prerender/prerender#176]
I had the following problem while dealing with multiple hash parameters, so when I go to 'link 1' I suppose that I should get all parameters next to '_escaped_fragment_=' as parameters in hashbang 'link 3', but I got a wrong result 'link 2' from prerender.io service.

link 1 : 
http://www.example2.com/tr/?_escaped_fragment_=languageCode=tr&getFilter=all&getGroup=5%3A23_45_outright

link 2 : 
http://www.example2.com/tr/?getFilter=all&getGroup=5%3A23_45_outright%3B#!languageCode=tr

link 3 : 
http://www.example2.com/tr/#!languageCode=tr&getFilter=all&getGroup=5%3A23_45_outright%3B

**Comment by thoop** [comment]
Hmm, so you are using ampersands (&) after the hashbang but they are not query parameters? If you escape the ampersands in link 1, does that generate the correct URL?

**Comment by rabihsyw** [comment]
@thoop thanks for your reply, I tried to change all ampersands (&) with (%26) but I am still getting the same result :

http://www.example2.com/tr/?_escaped_fragment_=getUniqueId%3D23_150_match%26getEventId%3D77656%26getSportId%3D5%26languageCode%3Den

**Comment by thoop** [comment]
I'll look into this some more and see what I can do to make that work correctly because the encoded & should get unencoded correctly but it looks like we are thinking it's causing more query params.

**Comment by thoop** [comment]
This should work fine in the latest version of our Prerender server (v4.0.3)
