### ISSUE TITLE
Invalid Parameter Value: '0.10.10'

### ISSUE THREAD

**Issue by justinlevi** [prerender/prerender#180]
I'm getting an error when trying to deploy prerender on aws elastic beanstalk via the command line tools. I have it up and running locally but I'm getting the following error

```ERROR: "option_settings" in one of the configuration files failed validation. More details to follow.
ERROR: Invalid Parameter Value: '0.10.10' for parameter: NodeVersion - Value is not one of the allowed values: [0.8.26, 0.8.28, 0.10.21, 0.10.26, 0.10.31, 0.12.0]
ERROR: Failed to deploy application.```              

I've done a few searches but can't seem to find anything. I am trying to deploy this on a micro instance just to see if I can get it up and running.

**Comment by thoop** [comment]
You might be using a newer AMI that doesn't have 0.10.10 anymore. Try using an older AMI for now.

We should upgrade to node 0.12.0 sometime...

**Comment by justinlevi** [comment]
Thanks for the quick response. Sorry, I'm a bit green with AWS. Can you point me in the direction where I can set the AMI? Everything I'm using is default out of the box Elastic Beanstalk and CLI tools installed from Brew

**Comment by thoop** [comment]
Did you run `eb init` in your project to pick all the options for your Elastic Beanstalk environment? It will ask you what server type you want, location, rds, etc.

You'll want to pick an AMI from this page that has access to 0.10.10: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs

**Comment by justinlevi** [comment]
Yes, I did run `eb init` but don't recall the option to enter the server. I'll review that link and thanks again!

**Comment by justinlevi** [comment]
Todd, I was able to get beyond the AMI issue with the `eb -i` so thanks for that. I'm now running into an issue where I'm getting a ton of 502 bad gateway requests when testing the server directly. Any ideas there?

**Comment by thoop** [comment]
Are you getting 502s if you try to access https://your-prerender-server.com/https://www.google.com/ ? Or is it only when accessing your pages? Also, are you having the 502 problems if you try testing a Prerender server locally with the same pages? Feel free to email me any private info to help me look into it with you. todd@prerender.io

**Comment by graywithanA** [comment]
Hey @thoop ,

I'm working with @justinlevi on this project and we are getting 504 errors on 3 PNG files when visiting https://our-prerender-server.com/https://www.google.com/ .  When visiting https://our-prerender-server.com/http://www.our-test-site.com we are getting either a combo of 502 & 504 errors or just 504 errors, with each reload.  Again those errors are for images that are trying to be loaded from https://our-prerender-server.com/images/image.png which is the same path when loading google.

It's also worth noting that accessing our preload server via the middleware in our app (aka http://our-test-site.com/test-page??_escaped_fragment_= seems to work as expected without any errors.

I'll also note for anyone who comes across this in the future that the command that we actually used to install the specific AMI was:
```eb init -p "64bit Amazon Linux 2014.09 v1.0.8 running Node.js" -i```

**Comment by thoop** [comment]
Ah, that happens when you are accessing your Prerender server directly in the browser because the relative links are loaded with the wrong domain so we 504. That's expected.

Once you proxy the requests through your middleware, everything will work as expected and the png's should never get sent to your Prerender server. The only request that goes to the Prerender server should be the HTML page and all other requests should be sent to your normal webserver.

**Comment by graywithanA** [comment]
That's what I thought was happening.  Thank you for the prompt replies and helpful info, it is very much appreciated.

**Comment by thoop** [comment]
Great! Feel free to open another issue if you see any other problems. Or feel free to email me too.
