### ISSUE TITLE
Tumblr: no user agent or escaped fragment support?

### ISSUE THREAD

**Issue by graywithanA** [prerender/prerender#181]
I'm wondering if anyone here may have a suggestion as to how to identify the Tumblr crawler.  Their documentation even mention that they use one but it seems as though they do when using their like buttons.

Here's my situation:
I created a custom like button by following their [documentation] (https://www.tumblr.com/docs/en/share_button).  I'm setting options using query string parameters and using ` https://www.tumblr.com/widgets/share/tool ` as the docs suggest.

When testing the button I'm seeing {{og.description}} in the like popup dialog which tells me that Tumblr is attempting to get Open Graph data using a crawler ( {{og.description}} doesn't appear anywhere in the like button code only in my head) and that the site is not being prerendered for the crawler.

When I look at the connections to the Express server that is hosting the site (and the prerender middleware) the Tumblr crawler doesn't appear to provide any user agent info and apparently they aren't using the escaped fragment spec either since the middleware isn't catching that.

Edit: I should also mention that we are running our own prerender server and it is working in other situations.

Does anyone know how I can identify the Tumblr requests and ensure that they get prerendered?  I know you can white/black list IP addresses but this seems like a less than desirable/reliable option.

Any input is greatly appreciated.  Thanks!

**Comment by thoop** [comment]
Interesting...So tumblr doesn't user a custom user agent or anything? Do they use a custom header, javascript variable, or anything?

**Comment by graywithanA** [comment]
I don't see anything in the request that could be used to identify it as a crawler.  Here's some gists, there's a blurb from the nginx access.log showing the 3 requests made by the crawler, then there are the contents of those three requests.  If you see anything that could be of use please let me know.

[Access.log entries] (https://gist.github.com/graywithanA/4e5aaa275c8d22ca7619)
[Crawler's HEAD request] (https://gist.github.com/graywithanA/e469af2795e2752fd471)
[Crawler's 1st GET request (no user agent)] (https://gist.github.com/graywithanA/49814aa763e27d6d84b8)
[Crawler's 2nd GET request (with generic user agent)] (https://gist.github.com/graywithanA/fd55b6d135befe2e0ebe)

**Comment by thoop** [comment]
Weird.... Yeah we wouldn't be able to do anything in that case. Is there a way you can contact their support letting them know what you're trying to do and see what they say? Seems bad that they wouldn't put tumblr in their user agent.

**Comment by graywithanA** [comment]
I've already submitted a post to their 'support forums' which is just a Google group that appears to be mostly abandoned.  After 2 days I've gotten 1 view and no responses.

They don't present any contact info on their page unless you do some digging but I finally found it.  I've now submitted a request directly to Tumblr's support.  I'll report back when I've received a response. 

Thanks for your input.

**Comment by thoop** [comment]
Great! I'm interested to hear what they have to say.

**Comment by graywithanA** [comment]
Just an update:  A week after contacting Tumblr I received an unhelpful form response that made it pretty clear they hadn't even read my initial email.  At the very end of the email they did provide a method of contacting their developers so I did that on April 29th and still haven't received any response.

**Comment by thoop** [comment]
No worries. Feel free to let me know as soon as you hear something from them.

**Comment by graywithanA** [comment]
Update:  I am still yet to receive any further response from Tumblr despite a second attempt to contact their developers a few weeks after my Apr 29th attempt.  It does appear as though the message was received though as now their crawlers user agent is listed as 'Tumblr/14.0.835.186'.  Disappointing customer service on Tumblr's part but at least the situation is now resolved.
