### ISSUE TITLE
phantom stderr: 'C:\Users\Mykhaylo' is not recognized as ...?

### ISSUE THREAD

**Issue by Vayvala** [prerender/prerender#183]
I have installed Phantom.JS and add it to the windows env.path.
When I type `phantomjs`, phantom console shows up.

I have also cloned Prerender.io [repository][1], and ran `npm install`.

When I tried to run it with `node server.js`, I get the following error:

    2015-04-24T13:11:12.710Z phantom crashed, restarting...
    2015-04-24T13:11:12.710Z starting phantom on port [12301]
    phantom stderr: 'C:\Users\Mykhaylo' is not recognized as an internal or external command, operable program or batch file.

**Why am I getting this error?
How can I fix it?**

**Comment by thoop** [comment]
Sorry for never answering this! Feel free to try out latest version of Prerender (v4.0.3) and this shouldn't happen.
