### ISSUE TITLE
Cannot Access Response Headers in Angular.js for XHR requests from http.post()

### ISSUE THREAD

**Issue by kherrmann** [prerender/prerender#185]
In our single-page app, we have some services that need to parse response headers of issued http requests to work. it seems that these are not available when executed by phantom:

$http.post(...').then( function(data){
var location = data.headers('Location');
// ...

in a browser, the location header is available, inside phantom it's null. the post request returns 200 OK, not a redirect. 

is there something about headers that can be tuned, or is that a bug in handling redirects, or intentional behaviour?

**Comment by thoop** [comment]
Interesting. I haven't seen this before and I've seen PhantomJS send headers just fine. Is there a public URL you can email me so I can test this and see what PhantomJS is showing when I try it? You can email me at todd@prerender.io if you want to keep the URL private.

Thanks!

**Comment by kherrmann** [comment]
Thanks! I'm trying locally but can reproduce with an external URL, will email you.

**Comment by kherrmann** [comment]
I've opened https://github.com/ariya/phantomjs/issues/13200 for this, as it seems to be a problem with phantomjs rather than prerender.
