### ISSUE TITLE
Syncronous ajax requests are slowing down render

### ISSUE THREAD

**Issue by sharshenov** [prerender/prerender#194]
There is a [bug in phantomjs](https://github.com/ariya/phantomjs/issues/11284). OnResourceReceived is not fired after a synchronous ajax request.

In case of prerender this bug is causing unexpected 10s+ delays. I will try to investigate more...

UPD. I'm testing on master branch with phantomjs 1.9.8

**Comment by sharshenov** [comment]
Looks like phantomjs 2.0.0 has this bug too

**Comment by sharshenov** [comment]
I've disabled all synchronous ajax requests in my app. No delays now

**Comment by thoop** [comment]
Interesting. Thanks for the heads up. Looks like someone said in that thread that it's a qtwebkit bug. Going to close this since it's not an issue with Prerender, but with our dependency on PhantomJS.
