### ISSUE TITLE
Prerender.io service - lots of 504 errors

### ISSUE THREAD

**Issue by hades200082** [prerender/prerender#195]
We're seeing a lot of 504 responses from prerender.io's hosted service to crawlers from our site.

![prerender - angularjs seo backbonejs seo or emberjs seo - google chrome](https://cloud.githubusercontent.com/assets/1023581/7678559/0f6685c4-fd4d-11e4-893b-74770701e18f.png)

Any ideas?

**Comment by maxweldsouza** [comment]
I can confirm the issue. Lots of 504s in webmaster tools. I tried running a local copy of prerender and its returning 504's on css files. Ive tried with css files on google hosted libraries.

**Comment by hades200082** [comment]
Oddly I've only seen it with Bingbot and Facebook crawlers so far.  Google seems to have no issue.

**Comment by thoop** [comment]
@hades200082 Please send any support issues for our hosted service to support@prerender.io. It's easier to manage there so we can keep our github for the open source project issues.

@maxweldsouza Can you also send us an email at support@prerender.io? I'm happy to take a look and figure out what might be going on. If you are seeing css files get passed through to Prerender, that means something isn't set up correctly. The Prerender server should only try to load the html pages and should not try to prerender a css file.

Thanks!

**Comment by danscrima** [comment]
I also am seeing the same issue running prerender locally.. Was there a resolution that was a general solution for this or was it really specific to your environment? Any guidance is greatly appreciated. Thanks!

**Comment by thoop** [comment]
These issues are usually specific to setup. Please email me at todd@prerender.io and I'd be happy to help.

**Comment by thavaamm** [comment]
Hi ,

I too getting same 504 error in many urls from google webmaster. Please find the attached file. 
![prerenderusr_504](https://cloud.githubusercontent.com/assets/10183541/20556335/a1874f48-b18c-11e6-8e50-78c3a1b4610c.jpg)

**Comment by thoop** [comment]
Please send us an email at support@prerender.io for any issues with 504s so we can look into it. Usually it's not an issue with the Prerender server.

**Comment by cullsin** [comment]
Hi, 

I am also getting same 504 error with escape_fragment_=. Any resolution yet?

Raja K

**Comment by alexstanbury** [comment]
We are also getting a lot of 504 errors with the reason being given in console that PhantomJS restarted in the middle of the request. Is there a way to avoid this happening?

Here is my server config:

PRERENDER_SERVER_PORT=4000
REDIS_URL="redis://localhost:4001/0"
PAGE_TTL=604800
RESOURCE_DOWNLOAD_TIMEOUT=10000
PAGE_DONE_CHECK_TIMEOUT=300
WAIT_AFTER_LAST_REQUEST=2000
JS_TIMEOUT=10000
JS_CHECK_TIMEOUT=300
NO_JS_EXECUTION_TIMEOUT=3000
EVALUATE_JAVASCRIPT_CHECK_TIMEOUT=300
PHANTOM_CLUSTER_NUM_WORKERS=16
PHANTOM_WORKER_ITERATIONS=500
PHANTOM_WORKER_SOFT_ITERATIONS=100

**Comment by thoop** [comment]
Please send us an email at support@prerender.io for any issues with 504s so we can look into it. Usually it's not an issue with the Prerender server. I'm going to lock this thread but please do get in touch!
