### ISSUE TITLE
Use prerenderer for site without hashbang

### ISSUE THREAD

**Issue by ka8725** [prerender/prerender#198]
Our application is fully single page and we use html5 push state. It means that we don't have urls with `#!` at all and are not going to use them. But we want the pages to be indexed by Google.

Following [this Google FAQ](https://developers.google.com/webmasters/ajax-crawling/docs/getting-started#3-handle-pages-without-hash-fragments) and README of this tool we can do the following:

1. Add `<meta name="fragment" content="!">` to our pages's head
2. Listen to `?_escaped_fragment_=/some-page` with **prerenderer**. In order to do this we can use [ready ruby gem](https://github.com/prerender/prerender_rails) pointing to the nodejs service.

But actually it doesn't work because of [this line](https://github.com/prerender/prerender/blob/master/lib/util.js#L27). You don't provide a choice and force us to have all urls with `#!`.

Actually it's not clear why. Is it any restriction or I missed something? May be allow to configure this behavior and users will be able to set option if they use urls with `#!` or without them.

Currently I fixed the issue like this:

```javascript
// Gets the URL to prerender from a request, stripping out unnecessary parts
util.getUrl = function (req) {
    var decodedUrl
      , parts, escapedFragment = '';

    try {
        decodedUrl = decodeURIComponent(req.url);
    } catch (e) {
        decodedUrl = req.url;
    }

    parts = url.parse(decodedUrl, true);

    // Remove the _escaped_fragment_ query parameter
    if (parts.query && parts.query.hasOwnProperty('_escaped_fragment_')) {
        if (parts.query['_escaped_fragment_']) { escapedFragment = parts.query['_escaped_fragment_']; }
        delete parts.query['_escaped_fragment_'];
        delete parts.search;
    }

    var newUrl = url.format(parts);
    if (newUrl[0] === '/') newUrl = newUrl.substr(1);
    return url.resolve(newUrl, escapedFragment);
};
```

**Comment by thoop** [comment]
Your first bullet point is correct, you should add `<meta name="fragment" content="!">` to the `<head>` of your page since you are using HTML 5 push state.

But your second bullet point is incorrect. The URL that the crawlers will access would be:
```
http://www.example.com/some-page?_escaped_fragment_=
```
Since the escaped fragment parameter is empty, the Prerender code will turn that back into `http://www.example.com/some-page`

Sorry if this wasn't clear in the documentation. Is there a way we can make that more clear from what you were looking at?

**Comment by ka8725** [comment]
@thoop , thanks for the response! Now it's clear. Yes, you could improve README with the example  provided here: `http://www.example.com/some-page?_escaped_fragment_=` will be redirected to `http://www.example.com/some-page` by **prerenderer**.
And also as I understand: `http://www.example.com/some-page?_escaped_fragment_=/some-part-of-the-page` will be redirected to `http://www.example.com/some-page/#!/some-part-of-the-page`. Is it correct? Thank in advance.

**Comment by thoop** [comment]
Thanks! I'll update our documentation.

You are correct. `http://www.example.com/some-page?_escaped_fragment_=` will be changed to `http://www.example.com/some-page` (not redirect, but that's the URL we will access).

And for the `#!`, `http://www.example.com/some-page?_escaped_fragment_=/some-part-of-the-page` will be changed to `http://www.example.com/some-page#!/some-part-of-the-page`

**Comment by info2ankit** [comment]
Hello,

Guys your this communication gonna really help me,
My site url is unplan.in
I am gonna use Prerender for my angular app and i have all my URLs with no hash n all.
So let me know if Prerender will gonna help me to index my site , if yes then how ? because crawler needs to know that my app supports AJAX Crawling. If my site does not have this URL format then how crawler will index my site.

**Comment by thoop** [comment]
You'll want to add `<meta name="fragment" content="!">` to the `<head>` of your pages so that the crawlers will then request the `?_escaped_fragment_=` URL.

**Comment by info2ankit** [comment]
thanks for response and suggestion :)

**Comment by verishal** [comment]
Almost done prerender but only i'm fetching problem :
 why not redirect https://www.xyz.com/?_ escaped_fragment= request.
only for redirect the page the http://www.xyz.com/?_ escaped_fragment= request.
please help me.only getting issue https how can resolve this problem.

**Comment by thoop** [comment]
Can you send your prerender config and a little more information to us at support@prerender.io? I don't understand what issue you're facing there.

**Comment by verishal** [comment]
please check it sir . what is the issue in .htaccess file




<VirtualHost _default_:80>
 #  Redirect "/blog" "http://blog.xyz.com/"
   DocumentRoot "/opt/bitnami/apache2/htdocs"
   ServerName www.xyz.com
   RewriteEngine On
RewriteCond %{HTTPS} !=on

 #RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
    # Tried for SSR -  Verishal
   Options +FollowSymLinks
 RewriteCond %{REQUEST_URI}  ^/$
 RewriteCond %{QUERY_STRING} ^_escaped_fragment_=/?(.*)$
 #RewriteCond %{QUERY_STRING} _escaped_fragment_=/([^&]*)
 RewriteRule ^/(.*) http://www.xyz.com:9090/$1 [NC,L]
  ProxyPassReverse / http://www.xyz.com:9090/
 Options Indexes FollowSymLinks MultiViews



# Tried for SSR - Verishal ---- END ----
  # RewriteCond %{QUERY_STRING} ^_escaped_fragment_=/?(.*)$
  # RewriteRule ^(.*)$ /snapshots/%1? [NC,L]
  #Options Indexes FollowSymLinks MultiViews
#<Directory "D:/snapshots">
   #Allow from all
   #Require all granted
#</Directory>

**Comment by thoop** [comment]
Your config looks incorrect. You'll want to use our configuration from: https://gist.github.com/thoop/8072354

You'd then want to make sure you are passing in the correct protocol on this line:
`http://service.prerender.io/http://example.com/$2`

**Comment by verishal** [comment]
thank you for response.

**Comment by verishal** [comment]
Thanks @thoop  . These 2 solution worked. Now I only have to figure out that SSL Error and port number thing.

**Comment by thoop** [comment]
Great! Let us know if we can help with anything else. Feel free to create a new issue if needed.

**Comment by verishal** [comment]
Ok @thoop
