### ISSUE TITLE
Render time equal timeout option value

### ISSUE THREAD

**Issue by michelem09** [prerender/prerender#199]
Hello,
I have this issue, I was looking for the problem why my prerender got always 10 seconds timeout issue on Facebook debug tool (sharer) or with any curl call.
Anytime I try to get a page the process time was equal (or almost equal) to 10 seconds.

Then I found you can set the prerender timeout via `jsTimeout` option, so I tried to increase it to 30 seconds and oplà curl process gets almost 30 seconds to complete the request, weird.

Then I tried to decrease it to 5 seconds `jsTimeout: 5000` and guess? The curl takes almost 5 seconds to complete the request!

Just to completeness I used also this option `resourceDownloadTimeout: 5000`

Now the question is, why the rendering takes almost always the timeout value set? Is it normal?
Thanks

**Comment by thoop** [comment]
Can you send me a URL that I can test? That will help me determine what is causing the page to take a while to render. My email is todd@prerender.io

**Comment by michelem09** [comment]
After private discussion problem was a request from the original rendered web page that remained in pending status. Specifically that was due to a misconfigured AWS CloudFront.
Thanks for all the support!
