### ISSUE TITLE
Having difficulties synchronizing!

### ISSUE THREAD

**Issue by ahmedmohiduet** [prerender/prerender#201]
I am currently using prerender.io with a postgresql cache. I am trying to write a cron script for a periodic synchronizer. Now I know if I hit at http://myprerenderserverwithcahche:3000/pageurls this will return the cached html.So, what I did, I have setup another prerender node server without cache. And when my synchronizer starts, it starts the chache-less server temporary ly and hit http://myanotherserverwithoutcache:3000/pageurls and upsert in the cache.
So, my question is, is there any flag or something so that I can tell my prerender server return a rendered html rather than the cached snapshot so that I dont need setting up two node servers? I am looking for something like this:

 http://myprerenderserverwithcahche:3000/?useCache=false&url=pageurl

**Comment by thoop** [comment]
That can be built into your cache plugin. You could provide a query string that skips the cache or something else like a `POST`. But that isn't a feature of the normal Prerender server.

**Comment by ahmedmohiduet** [comment]
Hmm. Pretty useful info :) Thank you :)
