### ISSUE TITLE
Adding phantomjs logic

### ISSUE THREAD

**Issue by ramikh86** [prerender/prerender#202]
I want to add the following phantomjs logic but i'm not sure where to add it, I tried "onPhantomPageCreate" but i'm not able to find phantom page "evaluate" or "window". what it does basically is it scrolls to the bottom of the page to load more data.
Thanks

  setInterval(function() {
        page.evaluate(function() {
          // Scrolls to the bottom of page
          window.document.body.scrollTop = document.body.scrollHeight;
        });
  }, 500); // Number of milliseconds to wait between scrolls

**Comment by thoop** [comment]
Why are you trying to do this? If it's for infinite scroll lists, you should do that a different way. Here's a good description from Google on how to do that correctly for SEO: http://googlewebmastercentral.blogspot.com/2014/02/infinite-scroll-search-friendly.html

**Comment by ramikh86** [comment]
I read something like this before, what I don't like it about this is that you are duplicating the logic on the server and that goes against DRY. 
We are using MVC and Backbone, backbone gets the data from web api's and use handlebars to render the views. I don't want to repeat rending logic on the server to create SEO pages.

**Comment by thoop** [comment]
You wouldn't have to write logic on the server for that (besides the offset/limit query for paging). You just simply support pagination on the client in the same way that scrolling loads a new page. Trying to scroll the page with PhantomJS isn't a very elegant solution either.
