### ISSUE TITLE
does not work with system.js

### ISSUE THREAD

**Issue by devmondo** [prerender/prerender#203]
hi, i am using Aurelia framework, and it uses System.js and jspm to load scripts,

the thing is that with prerender.io no scripts get loaded, no errors, just scripts dont get loaded
here is a site you can test it on
http://gooy.github.io/aurelia-animator-velocity/

thanks in advanced.

**Comment by thoop** [comment]
Hi @devmondo, I'll have to look into this and get back to you with what I can find. I took a quick look and I'm seeing the problem that you saw, but didn't see what was causing it. I'll report back soon.

**Comment by devmondo** [comment]
thank you very much i really appreciate it.

**Comment by stela5** [comment]
subscribing

**Comment by thoop** [comment]
We upgraded to the latest version of PhantomJS with our latest Prerender v4.0.3. Please try that and reopen if you run into issues.
