### ISSUE TITLE
Some http requests works, but some https requests does not

### ISSUE THREAD

**Issue by harianus** [prerender/prerender#205]
I'm running a hobby dyno on Heroku (just one dyno and no environment variables).

Some pages work like this one:
* http://mgmco-prerender.herokuapp.com/https://www.google.nl

But these page won't work:
* https://mgmco-prerender.herokuapp.com/https://pagina.io (on CloudFlare and Heroku)

The same happens when I run it local on my Mac.

Running prerender@3.18.0 and phantomjs@1.9.17

**Comment by thoop** [comment]
Looks like PhantomJS is having trouble rendering the page. I'll have to look into this more and get back to you.

**Comment by dstringvc** [comment]
Related to SSL/TLS, I've found some sites that won't render and the prerender server log shows a 504 error. From what I can tell, prerender/phantom is using TLSv1. However, some sites apparently require a newer version. How can I configure prerender/phantom to use, for example, TLSv1.2?

For example, the site https://www.xscapers.com/ seems to require the latest TLS version.

Thanks!

**Comment by thoop** [comment]
I can't find anything showing that PhantomJS supports anything higher than v1.0 yet:

http://phantomjs.org/api/command-line.html
https://github.com/ariya/phantomjs/issues/12524

**Comment by rajachawat** [comment]
Is there a nightly build (2.0.1) available that suuports tlsv1.2?

**Comment by thoop** [comment]
There are no 2.x builds available. You currently have to build them yourself from compiling the PhantomJS source.

**Comment by mattclark** [comment]
If I follow correctly, once the phantomjs2 branch is merged then TLS1.2 is possible?

**Comment by thoop** [comment]
That is correct.

**Comment by thoop** [comment]
Please upgrade to our latest version of Prerender (v4.0.3). It has support for PhantomJS 2.1 with TLS 1.2.

**Comment by harianus** [comment]
Thanks, that solved the issue.

**Comment by felipe-pereira** [comment]
Hi @thoop,  is this ported to prerender-node?, don't know if my question makes any sense, but asking since I'm using it, and while you recomend v4.0.3, prerender-node latest version is 2.2.1, thanks.

**Comment by thoop** [comment]
prerender-node is different. prerender-node is just middleware while the prerender repo is the actual prerender server. Feel free to send us an email if you are having issues and using our hosted service.
