### ISSUE TITLE
Prerender timeout

### ISSUE THREAD

**Issue by simonefalcini** [prerender/prerender#206]
When rendering http://www.swite.com/simone I get this error:

```bash
2015-06-25T09:15:30.321Z getting http://swite.com/simone
phantom stdout: INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
phantom stdout:   :45
phantom stdout:   :38 in c1
phantom stdout:   :38
phantom stdout:   http://maps.gstatic.com/maps-api-v3/api/js/21/5a/main.js:32
phantom stdout:   :38
phantom stdout:   http://maps.gstatic.com/maps-api-v3/api/js/21/5a/main.js:32
phantom stdout:   :44
phantom stdout:   http://maps.gstatic.com/maps-api-v3/api/js/21/5a/main.js:29
phantom stdout:   :44
phantom stdout:   :32
phantom stdout:   :68
2015-06-25T09:15:44.489Z Timed out. Sending request with HTML on the page
2015-06-25T09:15:44.510Z got 200 in 14189ms for http://swite.com/simone
```

You can try it here: http://prerender.herokuapp.com/http://www.swite.com/simone

**Comment by thoop** [comment]
prerender.herokuapp.com is deprecated and could be deleted any day now. Where did you find that URL? I'd like to remove any links to it.

I'll have to look into this issue and get back to you.

**Comment by simonefalcini** [comment]
@thoop I found it here: https://github.com/prerender/prerender/issues/17#issuecomment-26592453

Please let me know if you found the cause of the issue

Thanks

**Comment by simonefalcini** [comment]
Hey @thoop did you find something?
Prerender still hangs on rendering pages on our site like http://swite.com/simone
Even on prerender.io it takes more than 1 minute..

Thanks

**Comment by thoop** [comment]
Sorry! I'll look into this today. Been swamped. Thanks for your patience.

**Comment by simonefalcini** [comment]
Hey @thoop I found the issue.. We were setting the flag `window.prerenderReady = false;` without resetting to true.. so prerender was waiting until timeout :)

Maybe a log console would have been useful ;)

Thanks anyway

**Comment by thoop** [comment]
Ah, ok :)
