### ISSUE TITLE
Node cluster error: channel closed

### ISSUE THREAD

**Issue by ryanricard** [prerender/prerender#208]
I am testing Prerender with Phantom2 on a 24 core machine with 100gb of RAM. I'm working on a solution to keeping a MongoDB ~1,000,000 page cache warm. With a single Prerender cluster of 24 Phantoms, I am processing 3-5 pages per second (~7 second page loads). Phantom is crashing randomly and I am also seeing the following Node cluster error that seems to be resulting in orphaned Phantom processes:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:414:26)
    at sendHelper (cluster.js:676:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)
```

**Comment by thoop** [comment]
Sorry I didn't respond to this since we were talking about it in the other issue. Thanks for making this one and I'll let you know if I'm able to reproduce or prevent this.

**Comment by thoop** [comment]
Hey @ryanricard I meant to ask, which version of node are you running?

**Comment by ryanricard** [comment]
Thanks for following up, @thoop. The error occurred on Node v12.4. I have been away from the context of this issue for a few weeks. Looking back, it could have been very well associated to the instability of Phantom. A few weeks ago we configured a cron job to clean up orphaned Phantom processes; things seem to have been running much better since.

**Comment by thoop** [comment]
We're upgrading Prerender to officially work with 0.12.x and I ran into some other issues with cluster so I wonder if it's a node bug. I'll keep looking into it but the orphaned Phantom cleanup is a good way to do it.
