### ISSUE TITLE
Prerender renders a ui-router to a white blank page

### ISSUE THREAD

**Issue by phizaz** [prerender/prerender#209]
I have been trying to get my website prerendered with prerender.io. The problem, as mentioned, the webpage, which contains ui-router, is rendered to be a blank page. 

I'm pretty sure that it has something to do with phantomjs and ui-router, because extending the rendering time doesn't help.

My ui-view stays blank just like the one below.
```
<div ui-view></div>
```

I found a topic that might be related to this problem. https://github.com/ariya/phantomjs/issues/12568

**Comment by thoop** [comment]
I don't think ui-router would break anything unless there was some kind of parse error or syntax error. Can you share a URL with me at todd@prerender.io and I'll see if I can get some logs to help dig into the issue?

**Comment by phizaz** [comment]
@thoop I did send you an email.

**Comment by phizaz** [comment]
It turned out to be that I was wrong. The problem is not with "ui-router" but "ocLazyLoad".
The following code is where the problem resides: 
```
resolve:
  lazyLoad: ($ocLazyLoad, $q) ->
    # dependencies list
    scripts = defaultScripts.concat([
      'public/css/login.css?v=<#_VERSION_#>'
      ])

    # noraml way to load dependencies
    $ocLazyLoad.load scripts
    .then ->
      # load finished!
      ...
```
The code above *doesn't* work, and here is the error:
```
TypeError: Cannot read property '1' of null
```
And if I change the code above to something without "ocLazyLoad" it just works fine, as the code below (use head.js):
```
resolve:
  lazyLoad: ($ocLazyLoad, $q) ->
    # dependencies list
    scripts = defaultScripts.concat([
      'public/css/login.css?v=<#_VERSION_#>'
      ])

    # alternative way to load dependencies
    (do (scripts) ->
      $q (resolve, reject) ->
        head.load.apply this, scripts.concat ->
          resolve()
    ).then ->
      # load finished!
      ...
```
So, here I am now ...

**Comment by thoop** [comment]
Interesting. Thanks for that! Do you know what line of code was causing that error inside ocLazyLoad?

**Comment by phizaz** [comment]
The full error is:
```
TypeError: Cannot read property '1' of null
    at buildElement (...oclazyload/dist/ocLazyLoad.js:149:79)
    at loading (...oclazyload/dist/ocLazyLoad.js:208:29)
    at Object.m [as forEach] (...angular/angular.min.js:7:322)
    at ocLazyLoad.provider.$get.cssLoader (...oclazyload/dist/ocLazyLoad.js:207:21)
    at ocLazyLoad.provider.$get.filesLoader (...oclazyload/dist/ocLazyLoad.js:292:13)
    at Object.ocLazyLoad.provider.$get.load (...oclazyload/dist/ocLazyLoad.js:579:13)
    at ...oclazyload/dist/ocLazyLoad.js:428:42
    at Object.m [as forEach] (...angular/angular.min.js:7:322)
    at Object.ocLazyLoad.provider.$get.load (...oclazyload/dist/ocLazyLoad.js:426:23)
    at Object.t.state.resolve.lazyLoad
```
Around ocLazyLoad.js:149, I see:
```
if(!uaCssChecked) {
  var ua = navigator.userAgent.toLowerCase();

  // iOS < 6
  if(/iP(hone|od|ad)/.test(navigator.platform)) {
    var v = (navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);
    var iOSVersion = parseFloat([parseInt(v[1], 10), parseInt(v[2], 10), parseInt(v[3] || 0, 10)].join('.'));
    useCssLoadPatch = iOSVersion < 6;
  } else if(ua.indexOf("android") > -1) { // Android < 4.4
    var androidVersion = parseFloat(ua.slice(ua.indexOf("android") + 8));
    useCssLoadPatch = androidVersion < 4.4;
  } else if(ua.indexOf('safari') > -1 && ua.indexOf('chrome') == -1) {
    var safariVersion = parseFloat(ua.match(/version\/([\.\d]+)/i)[1]);
    useCssLoadPatch = safariVersion < 6;
  }
}
```
And I used this user agent to test the page:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 (development) Safari/538.1 Prerender (+https://github.com/prerender/prerender)
```

**Comment by thoop** [comment]
Looks like it's from this line:
```
var safariVersion = parseFloat(ua.match(/version\/([\.\d]+)/i)[1]);
```
That regex doesn't work with our user agent (same with chrome but they ignore chrome there)

**Comment by phizaz** [comment]
So, What's your suggestion then ? Should I report this to ocLazyLoad repo?

**Comment by mosiac** [comment]
@thoop and @phizaz Add this script to your index.html to fix this issue.


    <script type="text/javascript">
        function setUserAgent(window, userAgent) {
            if (window.navigator.userAgent != userAgent) {
                var userAgentProp = { get: function () { return userAgent; } };
                try {
                    Object.defineProperty(window.navigator, 'userAgent', userAgentProp);
                } catch (e) {
                    window.navigator = Object.create(navigator, {
                        userAgent: userAgentProp
                    });
                }
            }
        }
        if(navigator.userAgent.indexOf('Prerender') !== -1) {
            setUserAgent(window, navigator.userAgent + 'chrome');
        }
    </script>

**Comment by phizaz** [comment]
@mosiac Thanks a lot, that solves my problem beautifully.

**Comment by ZuSe** [comment]
I have exactly the same issue, but the code snippet didn't help me.
Which version of ocLazyLoad were you using? @phizaz

**Comment by gjgit** [comment]
i have the same issue and **UI Router** return blank page for me ., how you work around i did not use any ocLazyLoad .
