### ISSUE TITLE
UI router sref links don't work

### ISSUE THREAD

**Issue by unDemian** [prerender/prerender#210]
Hi,
I'm using prerender with hashbang and ui router. The links that are using ui router's sref attribute are getting autogenerated href values. The problem is that the hrefs are something like href="#!/route1" and are not working (this will get concatenated to server/?_escaped_fragment_=route2/#!/route1) because of the missing / at the start of the link. And I cannot force the value for href. Is this is an prerendering issue or phantomjs? 

Thanks a lot

**Comment by unDemian** [comment]
You can close this, actually the href was generated by ui-router's ui-sref directive. This can be fixed by using absolute urls through ui-sref-opts directive.
Sorry :)

**Comment by thoop** [comment]
Great, let me know if there's anything I can do to help!
