### ISSUE TITLE
Custom user-agent list

### ISSUE THREAD

**Issue by sabrehagen** [prerender/prerender#211]
We want to handle requests from certain bots ourselves, e.g. custom og:tags for facebook. However, prerender captures all requests that have facebook's user-agent. Is there a white/black list option? If not, what is a possible workaround?

**Comment by thoop** [comment]
This would be handled at the middleware level and is easy to do. Our middleware matches facebook's user agent by default so you'd just want to remove that user agent check from your middleware if you want to handle facebook on your own. Let me know which middleware you're using and I'd be happy to point you in the right direction.

**Comment by sabrehagen** [comment]
We're using the node middleware with this line:

app.use(require('prerender-node').set('prerenderToken', 'xxxxxxxxxxxxxxxxx'));

**Comment by thoop** [comment]
You can set the user agents explicitly like this:

```
var prerender = require('prerender-node').set('prerenderToken', 'YOUR_TOKEN');
prerender.set('crawlerUserAgents', [
  'baiduspider',
  //'facebookexternalhit',
  'twitterbot',
  'rogerbot',
  'linkedinbot',
  'embedly',
  'quora link preview',
  'showyoubot',
  'outbrain',
  'pinterest',
  'developers.google.com/+/web/snippet',
  'slackbot',
  'vkShare',
  'W3C_Validator',
  'redditbot'
]);

app.use(prerender);

**Comment by sabrehagen** [comment]
Thank you, that's fantastic. Shouldn't this be in the docs? It seems like very handy information.

**Comment by thoop** [comment]
Yeah, it probably should :)
