### ISSUE TITLE
Custom HTTP Request Headers

### ISSUE THREAD

**Issue by hocongly** [prerender/prerender#212]
We're hosting Prerender locally and an internal site we're accessing requires sending a custom HTTP header. Can this be done with Prerender? If so, would you please provide some directions?

Thank you,
Lee

**Comment by thoop** [comment]
Yep! You can create a custom plugin like this:
```
module.exports = {
    onPhantomPageCreate: function(phantom, req, res, next) {
        var headers = {
            myHeader: 'value'
        }

        req.prerender.page.setHeaders(headers, function() {
            next();
        });

    }
}
```
Then make sure to require that plugin in your server.js

**Comment by hocongly** [comment]
Great! Thank you so much...I'll give that a try!

**Comment by thoop** [comment]
Reopen this issue if you run into any problems. Going to close this for now.

**Comment by hocongly** [comment]
Not sure what I've done wrong... :(

I saved the below code to prerender/lib/plugins/httpRequestHeaders.js
<code>
module.exports = {
    onPhantomPageCreate: function(phantom, req, res, next) 
    {
        var headers = 
        {
            myHeaders: 'value'
        }

        req.prerender.page.setHeaders(headers, function() 
        {
            next();
        });
    }
};
</code>


And I added the following line into prerender/server.js before the server.start() line. Is this what you meant by "make sure to require that plugin in your server.js"?

<code>
server.use(prerender.httpRequestHeaders());
</code>

Stopped and started up prerender.
However, I still don't see "myHeaders" in the request headers. I'm using Chrome developer tools to check.

Did I miss something?

**Comment by thoop** [comment]
Yeah, you don't want to put that in another plugin. Try this:
```
server.use({
    onPhantomPageCreate: function(phantom, req, res, next) {
        var headers = {
            myHeader: 'value'
        }

        req.prerender.page.setHeaders(headers, function() {
            next();
        });

    }
});
```

**Comment by arrilot** [comment]
Looks like this is the correct way to add response header atm
```
module.exports = {
    pageLoaded: function (req, res, next) {
        req.prerender.headers['X-Was-Prerendered'] = 1;

        next();
    }
};
```
