### ISSUE TITLE
All renders cause 504 error

### ISSUE THREAD

**Issue by sabrehagen** [prerender/prerender#213]
Any time prerender tries to render our page we get a 504 error. It occurs after about 650ms. Currently the system seems to be a black box. How can we start to debug this? Is there a debug/trace option for prerender?

**Comment by thoop** [comment]
There isn't currently a debug/trace option. Sorry for the inconvenience. Can you send me the URL that you're having trouble with? I'll try to see what's going on. todd@prerender.io

**Comment by sabrehagen** [comment]
We were running pre-render node without the prerender service running locally. Sorry for the inconvenience!
