### ISSUE TITLE
?_escaped_fragment_= returns blank white page

### ISSUE THREAD

**Issue by dottodot** [prerender/prerender#214]
Doing http://stickyblood.co.uk/?_escaped_fragment_= returns a blanks white page but if I do http://myprerender.com/http://stickyblood.co.uk/ it works fine.

I'm using prerender-node middleware i.e

```
app.use(require('prerender-node').set('prerenderServiceUrl', 'http://myprerender.com'));
```

**Comment by thoop** [comment]
When you go to
`http://stickyblood.co.uk/?_escaped_fragment_=`
are you seeing any requests on the console output of your prerender server?

What status code are you seeing on that blank page response?

**Comment by dottodot** [comment]
Think I've worked it out, must be due to my nginx config as this is the output ```at=info method=GET path="/http://127.0.0.1:10070/?_escaped_fragment_="```

**Comment by thoop** [comment]
Ah, ok. Were you able to fix that? You can past host in prerender-node to get ride of that port when testing if it's problematic. You can also fix that upstream if needed for testing.
```
app.use(require('prerender-node').set('host', '127.0.0.1').set('prerenderServiceUrl', 'http://myprerender.com'));
```

**Comment by ekamnh** [comment]
Hello 

can you guys help me on this

i am also getting blank page when access url like this to check if prerender working or not

http://dkfashions.missio.io/?_escaped_fragment_=

please help

Thanks,
Ekam
