### ISSUE TITLE
Getting redirected to wrong URL

### ISSUE THREAD

**Issue by sumeetdas** [prerender/prerender#215]
OK, first a few relevant info about my app:

1. I've used HTML5 push state AND hash-bangs (because some tutorial suggested it).

2. I've used <meta name="fragment" content="!"> in my index file.

3. Since reloading pages after using HTML5 push caused 404, I've redirected them to their angular routes. So, mysite.com/animals/lion will redirect to mysite.com/#!/animals/lion

Here's the issue - if I go to 

http://service.prerender.io/http://www.mysite.com/?_escaped_fragment_=/animals/lion

I get the page rendered correctly.

However, if I go to 

http://service.prerender.io/http://www.mysite.com/animals/lion

I'm redirected to http://service.prerender.io/#!/animals/lion and of course no page gets rendered.

I have read some of the earlier issues here in this repo and know that prerender does not follow redirects. However, I just don't know what to do in order to solve this issue.

Please help!

**Comment by sumeetdas** [comment]
I have been redirecting users to www.mysite.com/animals/lion to www.mysite.com/#/animals/lion which would prevent prerender to further process the actual page and would return as soon as it receives status code 302.

I could resolve it by serving index.html for all requests. This way if I reload www.mysite.com/animals/lion and have enabled HTML5 push state, I would be served index.html file and would be redirected to /#/animals/lion in the client-side.

**Comment by thoop** [comment]
You should just use html5 push state and not combine both. That would fix this problem correctly.
