### ISSUE TITLE
I m getting this error after 3-4 hours of starting server.js 

### ISSUE THREAD

**Issue by Priyankaagrawal** [prerender/prerender#216]
events.js:72
        throw er; // Unhandled 'error' event

write EMFILE - cannot write to IPC channel.
 errnoException (child_process.js:1000:11)
 ChildProcess.target.send (child_process.js:465:16)
 Worker.send (cluster.js:406:21)
 sendInternalMessage (cluster.js:399:10)
 handleResponse (cluster.js:177:5)
 respond (cluster.js:192:5)
 Object.messageHandler.queryServer (cluster.js:247:5)
 handleMessage (cluster.js:197:32)
 ChildProcess.emit (events.js:117:20)
 handleMessage (child_process.js:322:10)

Node Version -0.10.29
Npm Version- 1.4.14

**Comment by thoop** [comment]
https://github.com/joyent/node/issues/2398

Are you on windows?
