### ISSUE TITLE
cloudfront timeout

### ISSUE THREAD

**Issue by mattetti** [prerender/prerender#218]
Hi @thoop we've recently moved our API behind cloudfront and noticed that prerender stopped working and all API calls are timing out/not going through. Prerender still gets a 200 but the page is obviously broken. I did see you mention SNI a few times, and PhantomJS 2. Since CF uses SNI, is that the root of our issue, and if that's the case, is there an alternative?

Thanks!

**Comment by thoop** [comment]
Our hosted service uses PhantomJS 2 which does not have SNI issues. Can you email me your URLs that you're seeing this issue with so I can test the timeout and see what's going on? todd@prerender.io

Thanks!

**Comment by mattetti** [comment]
Emailed you a demo url currently still behind CF, thanks!

**Comment by mattetti** [comment]
so the issue is indeed PhantomJS v1, thanks Thoop!

**Comment by mattetti** [comment]
note for others, I extracted the information I needed from this dockerfile https://hub.docker.com/r/rosenhouse/phantomjs2/~/dockerfile/ and built phantomJS v2 on ubuntu, I then uploaded the binary in a S3 bucket and setup my package.json to use prerender phantomjs2 branch.
I also exported/set `PHANTOMJS_CDNURL` as an env variable so npm would use my own version of the binary.
Finally I made sure my container also had the following runtime dependencies:   libicu-dev libfontconfig1-dev libjpeg-dev libfreetype6 openssl

**Comment by thoop** [comment]
Great, thanks @mattetti !!

**Comment by Darecjo** [comment]
I faced the same issue when we enabled cloudfront, is there a straightforward solution for this issue ?
