### ISSUE TITLE
Page renders sometimes but sometimes doesnt

### ISSUE THREAD

**Issue by biancarosa** [prerender/prerender#220]
Hi.

I'm trying to use prerender for quite a while. We're using amazon s3 cache.

I've noticed that  it takes several tries for the prerendered page to show up right. The page depends on an api call and when it returns, I set the window.prerenderReady flag, but it seems like prerender is rendering before I set the flag.

Example URL: http://www.encontreumimovelrj.com.br/flamengo/1quartos/minarea/54/maxarea/65/minprice/606000/maxprice/729000 (there's a high chance that this URL will be cached already)

**Comment by thoop** [comment]
Can you send me what the page looked like when it didn't show up right? I keep trying to render it and it seems to render correctly every time. Feel free to email me at todd@prerender.io if needed.

**Comment by biancarosa** [comment]
Without prerender: 
http://www.encontreumimovelrj.com.br/leme/4quartos/minarea/120/maxarea/180/minprice/1404000/maxprice/2105000

With prerender: 
http://www.encontreumimovelrj.com.br/leme/4quartos/minarea/120/maxarea/180/minprice/1404000/maxprice/2105000?_escaped_fragment_= or http://www.encontreumimovelrj.com.br/leme/4quartos/minarea/120/maxarea/180/minprice/1404000/maxprice/2105000/?_escaped_fragment_=

This one rendered correctly here: http://www.encontreumimovelrj.com.br/flamengo/1quartos/minarea/54/maxarea/65/minprice/606000/maxprice/729000/?_escaped_fragment_=
But not here: http://www.encontreumimovelrj.com.br/flamengo/1quartos/minarea/54/maxarea/65/minprice/606000/maxprice/729000?_escaped_fragment_=

**Comment by smaniotto** [comment]
Hi @biancarosa and @thoop,

I don't know if this is the same issue, but I'm facing some inconsistency while pre-rendering on a local server. It randomly fails sometimes with the following error:
```
TypeError: 'undefined' is not a function (evaluating 'ReactElementValidator.createElement.bind(
    null,
    type
)')
````
A quick search stated me that on phantomjs below version 2 the function bind is not implemented, but still I don't follow why sometimes it works. 

Any insights?
Thanks for the help!

**Comment by thoop** [comment]
We polyfil bind if it's not there: https://github.com/prerender/prerender/blob/master/lib/injections/bind.js

Running locally you will probably be running PhantomJS 1.9.8.

We run PhantomJS 2.0 in production which doesn't have the bind issue. I'm not sure why that would fail sometimes and not others.

**Comment by smaniotto** [comment]
I see, that might not be the problem, given this injection.

In production do you use the phantomjs2 branch?
When I run it locally I get an error:
```
2015-09-18T17:13:18.265Z phantom crashed, restarting...
2015-09-18T17:13:18.265Z starting phantom on port [12301]
```
No other feedback.

I've seen that PhantonJS version 2 is not building on Mac OS X - 10.10 (Yosemite).
When I try using Ubuntu 14.04, the installation doesn't complete (npm install), stating that PhantomJS (or a part of it) could not be found:
```
Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
```

Have you had any of these issues?

**Comment by nicolasaiz173** [comment]
Hi @thoop, I'm having some issues with Prerender. Sometimes it works, but sometimes don't.

Sometimes it shows this:

```
got 504 in 13136ms for http://www.enter.co/example-url...
phantom crashed, restarting...
starting phantom on port [12303]
started phantom
```

Sometimes shows this:
```
getting http://www.enter.co/example-url...
Experiencing infinite javascript loop. Killing phantomjs...
```

And sometimes it just works. Do you know why? Can you give me an idea of what can be happening?

Thanks :smile:

**Comment by thoop** [comment]
@nicolasaiz173 Can you send me the URLs that are having these issues? I'd be happy to look into them. todd@prerender.io

**Comment by thoop** [comment]
This issue should be fixed with our latest version of Prerender since it's upgraded to now use PhantomJS 2.1. Feel free to reopen if you are still seeing this issue.

**Comment by alisinabh** [comment]
I still got this issue with PhantomJS 2.1.1 (phridge 2.0.0)

sometimes pages randomly 

```
2017-05-05T20:44:49.721Z getting http://pre-dir.manmamanam.com/explainpost.html?PostId=13090&name=میم مثل مد&category=مد و زیبایی&categoryId=13&pageid=62#!/post/12920/کلینیک پوست دکتر زارعی/مد و زیبایی/13/2
2017-05-05T20:44:58.707Z Experiencing infinite javascript loop. Killing phantomjs...
2017-05-05T20:44:58.803Z got 504 in 9297ms for http://pre-dir.manmamanam.com/explainpost.html?PostId=286&pageid=54&category=خانه و خانواده&categoryId=24&name=میم مثل مزرعه#!/post/12257/میم مثل مهربانو/خانه و خانواده/24/52
2017-05-05T20:44:58.851Z PhantomJS restarted in the middle of this request. Aborting...
```

But when i use service.prerender.io all pages will render.

Im using master branch by the way. last commit: cb73d8605e

Thanks

**Comment by thoop** [comment]
Looks like your server might not having enough CPU/RAM available and is therefore too slow when executing the page? Can you restart your server and see if that makes things look better?
