### ISSUE TITLE
PHANTOM_WORKER_ITERATIONS affect the frequency of collapse

### ISSUE THREAD

**Issue by zhangfengGH** [prerender/prerender#221]
Now,I kown the number of iterations is how long before we forcibly shut down PhantomJS to prevent the memory leak issue. when I visit the frequency of five times per second, all phantomjs will collapse together, and then restart together, which leads to the CPU occupancy rate is very high.
.Another question, what I use is inMemoryHtmlCache, process not Shared cache? How to weigh the performance and stability?

**Comment by thoop** [comment]
5 URLs per second sounds like a little too much for PhantomJS to handle in our experience. If each URL takes 5 seconds to load then that means you would have an average of 25 pages loading at any given moment. We like to load balance across many machines to prevent those issues. The tree-kill module that we use kills phantomjs based on the worker pid. Are you seeing it kill all phantomjs instances at the same time?

If you need a cache across more than 1 worker, you shouldn't use the inMemoryHtmlCache. You should use a distributed cache like the S3 cache.

**Comment by thoop** [comment]
This should be fixed in the latest version of Prerender (4.0.3)

**Comment by zhangfengGH** [comment]
ok,I will have a try,thanks!
