### ISSUE TITLE
AWS S3 Bucket hierarchy created, but empty

### ISSUE THREAD

**Issue by Yushell** [prerender/prerender#222]
Each time I request a page, a hierarchy is created inside my bucket. For example:

`mybucket > https: > / > /www.google.com.mx`

The problem is, all folders are empty. ¿Is this normal? I can't tell if this is the intended functionality.

My Node Console reports
`2015-08-20T16:32:47.080Z getting https://www.google.com.mx/
cache hit`

All i'd like to know is if my S3 cache configuration is working correctly

**Comment by thoop** [comment]
That sounds normal. S3 just treats the `/` as a folder so two `//` together will be an "empty" folder that you can still click through to get to the rest of your files.

Also if you have a URL that ends in a `/` then S3 will show that as a folder with nothing inside. That's just how S3 decides to display things in their UI but the files are actually accessible based on their URL just fine.

Since you're seeing a cache hit, it looks like that's working as intended. Feel free to reopen if you are seeing an issue.

**Comment by Yushell** [comment]
Ok, I understand each `/` is treated as an empty folder in S3. The problem is, there are no files inside the folders. Even though I'm getting `cache hit` all folders inside S3 are empty.

Here are two screenshots

![screenshot 1](https://cloud.githubusercontent.com/assets/1242171/9413311/c57a89fc-47f6-11e5-9596-4c65a61d756d.jpg)

![screenshot 2](https://cloud.githubusercontent.com/assets/1242171/9413312/c57b7ef2-47f6-11e5-8099-767bd2007da3.jpg)

Is this normal? What should I see inside the folders?

**Comment by thoop** [comment]
Yes, that's intended.

`https://www.google.com.mx/` Is the URL in the second case.

Since S3 displays a `/` as a folder, the `www.google.com.mx` "folder" is empty.

We cache lots of pages in S3 and it works the same way for us.

**Comment by Yushell** [comment]
Thanks thoop. I guess the cache is working correctly. I was accessing the service directly through the browser's address bar. But now, I'm using the ASP.NET MVC middleware and I'm getting this in my hosted prerender service:

> 2015-08-21T22:16:56.579Z getting http://localhost:55018/
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  time: Fri Aug 21 2015 22:16:56 GMT+0000 (UTC),
  statusCode: 404,
  retryable: false,
  retryDelay: 30 }
2015-08-21T22:16:56.967Z got 504 in 388ms for http://localhost:55018/

And I'm getting a blank page when trying to spoof the UserAgent in chrome's developer tools. 504 is 'Bad Gateway'. Nothing in the response.

![screenshot 2015-08-21 1](https://cloud.githubusercontent.com/assets/1242171/9420802/a7de7f8c-482f-11e5-840a-29169ffadd80.jpg)

![screenshot 2015-08-21](https://cloud.githubusercontent.com/assets/1242171/9420801/a7dce15e-482f-11e5-8c85-44b76ce4a29a.jpg)

**Comment by thoop** [comment]
Are you using the s3HtmlCache plugin or did you create your own? It the key is not found, it shouldn't error. It should just continue on to render the page on the fly.

**Comment by alexgandy** [comment]
Piggy backing on this thread to say that I'm seeing the same thing. I'm using the s3HtmlCache plugin. The S3 object is created:

`http:` `//` `www.google.com`

But there are no contents inside of the folder(s). I've tried hardcoding the AWS credentials and granting full S3 access to the associated user/keys.

**Comment by sunshineo** [comment]
https://github.com/prerender/prerender/pull/343

**Comment by sunshineo** [comment]
![prerender](https://cloud.githubusercontent.com/assets/1072766/17997693/f62b3c66-6b24-11e6-9a4c-b6423ff9cc1a.jpg)

**Comment by thoop** [comment]
s3HtmlCache plugin is working as intended

**Comment by sunshineo** [comment]
I can make this a configuration. By default use "/". But you can set it to use "\".
Honestly, it is really confusing for new users.
