### ISSUE TITLE
PhantomJS 2.0?

### ISSUE THREAD

**Issue by shaneiseminger** [prerender/prerender#223]
We're having a lot of issues with PhantomJS crashing. I've tried various combinations of PHANTOM_CLUSTER_NUM_WORKERS and PHANTOM_WORKER_ITERATIONS, with and without caching. Some combinations are slightly more stable than others but none give acceptable performance. Right now I have PHANTOM_CLUSTER_NUM_WORKERS set to 1 (!) which seems to keep the crashes to, say, every 3-4 minutes, but obviously having every worker restart after every request isn't a good way to run things.

Looking through the other open issues here I see a number of others that look similar (e.g. "sometimes it renders, sometimes it doesn't"). With a bit more Googling it becomes apparent that PhantomJS crashes quite a bit with or without Prerender.

I understand that stability in PhantomJS 2.0 is greatly improved, and that their development efforts are focused there. Which leads me to believe that Prerender would be benefit from being able to use 2.0 (I see the composer.json pegs it at 1.9.x.). Is that on the radar? Is that a small or large undertaking?

**Comment by shaneiseminger** [comment]
Or is it possible that no one's tried it with 2.0 yet?

**Comment by thoop** [comment]
We use PhantomJS 2 fully on our hosted Prerender service. Check out our phantomjs2 branch.

Unfortunately, PhantomJS does crash more than we'd like but we try to insulate by caching heavily, load balancing requests across many different workers/machines, and we set iterations to 50 - 100.

**Comment by yagobski** [comment]
Please provide link for your phantomjs2 branch

**Comment by thoop** [comment]
They haven't officially released a phantomjs 2 binary yet so you have to compile your own PhantomJS 2 and provide a PHANTOMJS_CDNURL pointing to wherever you are hosting the version that you compiled.

**Comment by thoop** [comment]
Closing this issue since we are using phantomjs2 and it works well for us. Open a new issue if anything isn't working!

**Comment by shaneiseminger** [comment]
Belated thanks for the feedback Todd, much appreciated.

**Comment by thoop** [comment]
Sure thing!
