### ISSUE TITLE
Running Prerender on OpenShift

### ISSUE THREAD

**Issue by lammertw** [prerender/prerender#225]
I've been trying for hour to get prerender running on OpenShift. I keep getting "bind EACCES" errors. OpenShift is more restrictive with starting processes and using ports than Heroku and I believe it goes wrong when starting PhantomJS. Has anyone succeeded in running prerender on OpenShift?

**Comment by thoop** [comment]
I'm not sure if anyone has used OpenShift. Do you know how restrictive they are about ports?

**Comment by lammertw** [comment]
This is what they're saying:
    
> Please note: We don't allow arbitrary binding of ports on the externally accessible IP address.

> It is possible to bind to the internal IP with port range: 15000 - 35530. All other ports are reserved for specific processes to avoid conflicts. Since we're binding to the internal IP, you will need to use port forwarding to access it: https://openshift.redhat.com/community/blogs/getting-started-with-port-forwarding-on-openshift`

I've tried to bind on ports between that range but it still fails. I'm not sure if it's because the IP.

**Comment by thoop** [comment]
Did you set `phantomBasePort` to start PhantomJS somewhere in that range? Or did you just set the normal Prerender `PORT`?

**Comment by lammertw** [comment]
I had set the `phantomBasePort` to 16000

**Comment by thoop** [comment]
We use [phantomjs-node](https://github.com/sgentle/phantomjs-node) which lets us communicate with PhantomJS through node. It uses a library called dnode which I think uses express to communicate with PhantomJS using sockets or something so I wonder what port dnode is using? That could be an issue. 

Does your error tell you which section of code is trying to use that port that's failing? Or which port it's trying to start on?

**Comment by lammertw** [comment]
I was actually running an older version (from about a year ago) that still used the phantom cluster module. Maybe that's why it didn't work. I decided to give IBM Bluemix a try and there it does work. I'll try again on OpenShift with a newer version at some later time.

**Comment by thoop** [comment]
Ah, wow. Yeah you'll want to upgrade to a newer version! :)

**Comment by lammertw** [comment]
The main reason why I haven't upgraded yet is because I changed some things in the code to have gzipped content delivered to the plugins to cache and they also return this gzipped content. This saves a lot of space in the cached storage and also lets the contents be delivered faster because it doesn't need to be gzipped anymore before returning it to the requester. I sent some pull requests for that about a year ago and you adopted some of it but I believe the plugins still don't handle gzipped content. Do you have plans on adding support for that?

**Comment by thoop** [comment]
That would be nice to have but it makes things a little more complex since you might want some of your plugins to be able to access the non gzipped content, for example removing script tags. That would be nice though.

**Comment by thoop** [comment]
We upgraded to a new phantomjs -> node bridge that doesn't require creating an internal web server for communicating with PhantomJS. I'd suggest trying out Prerender v4.0.3 if you are still having this issue.
