### ISSUE TITLE
PhantomJS2

### ISSUE THREAD

**Issue by BrandonCopley** [prerender/prerender#227]
does the phantomjs2 branch run? I am trying to run it and getting numerous issues. I was hoping it's just my machine acting up, but I don't know if that's the case.

**Comment by thoop** [comment]
Yes it runs just fine. What issues are you having?

**Comment by dstringvc** [comment]
While researching the 'EventConstructor is not a constructor' issue, I found the phantomjs2 branch. I grabbed it and tried to run npm install on Ubuntu 14.04. The installation failed with the messages show below. I realize this is technically a PhantomJS v2 issue, but do you have any suggestions on how to proceed? Thanks!

npm ERR! Linux 3.13.0-58-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.0.0-0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.0.0-0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/projects/prerender-phantomjs2/npm-debug.log

**Comment by thedistricts** [comment]
I also have a problem with running the PhantomJS2 branch. 

I noticed the node_modules/phantomjs/bin/ exec is showing as 1kb once you run npm install. If I download the binary from http://phantomjs.org/ it shows as 14.6mb. Is this right?

**Comment by thoop** [comment]
@dstringvc you have to compile your own PhantomJS 2 if that's what you plan on using until the official builds are released. What error were you seeing before with PhantomJS 1.9.8?

@thedistricts Did you compile PhantomJS2 yourself to get the 1kb binary? Or where are you getting that binary from?

**Comment by thedistricts** [comment]
Hi - No, the 1kb binary was just through running ```npm install```. I'm I missing a step? Do I need to compile my own binary? I figured your phantom wrapper was there to download a local version to the node_module folder.

**Comment by thedistricts** [comment]
I've also forced it to download a new phantomjs 2 binary by deleting the 'var/folders/l0/24m7ff7x62z8yb09rph6fsbh0000gn/T/phantomjs/phantomjs-2.0.0-macosx.zip', running npm cache clean and deleting the node_modules folder. Same behaviour phantom crashes straight after running node server.js and the phantomjs binary is 1kb

**Comment by thoop** [comment]
Hmm, my local executable is 1kb so that seems correct.

Also, I'm not sure if our phantomjs2 branch works with the currently deployed version of phantomjsn2 by the phantomjs team. I know they were having some issues with builds on linux and that's why we compiled our own. So, right now, the phantomjs2 branch only supports compiling phantomjs 2 yourself

**Comment by dstringvc** [comment]
@thoop With PhantomJS 1.9.8, I was getting the error shown here:
TypeError: '[object EventConstructor]' is not a constructor (evaluating 'new Event('fb.load')')

Here is the code that caused the error:
$window.dispatchEvent(new Event('fb.load'));

While researching that error, I stumbled across the PrerenderIO phantom2 branch. Trying to install that branch by cloning the repo then running "npm install ...", I got the errors noted in my original post.

In the mean time, our Angular developer replaced the original code with:
$window.dispatchEvent(new CustomEvent('fb.load'));

I'm not getting the error any more so upgrading to PhantomJS v2 isn't such a high priority.

**Comment by thoop** [comment]
Ah ok great! Glad it's working. PhantomJS 1.9.8 is on an older version of webkit so it might run into issues with certain JS.

**Comment by Lochlan** [comment]
For anyone who wants to use [the phantomjs2 branch](https://github.com/prerender/prerender/tree/phantomjs2) (which my team has found is far more stable than using phantomjs1) but avoid the compilation required, I suggest using a fork of the npm phantomjs downloader.  The reason that [@thoop's phantomjs fork](https://github.com/thoop/phantomjs) works *if you compile a phantomjs2 binary first* is that it checks to see if phantomjs 2 is installed, and if it is then it skips the download.  IMO a better approach (although still a hacky one) is to have a fork of npm phantomjs that actually does downloading on your target systems.

Here is the fork of prerender that my team is planning on using in production: https://github.com/Lochlan/prerender

[The only difference](https://github.com/Lochlan/prerender/blob/phantomjs2/package.json#L15) is that I'm using [my own fork of npm phantomjs](https://github.com/Lochlan/phantomjs2), in package.json, that does successfully download on Ubuntu 14.04 and OS X (which are my only target systems right now).  To use, just use this line in package.json:

```JSON
"prerender": "git://github.com/Lochlan/prerender.git#phantomjs2",
```

(And if you want this in Travis I have [some travis config lines in the readme](https://github.com/Lochlan/phantomjs2/blob/master/README.md) that you can use.)

Anyone needing to support other systems (e.g. Windows) can use a similar approach for whatever their needs are.  [As I have mentioned elsewhere](https://github.com/Medium/phantomjs/issues/288#issuecomment-124263915) I think this is the best approach for now, while the phantomjs project is in this weird state.

**Comment by thoop** [comment]
Cool! And just a note, we host our compiled phantomjs2 binaries in our own s3 bucket and set our PHANTOMJS_CDNURL to point to it. My phantomjs fork checks for 2.0 and downloads it instead of requiring a local compilation. So you can do that to install on OSX, linux, and windows by just setting PHANTOMJS_CDNURL.

**Comment by Lochlan** [comment]
Ah, my mistake!  Thanks for clarifying, I will have our team try it out as-is!

**Comment by Lochlan** [comment]
OK, I see: you're referring to an environment variable.  Not an unreasonable solution, but IMO adding a configuration detail to deployment is a little worse than just forking the project.  (Definitely a matter of personal taste!)  Thanks for the response!

**Comment by thoop** [comment]
PhantomJS 2.1 is now enabled and running in the latest Prerender version (4.0.3). Please feel free to try it out!
