### ISSUE TITLE
[Question]  change  Accept-Language in the header

### ISSUE THREAD

**Issue by JasonSoft** [prerender/prerender#229]
Hi Folks,

I was wondering if we could change value of "Accept-Language" in the header when Prerender sends out requests to web server.  As I see it, the default value of " Accept-Language" is " en-US, * " in my case.  We'd prefer the value to be "zh-CN".  Any suggestions are welcome.  Thank you

Thanks,
Jason

**Comment by JasonSoft** [comment]
I created a plug-in to solve the problem.  You can modify the server.js file and add the following code.

```
server.use({
    onPhantomPageCreate: function(phantom, req, res, next) {
        req.prerender.page.set('customHeaders', { "Accept-Language": "en-GB" });
        next();
    }
});
```

**Comment by thoop** [comment]
Ah, cool. Yeah a plugin is a great way to do that.
