### ISSUE TITLE
Pages Not Found Only Through Prerender

### ISSUE THREAD

**Issue by CWSpear** [prerender/prerender#230]
You can see this URL is visible publicly: https://godirectfoods.com/products/meat-and-fish

However, if you try and send it through the `prerender` service (happens when running my own server or `service.prerender.io`), I get a 404. This happens with any page except the home page.

```bash
# the control
 ~/Sites/godirectfoods2 [master] ❯❯❯ curl -I https://godirectfoods.com/products/meat-and-fish
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: no-cache
Date: Sat, 05 Sep 2015 22:40:48 GMT

# any page other than home returns 404
 ~/Sites/godirectfoods2 [master] ❯❯❯ curl -I http://service.prerender.io/https://godirectfoods.com/products/meat-and-fish
HTTP/1.1 404 Not Found
Content-Length: 169
Content-Type: text/html;charset=UTF-8
Date: Sat, 05 Sep 2015 22:45:12 GMT
Server: nginx/1.4.7
vary: Accept-Encoding
X-Powered-By: Express
Connection: keep-alive

# home page works
 ~/Sites/godirectfoods2 [master] ❯❯❯ curl -I http://service.prerender.io/https://godirectfoods.com/
HTTP/1.1 200 OK
cache-control: no-cache
Content-Length: 10581
Content-Type: text/html;charset=UTF-8
Date: Sat, 05 Sep 2015 22:46:31 GMT
Server: nginx/1.4.7
vary: Accept-Encoding
X-Powered-By: Express
Connection: keep-alive
```

**Comment by CWSpear** [comment]
In the logs, it's attempting to get the correct URL, it's just not found...

There really feels like a "me not you" problem, but I'm totally stumped.

```
2015-09-05T22:36:17.426Z getting https://godirectfoods.com/products/meat-and-fish/
2015-09-05T22:36:18.052Z got 404 in 626ms for https://godirectfoods.com/products/meat-and-fish/
```

If it helps, my `location` blocks from my `nginx` config:

```nginx
server {
    listen 443 ssl;
    server_name godirectfoods.com;

    # lots of other stuff...

    location / {
        set $prerender 0;
        if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }
        if ($uri ~ "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff)") {
            set $prerender 0;
        }

        #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;

        if ($prerender = 1) {
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://localhost:9032;
        }

        try_files $uri $uri/ index.php /index.php$uri$is_args$args;
    }

    location ~ \.php {
        fastcgi_index     index.php;
        fastcgi_param     SCRIPT_FILENAME $request_filename;
        fastcgi_param     APP_ENV production;
        fastcgi_pass      unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param     SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param     PATH_INFO          $fastcgi_path_info;
        include fastcgi_params;
    }
}

**Comment by thoop** [comment]
Hmm, yeah it's weird we're seeing an nginx 404 page. Do you have anything in your `# lots of other stuff...` section that would cause that? Are you doing any user agent checking?

**Comment by CWSpear** [comment]
Just SLL stuff and logs and root:

```nginx
    client_max_body_size 20M;

    ssl_certificate         /etc/ssl/private/star_godirectfoods_com_bundle.crt;
    ssl_certificate_key     /etc/ssl/private/star_godirectfoods_com.key;
    ssl_protocols                   TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers       on;
    ssl_session_timeout 5m;

    access_log  /var/log/nginx/godirectfoods.access.log;
    error_log   /var/log/nginx/godirectfoods.error.log;

    index  index.html index.htm index.php;
    root   /www/godirectfoods/current/public;

    # allow CloudFront to access webfonts CORS style
    location ~* \.(eot|ttf|woff|svg)$ {
        add_header Access-Control-Allow-Origin *;
    }
```

Just didn't want to add it to make the paste so large as to distract, etc.

**Comment by CWSpear** [comment]
@thoop Is there any more information you need that might help? Any idea why something like this might happen?

**Comment by thoop** [comment]
If I spoof my user agent in Chrome to:
```
Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 (development) Safari/538.1 Prerender (+https://github.com/prerender/prerender)
```
I see the 404 in Chrome so it does seem like it's a user agent check somewhere

**Comment by SinisaG** [comment]
@CWSpear  - Did you maybe come to the bottom of this?

**Comment by CWSpear** [comment]
Unfortunately, no. But not for lack of trying. We (my sysadmin and me) debugged a lot and we tracked it down to something to do with setting `$prerender` back to `0`.

So if we remove this block:

```nginx
if ($http_user_agent ~ "Prerender") {
    set $prerender 0;
}
```

Then the basic curl tests and such pass. We cannot, for the life of us, figure out why that would made a difference, since `$prerender` should already be `0`, but in theory, as long as the request from Prerender doesn't do something to set trigger `$prerender` to be `1`, this should work...? Does Prerender forward any of those headers/the user agent, etc?

**Comment by thoop** [comment]
It's certainly possible to forward the user agent and headers but we don't by default.

We always send a header: `X-Prerender: 1` on every request so you might be able to check for that instead and set $prerender to 0

**Comment by thoop** [comment]
@CWSpear did you ever fix this issue from your end?

**Comment by CWSpear** [comment]
Nothing beyond what I'd already reported about removing the one block. Couldn't ever figure out why it would cause that.

**Comment by noogen** [comment]
I don't know if this is related but I'm also getting this 404 on relative assets trying to build latest Prerender Docker image.  I run a Docker instance build on v4.0.4 build before March and didn't have any issue.  I fork Prerender and revert commit back to 4.0.4 but still has the issue with new Docker build.  As a result, I suspect my issue is related to phridge or Phantomjs.

**Comment by thoop** [comment]
Interesting, thanks!

**Comment by thoop** [comment]
Closing this issue. Feel free to reopen if anyone runs into this. I'm wondering if this is an "if is evil" issue: https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by CWSpear** [comment]
Thanks!
