### ISSUE TITLE
Bing Problem

### ISSUE THREAD

**Issue by leopoiroux** [prerender/prerender#232]
Hi,
Bing call my prerender with this URL, can you help me ?
http://www.my-website.com/rubrics/page&_escaped_fragment_=/article-389227?tab=map

PS : I need the "?" at the end of the url :)

Thks

**Comment by thoop** [comment]
Can you send me the URL from your nginx (or other) server logs? Is that the URL that was shown in the Prerender console?

**Comment by leopoiroux** [comment]
I see this URL in the access log of my the node server :+1: 

Here is the actual address :
```[15/Sep/2015:10:28:40 +0000] "GET /http://www.beaune-tourism.com/discover/nature-hiking/suggested-itineraries&_escaped_fragment_=/circuit-18-the-trail-of-the-rocks-618422?tab=elevation HTTP/1.0" 404 10972 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"````

**Comment by thoop** [comment]
That's really weird. That's not even a valid URL. Are they accessing all of your URLs like that? Or did you only see one?

**Comment by leopoiroux** [comment]
Only Bing that generates this type of address. It does only when there is a "?" after the "#!". Microsoft People are crazy :) 
I have thousands of log lines with this type of address

**Comment by thoop** [comment]
I'll do some more research on our end. I'd recommend switching to html5 push state but I'll let you know what I find since we'll have to change how we parse URLs in that case.

**Comment by leopoiroux** [comment]
Thank you for your help, I will study the transition to HTMLT5 push state. I await your return.

**Comment by thoop** [comment]
We fixed some problems with our URLs generating double query strings but this should be fixed unless Bing actually found some URLs that looked like:

`http://yourwebsite.com/http://www.beaune-tourism.com/discover/nature-hiking/suggested-itineraries#!/circuit-18-the-trail-of-the-rocks-618422?tab=elevation'

Feel free to reopen if you still run into issues.

**Comment by thoop** [comment]
Also, we published a new version of Prerender that you should try if you are testing this locally.
