### ISSUE TITLE
Crashes on start: Error: Module version mismatch. Expected 46, got 14.

### ISSUE THREAD

**Issue by svenstaro** [prerender/prerender#233]
Node 4.1.0. I run it like this:

    node prerender/server.js

It used to work quite well but I think the node update to 4.1.0 broke it.

Sep 17 16:27:30 apoc prerender[14574]: 2015-09-17T16:27:30.913Z worker 612 died, restarting!
Sep 17 16:27:30 apoc prerender[14574]: /srv/prerender/node_modules/prerender/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:83
Sep 17 16:27:30 apoc prerender[14574]: throw e
Sep 17 16:27:30 apoc prerender[14574]: ^
Sep 17 16:27:30 apoc prerender[14574]: Error: Module version mismatch. Expected 46, got 14.
Sep 17 16:27:30 apoc prerender[14574]: at Error (native)
Sep 17 16:27:30 apoc prerender[14574]: at Module.load (module.js:355:32)
Sep 17 16:27:30 apoc prerender[14574]: at Function.Module._load (module.js:310:12)
Sep 17 16:27:30 apoc prerender[14574]: at Module.require (module.js:365:17)
Sep 17 16:27:30 apoc prerender[14574]: at require (module.js:384:17)
Sep 17 16:27:30 apoc prerender[14574]: at bindings (/srv/prerender/node_modules/prerender/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
Sep 17 16:27:30 apoc prerender[14574]: at Object.<anonymous> (/srv/prerender/node_modules/prerender/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
Sep 17 16:27:30 apoc prerender[14574]: at Module._compile (module.js:434:26)
Sep 17 16:27:30 apoc prerender[14574]: at Object.Module._extensions..js (module.js:452:10)

**Comment by svenstaro** [comment]
I also tested 0.12.7 (works) and 4.0.0 (also broken).

**Comment by thoop** [comment]
Looks like something to do with node-weak. We haven't upgraded past 0.12 so node 4.0 isn't supported yet.

**Comment by svenstaro** [comment]
You might want to look at this soon since 4.0 is the current stable version and many people might run into this soon. I, for one, would appreciate it.

**Comment by stanislavromanov** [comment]
You need to `npm remove ...` and `npm install ...`. Basically you need to rebuild the package that is causing the error in newer node version.

**Comment by svenstaro** [comment]
I deleted my node_modules. Isn't that good enough?

**Comment by stanislavromanov** [comment]
@svenstaro How can you even run your application without node_modules?

The reason why you need to re-build those is because some modules store NODE_VERSION constant which is used later so when you update your node version the numbers don't match thus you get the error.

**Comment by svenstaro** [comment]
Well, they get rebuild, obviously. Therefore I was wondering whether I'd need to manually do the procedure you mentioned.

**Comment by stanislavromanov** [comment]
Ah, yea sorry. My bad. You're correct.

**Comment by thoop** [comment]
Our latest version of Prerender (4.0.3) runs correctly on node v4.2.6. Please reopen if you see issues.
