### ISSUE TITLE
Determine When Pages Completed

### ISSUE THREAD

**Issue by hocongly** [prerender/prerender#234]
The pages we're accessing vary in size and further AngularJS processing...so some pages take a few second while others take 30+ seconds to complete. Using the default timers in lib/server.js, we're getting incomplete contents for large and/or complex pages.

How can we reliably determine when a page is completed?

Thank you!

**Comment by ginovva320** [comment]
I've had success using `window.prerenderReady = true;`. It's documented on the [prerender.io site](https://prerender.io/documentation/best-practices).

**Comment by thoop** [comment]
Thanks @ginovva320! `window.prerenderReady` is the currently supported way to handle pages that take longer to load/render than can be reliably determined by our default way of counting the number of requests in flight.
