### ISSUE TITLE
Installation prerender-phantomjs2 failed

### ISSUE THREAD

**Issue by dugainet** [prerender/prerender#236]
I have the same issue as this topic: 
https://github.com/prerender/prerender/issues/148

It would be nice to have a guide on how to install the software.. thank you

**Comment by dugainet** [comment]
The link to binary version of phantomjs have been updated by some "stupid" guy. I have fixed it by : 
- open package.json, replace    
 "phantomjs": "git+something"  
by
 "phantomjs": "git+https://github.com/dugainet/phantomjs.git",

**Comment by antoineco** [comment]
@dugainet maybe you could send a push request with your changes so that all users of prerender + phantomjs2 can benefit from your update?
