### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by thedistricts** [prerender/prerender#237]
I've had a good read of the docs, google and past issues but can't find any leads on my problem with Prerender.

I have an Angular app and a Prerender server with the S3 plugin running locally on Node.  I also have window.prerenderReady both within the page markup and the app to signal when it's an appropriate time to grab the page.

Everything tests well using the Google URL example both directly on the Prerender server and using the middleware. When I request a page from my app, however, I get the surrounding HTML but no JS derived content. In the console is logged  

```phantom stdout: ReferenceError: Can't find variable: Location```

```phantom stdout:   http://localhost:5000/scripts/8381dd7b.all.min.js:9 http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:30 in d http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:32```

```Timed out. Sending request with HTML on the page
got 200 in 12380ms for http://localhost:5000/login?cache=223```

Any ideas? Could it be an issue with pulling the angular scripts from a CDN?

**Comment by thoop** [comment]
It looks like `Location` is a global variable in Chrome so PhantomJS might not support it. Try using a polyfill for `Location` or just checking for the existence before using it.
