### ISSUE TITLE
Phantom crash after some requests

### ISSUE THREAD

**Issue by dmitriy-dokshin** [prerender/prerender#238]
2015-10-06T08:21:38.432Z phantom crashed, restarting...
2015-10-06T08:21:38.432Z starting phantom on port [12308]

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at SharedHandle.add (cluster.js:97:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

**Comment by dmitriy-dokshin** [comment]
I uncommented "server.use(prerender.logger());" in server.js and found many identical messages in the output:
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
Error: Problem parsing d="M NaN NaN A 35 35 0 1 0 39 4"
After one of the blocks of these messages phantom crashed.

**Comment by thoop** [comment]
Hmm, I've never seen that message. Is that something that you're doing in your code?

**Comment by dmitriy-dokshin** [comment]
Yes, now we found it in the SVG code of one indicator. It's not clear why it works so.

**Comment by thoop** [comment]
I haven't seen that before. Can you send me the URL you're trying so that I can see if it runs on my phantomjs? todd@prerender.io

**Comment by thoop** [comment]
We upgraded to a new phantomjs -> node bridge in version 4.0.3 of Prerender. Please try upgrading and let me know how that works out.
