### ISSUE TITLE
 Use of '&' escaped or not in URL

### ISSUE THREAD

**Issue by Desmodue** [prerender/prerender#239]
Hi
My Angular routes sometimes contain '&'. Whether this is encoded or not the page fails to work correctly when passed through prerender. Within lib/util.js in the getUrl function the url is decoded and split into parts using url.parse().
The return values are incorrect, see below

This is the route passed in

http://localhost/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20%26%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders

This is the value of realUrl in the function, which is correct

http://localhost/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20%26%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders

This is then decoded into var decodedUrl, still ok

http://localhost/?_escaped_fragment_=/shop/BMW/3 SERIES/83-93/E30 3 SERIES 320, 323 & 325/Front - Brake Calipers and Wheel cylinders

var parts from parts = url.parse(decodedUrl, true); This is where it all gets messed up

{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'localhost',
  port: null,
  hostname: 'localhost',
  hash: '#!/shop/BMW/3 SERIES/83-93/E30 3 SERIES 320, 323 ',
  query: { ' 325/Front - Brake Calipers and Wheel cylinders': '' },
  pathname: '/',
  path: '/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20&%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders',
  href: 'http://localhost/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20&%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders' }

Not a lot I can do with the inbuilt Node url function, so as a test I commented out the decodeURI part to see if not decoding it would work

/*try {
        decodedUrl = decodeURIComponent(realUrl);
    } catch (e) {
        decodedUrl = realUrl;
    }*/

It works !

So my question is, why are you decoding the URI ? as this appears to break url.parse() when '&' is encoded in the route. 

Regards

Gary

**Comment by thoop** [comment]
We decode the URL because the URL can be encoded according to Google's escaped fragment protocol. I'll look into this and see what we can do here to make sure this works correctly in all cases

**Comment by Desmodue** [comment]
Maybe this will help, it passes all of my testing.... just a small reactoring of the util.getUrl function. Basically it changes '?_escaped_fragment_= ' to not look like a query parameter, i.e. remove '?' and '='. It is then just a place holder. I also moved the Bing anomaly higher up and do the same replacement. Once the URI has been decoded and url parsed, the '_escaped_fragment_' place holder is replaced with '#!' ( only string elements though). From then on the url format works as expected. No need to delete elements of parts or concatenate to create the hash. Admittedly my testing is fairly limited.
```javascript
util.getUrl = function (req) {
	var decodedUrl, 
		realUrl = req.url,
		parts;

	realUrl = realUrl.replace(/^\//, '');
	// Alter ?_escaped_fragment_= so that it does not look like a query param
	realUrl = realUrl.replace('?_escaped_fragment_=', '_escaped_fragment_');
	// Bing was seen accessing a URL like /?&_escaped_fragment_=
	realUrl = realUrl.replace('?&_escaped_fragment_=', '_escaped_fragment_');

	try {
		decodedUrl = decodeURIComponent(realUrl);
	} catch (e) {
		decodedUrl = realUrl;
	}
	parts = url.parse(decodedUrl, true);
	// Replace the _escaped_fragment_ place holder in any string elements
	for (var key in parts) {
		if (parts.hasOwnProperty(key)) {
			if (typeof parts[key] === 'string') {
				parts[key] = parts[key].replace('_escaped_fragment_', '#!');
			}
		}
	}
	var newUrl = url.format(parts);
	//url.format encodes spaces but not arabic characters. decode it here so we can encode it all correctly later
	try {
		return decodeURIComponent(newUrl);
	} catch (e) {
		return newUrl;
	}
};

**Comment by thoop** [comment]
Thanks! I'll look into this.

**Comment by thoop** [comment]
We decode & correctly now in the URL and have some tests to verify that. Please reopen if you are still seeing a problem here. Please upgrade to our latest version of Prerender if you are going to test locally.
