### ISSUE TITLE
Odd 403 error

### ISSUE THREAD

**Issue by graywithanA** [prerender/prerender#241]
When running my own prerender server via WebFaction and attempting to prerender my site I'm getting the following output in the console:

```
2015-10-13T19:27:52.549Z getting https://foo.bar.com/
{ [AccessDenied: Access Denied]
  message: 'Access Denied',
  code: 'AccessDenied',
  time: Tue Oct 13 2015 19:27:52 GMT+0000 (UTC),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }
2015-10-13T19:27:54.887Z got 200 in 2338ms for https://foo.bar.com/
{ [AccessDenied: Access Denied]
  message: 'Access Denied',
  code: 'AccessDenied',
  time: Tue Oct 13 2015 19:27:55 GMT+0000 (UTC),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }
```

Despite the above the page seems to be prerendering fine.

Yesterday, when I ran the prerender server locally on my machine the page would render fine and I wouldn't get the 'access denied' output in console, only:
```
2015-10-13T19:32:36.743Z getting https://foo.bar.com/
2015-10-13T19:32:47.020Z got 200 in 10277ms for https://foo.bar.com/
```  
Today when I run the server locally I get the same output as yesterday but the page is rendered blank (white).  I'm currently on an airplane though so I wonder if there's something odd happening because of that.  I'll try the local server again when I'm on the ground and report back.

Any idea why I'd be getting the 403 output when running the server via WF?

**Comment by thoop** [comment]
That looks like an Access Denied response from AWS. Are you using s3 caching? Are you providing the correct token?

**Comment by graywithanA** [comment]
I am attempting to use the s3 cache but now that you mention it I don't see any files in the bucket. I'll check the key, that's gotta be the issue. I didn't set it up on the local server so that would explain why I didn't see the error on that server.

Thanks for you prompt reply.

**Comment by graywithanA** [comment]
You were right, this was an S3 error.  Thank you.
