### ISSUE TITLE
Prerender spawns exponentially growing number of phantomjs processes

### ISSUE THREAD

**Issue by fatalbanana** [prerender/prerender#243]
It seems that in some case (when phantomjs is crashing at fairly rapid rate?) prerender will spawn more phantomjs processes than it started out with (which leads to exponentially growing number of processes).

Log:
https://gist.github.com/fatalbanana/edb5841dbcf53458128a

$ grep 'started phantom' the.log | wc -l
40
$ grep 'phantom crashed' the.log | wc -l
40
$ grep 'starting phantom' the.log | wc -l
44

... And we came out of this with 4 extra `phantomjs` processes.

Tested @ prerender 3.22.1 (Nodejs v0.12.7 & Nodejs v4.2.0) - running under supervision by `runit` fwiw.

Let me know if any further information may be useful.

**Comment by thoop** [comment]
How many iterations are you using? And are you using any other config options when starting your Prerender server? Can you talk a little more about "at a fairly rapid rate"? What are the specs on the server that you are running Prerender on?

**Comment by fatalbanana** [comment]
Iterations is set to 10. Script here: https://gist.github.com/fatalbanana/6a518b07b55dd203e1c7 - I'm using a handful of custom-built modules (comments added in script explaining what these do).

Timestamps in the logfile will give some indication as to the rate of crashes- I'm not sure if this only happens when it's crashing at such a rate.

Prerender is running inside a Docker container alongside other containers; no resource limits applied; typically with plenty free RAM/CPU (Intel® Core™ i7-4770 (so 8 children normally), 32GB RAM).

**Comment by fatalbanana** [comment]
Not apparent to me where the problem actually lies but disabling `prerender-redis-cache` appears to solve the problem.

Will comment if I manage to find out something further.

**Comment by thoop** [comment]
Interesting, please do!

**Comment by jonlinper** [comment]
Hello,

How to reproduce this problem:
1. Set WORKERS to 1
2. Set ITERATIONS to 1
3. Call one task.
4. Call another task before the first one has been completed.

When first tasks completes, Phantom is terminated (due to iterations=1).
The second task is in progress, and fires "PhantomJS restarted in the middle of this request. Aborting...".
Finally 2 Phantom processes are started.

> 2016-02-26T23:25:20.491Z getting http://localhost:5202/page/1
> 2016-02-26T23:25:20.701Z getting http://localhost:5202/page/2
> 2016-02-26T23:25:21.127Z got 200 in 636ms for http://localhost:5202/page/1
> 2016-02-26T23:25:21.190Z phantomjs terminated
> 2016-02-26T23:25:21.190Z starting phantom...
> PhantomJS restarted in the middle of this request. Aborting...
> 2016-02-26T23:25:22.035Z got 504 in 1333ms for http://localhost:5202/page/2
> 2016-02-26T23:25:22.036Z phantomjs terminated
> 2016-02-26T23:25:22.038Z starting phantom...
> 2016-02-26T23:25:23.788Z started phantom
> 2016-02-26T23:25:25.008Z started phantom

**Comment by thoop** [comment]
Fixed by https://github.com/prerender/prerender/pull/289
