### ISSUE TITLE
304 status response

### ISSUE THREAD

**Issue by twoheaded** [prerender/prerender#245]
I'm use Phantomjs 2, prerender-node middleware and own prerender service.
On first request on `http://mysite.com/?_escaped_fragment_=` I'm got my prerendered page. It's ok.
But in second times I'm got empty body and 304 status.
The same thing when i try in other brouser, where this page wasn't open before. In anonymizer the same problem. Empty page and 304 status.
It's looks like Phantome keeps rendered page in cache. But i don't know, how to clear it.
Or this is how it should work?

**Comment by thoop** [comment]
That should be fine. Does your browser still show the correct page when it receives the 304? You should be caching your pages so that doesn't happen.

**Comment by twoheaded** [comment]
No. If the browser cache is disabled, the response comes 304 status and a blank page. 
![1](https://cloud.githubusercontent.com/assets/15314781/11044193/6ec385f8-8731-11e5-8944-d0de6cc6dd23.jpg)

I suppose that if you disable your browser cache server must always return a 200 status and rendered page, as the request does not have headers If-None-Match and If-Modified-Since.
Now I try to add prerender-mongodb-cache. Perhaps it will solve the problem.

**Comment by thoop** [comment]
Let me know if those changes help!

**Comment by twoheaded** [comment]
I added mongo cache plugin with processing 304 status  in method "beforeSend." It seems that it works well. Thank you

**Comment by hooke** [comment]
@twoheaded , got the same problem. Could you please explain how 304 status is processed in beforeSend method? Haven't found  it in your fork of mongo cache plugin :(

**Comment by twoheaded** [comment]
@hooke , try to look my [prerender2 branch](https://github.com/twoheaded/prerender/commit/d7b7bed43e1efc7f8bdc83c82e0c283a034107f4)

**Comment by hooke** [comment]
@twoheaded , thanks, got it. Though, it doesn't help :smile:. As I've found out, the problem was with PhantomJS itself, it is caching pages in local storage and memory, and server answers with 304, though PhantomJS couldn't build page correctly after :disappointed: 

So I am playing with [prerender-clear-local-storage](/hightail/prerender-clear-local-storage) and [clearMemoryCaches](/ariya/phantomjs/commit/5768b705a0)

**Comment by thoop** [comment]
Looks like a command to disable local storage should be coming out in a newer version of PhantomJS

https://github.com/ariya/phantomjs/commit/fc57497166b85678d5a6616019c8c21139b74d05

**Comment by hooke** [comment]
Well, disabling local storage still may not help with memory cache?

**Comment by S-YOU** [comment]
btw, I personally adding `customHeaders['Cache-Control'] = 'no-cache';`
in lib/plugins/sendPrerenderHeader.js to solve 304 issue.

**Comment by hooke** [comment]
@S-YOU thank you for the solution, I will try it!
 At the moment I am clearing memory cache using clearMemoryCache() along with clearing local storage before page disposing in [lib/server.js](/hooke/prerender/commit/c906e23fc4248afb36d60bd4539edf1decd86b53)

**Comment by rodrigo-barraza** [comment]
Am I ever glad I'm not the one one with this issue, and not the first one either. Hopefully that fix works @S-YOU

**Comment by cbbaaa1989** [comment]
@S-YOU i add customHeaders['Cache-Control'] = 'no-cache';
but it doesn't work,how can i resolve the problem

**Comment by S-YOU** [comment]
@cbbaaa1989, please take a look at your request/response headers as in https://github.com/prerender/prerender/issues/245#issuecomment-155167066

**Comment by nottix** [comment]
I'm having the same issue, any plan to release a fix? Thank you.

**Comment by thoop** [comment]
Yes! We will be releasing a fix for this soon.
