### ISSUE TITLE
Enable resource caching in PhantomJS

### ISSUE THREAD

**Issue by thedarklord1** [prerender/prerender#247]
Hey, Thanks a ton for this awesome project. 
My PhantomJS is not caching my web resources like JS/CSS etc, and making a server hit every time a URL comes to it. A quick google gave me [this link](http://stackoverflow.com/questions/22822617/how-do-i-make-phantom-js-cache-resources-like-a-normal-browser) which says to enable caching in the PhantomJS, by giving flag `disk-cache=True` while starting it. But, when I `grep` my PhantomJS process (`phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1 shim.js 12347 127.0.0.1`) , this flag is not there. My question is how to provide this flag to PhantomJS instance, so that PhantomJS caches the resources?

**Comment by sschueller** [comment]
You can set phantomjs paramters in the server.js file like so:

```
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
    workers: process.env.PHANTOM_CLUSTER_NUM_WORKERS || 4,
    iterations: process.env.PHANTOM_WORKER_ITERATIONS || 10,
    phantomBasePort: process.env.PHANTOM_CLUSTER_BASE_PORT || 12300,
    messageTimeout: process.env.PHANTOM_CLUSTER_MESSAGE_TIMEOUT,
    phantomArguments: ['--load-images=false','--ignore-ssl-errors=true','--ssl-protocol= tlsv1', '--disk-cache=true']
});

.....
```

**Comment by thedarklord1** [comment]
Hey Thanks @sschueller :))
I figured that out after some code browsing.

**Comment by talbenbasat** [comment]
just for the documentation the phantomArguments is now a json instead of an array
```
var server = prerender({
    workers: process.env.PRERENDER_NUM_WORKERS,
    iterations: process.env.PRERENDER_NUM_ITERATIONS,
    phantomArguments: { '--load-images': false, '--disk-cache': true },
});
```
