### ISSUE TITLE
httpHeaders and caching plugins

### ISSUE THREAD

**Issue by s4tori** [prerender/prerender#248]
Hi,

The "httpHeaders" plugin implements the `beforeSend` method.
But all cache plugins (s3HtmlCache, inMemoryHtmlCache, prerender-redis-cache) use `afterPhantomRequest`.

Even if "httpHeaders" detects a custom header (404 for example), the result page will be stored in the cache.
It could be useful to use the `afterPhantomRequest` method (instead of `beforeSend`) for the "httpHeaders" plugin.

```js
Example: 
   prerenderServer.use(prerender.httpHeaders());
   prerenderServer.use(prerender.<cachePlugin>());

With beforeSend: 
   200 ---> cache plugin ---> httpHeaders : next()        ---> end
   404 ---> cache plugin ---> httpHeaders : res.send(404) ---> end

With afterPhantomRequest: 
   200 ---> httpHeaders : next()        ---> cache plugin ---> end
   404 ---> httpHeaders : res.send(404) ---------------------> end
```

What do you think about it?

**Comment by thoop** [comment]
Yeah, you're right. We've been using a custom httpHeaders plugin that didn't have this issue so this one went unnoticed. Do you want to send a pull request? You can just change the httpHeaders plugin from beforeSend to afterPhantomRequest. If not, let me know and we'll make the change.

Thanks!

**Comment by s4tori** [comment]
No problem, I will.
