### ISSUE TITLE
npm install Error making request.

### ISSUE THREAD

**Issue by montagez** [prerender/prerender#249]
> phantomjs@1.9.18 install /app/data/site/prerender/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /app/data/site/prerender/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: socket hang up
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at CleartextStream.read [as _read] (tls.js:499:24)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! weird error 1
npm ERR! not ok code 0

under  prerender/
when i run # npm install 
show this error.

**Comment by thoop** [comment]
Which version of NPM are you using? Can you post your npm-debug.log?

**Comment by intellix** [comment]
Getting this as well actually. I'm trying the PhantomJS2 branch and get something similar:

This causes a 404: `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2`.

Looked at the list of downloads and that file doesn't exist. There's a 2.1.1 and can't find the reference to 2.0.0 anywhere, it seems to be using a fork of yours?

Tried this on 0.12.6 and now just tried 4.2.6 to get the same error... will keep digging

**Comment by thoop** [comment]
Our phantomjs2 branch is meant for a custom compiled version of PhantomJS 2.0. We are not yet able to run Prerender with PhantomJS 2.1.

**Comment by thoop** [comment]
We just pushed phantomjs 2.1 support to our master branch using a new phantomjs -> node bridge. Reopen this issue if you run into problems but this should be fixed.
