### ISSUE TITLE
Page running on custom port throws 404

### ISSUE THREAD

**Issue by antoineco** [prerender/prerender#250]
I run my development environments on non standard ports and use the official nginx middleware configuration. Because of that I had to replace `$host` by `$http_host`, unfortunately this is not enough and prerender responds with a 404 as soon as the requested URL contains ":port".

Example:
```
# curl -I -H "X-Prerender-Token: <token>" http://service.prerender.io/http://example.com:32516/en
HTTP/1.1 404 Not Found
```
```
# curl -I http://example.com:32516/en
HTTP/1.1 200 OK
```

I tried to reproduce this on a local environment with prerender  3.22.1. The prerender logs show:
```
2015-11-29T20:08:00.505Z getting http://example.com:32516/en/
2015-11-29T20:08:01.228Z got 404 in 723ms for http://example.com:32516/en/
```

**Comment by antoineco** [comment]
My bad, I though I could replace

```
if ($prerender = 0) {
  rewrite .* /index.html break;
}
```

by a `try_files` directive. I wrongly assumed this would work as long as $prerender != 1, but it doesn't when proxied through Prerender.

**Comment by thoop** [comment]
No problem!

**Comment by antoineco** [comment]
I found my answer here to be more precise: https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

try_files is never evaluated because of `if ($prerender = 0)`, and my backend happened to run with this setup, so the 404 was not related to prerender but to the nginx config.

**Comment by ghfkui** [comment]
Hi, @antoineco，could you help me?
IThe same problem is with me. My nginx.conf is following:
`location / {
            root   /dist;
			try_files $uri @prerender;
            # try_files $uri $uri/ /index.html;
            # index  index.html index.htm;
			
        }

        location @prerender {
            # proxy_set_header X-Prerender-Token YOUR_TOKEN;
            
            set $prerender 0;
            if ($http_user_agent ~* "googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest\/0\.|pinterestbot|slackbot|vkShare|W3C_Validator|whatsapp") {
                set $prerender 1;
            }
            if ($args ~ "_escaped_fragment_") {
                set $prerender 1;
            }
            if ($http_user_agent ~ "Prerender") {
                set $prerender 0;
            }
            if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") {
                set $prerender 0;
            }
            
            #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
            resolver 8.8.8.8;
    
            if ($prerender = 1) {
                #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
                set $prerender "127.0.0.1:3000";
                rewrite .* /$scheme://$host$request_uri? break;
                proxy_pass http://$prerender;
                break;
            }
            try_files $uri $uri/ /index.html;
        }`
when I using the command: curl http://localhost:3000/render?url=http://localhost
The result is right. But when I using the command: curl http://localhost:3000/render?url=http://localhost/help
The result is 404.  Could you tell me how to resolve it? Thanks in advance.

**Comment by ghfkui** [comment]
Resolved the problem as the method in https://github.com/prerender/prerender/issues/230.
Just remove the code
`if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }`
