### ISSUE TITLE
Problem integrating with prerender.io (PHP lavarel prerender middleware)

### ISSUE THREAD

**Issue by kaiwangjimmy** [prerender/prerender#251]
Hi,

I am trying to set up prerender.io for our website. But I have problem integrating with service.prerender.io.

Our web app is using PHP Lavarel and knockoutjs as the main framework.

I have already set up the PHP lavarel prerender middleware.
I also set up the code prerender server running as http://localhost:3000

The url of our web app is like: https://example.com/#!/support (we use hashbang #!)

When I test it locally, it works well. When I get access to https://localhost/?_escaped_fragment_=/support in browser, it returns static HTML. and the log in nodejs console looks good.

Then I change 'prerender_url' => 'https://service.prerender.io', and set up 'prerender_token' and deployed it to amazon web service.
The web server is behind load balancer(ELB).

The following url also works fine
https://service.prerender.io/https://example.com/?_escaped_fragment_=/support
I can get back static html.

But if i directly try to get access to
https://example.com/?_escaped_fragment_=/support
There is no response returned.

From prerender.io web console's crawl status, I can see the status code is 302.

I have no idea what the problem is. Please give help!

Thanks,

**Comment by thoop** [comment]
It sounds like you might be sending an `http` URL to our prerender service? If you are using SSL termination at the load balancer, then your middleware might be seeing the http URL instead of the https URL so it's just forwarding the http URL to us. We would then try to access the http URL and get an http -> https redirect and return that to the crawler.

Can you try to force your middleware to send an https URL to us in production?

**Comment by kaiwangjimmy** [comment]
I have fixed the problem change http to https.
Now when I load in chrome
https://example.com/?_escaped_fragment_=/support

From Chrome's Network console, I see finally 502 http code returned and I cannot see the web page.
But in prerender.io web console, I can see that page is cached successfully and from Crawl Stats, I see that URL and the status Code is 200.

Is it normal?

**Comment by thoop** [comment]
Hmm, no that isn't normal. If we are returning a 200 status code, your middleware should also return a 200 status code. Are you able to debug the middleware or look in your logs for hints at what's causing the 502?

**Comment by kaiwangjimmy** [comment]
I think I have fixed the problem. The reason is basically not accept the php server's response with the header of service.prerender.io.  I have to change the header to the php web server's own header.
