### ISSUE TITLE
script tags not removed

### ISSUE THREAD

**Issue by antoineco** [prerender/prerender#255]
I use a self-deployed prerender instance (phantomjs2 branch, current HEAD) internally for testing purposes. The server is configured with all the default settings and I enabled the following plugins:
```
server.use(prerender.removeScriptTags());
server.use(require('prerender-redis-cache'));
```
* Pages are cached in redis with the expected HTML content but all `<script>` tags remain.
* Pages proxied through the hosted service are rendered without `<script>` tags.

If I perform a diff of pages from my local redis and from the hosted prerender service the only difference is the presence of `<script>` tags (test page: https://www.freeletics.com/en/)

Did I miss something, or is that a regression?

**Comment by antoineco** [comment]
Looks like a wrong assumption on my side, pages are actually served by the (nginx) prerender middleware **without** script tags, but nevertheless cached with the tags in redis.

If that's by design please let me know and I'll send a PR to add a note about it in the readme.

**Comment by thoop** [comment]
That was initially intended since the `removeScriptTags` plugin implements the `beforeSend` function but I think that could probably be changed to the `afterPhantomRequest` function to let you cache pages without the script tags so that they don't have to be removed every time the page is requested.

**Comment by antoineco** [comment]
Thanks for the answer @thoop. I'm absolutely fine with keeping the tags in cache as long as the html is served without them. It might even be a good thing for people who decide to re-enable script tags, this way they don't have to render cached pages one more time.

I was just surprised to see them when I analyzed the content of my Redis db. Therefore I think this should be mentioned in the readme, a simple note is probably enough.

I'll send a PR
