### ISSUE TITLE
baidu issues

### ISSUE THREAD

**Issue by zhangfengGH** [prerender/prerender#259]
Dear, in the chrome simulation Baiduspider is very fast,but Baidu webmaster tools to grab the page is very slow, what is the reason?

**Comment by thoop** [comment]
Baidu webmaster tools must not be passing the right user agent? Can you verify that you see a request from them with the same user agent as their crawler when you use webmaster tools?

**Comment by thoop** [comment]
Feel free to reopen this issue if you find more information.
