### ISSUE TITLE
Prerender changes URLs in meta tags

### ISSUE THREAD

**Issue by antoineco** [prerender/prerender#260]
URLs in meta tags are transformed by prerender (hosted)

Example:
`<meta property="og:image" ng-attr-content="{{pageImage}}" content="https://cdn.example.com/images/share.png">`
becomes
`<meta property="og:image" ng-attr-content="{{pageImage}}" content="/images/share.png">`

This prevents logos from being displayed on social platforms.

**Comment by antoineco** [comment]
The issue is not specific to prerender in this case, contrary to what I thought. Closing the issue here, sorry for the noise.

**Comment by thoop** [comment]
No problem!
