### ISSUE TITLE
Prerender throwing 504 for some request......  PhantomJS is getting crashed and creating dump under /tmp folder.

### ISSUE THREAD

**Issue by ankitkl** [prerender/prerender#265]
PhantomJS is getting crashed and creating dump under /tmp folder.
Getting Error:
2016-01-25T03:55:28.137Z getting https://xyz.com/#!/listing/naples-asf/
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/6f8bfa36-74cd-5034-15afc14d-70843d18.dmp

**Comment by thoop** [comment]
This is most likely due to something in the internals of PhantomJS that we won't be able to help fix. Can you send me the full URL and what version of PhantomJS you are using to todd@prerender.io?

**Comment by ankitkl** [comment]
We are using prerender in-build phantomjs@1.9.19

**Comment by thoop** [comment]
Send me an email with the real URL you are accessing and I can run some tests. todd@prerender.io

**Comment by ankitkl** [comment]
Getting DUMP:


2016-02-02 17:17:14: minidump_processor.cc:258: INFO: Processed /tmp/6054990a-9b72-09aa-0e5655bc-6d1a76e8.dmp
2016-02-02 17:17:14: minidump.cc:3747: INFO: Minidump closing minidump
Operating system: Linux
                  0.0.0 Linux 4.1.13-19.30.amzn1.x86_64 #1 SMP Fri Dec 11 03:42:10 UTC 2015 x86_64
CPU: amd64
     family 6 model 62 stepping 4
     2 CPUs

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs + 0xb5d8c2
    rbx = 0x0000000000477f20   r12 = 0x00007ffe53e7c4e0
    r13 = 0x00007fd5dc877048   r14 = 0xffff000000000000
    r15 = 0x00007fd57f33ad30   rip = 0x0000000000f5d8c2
    rsp = 0x00007ffe53e7c490   rbp = 0x00000000028a9990
    Found by: given as instruction pointer in context
 1  phantomjs + 0xb60755
    rip = 0x0000000000f60756   rsp = 0x00007ffe53e7c4d0
    Found by: stack scanning
 2  phantomjs + 0x105d63
    rip = 0x0000000000505d64   rsp = 0x00007ffe53e7c4e0
    Found by: stack scanning
 3  libc-2.17.so + 0x3bb75f
    rip = 0x00007fd5e619f760   rsp = 0x00007ffe53e7c590
    Found by: stack scanning
 4  phantomjs + 0xb2e475
    rip = 0x0000000000f2e476   rsp = 0x00007ffe53e7c620
    Found by: stack scanning
 5  phantomjs + 0xb72a1c
    rip = 0x0000000000f72a1d   rsp = 0x00007ffe53e7c6f0
    Found by: stack scanning
 6  phantomjs + 0x142fcd
    rip = 0x0000000000542fce   rsp = 0x00007ffe53e7c700
    Found by: stack scanning
 7  phantomjs + 0xb5cfff
    rip = 0x0000000000f5d000   rsp = 0x00007ffe53e7c718
    Found by: stack scanning
 8  phantomjs + 0x195fe3f
    rip = 0x0000000001d5fe40   rsp = 0x00007ffe53e7c768
    Found by: stack scanning
 9  phantomjs + 0xb35bd3
    rip = 0x0000000000f35bd4   rsp = 0x00007ffe53e7c7b0
    Found by: stack scanning
10  phantomjs + 0xb5e0ff
    rip = 0x0000000000f5e100   rsp = 0x00007ffe53e7c7c8
    Found by: stack scanning
11  phantomjs + 0xb8224f
    rip = 0x0000000000f82250   rsp = 0x00007ffe53e7c7f8
    Found by: stack scanning
12  phantomjs + 0x195fe3f
    rip = 0x0000000001d5fe40   rsp = 0x00007ffe53e7c868
    Found by: stack scanning
13  phantomjs + 0xb38c97
    rip = 0x0000000000f38c98   rsp = 0x00007ffe53e7c930
    Found by: stack scanning
14  phantomjs + 0x143a0b
    rip = 0x0000000000543a0c   rsp = 0x00007ffe53e7c980
    Found by: stack scanning
15  phantomjs + 0x18f725f
    rip = 0x0000000001cf7260   rsp = 0x00007ffe53e7c9b0
    Found by: stack scanning

Thread 1
 0  libc-2.17.so + 0xbde2d
    rbx = 0x00007fd5ddc77cc0   r12 = 0x00007fd5ddc77d40
    r13 = 0x00007fd5ddc789c0   r14 = 0x00007fd5ddc78700
    r15 = 0x0000000000000000   rip = 0x00007fd5e5ea1e2d
    rsp = 0x00007fd5ddc77ca0   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.17.so + 0xbdcc3
    rip = 0x00007fd5e5ea1cc4   rsp = 0x00007fd5ddc77cb0
    Found by: stack scanning

Thread 2
 0  libc-2.17.so + 0xee303
    rbx = 0x0000000000000000   r12 = 0x00007fd5dd476df0
    r13 = 0x0000000000000008   r14 = 0x00007fd5d8000a98
    r15 = 0x00007fd5d8000d30   rip = 0x00007fd5e5ed2303
    rsp = 0x00007fd5dd476bc0   rbp = 0x00007fd5d80008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906426
    rip = 0x0000000001d06427   rsp = 0x00007fd5dd476bd0
    Found by: stack scanning
 2  libpthread-2.17.so + 0xeff
    rip = 0x00007fd5e69c3f00   rsp = 0x00007fd5dd476bf0
    Found by: stack scanning
 3  ld-2.17.so + 0x9b8a
    rip = 0x00007fd5e74c5b8b   rsp = 0x00007fd5dd476c10
    Found by: stack scanning
 4  libpthread-2.17.so + 0xeeb
    rip = 0x00007fd5e69c3eec   rsp = 0x00007fd5dd476c28
    Found by: stack scanning
 5  phantomjs + 0x19076e6
    rip = 0x0000000001d076e7   rsp = 0x00007fd5dd476c60
    Found by: stack scanning
 6  phantomjs + 0x18f6bb6
    rip = 0x0000000001cf6bb7   rsp = 0x00007fd5dd476c80
    Found by: stack scanning
 7  phantomjs + 0x1801ac2
    rip = 0x0000000001c01ac3   rsp = 0x00007fd5dd476c90
    Found by: stack scanning
 8  libc-2.17.so + 0x10a82c
    rip = 0x00007fd5e5eee82d   rsp = 0x00007fd5dd476cd0
    Found by: stack scanning
 9  phantomjs + 0x1840c73
    rip = 0x0000000001c40c74   rsp = 0x00007fd5dd476ce0
    Found by: stack scanning
10  phantomjs + 0x1840b78
    rip = 0x0000000001c40b79   rsp = 0x00007fd5dd476d20
    Found by: stack scanning
11  phantomjs + 0x19070a5
    rip = 0x0000000001d070a6   rsp = 0x00007fd5dd476d30
    Found by: stack scanning
12  phantomjs + 0x1908191
    rip = 0x0000000001d08192   rsp = 0x00007fd5dd476da0
    Found by: stack scanning
13  phantomjs + 0x18dd5b4
    rip = 0x0000000001cdd5b5   rsp = 0x00007fd5dd476df0
    Found by: stack scanning
14  phantomjs + 0x18ddda8
    rip = 0x0000000001cddda9   rsp = 0x00007fd5dd476e00
    Found by: stack scanning
15  phantomjs + 0x18dda17
    rip = 0x0000000001cdda18   rsp = 0x00007fd5dd476e20
    Found by: stack scanning
16  phantomjs + 0x17dfef5
    rip = 0x0000000001bdfef6   rsp = 0x00007fd5dd476e80
    Found by: stack scanning
17  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd5dd476ed0
    Found by: stack scanning
18  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd5dd476f20
    Found by: stack scanning
19  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd5dd476fc0
    Found by: stack scanning

Thread 3
 0  libc-2.17.so + 0xee303
    rbx = 0x00007fd597b01da0   r12 = 0x00000000001967d9
    r13 = 0x000000000000000e   r14 = 0x00007fd590000a98
    r15 = 0x00007fd590000d30   rip = 0x00007fd5e5ed2303
    rsp = 0x00007fd597b01bc0   rbp = 0x0000000000006f30
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906327
    rip = 0x0000000001d06328   rsp = 0x00007fd597b01bd0
    Found by: stack scanning
 2  phantomjs + 0x1725559
    rip = 0x0000000001b2555a   rsp = 0x00007fd597b01c00
    Found by: stack scanning
 3  phantomjs + 0x19076e6
    rip = 0x0000000001d076e7   rsp = 0x00007fd597b01c60
    Found by: stack scanning
 4  phantomjs + 0x18f6bb6
    rip = 0x0000000001cf6bb7   rsp = 0x00007fd597b01c80
    Found by: stack scanning
 5  phantomjs + 0x1801af3
    rip = 0x0000000001c01af4   rsp = 0x00007fd597b01c90
    Found by: stack scanning
 6  libc-2.17.so + 0x10a82c
    rip = 0x00007fd5e5eee82d   rsp = 0x00007fd597b01cd0
    Found by: stack scanning
 7  phantomjs + 0x1840c73
    rip = 0x0000000001c40c74   rsp = 0x00007fd597b01ce0
    Found by: stack scanning
 8  phantomjs + 0x172546f
    rip = 0x0000000001b25470   rsp = 0x00007fd597b01d00
    Found by: stack scanning
 9  phantomjs + 0x1840b78
    rip = 0x0000000001c40b79   rsp = 0x00007fd597b01d20
    Found by: stack scanning
10  phantomjs + 0x19070a5
    rip = 0x0000000001d070a6   rsp = 0x00007fd597b01d30
    Found by: stack scanning
11  phantomjs + 0x1908191
    rip = 0x0000000001d08192   rsp = 0x00007fd597b01da0
    Found by: stack scanning
12  phantomjs + 0x18dd5b4
    rip = 0x0000000001cdd5b5   rsp = 0x00007fd597b01df0
    Found by: stack scanning
13  phantomjs + 0x18ddda8
    rip = 0x0000000001cddda9   rsp = 0x00007fd597b01e00
    Found by: stack scanning
14  phantomjs + 0x18dda17
    rip = 0x0000000001cdda18   rsp = 0x00007fd597b01e20
    Found by: stack scanning
15  phantomjs + 0x17dfef5
    rip = 0x0000000001bdfef6   rsp = 0x00007fd597b01e80
    Found by: stack scanning
16  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd597b01ed0
    Found by: stack scanning
17  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd597b01f20
    Found by: stack scanning
18  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd597b01fc0
    Found by: stack scanning

Thread 4
 0  libc-2.17.so + 0xee303
    rbx = 0x00007fd59725fda0   r12 = 0x00000000001967de
    r13 = 0x0000000000000030   r14 = 0x00007fd588000a98
    r15 = 0x00007fd588000d30   rip = 0x00007fd5e5ed2303
    rsp = 0x00007fd59725fbc0   rbp = 0x0000000000015afe
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906327
    rip = 0x0000000001d06328   rsp = 0x00007fd59725fbd0
    Found by: stack scanning
 2  phantomjs + 0x19076e6
    rip = 0x0000000001d076e7   rsp = 0x00007fd59725fc60
    Found by: stack scanning
 3  phantomjs + 0x18f6bb6
    rip = 0x0000000001cf6bb7   rsp = 0x00007fd59725fc80
    Found by: stack scanning
 4  phantomjs + 0x1801af3
    rip = 0x0000000001c01af4   rsp = 0x00007fd59725fc90
    Found by: stack scanning
 5  libc-2.17.so + 0x10a82c
    rip = 0x00007fd5e5eee82d   rsp = 0x00007fd59725fcd0
    Found by: stack scanning
 6  phantomjs + 0x1840c73
    rip = 0x0000000001c40c74   rsp = 0x00007fd59725fce0
    Found by: stack scanning
 7  phantomjs + 0x1907ded
    rip = 0x0000000001d07dee   rsp = 0x00007fd59725fd10
    Found by: stack scanning
 8  phantomjs + 0x1840b78
    rip = 0x0000000001c40b79   rsp = 0x00007fd59725fd20
    Found by: stack scanning
 9  phantomjs + 0x19070a5
    rip = 0x0000000001d070a6   rsp = 0x00007fd59725fd30
    Found by: stack scanning
10  phantomjs + 0x1908191
    rip = 0x0000000001d08192   rsp = 0x00007fd59725fda0
    Found by: stack scanning
11  phantomjs + 0x18dd5b4
    rip = 0x0000000001cdd5b5   rsp = 0x00007fd59725fdf0
    Found by: stack scanning
12  phantomjs + 0x18ddda8
    rip = 0x0000000001cddda9   rsp = 0x00007fd59725fe00
    Found by: stack scanning
13  phantomjs + 0x18dda17
    rip = 0x0000000001cdda18   rsp = 0x00007fd59725fe20
    Found by: stack scanning
14  phantomjs + 0x17dfef5
    rip = 0x0000000001bdfef6   rsp = 0x00007fd59725fe80
    Found by: stack scanning
15  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd59725fed0
    Found by: stack scanning
16  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd59725ff20
    Found by: stack scanning
17  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd59725ffc0
    Found by: stack scanning

Thread 5
 0  libpthread-2.17.so + 0xba82
    rbx = 0x00007fd5880068e0   r12 = 0x0000000000000010
    r13 = 0x00007fd596a5ee30   r14 = 0xffffffffffffff92
    r15 = 0x00007fd588006800   rip = 0x00007fd5e69cea82
    rsp = 0x00007fd596a5edc0   rbp = 0x00007fd588006c80
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e3ad6
    rip = 0x0000000001be3ad7   rsp = 0x00007fd596a5ee10
    Found by: stack scanning
 2  phantomjs + 0x17d793c
    rip = 0x0000000001bd793d   rsp = 0x00007fd596a5ee90
    Found by: stack scanning
 3  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd596a5eed0
    Found by: stack scanning
 4  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd596a5ef20
    Found by: stack scanning
 5  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd596a5efc0
    Found by: stack scanning

Thread 6
 0  libpthread-2.17.so + 0xb6d5
    rbx = 0x000000000436f390   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x000000000436f3b8
    r15 = 0x000000000434bc60   rip = 0x00007fd5e69ce6d5
    rsp = 0x00007fd595dffd80   rbp = 0x00007fd5dc0fcb90
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e3af4
    rip = 0x0000000001be3af5   rsp = 0x00007fd595dffdb0
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 2  phantomjs + 0xe71e9
    rip = 0x00000000004e71ea   rsp = 0x00007fd595dffe30
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 3  phantomjs + 0xd85368
    rip = 0x0000000001185369   rsp = 0x00007fd595dffe50
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 4  phantomjs + 0xd85592
    rip = 0x0000000001185593   rsp = 0x00007fd595dffe90
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 5  phantomjs + 0xe69fa
    rip = 0x00000000004e69fb   rsp = 0x00007fd595dffec0
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 6  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd595dffed0
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 7  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd595dfff20
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning
 8  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd595dfffc0
    rbp = 0x00007fd5dc0fcb90
    Found by: stack scanning

Thread 7
 0  libpthread-2.17.so + 0xba82
    rbx = 0x00007fd5880068e0   r12 = 0x0000000000000012
    r13 = 0x00007fd5954ace30   r14 = 0xffffffffffffff92
    r15 = 0x00007fd588006800   rip = 0x00007fd5e69cea82
    rsp = 0x00007fd5954acdc0   rbp = 0x00007fd5880db550
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e3ad6
    rip = 0x0000000001be3ad7   rsp = 0x00007fd5954ace10
    Found by: stack scanning
 2  phantomjs + 0x17d793c
    rip = 0x0000000001bd793d   rsp = 0x00007fd5954ace90
    Found by: stack scanning
 3  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007fd5954aced0
    Found by: stack scanning
 4  libpthread-2.17.so + 0x7dc4
    rip = 0x00007fd5e69cadc5   rsp = 0x00007fd5954acf20
    Found by: stack scanning
 5  libc-2.17.so + 0xf6bdc
    rip = 0x00007fd5e5edabdd   rsp = 0x00007fd5954acfc0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7fd57e2cb000 - 0x7fd57e323fff  DejaVuSerif.ttf  ???
0x7fd57e324000 - 0x7fd57e331fff  cursor.pfa  ???
0x7fd57e332000 - 0x7fd57e33afff  c0648bt_.pfb  ???
0x7fd57e33b000 - 0x7fd57e344fff  c0419bt_.pfb  ???
0x7fd57e345000 - 0x7fd57e356fff  UTRG____.pfa  ???
0x7fd57e373000 - 0x7fd57e40dfff  DejaVuSansCondensed-Bold.ttf  ???
0x7fd57eabb000 - 0x7fd57eb58fff  DejaVuSansCondensed.ttf  ???
0x7fd595e40000 - 0x7fd596045fff  libnss_dns-2.17.so  ???
0x7fd596046000 - 0x7fd596252fff  libnss_files-2.17.so  ???
0x7fd5ddc79000 - 0x7fd5dde97fff  libselinux.so.1  ???
0x7fd5dde9a000 - 0x7fd5de0b1fff  libresolv-2.17.so  ???
0x7fd5de0b4000 - 0x7fd5de2b6fff  libkeyutils.so.1.5  ???
0x7fd5de2b7000 - 0x7fd5de4c5fff  libkrb5support.so.0.1  ???
0x7fd5de4c6000 - 0x7fd5de6f6fff  libk5crypto.so.3.1  ???
0x7fd5de6f8000 - 0x7fd5de8fafff  libcom_err.so.2.1  ???
0x7fd5de8fb000 - 0x7fd5debdffff  libkrb5.so.3.3  ???
0x7fd5debe0000 - 0x7fd5dee2bfff  libgssapi_krb5.so.2.2  ???
0x7fd5dee2c000 - 0x7fd5df098fff  libssl.so.1.0.1k  ???
0x7fd5df099000 - 0x7fd5df2aefff  libz.so.1.2.8  ???
0x7fd5df2af000 - 0x7fd5df68ffff  libcrypto.so.1.0.1k  ???
0x7fd5df694000 - 0x7fd5e5bbafff  locale-archive  ???
0x7fd5e5bbb000 - 0x7fd5e5de3fff  libexpat.so.1.6.0  ???
0x7fd5e5de4000 - 0x7fd5e61a0fff  libc-2.17.so  ???
0x7fd5e61a6000 - 0x7fd5e63bbfff  libgcc_s-4.8.3-20140911.so.1  ???
0x7fd5e63bc000 - 0x7fd5e66bdfff  libm-2.17.so  ???
0x7fd5e66be000 - 0x7fd5e69adfff  libstdc++.so.6.0.19  ???
0x7fd5e69c3000 - 0x7fd5e6bdafff  libpthread-2.17.so  ???
0x7fd5e6bdf000 - 0x7fd5e6de6fff  librt-2.17.so  ???
0x7fd5e6de7000 - 0x7fd5e6feafff  libdl-2.17.so  ???
0x7fd5e6feb000 - 0x7fd5e721ffff  libfontconfig.so.1.4.4  ???
0x7fd5e7220000 - 0x7fd5e74bbfff  libfreetype.so.6.3.22  ???
0x7fd5e74bc000 - 0x7fd5e74dcfff  ld-2.17.so  ???
0x7fd5e76c7000 - 0x7fd5e76cdfff  12b26b760a24f8b4feb03ad48a333a72-le64.cache-3  ???
0x7fd5e76d9000 - 0x7fd5e76dbfff  beeeeb3dfe132a8a0633a017c99ce0c0-le64.cache-3  ???
0x7ffe53f6e000 - 0x7ffe53f6ffff  linux-gate.so  ??

**Comment by thoop** [comment]
We don't fix PhantomJS crashes through dumps currently so we can't help there. PhantomJS 1.9.8 sometimes has problems with fonts so you might be seeing the crash due to a font being loaded. Send me the URL and I'll test it locally with my PhantomJS instance.

**Comment by ankitkl** [comment]
@thoop : Application URL: https://wikirealty.com/?_escaped_fragment_=/discussion/3885/

For this Url sometimes i get 504 in logs [There are other URL also but there is no pattern for 504 it throw randomly]

**Comment by thoop** [comment]
This seems to work fine when I test locally with PhantomJS 2.0. I don't think there's much we can do here. You can compile an older version of PhantomJS 2.0 or wait until we make Prerender compatible with the latest 2.1 release to upgrade.

**Comment by ankitkl** [comment]
To upgrade it we need to change line in package.json
"phantomjs": "^1.9.15"
with
"phantomjs": "2.0.0"

i'm i correct?

**Comment by thoop** [comment]
It won't work there because our phantomjs-node bridge has an issue with 2.0. You'll have to compile it yourself and use our phantomjs2 branch or wait for us to push the fix.

**Comment by ankitkl** [comment]
PLease give me your prerender branch

**Comment by thoop** [comment]
You have to check it out. It's here: https://github.com/prerender/prerender
