### ISSUE TITLE
Don't switch to http from https?

### ISSUE THREAD

**Issue by danconnell** [prerender/prerender#267]
Can prerender be configured to not request http URLs if the URL being requested is https?

If a request is made to https://www.example.com/?_escaped_fragment_= I can see in the prerender logs that it's requesting http://www.example.com and not https://www.example.com.

The problem is that we redirect all traffic to https via 301 with CloudFlare, so prerender is thus rendered useless if it makes all its requests in http since prerender doesn't follow redirects.

Is there a way around this? Thanks!

Edit: Worth noting that I didn't used to have this problem with prerender and now I do. Not sure when this changed.

**Comment by danconnell** [comment]
Sorry, needed to set FORCE_HTTPS on Heroku for the heroku-buildpack-ember-cli package. I guess something changed there at some point.

**Comment by thoop** [comment]
No problem! Yeah sometimes this can happen if SSL termination is happening at the load balancer since your app just sees an "http" request even though it was really https. Most of our middleware has a way to force https like you mention.
