### ISSUE TITLE
Error when rendering an AngularJS page

### ISSUE THREAD

**Issue by ekussberg** [prerender/prerender#268]
Hello,
we have a strange issue with prerenderer for different pages we get every 3rd time following error:
```
PMphantom stdout: Error: [$rootScope:infdig] http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D
```
Does anybody know how to solve the issue?

**Comment by thoop** [comment]
This can happen in PhantomJS 1.9.8 when there are spaces in the URL on an AngularJS page. There isn't a good way to solve this issue besides upgrading PhantomJS to 2.x (which there are currently issues with unless you use a slightly older version of PhantomJS 2.0)

**Comment by ekussberg** [comment]
Does prerender work with PhantomJS 2.0?

**Comment by thoop** [comment]
Yes. When rendering that directly against our service, I'm seeing the correct HTML returned.
