### ISSUE TITLE
process may not exist on phantom

### ISSUE THREAD

**Issue by YouriT** [prerender/prerender#269]
Hi,

First of all, thanks for this great work guys, having a good wrapper around Phantom is not always easy...

I found a bug that makes crash the workers and therefore the request...

File concerned lib/server.js
```js
server._killPhantomJS = function() {
    ...
    require('tree-kill')(this.phantom.process.pid, 'SIGTERM');
    ...
}
```

The property ```process```on ```this.phantom``` may not exist and therefore a little check is needed to avoid troubles. I just added those lines, you might want to integrate them:
```js
if (this.phantom == void 0 || this.phantom.process == void 0) {
        return;
}
```

Cheers,

Youri

**Comment by thoop** [comment]
Thanks! Which system are you running on? Would help to pinpoint when/why that might be null.

**Comment by YouriT** [comment]
With pleasure :) running Debian 8 64bits. I'm not sure why it's null but a simple guess would be that the process isn't running yet I assume and that it gets killed two times in a row, but not sure about this assumption.

**Comment by thoop** [comment]
Awesome thanks. We don't see this problem on our AWS m1.mediums but we did see this issue when we started running on m3.mediums. I'll look into this and see what we can do.

**Comment by thoop** [comment]
@YouriT We changed to a new phantomjs -> node bridge so this shouldn't be an issue anymore. If you try upgrading and run into an issue, feel free to open another issue!

**Comment by YouriT** [comment]
Okay I will check that out and come back if there is any issue
