### ISSUE TITLE
angular 2 support

### ISSUE THREAD

**Issue by samvloeberghs** [prerender/prerender#279]
Hi,

Have you already been looking into Angular 2 support?
They might come up with Angular Universal, so it might make Prerender.io obsolete ( in the ng2 specific case ).

What are your thoughts on this?

@gdi2290 : do you have anything to share on this?

Grtz

**Comment by gdi2290** [comment]
Prerendering in ng2 is free as a Gulp/Grunt/Webpack plugin. Prerender.IO is a service so they can still be used to prerender your app. For example, if any of the modules don't support Universal that means it can't work in a web worker or render on the server. So the answer is both yes and no depending on if prerender.io wants to provide a better experience

**Comment by thoop** [comment]
Angular 2 support should work out of the box, but you are right that prerendering may not be needed depending on how it's implemented. If they go the isomorphic route like react and allow rendering of the full HTML on the server side, followed by client side rendering after that, then Prerender.io might not be needed for Angular 2.

**Comment by SherlockStd** [comment]
Hi,
Angular 2 support isn't out of the box as it show the loading screen only, and not the rendered components.

Any support planned or should we use Universal ?

Thanks in advance

**Comment by thoop** [comment]
Can you send a URL that you are testing to support@prerender.io? We'd be happy to look into your issue! Usually if it's not working it's just a javascript error that can be easily fixed.
