### ISSUE TITLE
Local setup not working with Node 5.2 and Ubuntu 1504

### ISSUE THREAD

**Issue by sawantuday** [prerender/prerender#284]
I am trying this on local virtual machine with _Ubuntu 15.04_ and _Node version 5.2.0_. Everything goes right till I start the server with `node server.js`. After that when I try to parse some page, the server never responds. Browser tab only shows the loading animation. I need to kill node process to stop this.

The Phantom version installed is _2.1.1_. I tested it with few example scripts and it is working fine. 

The url accesses is `http://192.168.1.10:3000/http://google.com` where `192.168.1.10` is my Prerender VM.

Following are the logs I found on Ubuntu console 

> ubuntu@ubuntu:~/prerender$ node server.js
> 2016-02-17T12:11:18.768Z starting worker thread #0
> 2016-02-17T12:11:18.894Z starting phantom...
> 2016-02-17T12:11:18.901Z Server running on port 3000
> Fontconfig warning: ignoring UTF-8: not a valid region tag
> 2016-02-17T12:11:26.055Z getting https://github.com/prerender/prerender
> 2016-02-17T12:12:21.551Z getting http://www.google.com/

**Comment by thoop** [comment]
We just published a new version (4.0.4) 0f our prerender server. Can you try that version and see if you are still experiencing this issue?

**Comment by sawantuday** [comment]
Yup its working, Thanks :)
