### ISSUE TITLE
It looks like phridge does not dispose phantomjs on SIGTERM

### ISSUE THREAD

**Issue by vkartaviy** [prerender/prerender#285]
I am using supervisor to run prerender server and when I stop or restart service phantomjs process still alive.

**Comment by thoop** [comment]
How are you using the server with supervisor and how are you stopping/restarting the service so that I can reproduce this?

**Comment by thoop** [comment]
Interesting, thanks! I'll take a look at this.

**Comment by vkartaviy** [comment]
https://github.com/vkartaviy/prerender/commit/f13409542d29e50857937717132699ff43b5362c fixed my problem but I am not sure is this good and correct way?

**Comment by thoop** [comment]
Thanks I'll look into that.

**Comment by vkartaviy** [comment]
Please note I just updated patch because forgot to add check for ```worker.suicide```. I updated my previous comment with correct link.

**Comment by thoop** [comment]
published your fix in v4.0.4. Mind testing that and making sure it works?

**Comment by vkartaviy** [comment]
Thanks! Will try it later today and give you to know...

**Comment by vkartaviy** [comment]
Thanks! Now it works as expected!
