### ISSUE TITLE
Still leaks memory on Heroku

### ISSUE THREAD

**Issue by danconnell** [prerender/prerender#286]
The restart-heroku hack was recently removed from this repo, but it appears it's still necessary. 

I'm running the latest master code from a couple days ago with no changes except for using the whitelist plugin. Prerender leaks for me after a pretty short amount of time. It leaks until it gets up 5136M of memory and then Heroku automatically restarts it.

Any idea why it would still be leaking memory? Should I just add back the restart hack for now?

**Comment by thoop** [comment]
What do you have `PRERENDER_NUM_ITERATIONS ` set to? Can you set `PRERENDER_NUM_ITERATIONS` to something low like 40? When we set ours to ~100, we see the phantomjs instances get cleaned up and the memory usage starts over with a new instance.

**Comment by danconnell** [comment]
I didn't have it set to anything. I'll try setting it to 40 and I'll let you know what happens.

**Comment by thoop** [comment]
It defaults to 40 if not set to that probably won't make a difference. Are you able to see if there are any extra PhantomJS instances running when it gets to the memory limit? Do you know how many PhantomJS workers are getting started?

**Comment by danconnell** [comment]
Can I get that info from the logs? Below is a snippet of the logs when it boots up. After 7 requests the memory started to get over 1037M. Let me know if you need me to enable the more advanced logging and I could show you those logs as well.

> Feb 17 17:41:03 prerenderio heroku/web.1:  State changed from starting to up 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.908Z starting worker thread #1 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.899Z starting worker thread #0 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.914Z starting worker thread #3 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.919Z starting worker thread #5 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.949Z starting worker thread #7 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.138Z Server running on port 22813 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.911Z starting worker thread #2 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.916Z starting worker thread #4 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:02.925Z starting worker thread #6 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.126Z starting phantom... 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.147Z starting phantom... 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.158Z Server running on port 22813 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.176Z Server running on port 22813 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.212Z Server running on port 22813 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.245Z Server running on port 22813 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.287Z starting phantom... 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.291Z starting phantom... 
Feb 17 17:41:03 prerenderio app/web.1:  2016-02-18T01:41:03.303Z Server running on port 22813 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.944Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.973Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.016Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.037Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.075Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.033Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.057Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:04.128Z started phantom 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.165Z starting phantom... 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.192Z starting phantom... 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.232Z starting phantom... 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.282Z starting phantom... 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.293Z Server running on port 22813 
Feb 17 17:41:04 prerenderio app/web.1:  2016-02-18T01:41:03.299Z Server running on port 22813

**Comment by thoop** [comment]
Yeah that's way too many phantomjs instances hah. It defaults to 1 instance per number of CPUs but it looks like that won't work well since they have lots of CPUs on heroku instances but limit you on memory. Try setting `PRERENDER_NUM_WORKERS` = 1

**Comment by danconnell** [comment]
Yeah, that seems to be better. I set that and only got one started phantomjs instance. I'll monitor it for a day or two and let you know if I see any more memory leaks.

Thanks!

**Comment by danconnell** [comment]
Still leaking memory unfortunately. The leak is a lot slower now, though. It took 31 requests for it to get to Heroku warning about memory use at 1038M.

Anything I can do to help you investigate further?

**Comment by thoop** [comment]
Can you put your `PRERENDER_NUM_ITERATIONS` at 10 or even 5? Sounds like Heroku just doesn't give enough memory to have a buffer there so PhantomJS will need to be restarted more often than 40.

**Comment by danconnell** [comment]
Sure thing. I set it to 10 and I'll monitor and let you know. Thanks!

**Comment by danconnell** [comment]
Seems to be working better now. Had a decent number of requests, and no memory warnings. Getting the following logging occasionally which I assume is what's preventing the memory usage from getting too high.

> Feb 18 16:02:40 prerenderio app/web.1:  2016-02-19T00:02:40.159Z phantomjs terminated 
Feb 18 16:02:40 prerenderio app/web.1:  2016-02-19T00:02:40.159Z starting phantom... 
Feb 18 16:02:40 prerenderio app/web.1:  2016-02-19T00:02:40.267Z started phantom

Would probably be worth adding to your README some info about setting `PRERENDER_NUM_WORKERS` to 1 and `PRERENDER_NUM_ITERATIONS` to 10 on Heroku for a 2X dyno. I expect `PRERENDER_NUM_ITERATIONS` would need to be even lower for a 1X dyno.

**Comment by thoop** [comment]
Awesome! Yeah we'll nee to improve our documentation there. Thanks for reporting back

**Comment by randi-wikirealty** [comment]
@thoop are there defaults set for PRERENDER_NUM_WORKERS and PRERENDER_NUM_ITERATIONS on the master branch?  i tried printing out process.env and didn't see anything.  

we're using a cluster with two t2.medium servers, do you recommend PRERENDER_NUM_WORKERS is set to 1 and PRERENDER_NUM_ITERATIONS be set to 10 for this setup as well?

**Comment by thoop** [comment]
They aren't defaulted to anything. If either of those aren't set, the default is:

- The number of workers created are equal to the number of CPUs. If you have 2 CPUs, 2 workers are started
- The number of iterations is defaulted to 40

t2.medium have 4Gb of memory so you shouldn't run into any issues there with 1 worker at 40 iterations. You might run into memory issues with 2 workers though, so you might have to set iterations to something lower. t2 servers don't have a lot of baseline CPU power so only use those servers if your server mostly sits idle, but with requests every once in a while.

**Comment by randi-wikirealty** [comment]
@thoop thanks for your response.  we get a lot of hits to our Prerender servers so using t2 servers is probably why we run out of memory quite often.  which instance type would you recommend?

**Comment by thoop** [comment]
I'd recommend m3.medium with 1 worker or m3.large with 2 workers
