### ISSUE TITLE
Error setting header

### ISSUE THREAD

**Issue by aaronkaz** [prerender/prerender#288]
Anyone else seeing this?
```error setting header: [TypeError: The header content contains invalid characters]```

I found this: https://github.com/npm/npm/issues/11515 - but is still an open issue.

I'm using....
node v5.7.0
npm v3.6.0
ubuntu 14.04 trusty

What does your environment look like? (if you're not getting the error)

Also big thanks for the latest commits!  The new updates, especially with PhantomJS2, are performing great, despite the issue above.

**Comment by thoop** [comment]
I think PhantomJS is the cause of that due to an invalid new line in the header: https://github.com/ariya/phantomjs/issues/14024

**Comment by sneakyfildy** [comment]
please, inspect this comment https://github.com/indexzero/http-server/issues/244#issuecomment-197804202
