### ISSUE TITLE
Socket Hangup issue

### ISSUE THREAD

**Issue by Overseas634** [prerender/prerender#290]
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1089:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

**Comment by Shakyamuni177te** [comment]
Is this Websocket? I don't understand Websocket yet and I need to :(.

**Comment by Overseas634** [comment]
Nodejs socket error

**Comment by Shakyamuni177te** [comment]
​Have to tried making sure the ports are aligned correctly?​

**Comment by Overseas634** [comment]
yes, can you take teamviewer session so you'll get idea about it

**Comment by Shakyamuni177te** [comment]
I can certainly have a look for you. It really seems like it's a port
alignment system but I am wondering how you have the non-visible elements
of your setup configed. Can you give me full details on your routing
system, give me a couple of days too look through them then after I'm done
I will be more than happy to teamviewer and 90% likely to fix the issue
first time.

**Comment by Overseas634** [comment]
i'm Making use of Angular Yeoman app setup.
now i'm getting view rendered for only default route.
but for other route socket hangup error still coming

**Comment by Shakyamuni177te** [comment]
Hhhhmmmm. I'm only tangentially familiar with Yeoman and I wasn't aware
anyone considered it a subset of Angular Yeoman though I suppose some
plausibly might. What are your routing URLs?

**Comment by thoop** [comment]
@Overseas634 Have you looked into any of these possible issues causing that? http://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean

Do you ever see a socket hangup in your browser? Any more info you can give, like a reproducible test case would be great.

**Comment by Overseas634** [comment]
Sorry on my local dev environment it was creating issue but when i moved it to production environment now it is working fine

**Comment by thoop** [comment]
Interesting... any idea why?

**Comment by Overseas634** [comment]
Didn't got why i also wonder about it 
But it is working Still sometime it is showing same error but for a time being my issue is resolved

**Comment by thoop** [comment]
Feel free to reopen if needed.
