### ISSUE TITLE
Prerender.io 4+ not working on Windows

### ISSUE THREAD

**Issue by mkukik** [prerender/prerender#291]
Upon start of the server (out of the box) errors received (per instance)
`SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"`

Upon standard request received
`2016-03-01T11:16:38.826Z getting https://some_url/path/`
then loading indefinitely. Server did not send any data.

Works on Linux.

**Comment by Shakyamuni177te** [comment]
Which distro?

**Comment by mkukik** [comment]
Windows 8.1
Linux Oracle (el6)
Prerender 4.0.3, 4.0.4, 4.0.5

**Comment by Shakyamuni177te** [comment]
D3, is the DPI process linked to the graphical output sub-processor in any
way? If it's a sub-processing issue we may well have a problem at the user
end.

**Comment by Shakyamuni177te** [comment]
Oh, wait, I'm looking at prerender not Vorpal.js so D3's code might not be
as heavily involved and he probably won't get this message. Whoops!
Anywhoose it's likely to be a graphical sub-processing issue. I'd start by
looking there.

**Comment by Shakyamuni177te** [comment]
I know it seems counter-intuitive but I would suggest the data may pass
through a graphic pipeline when processed which may cause the error even if
DPI does no mean dots per inch in this particular case.

**Comment by GranularDetective** [comment]
Peter, what ARE you doing my darlin'. I know you think you know it all already but seriously just because an error has DPI in it and you know all the terminology doesn't mean you understand what was causing the problem. Fixing the entire thing and actually getting the credit for it are two different things. No offense.

**Comment by Shakyamuni177te** [comment]
Just leave me alone.

**Comment by Shakyamuni177te** [comment]
Just leave me alone please.

**Comment by GranularDetective** [comment]
I don't know why you're so angry with me when I am just trying to help you. I mean, it's not like I'm deliberately sabotaging everything you do.

Also, you double posted my darling.

**Comment by Shakyamuni177te** [comment]
The problem has manifested within the graphical processing sub-system on
past occasions but I would posit the issue will change, expand and contract
over time due to multiple actors even assuming no obvious external library
calls.

**Comment by thoop** [comment]
@mkukik Can you try running PhantomJS 2.1 on it's own with a small script to load your webpage? Sounds like a PhantomJS issue.

**Comment by mkukik** [comment]
I did that and I get same 
`SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"`
however I eventually get `Status: success`

```
var webPage = require('webpage');
var page = webPage.create();

page.open('https://heavy_SPA_site/', function(status) {
  console.log('Status: ' + status);
});
```

**Comment by thoop** [comment]
Can you print out the content of the page to see if it's being rendered correctly?

**Comment by thoop** [comment]
Feel free to reopen if anyone runs into this issue. We run Prerender on linux/OSX exclusively and without more info it's hard for us to help here.
