### ISSUE TITLE
Cached responses do not respect httpHeaders

### ISSUE THREAD

**Issue by romanosipenko** [prerender/prerender#297]
As cache (s3HtmlCache) will cache any page content and headers (httpHeaders) will server page content even in case of 301, 302, we have situation, when only first (uncached) query return right headers and status code.

On next requests, cached version (with invalid content, probably) will be returned with status code 200.

**Comment by thoop** [comment]
Ah, `afterPhantomRequest` should probably check `req.prerender.statusCode` to see if it's a status code 200 and only cache pages to S3 that are a status code 200. Do you want to send a pull request? Thanks for letting us know! We use a different caching plugin on our end so we didn't notice that about the s3 plugin.

**Comment by romanosipenko** [comment]
Hi.
Yes, we will prepare pull request.
Thanks.

**Comment by romanosipenko** [comment]
@thoop can you please review pull request made by @legendar?

**Comment by thoop** [comment]
merged, thanks!
