### ISSUE TITLE
waiting time until page loaded

### ISSUE THREAD

**Issue by quape** [prerender/prerender#299]
Hi there,

i'm using this package to render pages that come from a Meteor app. The app just shows some content it gets from the server - very simple. So Meteor renders the html template and then puts in the content from the server afterwards. prerender retrieves this generated html as expected but about every 5 times the content is missing. In these cases the html which prerender retrieves only contains the stuff in the template but not the dynamic content which was inserted in by Meteor. prerender just waited about 0.5s too short.

The question is: Why didn't it wait and how can I increase that time or how can I tell prerender when the page is finished loading?

Thanks

**Comment by quape** [comment]
ok found the prerenderReady = true solution

**Comment by thoop** [comment]
Great!

**Comment by quape** [comment]
It turned out that this does not work 100% reliable. Sometimes, maybe every 50th request, an empty page is saved. Empty means html structure without the dynamic content that would have shown up if prerender waited a bit longer.

So why didn't it wait for `prerenderReady == true` or did I do a mistake there? Can I debug that somehow?

**Comment by thoop** [comment]
If one of your pages takes too long to load before setting prerenderReady to true, the Prerender server will save the page as-is. How long do your pages usually take to load?

**Comment by pdr0** [comment]
I have a very similar issue. My app takes 3000 ms in load (30Mb/s). How long prerender wait for the site has been loaded independently if the flag is set or not?

**Comment by thoop** [comment]
If `window.prerenderReady` is not set at all, then we will count the number of requests in flight and save the page a short time (1-2 seconds) after the number of requests in flight reaches zero.

If you set `window.prerenderReady` to `false` when the page loads (in the HTML), then we will until `window.prerenderReady` is set to `true` or 20 seconds total, whichever comes first.

**Comment by adlius** [comment]
@thoop I would like to follow up on this problem. For my use case it is important that the Prerender server would not return a page (504) if prerenderReady is set. Is it possible that I configure prerender so that it would only 200 on fully-rendered pages?

**Comment by thoop** [comment]
window.prerenderReady is meant only to be a tool to help with page load timing. If you want to return a different status code, you can use the `prerender-status-code` meta tag and default it to `503` and then set it to 200 when you set `window.prerenderReady` to true. You can find the documentation for `prerender-status-code` here: https://prerender.io/documentation/best-practices
