### ISSUE TITLE
Search Engines Penalties.

### ISSUE THREAD

**Issue by saibayadon** [prerender/prerender#3]
This is a good approach that i almost implemented in a project, but got shot down due to concerns of Search Engines giving penalties for serving something different to them vs. what users got served.

Have you tried this on a production site and how did it went?

**Comment by huoteng** [comment]
> This is a big unknown that will need to be answered through experiments and data.

@thoop 

Hi, as you said before, is there any experiments or data can tell us whether or not `Search Engines will giving penalties for serving something different to them vs. what users got served`.

**Comment by thoop** [comment]
As long as you use the `_escaped_fragment_` protocol and don't check Googlebot by their user agent, Google won't penalize you. If you check Googlebot by their user agent explicitly and serve different content, you could be penalized for cloaking.

**Comment by huoteng** [comment]
@thoop Thanks for your answer. I try to describe more clearly.

The web sites of my company are in China, so we are more concerned with the search engines which failure to observe the `_escaped_fragment_` protocol in China.

So I want to know is there any articles, experiments or data can tell us `Search Engines will not give penalties for serving something different to them vs. what users got served`.

As you know, verify whether the idea above is feasible, which is not a very easy task. So I want to ask you where I can get reliable foundation to deciding whether to use the `prerender` plan, or not.

Looking forward to your reply.

**Comment by thoop** [comment]
We don't have any specific info we can point to on Chinese search engines. Baidu does not follow the escaped fragment crawling protocol so we check for Baidu by their user agent directly. We haven't had anyone mention to us that they had any issues with Baidu so I think it should work just fine.

**Comment by huoteng** [comment]
@thoop Thanks for your patient answer.
