### ISSUE TITLE
prerender sometimes works only after xth try

### ISSUE THREAD

**Issue by fxck** [prerender/prerender#30]
Basically sometimes it works just fine, sometimes it returns something like this

`<html><head></head><body></body></html>`

And sometimes it works just fine. Console shows no errors in either case.

It's a website using angular, has anyone encountered similar issue? I've tried it on both prerender.herokuapp.com and my herkou instance. Is there any way to debug this? Seems to be the same problem as was discussed(and fixed) in https://github.com/collectiveip/prerender/issues/17

**Comment by fernandes** [comment]
just my2c

I'm testing with a rails middleware (rails act as a router delivering 3 different ember apps), and was getting a empty HTML (`<html><head></head><body></body></html>`) like @fxck and solved changing from webrick to puma... thank you!
