### ISSUE TITLE
Possible to retry request if PhantomJS restarts?

### ISSUE THREAD

**Issue by danconnell** [prerender/prerender#301]
Is it possible to retry a request if PhantomJS is restarted in the middle of the request instead of just aborting?

I see a number of these in my logs:
`PhantomJS restarted in the middle of this request. Aborting...`

This then shows as a bunch of 504s when doing a Moz Crawl of my site.

Possible through native support by prerender? Or could it be implemented as a plugin using the available hooks? If so, any guidance on where to begin with that would be appreciated and I could look into making a PR for that.

Thanks!

**Comment by thoop** [comment]
It would be possible but would add a bit of weird complexity and possible looping issues if a page were to keep crashing PhantomJS. We've tested this before on our hosted service and it didn't provide any benefit so we removed it.

I might be beneficial for us to change the "iterations" functionality to only restart PhantomJS if 0 requests are in flight which might prevent some of those aborted requests.

If you are seeing lots of those you might want to spread our your load across more servers.

**Comment by x3dfxjunkie** [comment]
I would certainly up-vote the idea of only killing phantomjs processes that are idle.

**Comment by danconnell** [comment]
Could you differentiate between a crash and an intentional restart? If so, would that prevent any potential looping issues?

If not, I would agree that only restarting idle PhantomJS processes sounds like a great idea.

I'm not getting a lot under normal circumstances, but when something like a Moz Crawl is done and it's doing a bunch of requests all at once then a number of them do get aborted.

**Comment by thoop** [comment]
Yeah we can't do much about a crash but an intentional restart is just a code condition that we have to make sure memory leaks don't take up too much memory. I'll look into adding that.

**Comment by thoop** [comment]
Should be fixed in Prerender v4.1.0. We have a `softIterations` parameter that will restart phantomjs only if phantomjs is idle. https://github.com/prerender/prerender#softiterations
