### ISSUE TITLE
Problem with es6

### ISSUE THREAD

**Issue by ZuSe** [prerender/prerender#303]
Hi folks,
since my page is not rendered probably on prerender.io I tried debugging using the local server.
I realized that it seems to have some problems with es6 data structures, since i get 

2016-04-13T18:34:04.493Z getting https://localhost:8047/
Error: Can't find variable: Map
which seems to break everything.

Is there a way to use prerender with es6 structures? I am already using babel to transcompile the code back to es5 (es2015 preset) but that only affects functions. I also have tried adding the polyfill in my project, but it does not seem to fix the issue above.

Any good idea would be appreciated pretty much.

**Comment by thoop** [comment]
Sorry! The latest version of PhantomJS does not support those features so you'd want to add a polyfill. If you are having trouble getting a polyfill to work, feel free to send us an email at support@prerender.io and we'd be happy to help.
