### ISSUE TITLE
Issue with sending parameters to prerender

### ISSUE THREAD

**Issue by Harishgolla** [prerender/prerender#304]
I have a URL to cache

http://xx.com/?_escaped_fragment_=/page/docs/details?targetId=TEXT:TEXT

However in prerender the url converts into

http://xx.com/?targetId=TEXT:TEXT#!/page/docs/details @ prerender. 

Where the converted URL is invalid. I wanted to use prerender.io hosted service. However this issue stops me to use prerender.

Why URL has been reframed in util.js?

**Comment by thoop** [comment]
It's rewritten that way since that's how the URL is supposed to look according to the URL spec. Let me see what we can do about keeping the URL as is. Can you email me at todd@prerender.io?
