### ISSUE TITLE
Erro when executing prerender locally

### ISSUE THREAD

**Issue by fjunior87** [prerender/prerender#305]
Hi,

I've cloned the project and followed the instructions but I'm getting the following error:

`\prerender\node_modules\phridge\lib\lift.js:14
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined`

Is there any workaround for this?

Thanks

**Comment by fjunior87** [comment]
I've found a workaround:

Added this to the prereder/package.json
"promise" : "^6.1.0"

and changed the lift.js adding:

var Promise = require('promise');

Is there an official solution for this?

**Comment by thoop** [comment]
Which version of node are you using? I think just upgrading to a version of node that has the global Promise object will work instead of the workaround that you did. I think 0.12+ has Promise.

**Comment by fjunior87** [comment]
Hi @thoop, you are right after upgrading Node it worked fine. Thanks
