### ISSUE TITLE
Is not compatible with nodejs 6.0

### ISSUE THREAD

**Issue by navarroaxel** [prerender/prerender#308]
TypeError: parsedQuery.hasOwnProperty is not a function
    at Function.prerender.shouldShowPrerenderedPage (...\node_modules\prerender-node\index.js:132:33)

Nodejs changelog: https://github.com/nodejs/node/blob/master/CHANGELOG.md#2016-04-26-version-600-current-jasnell
Breaking change: https://github.com/nodejs/node/pull/6055

**Comment by thoop** [comment]
Thanks! We're working through this on the prerender-node repo https://github.com/prerender/prerender-node/pull/104
