### ISSUE TITLE
URL change

### ISSUE THREAD

**Issue by ashokhirpara1** [prerender/prerender#309]
Here is my website www.peersreview.com and installed prerender.io but problem is that when i am trying to access www.peersreview.com/?_escaped_fragment_=/web/home it will be redirect to www.peersreview.com/?_escaped_fragment_=/web/home#!/web/home.

can anyone tell me what problem is there?

**Comment by thoop** [comment]
That happens when the middleware isn't installed correctly and the javascript is served back to your browser instead of the prerendered page. If you see this happen you'll want to double check your middleware installation. Responded to your email.
