### ISSUE TITLE
Directive not rendered

### ISSUE THREAD

**Issue by stellanhaglund** [prerender/prerender#311]
Hi I'm using angularjs and the prerender-node package.

I have added the fragment part and made changes to locationProvider, and those parts works but there is one directive that is not rendered.

Have a look here, http://industriromantik.se and then http://www.industriromantik.se/?_escaped_fragment_= 

as you see highlights is not there, and the bad thing is that in that directive I have some locations that I need to access but since the directive isn't there I cant access them.

**Comment by thoop** [comment]
I'm seeing this javascript error from the Vimeo player which might be causing issues:
```
TypeError: undefined is not a constructor (evaluating 'T.canPlayType(n)')

  https://f.vimeocdn.com/p/2.24.4/js/player.js:8 in get
  https://f.vimeocdn.com/p/2.24.4/js/player.js:8 in get
  https://f.vimeocdn.com/p/2.24.4/js/player.js:11 in value
  https://f.vimeocdn.com/p/2.24.4/js/player.js:11 in value
  https://f.vimeocdn.com/p/2.24.4/js/player.js:11 in set
  https://f.vimeocdn.com/p/2.24.4/js/player.js:12 in G
  https://f.vimeocdn.com/p/2.24.4/js/player.js:12 in a
  https://f.vimeocdn.com/p/2.24.4/js/player.js:2 in X
  https://f.vimeocdn.com/p/2.24.4/js/player.js:2 in z
  https://f.vimeocdn.com/p/2.24.4/js/player.js:2 in me
  https://f.vimeocdn.com/p/2.24.4/js/player.js:2 in o
  https://player.vimeo.com/video/144600597:1
```
Any idea why that's happening?

**Comment by stellanhaglund** [comment]
No ive never seen that, there is vimeo players embedded in some of the
highlights but i never had any problems with them

tisdag 10 maj 2016 skrev Todd Hooper <notifications@github.com>:

**Comment by thoop** [comment]
Is there a way you might be able to comment out that video to test it? I'd suggest trying to run a Prerender server locally and just test it on a development machine to see if that gets it to work.

**Comment by stellanhaglund** [comment]
Might be that the videos are private for a certain url?

tisdag 10 maj 2016 skrev Todd Hooper <notifications@github.com>:

**Comment by thoop** [comment]
Sorry for the delay here. Were you able to test that and get it working at all?

**Comment by thoop** [comment]
Feel free to reopen with more info if you are still having trouble here. I'd love to help!
