### ISSUE TITLE
504 when accessing Angularjs routes

### ISSUE THREAD

**Issue by UiCandy** [prerender/prerender#315]
I've setup an express wrapper for my angularjs app with the prerender-node package. 
I cannot access any nested urls, it's constantly returning a 504, without the ?_escaped_fragment bit the app runs as expected.

I've also included #!'s in my urls so that it's easier to debug. Has anyone faced this issue? I've been trying to resolve it since the past week.
Page Url: http://localhost:8080/#!/1/1877
While using Prerender: http://localhost:8080/?_escaped_fragment_=/1/1877/ - > 504 error

Thanks!

**Comment by thoop** [comment]
Are you running a local Prerender server? Our hosted service can only access publicly accessible URLs. If you are running a local Prerender server, can you post the console log from the prerender server?

Thanks!

**Comment by thoop** [comment]
Feel free to reopen if you have any more info so that we can help out here!
