### ISSUE TITLE
Difference with phantomjs

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [prerender/prerender#317]
Hello,

I'm trying prerenderer and I have problem with the loading of the page. With prerenderer the page is never fully loaded, even if I wait ages wait ages with prerendererReady.

Even if I get `Timed out. Sending request with HTML on the page` the content is not correct

On the other side when I run this simple phantomjs script the state of the page is correct: 

The missing part is an ajax query so maybe it is failing but I don't know how to test this. (I don't see the ajax query on the prerenderer log though)

```javascript
var page = require('webpage').create();
page.open('http://mydomain.com/property/5700fe21163d727120d3c4f6', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});

```

What could I miss ? 

Thank you

**Comment by thoop** [comment]
Hmm, can you send me your full URL so that I can test it locally with my own PhantomJS and see what the issue might be? Feel free to email me at todd@prerender.io

Thanks!

**Comment by GuillaumeLeclerc** [comment]
Hello,

Thank you for your answer.

Here is one of the problematic page: http://papayapods.com/property/57126c30877d4739fb1e04a7

Best regards

**Comment by thoop** [comment]
Sorry for the delayed response!

I'm seeing what looks to be the correctly rendered static HTML. Did you fix something since you last tried? Were you testing that URL against a local Prerender server that you were using or were you testing that URL against our hosted service?

**Comment by thoop** [comment]
Feel free to reopen if you are still seeing issues here since it looks like it was fixed.
