### ISSUE TITLE
Prerender stricter with JS than chrome or FF can cause failure to load JS

### ISSUE THREAD

**Issue by chozabu** [prerender/prerender#320]
In this particular case, we had some functions defined in the middle of a function inside an if statement - which works fine in FF/Chrome - but the JS file did not load atall in prerender (and did not provide an error message)

Happily, the IDE mentioned `function statement not at top level of function or statement is prohibited` - this seems like it is forcing strict mode, which should probably be disabled by default (just because it seems to be disabled by default in browsers, and would thus render in a more similar manner to them)

**Comment by thoop** [comment]
Yeah we've seen some stuff like this. Not sure of a way to do that since that's part of PhantomJS that I don't think we can easily change. Chrome and FF don't use webkit anymore so PhantomJS should be closer to Safari.

**Comment by thoop** [comment]
I don't think we can do anything about this since we are relying on PhantomJS but feel free to reopen if you have any more info that would help us solve this!

**Comment by chozabu** [comment]
I guess without changing the rendering engine in phantomjs, there is not alot that can be done.
Perhaps a prominent note in the docs?

Or backporting the less strict JS code to webkit, but that's another kettle of fish :grinning:

**Comment by thoop** [comment]
I haven't found any docs or anything showing that PhantomJS forces strict mode. Do you have strict mode somewhere in your project?
