### ISSUE TITLE
Problem loading relative images

### ISSUE THREAD

**Issue by declanelcocks** [prerender/prerender#321]
I saw the previous issue about a similar thing, but I'm not so sure it applies here as I am using prerender specifically for web crawlers. I will write a quick note about my setup below:

**Prerender:** Running on `localhost:8000`, working fine
**Frontend:** Running on`localhost:9000` using `prerender-node` and also working fine, I can make a simple `curl` request to the frontend or to the prerender server and I receive the correct, fully-rendered HTML.

The index page itself will load fine, but all of the relative URLs are incorrectly trying to load from the 
prerender server. So I will end up with a bunch of `404` errors like this:

`GET http://localhost:8000/app/app.css`

Are there any extra steps I should be taking to fix this issue? I didn't see anything specific about this on the documentation so I'm unsure of how to fix this.

Note: It's possible (and likely) that I'm also testing this incorrectly. For testing how the page will render for the bots, should I be using `http://localhost:9000/?_escaped_fragment_=`? If so, then it is working absolutely fine...but I was concerned about the results when doing `http://localhost:8000/http://localhost:9000/`

**Comment by thoop** [comment]
The only URL you should use for testing how it will render for the bots would be:

`http://localhost:9000/?_escaped_fragment_=`

The other URL `http://localhost:8000/http://localhost:9000/` will never be accessed by crawlers. That's more like the API URL that the middleware is making a request to, not a URL that a crawler would access.

**Comment by declanelcocks** [comment]
Thanks for the quick reply by email and GitHub! 👍

**Comment by thoop** [comment]
Sure thing!
