### ISSUE TITLE
Higher download time

### ISSUE THREAD

**Issue by gbranco** [prerender/prerender#322]
Hi, first of all congrats e thanks for this awesome solution.

Recently I faced the memory leak using prerender, I'm using the reverse proxy strategy through nginx and nginx and phantom was in the same instance (amazon ec2), so I changed my stack and moved prerender to another instace to prevent website unavailability. So far so good. But acessing google search console I saw that the number of crawl pages is lower and the download time is higher since the day I made this change.

I was searching through issues and I read that you are using amazon too. any ideas about why this happen?

**Comment by thoop** [comment]
Thanks for the kind words!

Hmm, longer response times could mean you aren't caching your pages or you are having some kind of connection/performance issue. Do you have any more information you can give? Are you still seeing requests get sent to your Prerender server and still seeing cache hits on the Prerender server console? Are you using any kind of cache for the pages served through your Prerender server?

**Comment by gbranco** [comment]
Hi @thoop ,

I'm not using any cache strategy, it's everything on the fly the, same as when I was running ngnix and prerender in the same server and the response time was lower.

I'll be looking into infrastructure issues. 

Tks for your help. I'll comeback with the solution.
