### ISSUE TITLE
Allow for additional rendering engines

### ISSUE THREAD

**Issue by konobi** [prerender/prerender#323]
Phantomjs can be a bit of a beast to handle at times, so it'd be nice if prerender could support other engines like zombie.js that are much lighter weight.

**Comment by thoop** [comment]
Thanks for the suggestion! Does zombie.js support most features of phantomjs or real browsers?

**Comment by konobi** [comment]
yes, it's a full DOM implementation... it's just headless and stupidly quick.

**Comment by thoop** [comment]
I'm going to link this issue with the code cleanup issue since I think code cleanup and allowing additional rendering engines should be tackled at the same time.
