### ISSUE TITLE
Latest aws_sdk package results in 'SignatureDoesNotMatch' errors in S3 plugin

### ISSUE THREAD

**Issue by clintbeacock** [prerender/prerender#325]
Hi.  Just wanted to give a heads up that the latest aws_sdk package (and likely anything above v2.4.0) results in signature errors.

As a simple solution, I locked my version down to the one that was working on my staging server, which was 2.3.18.

**Comment by thoop** [comment]
Thanks for the heads up! Is this when downloading the aws_sdk package or when using it? Which plugins do you have enabled?

**Comment by clintbeacock** [comment]
You're welcome!

I have the following plugins enabled:
```
sendPrerenderHeader
blacklist
removeScriptTags
s3HtmlCache
```

The latest aws_sdk package downloads fine.  It hits the error every time a page is requested from the prerender server.

Here's a sample of the error logs:
```
niagara-prerender-5 2016-07-07T17:01:45.500Z getting https://<SITE>/blog#!/
niagara-prerender-5 { [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
niagara-prerender-5   message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
niagara-prerender-5   code: 'SignatureDoesNotMatch',
niagara-prerender-5   region: null,
niagara-prerender-5   time: Thu Jul 07 2016 12:01:45 GMT-0500 (CDT),
niagara-prerender-5   requestId: '2EE8B611EEAAD4FC',
niagara-prerender-5   extendedRequestId: 'J4fwfe+vn7K2K4oM+oe30A5oMyaOt8ohHTub954JzgflvoFnLOOKOiKR8ARo5pjJgMKc1cbr6fo=',
niagara-prerender-5   cfId: undefined,
niagara-prerender-5   statusCode: 403,
niagara-prerender-5   retryable: false,
niagara-prerender-5   retryDelay: 11.767100566066802 }
```
Reverting the package to 2.3.18 allowed it to resume working properly as it was on the staging server, which had been deployed a week or so before the 2.4 version of aws_sdk

**Comment by thoop** [comment]
It looks like I'm not seeing those signature errors with those same modules enabled. You can see the 404 because the page isn't cached and then the second request results in a cache hit from S3. This is all testing with a local Prerender server with the latest modules installed (aws-sdk 2.4.5). Are you doing anything else differently? Do you have any other S3 settings being applied?
```
2016-07-07T20:15:10.493Z getting https://prerender.io/
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: Thu Jul 07 2016 15:15:11 GMT-0500 (CDT),
  requestId: '26272F72FB733ACB',
  extendedRequestId: '7b+SGSstyjdLOVt+ky4XQLGjZVmgGeLhYAMjxtXKFiJyfH6JemlZ1Fi2sUNuMm397CWHdv4NdSc=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 44.106490071862936 }
2016-07-07T20:15:21.971Z got 200 in 11478ms for https://prerender.io/
2016-07-07T20:15:24.859Z getting https://prerender.io/
cache hit
2016-07-07T20:15:27.008Z got 200 in 2149ms for https://prerender.io/
```

**Comment by clintbeacock** [comment]
Ah, it's probably my setup then.  I'd had to downgrade to version 4.0.5 due to this issue: https://github.com/prerender/prerender/issues/296

I also did manually pull a couple small fixes into it from the later releases that I needed.

I haven't tried it with the latest version.  So, I suppose, it may not be working with 4.0.5, but I can't say that for sure either without a vanilla install.

Thanks for your quick replies.  If no one else is running into this, it's likely isolated to my setup.

**Comment by thoop** [comment]
Ah ok thanks. Please feel free to reopen if you run into any other issues there. If you test the vanilla release, I'd be curious to see if you have any problems.
