### ISSUE TITLE
Prerender servers hangs at 'getting'

### ISSUE THREAD

**Issue by Wingie** [prerender/prerender#327]
```
==> log/prerender.out.log <==
2016-07-11T09:14:31.621Z getting http://google.com/
2016-07-11T09:15:48.314Z getting http://dev.local/landing_page/Projects-in-Saudi_Arabia/?country=MTg4&sector=MTAwMDAw

==> log/http_error.log <==
[Mon Jul 11 09:15:48.330257 2016] [proxy_http:error] [pid 11402:tid 140229348361984] (20014)Internal error: [client 10.1.1.1:34573] AH01102: error reading status line from remote server 192.168.0.141:3000

==> log/prerender.out.log <==
2016-07-11T09:16:42.575Z getting http://10.1.1.1/
2016-07-11T09:16:49.446Z getting http://10.1.1.1/
2016-07-11T09:17:07.916Z getting 
2016-07-11T09:17:20.130Z getting localhost:80.
2016-07-11T09:17:21.879Z getting localhost:80/

==> log/http_error.log <==
[Mon Jul 11 09:17:48.343195 2016] [proxy_http:error] [pid 11402:tid 140229398718208] (20014)Internal error: [client 10.1.1.1:34627] AH01102: error reading status line from remote server 192.168.0.141:3000
[Mon Jul 11 09:17:48.343661 2016] [proxy:error] [pid 11402:tid 140229398718208] [client 10.1.1.1:34627] AH00898: Error reading from remote server returned by /landing_page/Projects-in-Saudi_Arabia/
```

this gives me the page i want to cache
```
curl dev.local/landing_page/Projects-in-Saudi_Arabia/
```
prerender.io is running on my local
```
curl http://localhost:3000/http://dev.local
```
give me an error

any idea what is happening?

**Comment by thoop** [comment]
What system are you running this on? Did you change your hosts file or anything? It's weird that it just isn't loading anything.

Did you see any errors when you ran npm install? Do you see the phantomjs process running when you `ps aux | grep phantomjs`?

**Comment by thoop** [comment]
Feel free to reopen if you have any more info so we can look into this. Thanks!

**Comment by simonxu72** [comment]
I found this error too...

2016-07-28T13:24:47.866Z getting http://www.trust-one.com/product/cef027b8-9542-4cf8-affe-b6e6195a016e
2016-07-28T13:24:59.524Z getting http://www.trust-one.com/appointment_small/93484cac-dd83-4678-841d-0fda7537a85b
2016-07-28T13:25:05.753Z getting http://www.trust-one.com/news/155657
2016-07-28T13:25:09.118Z getting http://www.trust-one.com/news/36870
2016-07-28T13:25:10.311Z getting http://www.trust-one.com/news/898
2016-07-28T13:25:11.314Z getting http://www.trust-one.com/news/147845
2016-07-28T13:25:12.339Z getting http://www.trust-one.com/news/31880
2016-07-28T13:25:12.850Z getting http://www.trust-one.com/news/6708
2016-07-28T13:25:15.099Z getting http://www.trust-one.com/orgs/5218?tab=2
2016-07-28T13:25:19.040Z getting http://www.trust-one.com/news/120891
2016-07-28T13:25:30.069Z getting http://www.trust-one.com/news/observe
2



system: fbsd 10 /centos 7, all the same result

curl -v http://localhost:3000/http://www.trust-one.com/
[root@iZ23yk1teowZ ~]# curl -v http://localhost:3000/http://www.baidu.com
* About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /http://www.baidu.com HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3000
> Accept: */*
> 


nothing output.

ps aux |grep ahantomjs

$ ps aux |grep node
jxt-op 40714  1.0  0.8 674816 69532  2  I+    8:43PM     0:25.98 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40718  1.0  0.8 674816 69136  2  I+    8:43PM     0:25.19 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40719  1.0  0.8 674816 69156  2  I+    8:43PM     0:26.62 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40721  1.0  0.8 674816 68988  2  I+    8:43PM     0:26.27 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40716  0.9  0.8 674816 69036  2  I+    8:43PM     0:26.42 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40717  0.9  0.8 674816 69356  2  I+    8:43PM     0:25.74 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40722  0.9  0.8 674816 69476  2  I+    8:43PM     0:25.34 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40723  0.9  0.8 674816 69336  2  I+    8:43PM     0:26.07 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40715  0.8  0.8 674816 68968  2  I+    8:43PM     0:25.44 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40720  0.8  0.8 674816 69488  2  I+    8:43PM     0:25.81 /usr/local/bin/node /usr/home/jxt-op/prerender/server.js
jxt-op 40713  0.0  0.8 675124 68900  2  I+    8:43PM     0:00.74 node server.js
jxt-op 40961  0.0  0.0    380   288  3  R+    9:30PM     0:00.00 grep node
$ ps aux |grep phan
jxt-op 40963  0.0  0.0    380   288  3  R+    9:30PM     0:00.00 grep phan

any idea?

thanks.

**Comment by thoop** [comment]
Can you try setting the number of `workers` to 1 and then restart the server? And then send over the log output of the server starting. I want to see if phantomjs says it started fully. Then once you do that, can you send over the output of `ps aux | grep phantomjs`?

**Comment by simonxu72** [comment]
$ node server.js
2016-07-28T23:52:49.970Z starting worker thread #0
2016-07-28T23:52:50.227Z starting phantom...
2016-07-28T23:52:50.238Z Server running on port 3000
2016-07-28T23:52:53.468Z getting http://www.trust-one.com/news/35229
2016-07-28T23:52:56.643Z getting http://www.trust-one.com/news/140226


just the same result

$ ps aux |grep ph
jxt-op 44223  0.0  0.0    380    288  3  R+    7:53AM     0:00.00 grep ph


no phantomjs process

**Comment by simonxu72** [comment]
$ cat server.js
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
    workers: process.env.PHANTOM_CLUSTER_NUM_WORKERS ,
// || 10,
    iterations: process.env.PHANTOM_WORKER_ITERATIONS || 100
//    phantomBasePort: process.env.PHANTOM_CLUSTER_BASE_PORT || 12300,

});


process.env.PAGE_TTL = 3600 * 24 * 5; // change to 0 if you want all time cache
//server.use(require('prerender-redis-cache'));

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.basicAuth());
server.use(prerender.whitelist());
// server.use(prerender.blacklist());
server.use(prerender.logger());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
// server.use(prerender.inMemoryHtmlCache());
// server.use(prerender.s3HtmlCache());

server.start();

**Comment by simonxu72** [comment]
I found on my macbook 👍 

192:prerender simonxu$ node server.js
2016-07-29T00:11:00.350Z starting worker thread #0
2016-07-29T00:11:00.364Z starting worker thread #1
Redis Cache Connected
2016-07-29T00:11:00.870Z starting phantom...
2016-07-29T00:11:00.893Z Server running on port 3000
Redis Cache Connected
2016-07-29T00:11:00.907Z starting phantom...
2016-07-29T00:11:00.983Z Server running on port 3000
Redis Cache Connected
2016-07-29T00:11:03.155Z started phantom
2016-07-29T00:11:03.155Z started phantom
2016-07-29T00:11:34.865Z getting http://www.trust-one.com/
2016-07-29T00:11:40.295Z got 200 in 5430ms for http://www.trust-one.com/


---
phantom started ok!

</body></html>192:~ simonxu$ ps aux |grep phan
simonxu         10028   2.3  1.1  3757404  91336 s001  U+    8:11上午   0:06.62 /Users/simonxu/projects/prerender/node_modules/.npminstall/phantomjs-prebuilt/2.1.8/phantomjs-prebuilt/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1.2 --config=/var/folders/d6/kkwq6kbs5djgrb55btbxcvlw0000gn/T/f-116629-10027-5np2jk /Users/simonxu/projects/prerender/node_modules/.npminstall/phridge/2.0.0/phridge/lib/phantom/start.js /var/folders/d6/kkwq6kbs5djgrb55btbxcvlw0000gn/T/f-116629-10027-5np2jk
simonxu         10029   2.3  0.5  3616216  40780 s001  U+    8:11上午   0:06.05 /Users/simonxu/projects/prerender/node_modules/.npminstall/phantomjs-prebuilt/2.1.8/phantomjs-prebuilt/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1.2 --config=/var/folders/d6/kkwq6kbs5djgrb55btbxcvlw0000gn/T/f-116629-10026-qoaita /Users/simonxu/projects/prerender/node_modules/.npminstall/phridge/2.0.0/phridge/lib/phantom/start.js /var/folders/d6/kkwq6kbs5djgrb55btbxcvlw0000gn/T/f-116629-10026-qoaita


----

why phantomjs process not started in my production system?

thanks

**Comment by simonxu72** [comment]
redo npm install under freebsd 10:

npm install ok

node server.js
 node server.js
2016-07-29T00:20:14.485Z starting worker thread #0
2016-07-29T00:20:14.779Z starting phantom...
2016-07-29T00:20:14.791Z Server running on port 3000
/usr/home/jxt-op/prerender/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: 1: Syntax error: Unterminated quoted string
/usr/home/jxt-op/prerender/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: 1: Syntax error: Error in command substitution
2016-07-29T00:20:15.816Z getting http://www.trust-one.com/news/25903
2016-07-29T00:20:37.668Z getting http://www.trust-one.com/news/17551
2016-07-29T00:20:37.812Z getting http://www.trust-one.com/news/136818


---
strange!

while install, download phantomjs package name is :  phantomjs.....macosx.zip, does it right?

**Comment by simonxu72** [comment]
while install on centos 6, with node 4 local installed:
[jxt-op@trust-web prerender]$ npm install

> phantomjs-prebuilt@2.1.8 install /home/jxt-op/prerender/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT 192.30.252.123:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Please report this full log at https://github.com/Medium/phantomjs
prerender@4.0.10 /home/jxt-op/prerender
└── (empty)

npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/home/jxt-op/node-v4.4.7-linux-x64/bin/node" "/home/jxt-op/node-v4.4.7-linux-x64/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.8 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.8 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jxt-op/prerender/npm-debug.log
npm ERR! code 1
[jxt-op@trust-web prerender]$ 


-----
strange

**Comment by simonxu72** [comment]
freebsd install phantomjs was a known bug : #12963

**Comment by thoop** [comment]
Ah interesting. Good find. Yeah it looks like you weren't seeing this output confirming that phantomjs was started:

2016-07-29T00:11:03.155Z started phantom

This might be something good to create an issue on the phantomjs-prebuilt repository or whoever controls what gets installed on each system.

**Comment by simonxu72** [comment]
2016-07-29T00:11:03.155Z started phantom

this is ok for my macbook.

----
today I reinstalled several times, and finally get it done.

process: 
1.npm cache clean -n
2.npm install -g n
3.n stable

update nodejs version to 6.2.2

then, 
cd prerender
npm install

at this time, node server.js  running ok!

**Comment by thoop** [comment]
Great!
