### ISSUE TITLE
Cache freshness

### ISSUE THREAD

**Issue by someone235** [prerender/prerender#330]
In http://prerender.io there's a "Cache freshness" setting. How can I set this on my own prerender server?

**Comment by x3dfxjunkie** [comment]
We use S3 for cache, and have a policy on the bucket to remove objects over N days old.

**Comment by someone235** [comment]
Thank you

**Comment by thoop** [comment]
Be careful because that can cause you to have high average response times due to clearing a cached page instead of recaching over a previously cached page in order to keep it up to date. If you have a large website, clearing the cache entirely might cause the crawlers to think your website is slow.

**Comment by ArnaudValensi** [comment]
I made a fork with and automatic refresh system, based on urls of a sitemap.xml.
It uses mongodb.
You can deploy it with docker-compose to install mongodb at the same time.
It should work with heroku too.

https://github.com/ArnaudValensi/prerender-schedule-from-sitemap
