### ISSUE TITLE
$ is not defined from GoogleBot

### ISSUE THREAD

**Issue by someone235** [prerender/prerender#333]
Hi,
My site notify me for some of the JS errors user get. When I browse my site with ?_escaped_fragment_= , I get a page with not even one <script> tag, but I keep getting notified with "$ is not defined" from users with Googlebot user agent. How is it possible? Is it possible that googlebot somehow don't use ?_escaped_fragment_= ? How can I check it?

**Comment by thoop** [comment]
Did you try running your URL through a Prerender server to see if you see any error output? Make sure to enable the logger() plugin in server.js. Reopen this if you run into any issues.
