### ISSUE TITLE
Possible to integrate cloudfront with self hosted Prerender?

### ISSUE THREAD

**Issue by ankitkl** [prerender/prerender#334]
I know this question don't make any sense as CloudFront CDN meant for application performance enhancement.
Just want to make sure that is it possible to integrate any Cloudfront with prerender.io. As prerender modify URL to servers the JS content using phantom js

**Comment by thoop** [comment]
Last time I checked, it wasn't possible to implement the Prerender.io middleware at the CloudFront layer, but it's been a while.

If it's possible to create a behavior that checks for the `_escaped_fragment_` query parameter in the URL or the [specific user agents](https://gist.github.com/thoop/8165802#file-nginx-conf-L20) and send those requests to a different origin (the Prerender server), then that should work. I'm not sure if that's possible through CloudFront though.

We've had customers implement the Prerender.io middleware with CDN's like Akamai and it works well.

Feel free to reopen if you find that it's possible and have any questions.

**Comment by damwhit** [comment]
Any new findings on this?  Trying to figure out how to use prerender with an ember cli app that's being hosted on cloudfront.  
Would prefer not to have to use an ec2 nginx proxy but it seems like that may be the only way to go?

**Comment by thoop** [comment]
AWS recently introduced [Lambda@Edge](https://aws.amazon.com/blogs/aws/coming-soon-lambda-at-the-edge/) to be able to run small amounts of code at the CloudFront level! I haven't tried it yet but it looks like it should work just fine for integrating with Prerender.io. I think you can probably use the prerender-node middleware too.

**Comment by damwhit** [comment]
That's awesome news!  I'll check it out.  Thanks for getting back to me so quickly @thoop!

**Comment by jinty** [comment]
I just made an example of how to use Lambda@Edge to integrate Cloudfront and prerender.io:

https://github.com/jinty/prerender-cloudfront/blob/master/prerender-cloudfront.yaml

**Comment by thoop** [comment]
@jinty Whoa awesome! Have you tried it yet and does it work well?

**Comment by jinty** [comment]
@thoop 
Well, I wrote it ;) It definitely works for me on my S3 based SPA, I distilled the example from the configuration we're using at work.

**Comment by thoop** [comment]
That's super cool. Do you mind if I send people to it that ask me about using Prerender.io with Lambda@Edge?

**Comment by jinty** [comment]
On Thu, Feb 08, 2018 at 08:19:04AM -0800, Todd Hooper wrote:
> That's super cool. Do you mind if I send people to it that ask me about using Prerender.io with Lambda@Edge?

Go for it, that's why I published it.

Hmm, to complete the example I'm missing a good example domain with a
simple SPA. Do you know of one offhand?

-- 
Brian Sutherland

**Comment by thoop** [comment]
Hmm, I don't know of any good example SPAs that wouldn't mind being included in the example. You could always use www.example.com but that's not a SPA.

**Comment by tsgoff** [comment]
tested with self hosted prerender instance

`   {
    "name": "prerender.io",
    "children": [],
    "behaviors": [
        {
            "name": "origin",
            "options": {
                "cacheKeyHostname": "ORIGIN_HOSTNAME",
                "compress": true,
                "customValidCnValues": [
                    "{{Origin Hostname}}",
                    "{{Forward Host Header}}"
                ],
                "enableTrueClientIp": false,
                "forwardHostHeader": "ORIGIN_HOSTNAME",
                "hostname": "prerender.io",
                "httpPort": 80,
                "httpsPort": 443,
                "originCertificate": "",
                "originCertsToHonor": "STANDARD_CERTIFICATE_AUTHORITIES",
                "originSni": true,
                "originType": "CUSTOMER",
                "ports": "",
                "standardCertificateAuthorities": [
                    "akamai-permissive"
                ],
                "verificationMode": "CUSTOM"
            }
        },
        {
            "name": "baseDirectory",
            "options": {
                "value": "/render?width=320&height=820&url=https://{{builtin.AK_HOST}}"
            }
        }
    ],
    "criteria": [
        {
            "name": "userAgent",
            "options": {
                "matchCaseSensitive": false,
                "matchOperator": "IS_ONE_OF",
                "matchWildcard": true,
                "values": [
                    "*Googlebot*",
                    "Googlebot-News",
                    "*googlebot*"
                ]
            }
        },
        {
            "name": "fileExtension",
            "options": {
                "matchCaseSensitive": false,
                "matchOperator": "IS_NOT_ONE_OF",
                "values": [
                    "js",
                    "css",
                    "xml",
                    "less",
                    "png",
                    "jpg",
                    "jpeg",
                    "gif",
                    "pdf",
                    "doc",
                    "txt",
                    "ico",
                    "rss",
                    "zip",
                    "mp3",
                    "rar",
                    "exe",
                    "wmv",
                    "avi",
                    "ppt",
                    "mpg",
                    "mpeg",
                    "tif",
                    "wav",
                    "mov",
                    "psd",
                    "ai",
                    "xls",
                    "mp4",
                    "m4a",
                    "swf",
                    "dat",
                    "dmg",
                    "iso",
                    "flv",
                    "m4v",
                    "torrent",
                    "ttf",
                    "woff",
                    "svg",
                    "eot"
                ]
            }
        }
    ]
} 
`
