### ISSUE TITLE
Pre-render with reactjs?

### ISSUE THREAD

**Issue by jinxac** [prerender/prerender#338]
I compiled my reactjs using webpack and got a bundle file bundles.js. My bundles.js contains a component that make API calls to get the data.

Now,I call  http://service.prerender.io/https://mypage/home.

Now, I am witnessing something strange here, the ajax calls for APIS are not getting fired at all.

For example, I have a component called Home which is called when I request for url /home. My Home components makes an ajax request to backend(django-rest) to get some data. Now when I call home page in phantomjs this api call is not getting fired.

Am I missing something here?

**Comment by thoop** [comment]
Can you send the real URL to my email address so that I can test it? I'm not sure what's going on and I'd love to test it out. todd@prerender.io

**Comment by jinxac** [comment]
Sent you a mail regarding the details. Can you please check it once?

**Comment by nantaphop** [comment]
Me too...
No ajax call out from my component

**Comment by thoop** [comment]
@nantaphop Feel free to send me an email at todd@prerender.io with any issue you are seeing so that I can test it. Usually this is just a javascript issue on the page.

**Comment by isTravis** [comment]
Was there a solution to this? I'm having similar problems. No API calls are being fired from within my componentDidMount functions.

**Comment by jinxac** [comment]
I was not able to solve this either with pre-render or with phantom.js . So had to write little more code and do server side rendering.

**Comment by isTravis** [comment]
Found a solution for my issue at least. Turns out PhantomJS doesn't support promises [see issue](https://github.com/ariya/phantomjs/issues/12401) and all of my API requests use promises. So phantom would silently fail, never fire the request, and eventually time out after ~12s. 

The quick fix for me was to add a Promise polyfill somewhere towards the base of my code: 

```js
if (/PhantomJS/.test(window.navigator.userAgent)) { 
  require('es6-promise').polyfill(); 
}
```
