### ISSUE TITLE
?_escaped_fragment_= is not fetching from privately hosted heroku prerender server

### ISSUE THREAD

**Issue by xiaopow** [prerender/prerender#340]
Using Rails middleware.
set heroku ENV PRERENDER_SERVICE_URL=https://codeforxprerender.herokuapp.com/
prerender server is only modified with one setting `logRequests: true`
prerender server seems to be working fine by visiting https://codeforxprerender.herokuapp.com/https://www.google.com

but going to `production.com/?_escaped_fragment_=` is not fetching heroku prerender server, not logging fetch requests on prerender server log. 

Worked fine with prerender.io hosted service.

Also works when tested locally.

**Comment by xiaopow** [comment]
Modified prerender server slightly but still not working.

endable cookies plus the following plugins.

```
server.use(prerender.sendPrerenderHeader());
// server.use(prerender.basicAuth());
// server.use(prerender.whitelist());
// server.use(prerender.blacklist());
// server.use(prerender.logger());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
server.use(prerender.inMemoryHtmlCache());
// server.use(prerender.s3HtmlCache());
```

Switched back to prerender.io for now until we can figure out what's causing this.

server log shows that the requests is not being intercepted by prerender middleware when using heroku hosted prerender server.

```
Aug 23 12:29:44 codeforx app/web.1:  Started GET "/?_escaped_fragment_=" for 173.245.62.124 at 2016-08-23 04:29:43 +0000 
Aug 23 12:29:44 codeforx app/web.1:  Processing by StaticPagesController#index as HTML 
Aug 23 12:29:44 codeforx app/web.1:    Parameters: {"_escaped_fragment_"=>""} 
```

After switching back to prerender.io everything works as expected.

```
Aug 23 12:41:26 codeforx heroku/router:  at=info method=GET path="/?_escaped_fragment_=" host=www.codeforx.com request_id=6f450d41-aa57-40d5-a08a-42606ece1336 fwd="219.76.19.194,108.162.222.186" dyno=web.1 connect=0ms service=114ms status=200 bytes=5817 
Aug 23 12:41:26 codeforx app/web.1:  Started GET "/?_escaped_fragment_=" for 108.162.222.186 at 2016-08-23 04:41:25 +0000 
```

**Comment by thoop** [comment]
Sorry for the delay! There shouldn't be anything different about running your own prerender server that would cause the request to not go through. Which heroku command are you using to set the `PRERENDER_SERVICE_URL`?

**Comment by xiaopow** [comment]
@thoop , so after a few days of running the server it works now, with no settings changed. Not sure why. Consider it solved.
