### ISSUE TITLE
Javascripts are not rendering from html page.

### ISSUE THREAD

**Issue by mohitdguptattn** [prerender/prerender#341]
Hello Team,

The following is the nginx conf that I am using. I have used self hosted prerender. The java scripts are not rendering:

##
server {
	listen 443;
	root /usr/share/nginx/html;
	server_name test.fame.live;
	error_log /var/log/nginx/test.fame.live-error.log;
	access_log /var/log/nginx/test.livfame.com.access.log;
	#error_log /var/log/nginx/m.livfame.com.error.log debug;
        charset        utf-8;
        add_header Strict-Transport-Security "max-age=10886400; includeSubDomains; preload";
        ssl on;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 kEECDH+AES128 kEECDH+AES256 DES-CBC3-SHA +SHA !aNULL !eNULL !LOW !kECDH !kEDH !DSS !MD5 !EXP !PSK !SRP !CAMELLIA !SEED';
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_certificate /etc/nginx/ssl/start_fame_live.crt;
        #ssl_trusted_certificate /etc/nginx/ssl/intermediate.crt;
        ssl_certificate_key /etc/nginx/ssl/start_fame_live.key;
        ssl_session_cache shared:ssl_session_cache:100m;
        ssl_session_timeout 10m;

        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/ssl/trustchain.crt;
        resolver 172.31.0.2;

        location /nginx_status {
          stub_status on;
          access_log   off;
        }

	location / {
	  try_files $uri $uri/ /index.html;
                expires    1h;
                add_header Cache-Control "public";
                #add_header Vary Accept-Encoding;
	}

# Change YOUR_TOKEN to your prerender token and uncomment that line if you want to cache urls and view crawl stats
# Change example.com (server_name) to your website url
# Change /path/to/your/root to the correct value

 
    location @prerender {
        #proxy_set_header X-Prerender-Token YOUR_TOKEN;
        
        set $prerender 0;
        if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }
        if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") {
            set $prerender 0;
        }
        
        #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;
 
        if ($prerender = 1) {
            
            #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
            set $prerender "localhost:3000";
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://$prerender;
        }
        if ($prerender = 0) {
            rewrite .* /index.html break;
        }
    }
}

**Comment by thoop** [comment]
You need to use the `@prerender` location.

Try:

try_files @prerender $uri $uri/ /index.html;

or

try_files $uri @prerender $uri/ /index.html;

If those don't work, try moving all of the config inside the `@prerender` location above the try_files to see if it will execute first. Feel free to email support@prerender.io if you want us to help you get the middleware config set up.

**Comment by mohitdguptattn** [comment]
I have tried all these methods. But nothing is helping out.
