### ISSUE TITLE
prerender-status-code 404 returned as 200 not rendered

### ISSUE THREAD

**Issue by mkoczorowski** [prerender/prerender#344]
Hi.
I'm struggling to get 404 working in my app. I would appreciate some help here.

after adding dynamically <meta name="prerender-status-code" content="404"/>
before **window.prerenderReady = true** the request in the browser still returns **200** despite 

`2016-08-30T14:55:01.316Z got 404 in 3437ms for http://app.dev/page-not-found`
being logged in the prerender

the page renders fine, but it returns 200 code and loads all of the javascript like protractor were never run.

removing <meta name="prerender-status-code" content="404"/> from the response makes page being prerendered again.

am I missing somethig ? thanks

**Comment by mkoczorowski** [comment]
just noticed that even hard coding  <meta name="prerender-status-code" content="404">  int he html file results in curl returning 
HTTP/1.1 200 OK
Date: Tue, 30 Aug 2016 15:30:27 GMT

(content rendered is fine)

What am I doing wrong ?

**Comment by thoop** [comment]
Can you send a URL to test to support@prerender.io so that we can reproduce this and look into it?

Thanks!

**Comment by thoop** [comment]
Feel free to reopen if you are still having issues here. And we're happy to look into this if you'll email us the URL where you are facing this issue. support@prerender.io

**Comment by ciao-chung** [comment]
Hi, I had same problem.
I had appended prerender-status-code meta tag into head
`<meta name="prerender-status-code" content="404">`
And my prerender server log also display 404 status.
But crawler still got HTTP 200 status.
Is any solution for this issue?

**Comment by thoop** [comment]
In case anyone finds this issue in the future, it looks like the problem for @ciao-chung was the php middleware used was not returning the status code properly. I'm going to lock this issue. If anyone runs into this and needs help, please create a new issue so we can help!
