### ISSUE TITLE
render page on .onCallback

### ISSUE THREAD

**Issue by classyPimp** [prerender/prerender#346]
Is there any way to add custom handler for Phantom to listen to callback from client when it should  render, without relying on timeOut?

It could be done like: 
client-side:
when app decides that all is rendered it calls
`window.callPhantom({ msg: "render"});`

and on phantom side this will be caught and phantom would render the page
`
page.onCallback = function(data) {
  resolve page.content logic
};
`

I can't find where could I put such logic in your code.

**Comment by thoop** [comment]
I'm pretty sure Phridge, our Node -> PhantomJS binding, is a one way binding which is why we have to do the polling instead of something like this. If you find otherwise, feel free to let us know!

**Comment by classyPimp** [comment]
Thanks for the reply. 

Found the window.prerenderReady, it solves what I was asking. 

Though, Phantom supports callPhantom/onCallback, which could be used for the same purpose but without polling for prerenderReady.

**Comment by thoop** [comment]
Phantom supports that but Phridge doesn't give us access to that from the Node side of things so that isn't currently possible. Polling hasn't yet given us any issues there and we expose a lot of the timings for the polling intervals if you want to modify them.
