### ISSUE TITLE
Return custom status code

### ISSUE THREAD

**Issue by fk1blow** [prerender/prerender#347]
We have a single page app that connects to an api which may or may not respond, eg: could be down, the request object may be invalid, connectivity issues, etc. and we'd like to respond with a proper response code for those cases(4xx, 5xx) and not just a 200 and a page with important notifications/warning.

I think, this problem is very similar to `window.prerenderReady`, where the spa "notifies"
the prerender server that the page is ready to be rendered.

At this moment, i can see only 2 options: 
  - modify prerender io internals to return a status code based on a window variable, similar
    to `prerenderReady`, adding the proper status code to the response returned by prerender
  - build a plugin that "reads" a specific window variable which returns the proper status code

I would very much like to use the second option but before jumping to various hacks and workarounds.

Thanks in advance!

**Comment by thoop** [comment]
We currently have the `prerender-status-code` meta tag to allow you to do this. Would that work? See the plugin here: https://github.com/prerender/prerender/blob/master/lib/plugins/httpHeaders.js

After a 4xx or 5xx response from your server, you would insert this meta tag into the `<head>` of your page:
`<meta name="prerender-status-code" content="404">`

The plugin I linked above looks for this meta tag after the page is done loading and then returns the status code found in the content property as the new status code.

**Comment by fk1blow** [comment]
thanks, thoop, 
will try it out and come back with a result.

**Comment by fk1blow** [comment]
ok, this plugin works but with a slight problem(huge one, imho).
At the first hit, if i add a "prerender-status-code" meta, the status code inserted as the "content" attribute, makes prerender return that specific status code. One a second hit, the page is being fetched from the disk(we use the 'prerender-filesystem-cache' middleware) but now the status code returned is 200.
I think this happens because the `prerender-status-code` middleware is being bypassed, somehow(haven't looked at the flow, it's just my presumption).

**Comment by thoop** [comment]
calling res.send with the result is fine. You don't want it to continue on and render the page again. You want it to end there while returning the cached page.

It looks like the real issue is [this line](https://github.com/matthesrieke/prerender-filesystem-cache/blob/master/lib/file-system-cache.js#L33) isn't checking for a status code. They are always just saving to the cache, no matter the status code. That's bad.

Feel free to fork their code, check the status code, and send them a pull request!
