### ISSUE TITLE
Configuration for phantomJs

### ISSUE THREAD

**Issue by cullsin** [prerender/prerender#349]
Hello, 

Seems like prerender.io executes before phantomjs page load. Is there any configuration to allow the page to completely load all the html and doms.

Please suggest me on the same.

Raja  K

**Comment by thoop** [comment]
Prerender tries to wait for the page to fully load by counting the number of requests in flight and saving the page a short time after that number of requests in flight reaches zero. If that's still too early, you can use our `window.prerenderReady` flag: https://prerender.io/documentation/best-practices

If it's still saving too early, you might be running into a javascript error that is preventing the page from loading fully. You can turn on the `logger()` plugin by uncommenting that line in `server.js` and that should show any javascript errors when testing through the Prerender server.

If you need any help with that. Feel free to send an email to support@prerender.io.

**Comment by cullsin** [comment]
Hi, 

Thanks. One of our request talking little longer time to respond and it prerender / phantomjs unable to wait till the request or response complete. 

If incase I debug the prerender.io node module, can you suggest me where do I invoke setTimeout() function .

Please suggest me on the same. 

Raja K

**Comment by thoop** [comment]
You can change the values of different default timeouts by using environment variables from here: https://github.com/prerender/prerender/blob/master/lib/server.js
