### ISSUE TITLE
 og:url and Canonical url is not valid in facebook debugger

### ISSUE THREAD

**Issue by hardikaspire** [prerender/prerender#354]
Hi,
This is regarding angular js application having hashbang (!) in URL. So, normally the url for any page is like, **http://sampleurl.com/#!/home.**

The issue I am facing is with facebook debugger is passing the querystring parameters in URL. When og:url and canonical url contains the querystring parameters like, **"http://sampleurl.com/#!/home?id=123452&utm_source=samplesource&utm_campaign=samplename&utm_medium=samplemedium"** 

But, Facebook debugger, displays the canonical url and og: url as **"http://sampleurl.com/?id=123452&utm_source=samplesource&utm_campaign=samplename&utm_medium=samplemedium#!/home".**

is there any way to resolve it using prerender?

**Comment by thoop** [comment]
Responded to your email. Should be fixed now for you.
