### ISSUE TITLE
Is the project discontinued?

### ISSUE THREAD

**Issue by manusis** [prerender/prerender#355]
Hi Todd,

I do not see any recent commits to the code and I do not see any documentation for the prerender server as well. Is it intentional? 
Is the code base here is exactly the same as you run on your servers?

Thanks,
Rajiv

**Comment by thoop** [comment]
This project is not discontinued at all. We are working on Prerender.io every day. The Prerender server is in a very good position where it is as stable as it has ever been!

We run this exact code base on our servers, with a few custom plugins, and we have thousands of servers running at any moment.
