### ISSUE TITLE
How can I detect prerender request in my web app?

### ISSUE THREAD

**Issue by alexstanbury** [prerender/prerender#356]
I am using Angular 1.5 and ui-router, when accessing certain states from a desktop machine I automatically forward the user to a default child state, but I never do this on mobile. I would like to be able to disable this forwarding when prerender is accessing the page so only the parent state is shown.

I've tried searching for 'escaped_fragment' in the url and also doing some user agent matching but can't seem to get it to work. 

Can you shed any light on what approach I should be taking?

Thanks

**Comment by thoop** [comment]
I wouldn't recommend changing the content. You should serve the same content to the crawlers as you serve to users. If this is to make sure you serve the same content, then checking the user agent for "Prerender" should let you detect if Prerender is rendering your page.

**Comment by alexstanbury** [comment]
It's a little bit complicated because it's likely more people will be viewing on a mobile device which does not automatically go to the child state. This is also important for us to avoid duplicated/incorrect meta tags for specific URLs. 

Thanks for the tip, I'll see how I get on.
