### ISSUE TITLE
NGINX 504 Gateway timeout

### ISSUE THREAD

**Issue by benishak** [prerender/prerender#358]
Hi guys

I'm new to prerender

I just installed prerender on my server EC2 AWS t2.nano (1 CPU 512MB RAM)

I'm getting timeout Gateway

this is the logs

```
0|server   | 2016-10-31T17:38:24.804Z getting 
0|server   | 2016-10-31T17:38:25.409Z getting 
0|server   | 2016-10-31T17:38:35.369Z getting http://google.com/
0|server   | 2016-10-31T17:39:46.524Z Terminating worker #1 <-- crashes and restart again
0|server   | 2016-10-31T17:39:46.842Z starting worker thread #0
0|server   | 2016-10-31T17:39:47.032Z starting phantom...
0|server   | 2016-10-31T17:39:47.038Z Server running on port 3000 
```

my configuration in server.js

#!/usr/bin/env node
var prerender = require('./lib');

```
var server = prerender({
    workers: 1,
    iterations: 40 // i also try to set this to 10 then 0
});

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.basicAuth());
// server.use(prerender.whitelist());
server.use(prerender.blacklist());
// server.use(prerender.logger());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
// server.use(prerender.inMemoryHtmlCache());
// server.use(prerender.s3HtmlCache());

server.start();
```

In NGINX I set the send_timeout, proxy_timeout ... to 6000 

I also can see this error in the logs

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:380:9)
    at /home/centos/apps/prerender/node_modules/phridge/lib/spawn.js:102:38
    at startPhantom (/home/centos/apps/prerender/node_modules/phridge/lib/spawn.js:72:20)

```

How can I fix this issue

~~I'm using Node 6.9.1~~
~~I also tested with Node 4.6.1~~
I'm using Node 0.12.x

**Comment by benishak** [comment]
`unhandledRejection` is gone now after using Node 0.12.x
However it stills timing out

**Comment by benishak** [comment]
I also tested without using NGINX just using `http://myserver.com:3000/http://google.com` and it also timeout

**Comment by thoop** [comment]
Hi @benishak. A t2.nano might be too underpowered for running Prerender.

I'd also suggest putting your proxy_timeout higher to something like 20 seconds. I don't know how long your pages take to load, but you'll want to make sure the Prerender server has enough time to render your pages.

As for that error, are you seeing that when loading a page or is that error happening on startup? I haven't seen that error yet in Node v4 or v6.

You aren't passing any custom PhantomJS parameters?

**Comment by benishak** [comment]
when I check the load using `top` or `pm2 monit` I see 0% CPU usage for prerender process.
I even tried without NGINX just connecting directly to prerender NodeJS and still timing out. PhantomJS worker crashes and process restart.

I only saw that error on startup, only with Node 4.6.1 or 6.9.1

No i'm not passing any parameters

**Comment by benishak** [comment]
Im using last version of PhantomJS 2 , couldn't be the reason?
I install phantomjs binaries manually before runinng npm install,

**Comment by thoop** [comment]
Running `npm install` will install the correct PhantomJS version for you. That might be the reason. What happens when you just run `npm install` without already installing PhantomJS?

**Comment by benishak** [comment]
I got this error https://github.com/Medium/phantomjs/issues/344

I tried to fix it and only installing phantomjs manually solved the problem ....

**Comment by thoop** [comment]
Which error exactly? There are multiple errors there. Are you running your t2.nano with Windows?

**Comment by benishak** [comment]
this

https://cloud.githubusercontent.com/assets/12117128/7779940/223dd7f8-008e-11e5-9b28-b9e91d315a0b.PNG

**Comment by benishak** [comment]
no im using Centos7

**Comment by thoop** [comment]
Why is it trying to install PhantomJS 1.9.17? Which version of Prerender are you using?

Also why does it think you are on Windows NT?

It looks like it has you using Node v0.10.35. Can you upgrade to at least Node v4?

**Comment by benishak** [comment]
no that error is not from my screen but it is the same error, ignore windows and the other details.

the error is
```
Failed at the phantomjs-rebuild@2.... install script 'npm install.js'
```

**Comment by thoop** [comment]
Can you post the full error you are receiving? I'll need to see the full error to help diagnose the issue.

**Comment by benishak** [comment]
I removed the PhantomJS I manually install then I removed the node_module directory then I run `npm install` and didn't get that error
Then I realized why I got that error before is I didn't have `bzip2` installed and I install it when I install PhantomJS manually ... 

Now prerender works without timeout

```
0|server   | 2016-11-02T15:06:41.160Z getting http://google.com
0|server   | 2016-11-02T15:06:41.190Z + 1 http://google.com
0|server   | 2016-11-02T15:06:41.979Z - 0 http://google.com
0|server   | 2016-11-02T15:06:41.982Z + 1 http://google.com
0|server   | 2016-11-02T15:06:42.101Z got 301 in 941ms for http://google.com
```

So for everybody before running `npm install` make sure you have `bzip2` installed!

**Comment by benishak** [comment]
But I don't know why it do 301 redirection, i also tested on google.com

**Comment by thoop** [comment]
because http://google.com will redirect to https://www.google.com

Glad you figured it out.
