### ISSUE TITLE
How to prerender lazy-load content?

### ISSUE THREAD

**Issue by yairEO** [prerender/prerender#359]
There is much content which is being lazy-loaded (images, videos..) which for example means that an image HTML looks like this:

    <img data-src='whatever.jpg'>

And if a certain image is **in** the viewport area it will have its `src` attribute value changed to the value of `data-src`. in that case the chance will occur only on a real browser, where viewport measurement can be made, to determine if the image is "visible" or not. 

How would this work in a "prerendered" HTML page, which has no viewport or user scroll interaction which would replace all images `src`?

Thanks

**Comment by thoop** [comment]
In that case, Prerender would not scroll the page so those images wouldn't get lazy loaded. This is a case where I'd think you could check for "Prerender" in the user agent and just set the src from the data-src right away, and skip the lazy loading. As long as you are serving the same content to the crawler as you are serving to the user (same images, same content) then you shouldn't get penalized there.

**Comment by yairEO** [comment]
Maybe this would be helpful in the "Best Practices" or "FAQ" sections in your website, since I first went there to see what should I do in such situations but there was no information there regarding the user-agent sniffing, which is helpful. Thanks!

**Comment by thoop** [comment]
Ah, good suggestion. Thanks!

**Comment by pooledge** [comment]
Bumping this issue up. Let's say I would not want to pollute my markup with conditional output as suggested and serving a page with enormous amount of images above the fold, neither do I want prerenderer to trigger any lazy loading before caching. I'd rather let google bot decide about viewport size and provide it with more natural way of interaction with lazy content.

Could you please point out whether it is possible to inject `<script>` into the cached HTML on prerender.io? Wouldn't it be marvellous to have two different tiers of scripts for before and upon caching?

I hope it makes sense, thanks a lot.

**Comment by thoop** [comment]
Sorry, but we remove all `<script>` tags from the page after we capture the static HTML so that isn't possible to have two different tiers of scripts
