### ISSUE TITLE
Page running on custom port throws 404

### ISSUE THREAD

**Issue by theSupermacy** [prerender/prerender#360]
I am using prerender-node package which is running on localhost in port 8000. When I was using curl on 

> curl -X GET -H "Cache-Control: no-cache" -H "User-Agent: rogerbot" "http://example.com/ex"

.It gives me ,

> 2016-11-09T00:30:30.066Z got 404 in 2438ms for http://localhost:8080/ex
(8080 is the port Number)

Thus it is sending me the unrendered code.
After carefully seeing the log i have found the following error

**Comment by thoop** [comment]
Is your middleware just using the wrong host? Are you behind a proxy server that is changing the incoming URL? If so, you can use the host parameter in prerender-node similar to how protocol is set:https://github.com/prerender/prerender-node#protocol

just use `host` instead of `protocol`
