### ISSUE TITLE
Getting the error socket hang up and the Code is 'ECONNRESET'

### ISSUE THREAD

**Issue by theSupermacy** [prerender/prerender#361]
I am using prerender node package and I am getting the error after rendering. 
`prerender.set('afterRender', function(err, req, prerender_res) {
    if(err) console.log(err); 
})`
The output which i was getting 

>  [Error: socket hang up] code: 'ECONNRESET' 

I have still not found the way to solve this answer . My prerender server is running in the background and it is not throwing any error while redis server is also not showing any error.

**Comment by thoop** [comment]
What output are you seeing on your Prerender server? How long is the request taking before you see that error?

**Comment by theSupermacy** [comment]
It is taking too much time and after that it sends me this error . But in prerender server log i am not seeing any type of error

**Comment by thoop** [comment]
How long are you seeing the request take in the logs of your Prerender server? Can you show me the console output with your URL removed?

**Comment by thoop** [comment]
Going to close this issue since there hasn't been an update in a while. Please feel free to reopen if you are still experiencing issues.
