### ISSUE TITLE
cannot get prerender working with AngularJS build code

### ISSUE THREAD

**Issue by ChiragHindocha** [prerender/prerender#366]
I am using AngularJS 1.3.15. I want to make my AngularJS application crawlable by Google. Everything works when I test the app with local prerender server in my local environment as described here: https://prerender.io/documentation/test-it

I have generated angular app using yeoman angular generator. But when I build the code for production & test with prerender server, I get following error:

`Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.` 

I am also attaching a screenshot of the same.
I tried setting the window.prerenderReady = false; initially, & making it true only when everything is ready, but it doesn't help. Can you please help me with the issue? My codebase is very large. I have doubts that there might be some JS linting errors. Is there anything else I am missing or I need to work in that direction? (i.e. fixing JS linting errors) Kindly note that **it doesn't work only when I build my app for production**. Any help will be highly appreciated. Thanks
![screenshot_from_2016-12-17_17_40_31](https://cloud.githubusercontent.com/assets/10279728/21286770/f83e7f7e-c482-11e6-9404-de6ddbde2984.png)

**Comment by thoop** [comment]
I've sometimes seen this when <script> tags are in the <body>. PhantomJS will load <script> tags in the <body> completely asynchronously, so certain files can be loaded out of order. If your scripts have dependencies on other scripts, can you try loading them all in the <head> to make sure they load in the right order?

**Comment by ChiragHindocha** [comment]
Hi Todd Hooper thanks for the quick response. I forgot to mention but I tried all possible ordering for loading scripts, but it doesn't help. I re-confirmed that the order for loading scripts is correct. What might be wrong now? If you need I can provide more info. Thanks

**Comment by thoop** [comment]
Can you send me the URL you are testing? todd@prerender.io

I'll see what I can find.

**Comment by ChiragHindocha** [comment]
sure, I am testing on this url:
http://dev.fangol.pl/view/187323/gdy-zapomnisz-wylaczyc

**Comment by thoop** [comment]
I'm seeing the <script> tags in the body. Can you try moving them into the <head> so I can test that and see if the error is still present? Let me know when you make that change.

**Comment by ChiragHindocha** [comment]
Now scripts are in head on this url:
http://dev.fangol.pl/view/187324/kolejna-szalona-obietnica

**Comment by itaborda** [comment]
Hi @ChiragHindocha 

I have the same problem with the <script,s> load order in PhantonJS, because i have two scripts with dependency  between them.

Can you solve it?

**Comment by thoop** [comment]
@ChiragHindocha It looks like these errors might be causing the issues you're seeing:

```
[Error] SyntaxError: Attempted to redefine property 'description'.
(anonymous function) (scripts.fb9b6aa8.js, line 2)
```
```
[Error] SyntaxError: Unexpected string literal "impression". Expected a ':' following the property name 'change'.
(anonymous function) (kolejna-szalona-obietnica, line 124)
```

Can you fix those two errors and we'll see if that fixes things? Sorry for the delay here!

**Comment by ChiragHindocha** [comment]
@itaborda sure I can look at it if I can help

**Comment by ChiragHindocha** [comment]
@thoop thanks for the tips, can you provide me some hint to reproduce those errors as I am not able to reproduce same in my development environment.

**Comment by thoop** [comment]
Unfortunately, PhantomJS doesn't report those errors and I had to use an older version of Safari to see those errors. Let me know if you'd like me to test it again once you get those fixed.

**Comment by thoop** [comment]
Any update here? Fixing those errors should get things working again. Feel free to reopen if you are still experiencing issues there.
