### ISSUE TITLE
Feature: Is it possible to make --ssl-protocol as a configurable variable?

### ISSUE THREAD

**Issue by wyytctc** [prerender/prerender#368]
Right now the --ssl-protocol is hard coded to tlsv1.2
It doesn't work very well when there is code in ajax posting to some website using different ssl protocols.
I'm wondering if it's possible to make it a configurable variable so I don't have to hard code it to 'any'

Thanks

**Comment by thoop** [comment]
That's the default, but you can pass in custom arguments using `phantomArguments`: https://github.com/prerender/prerender/blob/master/lib/server.js#L74

```
var prerender = require('prerender');

var server = prerender({
    phantomArguments: {
        '--load-images': false,
        '--ignore-ssl-errors': true
    }
});

server.start();
```
That should default it to "any" and you can pass any other phantomjs options that are supported. Let me know if that doesn't work!

**Comment by wyytctc** [comment]
Thanks!
