### ISSUE TITLE
How to deploy at Cloudways / DigitalOcean  ?!

### ISSUE THREAD

**Issue by AymanEG** [prerender/prerender#369]
Hello there,

I managed to deploy @ heroku without any problem , but I already have an account at DigitalOcean through cloudways. It come with php and node and npm all installed.

Installing is ok , I managed to  node server.js through putty ,but what now ?! I can not listen to the server or scarp anything.

@ Heroku : https://app-name.herokuapp.com/http://google.com will do the trick ,but doing same with my php stack do nothing.

PS : I installed the git at "prerender" folder @ Cloudsway app stack
Any ideas ?!

regards

**Comment by thoop** [comment]
The prerender server just runs a node web server on a certain port. So as long you have it running on an accessible port, it should work just fine. Sounds like your configuration might not be allowing requests to go through to the prerender node server.

**Comment by AymanEG** [comment]
Thanks for your reply, I spoke with them and they appear to block the port server use through firewall.

Can I change the requested port to default one 80 ??! like running the server at mydomain.com/prerender. If possible ,kindly explain how.

Best regards

**Comment by thoop** [comment]
Yep! Just set the PORT environment variable and it will start on that port:
`export PORT=80`

**Comment by AymanEG** [comment]
Thanks, I knew there is a way around.
I will try and confirm if it works
