### ISSUE TITLE
First prerender call returns not rendered page

### ISSUE THREAD

**Issue by zwolej** [prerender/prerender#371]
So it seems that every first call to prerender server always return not rendered page. It is some known issue or something ? I am using curl to fetch page data
`curl sprawdzforex.pl/contact?_escaped_fragment_=`
Is there any problems with caching or something like that ?

I am using my own hosted prerender server and nginx configuration of prerender.(angular 2)

Edit I saw that it can be also problem that prerender fire to fast and it sometimes catch loading progress bar without waiting to fetch router outlet part

**Comment by thoop** [comment]
The Prerender server should work correctly every time.

Are you using `window.prerenderReady` to tell the prerender server to wait longer before caching the page?

Can you send over your prerender server console logs?

**Comment by zwolej** [comment]
So I'am not using prerenderReady flag(I dont know when to call it? in every component ngInit ?). Second in logs there's no any errors or so. I figure out that when I am calling from google search console  Google crawler sometimes show me full code of page, but sometimes:

```
<app-root _nghost-ajv-7=""><!!--template bindings={}--><i _ngcontent-ajv-7="" class="fa fa-spinner"></i>
<router-outlet _ngcontent-ajv-7=""></router-outlet>
</app-root>
```

So it seems that it not loaded router outlet. It seems like it finished rendering after app.component initialized. So i should use this prerenderReady flag, but I dont have idea how to call it in other way than calling when any component fire ngInit which is kinda ugly.

**Comment by zwolej** [comment]
at the moment the best way I found out is to use

```
constructor(private route: ActivatedRoute, private router: Router) {
    router.events.subscribe((event: any) => {
      if (event instanceof NavigationEnd) {
        window['prerenderReady'] = true;
      }
      this.navigationInterceptor(event);
    });
  }
```
It seems that now prerender always fetch whole content. But I am still not sure if google index proper my page in google search console I have no internal links and I have only 1 page indexed.

**Comment by thoop** [comment]
Sorry for the delay! It's hard to say if you are hosting your own prerender server since we won't have your logs...but it looks like I'm seeing a correctly prerendered page here:

http://sprawdzforex.pl/contact?_escaped_fragment_=

So it looks to be working correctly now!
