### ISSUE TITLE
Doesn't work with Discord, Slack clone

### ISSUE THREAD

**Issue by mcblum** [prerender/prerender#372]
I was just on it and I pasted one of our links which showed a bunch of Angular code. Any idea if this could be added?

**Comment by thoop** [comment]
Which middleware are you using? You should be able to add the discord user agent to the middleware.

**Comment by thoop** [comment]
Haven't heard back but feel free to reopen if you run into issues. You should be able to just add discord's user agent to your list of user agents being checked.
