### ISSUE TITLE
Isn't escaped_fragment deprecated? 

### ISSUE THREAD

**Issue by mort3za** [prerender/prerender#376]
Google [deprecated](https://developers.google.com/webmasters/ajax-crawling/docs/specification) using escaped_fragment for SEO. So what happens now with this project?
Should I use prerender `now`?
We know that google renders javascript but it has many issues with ajax contents and timeouts. So what should we do?!

**Comment by thoop** [comment]
Yes, Google did announce that they've deprecated the escaped fragment crawling protocol but their crawler still supports crawling and indexing content using the escaped fragment crawling protocol for websites that use it.

Google does still have issues indexing ajax content when executing javascript on their own. We've also seen issues with Google crawling at a very slow rate if they are executing javascript, which makes it extremely hard to index all of your pages.

Prerender works just as well as it has in the past, so we still suggest using Prerender and supporting the escaped fragment crawling protocol (don't check Googlebot by their user agent).

Feel free to reopen if you have any other questions!
