### ISSUE TITLE
The Render server wont free the memory

### ISSUE THREAD

**Issue by ztz0223** [prerender/prerender#377]
I have set my prerender server by myself, and everytime I use curl to get my site like the spider, I see the phantomjs process is using more and more memory, and the phantomjs is invoked by the prerender server.

And my site is evey lite and is a single page website with AngularJS, http://www.doocr.com/, any suggestions on this issue?  The memory not freed is boring me.

Thanks.

**Comment by ztz0223** [comment]
After read the doc again, I found that the prerender will free the memory by restarting, I will check and test this.

All in all, thanks a lot to the contributors.

**Comment by thoop** [comment]
Sure thing! I'd suggest lowering the `softIterations` and `iterations` options: https://github.com/prerender/prerender#softiterations

Feel free to reopen if you still have issues.
