### ISSUE TITLE
Run prerender on a subroute

### ISSUE THREAD

**Issue by jensvdh** [prerender/prerender#384]
Is it possible to run prerender on a seperate route?

I want to run prerender on http://localhost:3000/prerender/http://example.com instead of http://localhost:3000.

for technical reasons, I can not set-up a reverse proxy in front of prerender so that's not a possibility.

**Comment by thoop** [comment]
You can export a `PORT` environment variable to change which port it uses. If you mean a different route on your own website where localhost:3000/prerender goes to the prerender server and a request to localhost:3000 goes to your normal website, then that's not possible with just the prerender server.

**Comment by jensvdh** [comment]
Yeah I basically wanted prerender to listen on a different root path instead of "/". But since this is not supported I will have to find a different workaround.

Would be cool to have an option that can be passed in, root-route or something that would support this.

Feel free to close the issue. Thanks for answering my question 👍

**Comment by thoop** [comment]
Sure thing!
