### ISSUE TITLE
 try to test Prerender on localhost

### ISSUE THREAD

**Issue by Anikinly** [prerender/prerender#386]
how to point  local Prerender server with:

export PRERENDER_SERVICE_URL=http://localhost:3000

**Comment by RyanBertrand** [comment]
See the docs here: [https://github.com/prerender/prerender#running-locally](https://github.com/prerender/prerender#running-locally)

**Comment by thoop** [comment]
Thanks @RyanBertrand !

@Anikinly Depending on which middleware you are using, you might have to do something a little different to point to your local instance. Let me know which middleware you're using if you still have questions about that.
