### ISSUE TITLE
504 while trying to receive data

### ISSUE THREAD

**Issue by ilouHD** [prerender/prerender#389]
Hello,

I'm developing a software in Node.JS (Express) and Angular 4 and I added prerender using
`app.use(require('prerender-node').set('prerenderServiceUrl', 'http://127.0.0.1:3000'));`
to my Express-Server.

When I visit my website on localhost ( http://localhost:8080/?_escaped_fragments_ ) I get the prerendered website (Status-Code: 200) but when I try the same on my Website (proxied through nginx, see config below) I get an 504:

> 2017-04-05T21:23:43.097Z getting https://2001/:4dd7:caf0:0:b91f:e80a:58d7:38d1/
2017-04-05T21:23:43.446Z got 504 in 349ms for https://2001/:4dd7:caf0:0:b91f:e80a:58d7:38d1/

My Express-Server runs in both cases on port 8080 and the prerender-server in both cases locally on port 3000

My nginx-config at the moment looks like this (proxy-part):
```
	upstream websuite {
		server localhost:8080;
		keepalive 64;
	}
	
	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real_IP $remote_addr;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Host $remote_addr;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

		proxy_read_timeout 60s;
		proxy_send_timeout 60s;

		proxy_pass http://websuite;
		gzip on;
	}
```

In my nginx-error-log I get this message:

> 2017/04/05 21:39:35 [error] 4668#4668: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 2001:4dd7:caf0:0:b91f:e80a:58d7:38d1, server: nodelab-it.de, request: "GET /?_escaped_fragment_ HTTP/2.0", upstream: "http://[::1]:8080/?_escaped_fragment_", host: "nodelab-it.de"

Does anyone has an idea how to fix this issue?

Greetings from Germany
ilou

**Comment by ilouHD** [comment]
Do you mean to set the host-option using `prerender.set('prerenderServerRequestOptions', {host: '127.0.0.1'})`
?
If I did it right (Can't find any docs regarding these options) nothing changed; same error as before.

**Comment by thoop** [comment]
Great! You'll probably need to point that to the correct domain in production too
