### ISSUE TITLE
Links don't work in generated pages

### ISSUE THREAD

**Issue by bostondevin** [prerender/prerender#390]
I'm generating the cached pages and noticing none of the links work - they are still going to the hash. All the links are coded as such in angular:

`<a ui-sref="{page: 'contacts'}" ui-sref-opt="{absolute: true}">Contacts</a>
`

And then the output looks like this from Phantom:

`<a ui-sref="{page: 'contacts'}" ui-sref-opt="{absolute: true}" href="#!/contacts/">Shopping Cart</a>
`
Shouldn't these links be somehow converted to the cached page url so google can find them? I'm doing something wrong here...

Thanks
- Devin

**Comment by thoop** [comment]
If you are using the `#!` in your URLs, then that href looks to be correct. The URL in your HTML should not be the escaped fragment URL. It should just be the normal URL that you want crawlers and users to go to.

That being said, we don't recommend using the `#!` in your URLs. We recommend using normal html5 push state URLs with the `<meta name="fragment" content="!">` tag in the `<head>` of your pages if possible.

**Comment by thoop** [comment]
If you are using `#!` URLs on your site, the crawlers that support the escaped fragment crawling protocol will see those URLs and access them like `?_escaped_fragment_=/contacts/` by automatically replacing the `#!` with the `?_escaped_fragment_=` query parameter. The Prerender.io middleware will see that escaped fragment query parameter and send the request to Prerender.io.

You are right that the crawlers that don't support the escaped fragment crawling protocol will only ever see your homepage if you are using `#!` URLs. If you switch to html5 push state URLs, then everything will work just fine.
