### ISSUE TITLE
Prerender doesn't return rendered page

### ISSUE THREAD

**Issue by tevch** [prerender/prerender#391]
Express server runs on port 3100
Prerender server runs on port 3000

I am going 
http://localhost:3000/http://localhost:3100

Prerender server shows error

2017-04-17T06:19:20.361Z getting http://localhost:3100/
ReferenceError: Can't find variable: Map

  http://localhost:3100/assets/vendor.js:102759 in getJsMapConstructor
  http://localhost:3100/assets/vendor.js:102756 in jsMapCtor_$LI$
Error: Could not find module `ember-resolver` imported from `spotassist/resolver`

  http://localhost:3100/assets/vendor.js:233 in missingModule
  http://localhost:3100/assets/vendor.js:244 in findModule
  http://localhost:3100/assets/vendor.js:178 in findDeps
  http://localhost:3100/assets/vendor.js:248 in findModule
  http://localhost:3100/assets/vendor.js:178 in findDeps
  http://localhost:3100/assets/vendor.js:248 in findModule
  http://localhost:3100/assets/vendor.js:31 in requireModule
2017-04-17T06:19:31.966Z Timed out. Sending request with HTML on the page

I could guess some javascript fails, but why?

Going directly to http://localhost:3100 is ok, no errors

**Comment by thoop** [comment]
Can you try including a Map polyfill for browsers that don't support it? PhantomJS v2.1.1 (our current rendering engine) does not support Map out of the box. Sorry for the inconvenience!

**Comment by tevch** [comment]
Yes, that was it

Thanks a lot
