### ISSUE TITLE
Prerender returns blank page.

### ISSUE THREAD

**Issue by lakesare** [prerender/prerender#394]
I'm going to `http://www.memcode.com/courses?_escaped_fragment_=`, and see nothing (no errors too, just html page without script tags).

**Comment by lakesare** [comment]
Okay, on localhost I'm actually seeing `TypeError: undefined is not a function (evaluating 'query.startsWith(name)')`, I'll install the polyfill now.

**Comment by lakesare** [comment]
I was adding ES5 and ES6 polyfills to my backend's `index.js` accidentally :D 
When I added them to frontend's `index.js` issue disappeared.

**Comment by thoop** [comment]
Ah, great! We plan on switching our rendering engine to Headless Chrome once that's available. That will support ES6, but we haven't had many issues with that yet.
