### ISSUE TITLE
ReactApp

### ISSUE THREAD

**Issue by junaid-malik-confiz** [prerender/prerender#395]
Hello,

Its really great open-source helps a lot rendering html for the Search Engine crawler. We recently build a react app but it is not supported on it. Can you please guide us how we can fix this?

Regards,
Junaid

**Comment by thoop** [comment]
Hi there! React is supported by Prerender. Can you send us a URL of your website so we can test it? support@prerender.io

I assume there is another issue going on there. Thanks!
