### ISSUE TITLE
Prerender loads blank page, with no errors, how to debug?

### ISSUE THREAD

**Issue by kingsloi** [prerender/prerender#398]
Hi,

My prerender setup works fine for other sites, however, for the site I need to be prerendered, it loads a blank page with no errors in the console. 

The kicker is, I have already set up all my ES6 to be compiled down to ES5 using Laravel Elixir/Webpack. It worked roughly around a month ago, but I'm approaching the project launch, and decided to check everything is all up and running and realised it no longer works, but just shows a blank page, 0 errors in console. 

I'm just wondering if there are any tips you can recommend to debug? I guess it's a problem with my JavaScript, because other elements of the JS-generated DOM elements are included in the source code, but my `<router-view></router-view>` never seems to render. 

The URL for my app is: http://67.205.145.225/ and prerender server is at http://67.205.145.225/home?_escaped_fragment_=

Thanks!

**Comment by kingsloi** [comment]
**FIXED**

I believe it was something to do with a babel dependency I'm sure of it. Maybe an incorrect version, or I bumped up something along the way. What scared me was there was no actual messages being outputted, no logs, no console, no anything, so I had no idea how to debug.

I'm 99.9% sure it's babel/ES6 related at least. I found out that Phantom JS 2.5 had at least partial support for ES6, so I downloaded that and replaced the phantomjs executable in node_modules/phantomjs-prebuilt/lib/`

I was able to fix it by manually downloading 2.5 from https://bitbucket.org/ariya/phantomjs/downloads/ (specifically: phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz)

I hope I was able to help at least someone.

**Comment by thoop** [comment]
Unfortunately, PhantomJS doesn't show some errors when there are errors related to ES6. Not sure why that is, but we were able to get errors to show up by testing the same pages in older versions of Safari (v8).

We haven't tested the PhantomJS 2.5 beta yet so we don't suggest anyone use that in production without verifying themselves. Glad you were able to fix it!

**Comment by thecatontheflat** [comment]
@kingsloi You're a saver!

**Comment by thoop** [comment]
Our latest Prerender server uses Chrome and shouldn't have any issues with ES6.

**Comment by thecatontheflat** [comment]
@thoop Thanks for the update! 
I should have specified that the problem was on version `4.4.1`

Cheers!

**Comment by kingsloi** [comment]
@thecatontheflat I appreciate you! I'm actually running into issues with my prerender service now - I got this alert and saw @thoop's comment about headless Chrome! I never knew it was released. Cheers guys!
