### ISSUE TITLE
Forward http headers to target

### ISSUE THREAD

**Issue by mhf-ir** [prerender/prerender#401]
Hot to forward HTTP headers to target that phantomjs will be loaded?
I need to set custom headers to phantomjs that request from server.
For example
`X-My-Path: /app/proxy/dir`
i will send this header to prerender server and during console log it's available but prerender dosnt send this header to target server. how can i do this. what's the best practice.

This header must be available on request target for example in php

```
var_dump($_SERVER['HTTP_X_MY_PATH']); // '/app/proxy/dir'
```

**Comment by thoop** [comment]
you would want to write a plugin for the prerender server that set the customHeaders on PhantomJS like:

```
module.exports = {
    onPhantomPageCreate: function(phantom, req, res, next) {
        var headerKey = 'headerKey';
        var headerValue = 'headerValue',

        req.prerender.page.run(headerKey, headerValue, function(headerKey, headerValue, resolve) {

            var headerObj = {}
            headerObj[headerKey] = headerValue;

            this.customHeaders = headerObj;

            resolve();

        }).then(function() {

            next();
        });
    }
}
```
