### ISSUE TITLE
Error: Cannot communicate with PhantomJS process: Unknown reason

### ISSUE THREAD

**Issue by Mixelito** [prerender/prerender#403]
I'm using prerender to serve a site that is accessed over 3 million times a day by bots.

I mounted a structure in aws with ebs that scale c4.large instances based on cpu usage.

I use cache in s3 to decrease consumption in phantomjs, but it is very common to return error 504. 
It has hampered the indexing of our site.

I wanted to understand if they could explain how you stop the high consumption and how to minimize errors 504 phantomjs failures.

> 2017-06-12T17:40:22.605Z phantomjs terminated
> 2017-06-12T17:40:22.607Z starting phantom...
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 479): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 480): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 481): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 482): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 483): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 484): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 485): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 486): Error: Cannot communicate with PhantomJS process: Unknown reason
> (node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 487): Error: Cannot communicate with PhantomJS process: Unknown reason
> 2017-06-12T17:40:22.785Z started phantom

**Comment by thoop** [comment]
Sorry for the delay here!

How many PhantomJS servers are you running? Looks like you are just overloading PhantomJS and it's crashing. 3 million requests per day is a lot! We currently serve 45 million per day and have a large number of servers, along with heavy caching.

If you have a large number of pages, feel free to get in touch with me and I'll see how we can get you running on our hosted service at a reasonable cost. todd@prerender.io
