### ISSUE TITLE
Prerender.io not working in React App.  Need help

### ISSUE THREAD

**Issue by GoChartingAdmin** [prerender/prerender#404]
Hi,

I deployed my react app with prerender.io but I am unable to view the html version of my landing page.

Moving it to the support@prerender.io forum

Regards

**Comment by thoop** [comment]
I would expect to see a prerendered page when going to this URL but instead I'm seeing the javascript:
`https://www.gocharting.com/?_escaped_fragment_=`

Which middleware are you using? Feel free to send us an email at support@prerender.io
