### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by namerci** [prerender/prerender#410]
Hi, I have some troubles with prerender running on local machine. My current setup is:

```
#!/usr/bin/env node
var process = require('process');
var prerender = require('prerender');
var os = require('os');

var config = {
    workers: 2,
    softIterations: 5,
    iterations: 10,
    logRequests: false,
    accessLog: {
        // Check out the file-stream-rotator docs for parameters
        fileStreamRotator: {
            filename: 'log/access-%DATE%.log',
            frequency: 'daily',
            date_format: 'YYYY-MM-DD',
            verbose: false
        },

        // Check out the morgan docs for the available formats
        morgan: {
            format: 'combined'
        }
    }
};

var server = prerender(config);
server.use(require('prerender-access-log'));
server.use(prerender.sendPrerenderHeader());
server.use(prerender.blacklist());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();
```

And when I open 10 pages via prerender like http://localhost:1337/https://www.thetimes.co.uk/ then I got some errors like this. Sometimes I have more than one UnhandledPromiseRejectionWarning in a row. 

`│ prerender > 2017-07-07T09:07:56.979Z PhantomJS restarted in the middle of his request. Aborting...                                                     │ prerender > (node:17791) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): TypeError: Cannot read property 'stdin' of null`

Is there a option to prevent this errors? It looks like it crash when phantomjs is restarted. Is there a way to run all request on one phantomjs and if softIteration or maxInteration reached, then restart this phantomjs and in same time use second one?

**Comment by thoop** [comment]
It seems like you have iterations set to 10, and then you're sending a large number of requests so it hits 10 iterations and kills the server...which affects other requests in flight.

The softIterations is supposed to restart the server only when there are no requests in flight. I'd suggest you try setting iterations to something higher, like 50, and try spreading out your requests more so that it can restart itself more often.
