### ISSUE TITLE
Dynamic metas are placed in body

### ISSUE THREAD

**Issue by rkurbatov** [prerender/prerender#411]
We have a react SPA meta-tags dynamically changed for different routes and that is one of the reasons we use prerenderer.io. But it seems like our metatags are added to the end of rendered HTML BODY instead of HEAD. That's pretty strange, as in normal mode metas are updating correctly. Does anybody have this problem?

**Comment by thoop** [comment]
I've seen this before if you have an `<iframe>` being injected into the `<head>` of your HTML. Since `<iframe>`'s technically are supposed to be in the `<body>`, your browser will end the `<head>` and start the `<body>` before an `<iframe>`.

**Comment by rkurbatov** [comment]
Thnaks, but any other possible reason? I carefully checked everything and found no iframes either in head or in body tags.

**Comment by rkurbatov** [comment]
@thoop could you reopen this issue as I still no have answer for my question.

**Comment by thoop** [comment]
Can you send the URL in question to todd@prerender.io?

I'll be happy to take a closer look at the URL to see what might be the issue.

**Comment by rkurbatov** [comment]
Sent a link, thanks for quick response.

**Comment by ngodichat** [comment]
Hi @rkurbatov , is the problem solved? If yes, please share the experience and solution cuz I am experiencing the same issue. Thank you!

**Comment by thoop** [comment]
@ngodichat Are you seeing an `<iframe>` at the top of the `<body>` tag? Feel free to send us the URL in question so we can test and see what the issue might be.
