### ISSUE TITLE
Headless Chrome

### ISSUE THREAD

**Issue by Kikobeats** [prerender/prerender#413]
I want to ask if you have any plan for switch from PhantomJS to Headless Chrome.

Basically, because creator of Phantom stepping down as maintainer
https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE

Headless Chrome sounds promising with lower error rate,.

I suppose it isn't in your plan in terms of short or medio actions, but could be interesting use Headless Chrome in the future.

I see [some projects working on that](https://www.google.es/search?q=switch+phantomjs+to+headless+chrome&oq=switch+phantomjs+to+headless+chrome&aqs=chrome..69i57.8052j0j1&sourceid=chrome&ie=UTF-8).

**Comment by thoop** [comment]
Yep! See this issue:
https://github.com/prerender/prerender/issues/318

We also have our current state of our chrome implementation on the chrome branch of our prerender repo
