### ISSUE TITLE
airportd SecTaskLoadEntitlements failed error=22

### ISSUE THREAD

**Issue by jamgold** [prerender/prerender#414]
Whenever I run prerender on my Mac, the log is filling up with 

`airportd[43683]: SecTaskLoadEntitlements failed error=22`

messages. Does anybody know how to prevent this?

**Comment by thoop** [comment]
Hmm, I've never seen that. Which version of node are you using? And which version of OSX are you using?

**Comment by jamgold** [comment]
OSX 10.11.6 and node v0.12.7

**Comment by thoop** [comment]
It looks like airportd manages the wireless interface. We don't use airportd directly with our prerender server so I'm not sure what might be causing that. Seems like something specific to how you have your mac set up. Sorry we can't be of more help here!
