### ISSUE TITLE
phantom don't start after running node server.js

### ISSUE THREAD

**Issue by nasserghiasi** [prerender/prerender#415]
phantom don't start after running node server.js
I tried everything, node version 4,6,7,8
![2017-07-09_19-38-30](https://user-images.githubusercontent.com/2284751/27995126-51f8e92c-64de-11e7-90ef-623b5ca99b3b.jpg)

**Comment by thoop** [comment]
Which operating system are you using? Did you see any errors when running `npm install`?

**Comment by nasserghiasi** [comment]
my OS has locale issue and I solved this issue with this command:
```
sudo nano /etc/environment
#append below line
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

**Comment by thoop** [comment]
Great! Thanks for posting the fix.
