### ISSUE TITLE
Getting Temporarily unreachable error on Fetch as Google

### ISSUE THREAD

**Issue by manikmi** [prerender/prerender#417]
Hi,

I have cloned this project code and ran it on my server using PM2.
if I run the url http;//www.>myprerenderserver>.com/http://www.google.com, then it is working.
But, if I add the property in my google webmasters account and try to run fetch as google, it is always returning "Temporarily Unavailable"

![image](https://user-images.githubusercontent.com/797398/28557465-401f4360-712a-11e7-8a0b-ead5435edca6.png)

Can you help me what can be the issue.

**Comment by thoop** [comment]
I don't think you'd ever want to add the URL of your prerender server as a property under Google Webmaster Tools. The prerender server should sit behind your website and your website is the one serving prerendered pages to Google by using the Prerender middleware.

**Comment by manikmi** [comment]
Hi,
I am running my website only on angular (w/o nodejs) on nginx.

I tried the config that are mentioned here https://gist.github.com/thoop/8165802 

But it did not work and Fetch as Google showed angularjs {{}} based attribute names only, not the values. that's why tried to debug by putting the direct url to my prerender site in the Fetch as Google

**Comment by thoop** [comment]
You can use the nginx middleware instead of the node middleware.

Fetch as Google has a known bug where they don't automatically request the `?_escaped_fragment_=` URL so you will have to put `?_escaped_fragment_=` on the end of the URL manually when using Fetch as Google. The real Googlebot does not have that issue and they will request the `?_escaped_fragment_=` URL if they see the `<meta name="fragment" content="!">` tag in the `<head>` of your page.

**Comment by manikmi** [comment]
Thanks a lot Todd. This worked. 
So, I did 2 things:
1. Making my prerender installation a property in my fetch as google was not working, which started working.
2. Adding the ?_escaped_fragment_= at the end of url helped in getting the results in the fetch as google.

**Comment by saavyrelations** [comment]
Hello, This side of **Saavy Relations**, just starts up an IT company based in Gurgaon, India. I’m trying to fetch URL from last 3 days, but every time I'm getting a message (Temporarily unreachable). My server is fine & checked the Robots.txt is also ok. 

How to solve this issue. please resolve this issue asap. Thanks

**Comment by thoop** [comment]
Please send me an email at todd@prerender.io with some more information on your website, the middleware you are using, and how you have that set up. I'll be happy to look into it.
