### ISSUE TITLE
Prerender Self hosted Service failing intermittently

### ISSUE THREAD

**Issue by manikmi** [prerender/prerender#418]
Hi,

I am using angularjs based website with nginx as the server and without node js.
I have used the nginx settings as mentioned here: https://gist.github.com/thoop/8165802 
I have configured a two server approach:

1. Website is running on a server: www.mywebsite.com. Running on SSL port 443
2. Prerender is running on another server: www.myprerenderservice.com. Running on port 80

The prerender service is running with PM2 as the process manager

In google crawler, I have used ?_escaped_fragment_= as well

The google crawler is sometimes able to return the results, while sometimes not. If it fails, I just tried killing the Prerender PM2 service and start it again and clear memory on server and then try it again. It starts working again for once. But it fails again. Don't know what is happening. Can somebody help?

![image](https://user-images.githubusercontent.com/797398/28756170-ad39daf4-7586-11e7-9ead-54a3bb2eaeae.png)

**Comment by manikmi** [comment]
Guys,

Thank you for the continued support. Would appreciate if I could get a quick response. This is a production issue for us and requires little urgency.

Truly appreciate the help,
Manik Mittal

**Comment by thoop** [comment]
Feel free to send your logs to support@prerender.io if that's easier. We'll take a look.

**Comment by manikmi** [comment]
Thanks a lot Todd,
I was able to resolve the issue. Yes, looking at the logs helped.
So for the sake of community, I am adding the issue details and resolution.

I have two front-end servers take them as www.mywebsite.com and www.mywebsite2.com. On both the servers, Prerender is enabled in nginx. On the basis of some business logic, the app is redirecting the requests from 1 server to another. 

So, what happened is the request flows like this:

1. Request comes to www.mywebsite1.com from google crawler
2. It gets redirected to www.myprerenderservice.com
3. Which internally makes a call to www.mywebsite1.com
4. Which redirectes to www.mywebsite**2**.com
5. As the prerender is enabled there as well, it redirects to www.myprerenderservice.com

In this whole loop, the request gets time out (i guess) and failed.

> the fix is did is to stop the redirection in step 3 if the call is with user-agent="Prerender"

**Comment by thoop** [comment]
Make sure you are doing a proxy request to your prerender server and not a redirect. If you do a redirect, that's signaling Google that you want your users to be sent to your prerender server which is very bad. Proxying the request to your prerender server to return to the crawler will return the HTML through your website and it the correct way to set that up.

**Comment by manikmi** [comment]
Thankyou Todd for the continued support,

Yes, I am following your config mentioned here: https://gist.github.com/thoop/8165802
