### ISSUE TITLE
machine crashes after error in phantomjs

### ISSUE THREAD

**Issue by eefth** [prerender/prerender#419]
Hello, 
After the following errors that i see in kernel.log the machine crashes:
 ul 28 22:28:48 middleware kernel: [992951.013766] traps: phantomjs[12052] general protection ip:f5d7a0 sp:7ffdd4af39c0 error:0 in phantomjs[400000+228e000]
Jul 28 23:04:41 middleware kernel: [995103.884481] traps: phantomjs[23251] general protection ip:f5d7a0 sp:7fff23e9f0f0 error:0 in phantomjs[400000+228e000]
Jul 28 23:13:38 middleware kernel: [995641.248613] traps: phantomjs[9369] general protection ip:f5d8c2 sp:7fffb76eea00 error:0 in phantomjs[400000+228e000]
Jul 28 23:14:27 middleware kernel: [995689.938727] traps: phantomjs[7154] general protection ip:f5d7a0 sp:7fffa787c4b0 error:0 in phantomjs[400000+228e000]
Jul 29 02:52:14 middleware kernel: [1008756.459084] traps: phantomjs[2777] general protection ip:f5d7a0 sp:7ffec6aa3b70 error:0 in phantomjs[400000+228e000]
Jul 30 02:55:09 middleware kernel: [1095331.440084] traps: phantomjs[22463] general protection ip:f5d7a0 sp:7ffd5e556650 error:0 in phantomjs[400000+228e000]
Jul 30 02:55:12 middleware kernel: [1095335.263439] traps: phantomjs[17845] general protection ip:f5d7a0 sp:7ffc5a2ae710 error:0 in phantomjs[400000+228e000]

Do you have any idea?

**Comment by thoop** [comment]
I've never seen that before. Which operating system version are you using?

**Comment by thoop** [comment]
Which version of debian?

**Comment by eefth** [comment]
Linux middleware.hotelgenius.co 3.16.0-4-amd64 #1 SMP Debian
3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

**Comment by thoop** [comment]
Is there any more information you can provide like URL being crawled when it crashed? This seems more like a phantomjs issue instead of a prerender issue that we can fix.

**Comment by eefth** [comment]
Im sorry but i am new to prerender. 
Where can i find the logs of prerender, phantomjs? I use a docker image earlyclaim/docker-prerender-with-redis.

**Comment by eefth** [comment]
Although i don't see any log files changing, there is a folder with dumps. Could this be helpful to analyze?

**Comment by thoop** [comment]
The Prerender server just logs to the console by default and you can set that up to log somewhere else, like if you're using pm2 it might be under /var/log/nodejs/

**Comment by thoop** [comment]
Going to close this without any more information. Try using our `chrome` branch if you are still running into any issues here.
