### ISSUE TITLE
Is the S3 cache broken?

### ISSUE THREAD

**Issue by nlyn** [prerender/prerender#421]
I noticed the object structure in S3 seems kinda weird:

<img width="593" alt="screen shot 2017-08-11 at 13 51 11" src="https://user-images.githubusercontent.com/1793253/29213692-3be84ef2-7e9c-11e7-9c47-c27da6de8185.png">

It makes clearing the cache very time-consuming.

**Comment by nlyn** [comment]
S3 Cache is not broken - Transmit's UI is

If anyone else finds this, I recommend using the S3 manager in the AWS console. It works perfectly and you can delete objects much quicker in there.

**Comment by thoop** [comment]
Ah, weird! Yeah we use the S3 manager in the AWS console or write our own scripts to clear page on S3.
