### ISSUE TITLE
Pages not fully caching

### ISSUE THREAD

**Issue by aequasi** [prerender/prerender#422]
Trying to prerender https://discordservers.com, but its not doing and of the react logic... I'm probably missing something stupid simple

**Comment by aequasi** [comment]
Apparently, react doesnt support phantomjs...

https://github.com/facebook/react/pull/4393#issuecomment-121857904

**Comment by hensansi** [comment]
Have a look into this
https://github.com/prerender/prerender/issues/423

**Comment by thoop** [comment]
Yeah check out our chrome branch! If you are using our hosted prerender service, shoot me an email at todd@prerender.io and I'll turn on Chrome rendering for your account.
