### ISSUE TITLE
Its not work on SPA - Angular 1.x

### ISSUE THREAD

**Issue by muzammilahmed-gt** [prerender/prerender#424]
Hello,
I've build a website of online furniture and its front end build on angular 1.4 and its consists of api's which are on node 6. Its mean html are not generated on node(server side). Angular factory call node apis such like http://mysite.com/api/getcategories.

I've include a middleware in my node server.js file
app.use(require('prerender-node'));

Please make my life easier by smart solution

**Comment by thoop** [comment]
Hi there, can you email us at support@prerender.io and send over your real website URL? That way we can help look into it. Thanks!
