### ISSUE TITLE
ReferenceError: Can't find variable: Set    http://localhost:1337/bower_components/webcomponentsjs/webcomponents-lite.js:145

### ISSUE THREAD

**Issue by hekod777** [prerender/prerender#425]
Hi

I was trying to use prerender to render a simple polymer 2.0 app.

I experience this error:

```
ReferenceError: Can't find variable: Set

  http://localhost:1337/bower_components/webcomponentsjs/webcomponents-lite.js:145
  http://localhost:1337/bower_components/webcomponentsjs/webcomponents-lite.js:190
```
the actual code is 

`new Set("…`

even if I compile the polymer app down to ES5 compatible, this `new Set()` line is still there

I understand that this is an issue for phantomJS

I'd like to know if there is any workaround for it?

**Comment by thoop** [comment]
You can include a polyfill for Set for browsers that don't support it (like PhantomJS) or you can try to use the `chrome` branch of the prerender server to render your pages in Chrome instead. Chrome supports Set by default.
