### ISSUE TITLE
Recache manually some already cached pages

### ISSUE THREAD

**Issue by judit21ninjas** [prerender/prerender#426]
Good afternoon,

We have a question about the prerender service. We have installed prerrender in our web application infrastructure and until now we haven't got any problem, but now we want recache some pages manually to update our already cached server versions.

We've tried adding this to our url:
http://domain.com/?_escaped_fragment_=recach/, and it works.  The problem is that if you try again with http://domain.com/?_escaped_fragment_=/ the server sends the old version instead a new cached one.

We want to recache some pages in order to not remove all the already cached pages. Is there any way to do it?

We have checked this link, but doing the request to our server it happens nothing.
https://prerender.io/documentation/recache

Thank you.

**Comment by thoop** [comment]
The recache API on https://prerender.io/ only works when you are using our hosted service. If you are hosting your own Prerender server, you'll need to handle clearing pages from your cache however you've set your cache up.

If you are using our hosted service, you can log into your Prerender.io account and clear/recache any URLs using our website.

**Comment by rubenjimenez** [comment]
Uhm, if we have all our pages cached via S3, is there any way to handle that? When we open our S3 bucket we see http and https folders. Inside, there're a lot of folders with URLs in their titles.

But we don't know how to locate a concrete page (for example, the home) within S3 to remove it.

Thanks and regards!

**Comment by thoop** [comment]
You would want to write some code using one of the AWS SDK's to clear pages from S3. We use the node SDK[1] and it works great.

[1] https://aws.amazon.com/sdk-for-node-js/

**Comment by rubenjimenez** [comment]
Ok, that's what we were looking for. Great.

So, the key/value would be something like this: { "url": "http://www.example.com/" }

Am I right?

Thanks!

**Comment by thoop** [comment]
You'd want to use the deleteObject command from s3 and the `Key` would be the URL.

**Comment by rubenjimenez** [comment]
Thanks @thoop. It worked like a charm.

Regards!
