### ISSUE TITLE
Unhandled promise rejection on page with asynchronous call

### ISSUE THREAD

**Issue by Gnorro** [prerender/prerender#428]
Hi all

I have an Angular4 App

I cloned:
https://github.com/prerender/prerender

I added:
<meta name="fragment" content="!"> 

I started node server.js
Calling http://localhost:3000/http://localhost:4200/ I get this error:
TypeError: useValue,useFactory,data is not iterable!

So I uncomment the following in polyfills.ts file:
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/weak-map';
// import 'core-js/es6/set';

Then I got this error:
ERROR TypeError: undefined is not a constructor (evaluating 'b.style._set(a.prop
ertyName(c),d)')

  http://localhost:4200/vendor.bundle.js:113418 in defaultErrorLogger
ERROR TypeError: undefined is not a constructor (evaluating 'b.style._set(a.prop
ertyName(c),d)')

  http://localhost:4200/vendor.bundle.js:113418 in defaultErrorLogger
TypeError: undefined is not a constructor (evaluating 'b.style._set(a.propertyNa
me(c),d)')

  http://localhost:4200/polyfills.bundle.js:5875 in apply
  http://localhost:4200/polyfills.bundle.js:5875
  :0 in forEach
  http://localhost:4200/polyfills.bundle.js:5875
  http://localhost:4200/polyfills.bundle.js:5875 in k
  http://localhost:4200/polyfills.bundle.js:5875
  :0 in forEach
  http://localhost:4200/polyfills.bundle.js:5875 in g
  http://localhost:4200/polyfills.bundle.js:5875 in d

I solved importing NoopAnimationsModule instead of BrowserAnimationsModule in app.module

Now I can get some page working, except for those where there is an asynchronous call to backend API.
Here I have always this error:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot communicate with PhantomJS process: Unknown reason (node:8068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

Any ideas?
Thanks

**Comment by thoop** [comment]
Can you try running our `chrome` branch? PhantomJS sometimes has issues with Angular 4 and the `chrome` branch uses Google Chrome as the rendering engine instead. That should get things working correctly. If you are using our hosted service, let us know and we can switch your account over to use Chrome with our hosted service.

**Comment by Gnorro** [comment]
Hi and thanks for your reply

With this branch I get:

D:\Test\prerender-chrome>node server.js
2017-09-10T14:09:15.768Z Starting Prerender
2017-09-10T14:09:15.771Z Starting Chrome
2017-09-10T14:09:15.772Z unable to find Chrome install. Please specify with chro
meLocation
2017-09-10T14:09:15.788Z Prerender server accepting requests on port 3000
undefined
2017-09-10T14:09:15.790Z Failed to start and/or connect to Chrome. Please make s
ure Chrome is running
2017-09-10T14:09:15.791Z Stopping Chrome
(node:7252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 2): TypeError: Cannot read property 'kill' of undefined
(node:7252) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

Do I have to install something else?
Thanks

**Comment by thoop** [comment]
Where do you have the Chrome.exe installed on your windows system? By default we check at `C:\Program Files (x86)\Google\Application\chrome.exe` but that could be wrong.

**Comment by Gnorro** [comment]
Chrome location is:
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

But it continues to give the same error:
2017-09-11T07:18:08.453Z Starting Prerender
2017-09-11T07:18:08.458Z Starting Chrome
2017-09-11T07:18:08.461Z unable to find Chrome install. Please specify with chromeLocation
2017-09-11T07:18:08.464Z Prerender server accepting requests on port 3000
2017-09-11T07:18:08.465Z { Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at module.exports (D:\test\prerender-chrome\lib\index.js:25:13)
    at Object.<anonymous> (D:\test\prerender-chrome\server.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000 }
2017-09-11T07:18:08.479Z Stopping Chrome
D:\test\prerender-chrome\lib\browsers\chrome.js:38
        this.chromeChild.kill('SIGINT');
                        ^

TypeError: Cannot read property 'kill' of undefined
    at Object.chrome.kill (D:\test\prerender-chrome\lib\browsers\chrome.js:38:18)
    at Object.server.killBrowser (D:\test\prerender-chrome\lib\server.js:90:15)
    at Server.httpServer.on (D:\test\prerender-chrome\lib\index.js:18:10)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)

This is my server.js:
#!/usr/bin/env node
var prerender = require('./lib');

//var server = prerender();

var server = prerender({
	chromeLocation: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
});

server.use(prerender.sendPrerenderHeader());
server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();

**Comment by Gnorro** [comment]
Now it works with:
chromeLocation: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'

And seems to prerender correctly. I'll tell you something more in the next hours after some tests. 

Thanks

**Comment by thoop** [comment]
That previous error was a different error:

`2017-09-11T07:18:08.465Z { Error: listen EADDRINUSE :::3000`

That means something else was already using port 3000.

Can you try it again with the previous path (with the backslashes) and see if it works?

**Comment by Gnorro** [comment]
Hi
chromeLocation: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
doesn't wok

can't find chrome

**Comment by thoop** [comment]
Ok cool. We'll change that to forward slashes.

**Comment by thoop** [comment]
This should be fixed in our latest version of Prerender.
