### ISSUE TITLE
UI-VIEW is blank and bower injected components do not appear

### ISSUE THREAD

**Issue by ateixeiramunoz** [prerender/prerender#429]
In my site (MEAN.js stack)  i´m trying to make prerender work

Read [this issue](https://github.com/prerender/prerender/issues/209) before and no solution worked for me. 

I´ve been trying different combinations, but my ui-view is always blank. 

> **What I did:**
> 
> In My html:
> 
>  - Added  `<meta name="fragment" content="!">`
>  - Added  `<script> window.prerenderReady=false;</script>`
> 
> In my App.js: 
> 
>    $rootScope.$on('$viewContentLoaded', function(){ window.prerenderReady = true;});

 

> **What I see:** 
> 
>   - The ui-view is blank (from cached version, etc...)
>   - I solved a CORS incident before with one of the CSS´s. Nothing changed.

> **What I Suppose:**
> 
>   - It seems the `vendor.js` and `app.js` scripts are not being injected (bower). (cannot ensure the reason, but I don´t see any Js on prerender cache. 

Can anybody help me plz? 
Thanks in advance

**Comment by thoop** [comment]
Just responded to your email but I think the issue here is PhantomJS might be having trouble rendering your pages. You might want to try our `chrome` branch instead.

**Comment by ateixeiramunoz** [comment]
ok. Will try this week with your comments. Thanks a lot.
