### ISSUE TITLE
auto proxypass in server.js

### ISSUE THREAD

**Issue by scher200** [prerender/prerender#431]
@thoop 

Reffering to: [this issue comment](https://github.com/prerender/prerender/issues/44#issuecomment-329821820)

Would it not be nice if the standard server.js would do some nice proxying passing with static files like images and js and css. Just to make the tests work more out of the box and easy when viewing in the browser.
You would just launch node server.js and visit: http://localhost:3000/http://localhost:4200
And it would render your site (including relative paths css/js/images)

**Comment by thoop** [comment]
This makes it hard because our Prerender server would have to know if it's a static file so it doesn't try to open it in the browser. So we'd need to have a big whitelist for static files not to load in the browser.

That's out of the scope of this project since this is only an "issue" when testing. If your site had a <base> tag in the <head>, I think that would prevent these issues altogether since the base tag is used when determining the path of relative links.

**Comment by scher200** [comment]
Dear @thoop, you are right about the base tag, when I change the it to:
```
<script>
document.write("<base href='"+window.location.protocol+'//'+window.location.hostname+(window.location.port ? ':'+window.location.port:'')+'/'+"'/>");
</script>
```
instead of
```
<base href="/">
```
it starts working...

Could it maybe be possible to do a second chance, like if a file returns a 404, it will be retried once at "http://requested-domain.com/filename.ext".

**Comment by thoop** [comment]
I don't think that's possible since the HTML is returned to your browser and your browser is the one that sees the 404.

**Comment by scher200** [comment]
That's right but the request is on http://localhost:3000/http://localhost:4200 and that means http://localhost:3000 (which is the prerender io (test)server) sends the 404, then it could check rather it could be proxy passed to http://localhost:4200 (which is the real host).

**Comment by scher200** [comment]
That's right but the request is on http://localhost:3000/http://localhost:4200 and that means http://localhost:3000 (which is the prerender io (test)server) sends the 404, then it could check rather it could be proxy passed to http://localhost:4200 (which is the real host).

**Comment by thoop** [comment]
Well if the relative link is for "app-1234.css" then your browser makes a request to:

http://localhost:3000/app-1234.css

The Prerender server doesn't know which URL is the original URL besides checking the referer header or something. That's just not something we want to support. We don't want the prerender server to be a proxy for static files.

**Comment by scher200** [comment]
I see what you mean
