### ISSUE TITLE
Consider a setting to prevent loading images in Chrome

### ISSUE THREAD

**Issue by tspacek** [prerender/prerender#432]
With PhantomJS you can set `phantomArguments: { "--load-images": false }` to avoid loading images. This is useful as it avoids unnecessary loading.

With Chrome there's no equivalent setting, as far as I can tell. Puppeteer do it like this, by intercepting network requests: https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js

This would be a useful addition to the (already great) Chrome branch.

**Comment by thoop** [comment]
Thanks! We should already be preventing loading images:

https://github.com/prerender/prerender/blob/chrome/lib/plugins/blockResources.js

Are you currently not seeing images being blocked with the chrome branch?

I do like the way they are doing it though. That seems cleaner.

**Comment by tspacek** [comment]
Ah my bad! I just assumed it was loading them as I didn't see an option to disable it.

I added `.svg` and `.woff2` to that list but still got quite a lot slower performance than PhantomJS, which seems the wrong way around.

**Comment by thoop** [comment]
Yeah we've only seen Chrome speed up the rendering of pages. You might want to turn on the `logRequests` option and see what's taking longer to load. It could be that you have 3rd party resources sending more requests under Chrome.
