### ISSUE TITLE
Prerender not caching pages with graphs

### ISSUE THREAD

**Issue by Pia-Hasija** [prerender/prerender#433]
I have a website in angular js where on a page, I am showing graph. Few api's are getting called during page load. Pre-render caches blank page for those pages having graphs. Is there any way we can have a timeout when data gets cached?

**Comment by thoop** [comment]
It sounds like our PhantomJS rendering engine might be having trouble with those pages. Can you try the `chrome` branch of this repo and see if Chrome renders those pages correctly?

**Comment by Pia-Hasija** [comment]
Hi @thoop , 
Thanks for your reply. I tried chrome branch locally it seems to work fine.

**Comment by thoop** [comment]
Great! We'll eventually move away from phantomjs and move over to chrome as the rendering engine for Prerender on the master branch.
