### ISSUE TITLE
Not setting the documentHTML property

### ISSUE THREAD

**Issue by vIceBerg** [prerender/prerender#435]
Hi!

In the chrome branch, in the server.js file, server.firePluginEvent, res.send method:

```
res.send = function(statusCode, html) {
			if (statusCode) req.prerender.statusCode = statusCode;
			if (html) req.prerender.html = html;
			done = true;
			reject();
		};
```

I think the html assignation should be:

`if (html) req.prerender.documentHTML = html;`

**Comment by thoop** [comment]
ah, yes. You're correct! Sorry about that. We have an upcoming change that will fix that. If you checked out this repo, you can change that yourself to get it to work for now until we push our latest change with the fix.

**Comment by thoop** [comment]
This should be fixed with our latest version of Prerender.
