### ISSUE TITLE
Using this properly on an angular project for pre-rendering

### ISSUE THREAD

**Issue by hanoii** [prerender/prerender#436]
What would be the proper way to use this polyfill on an angular project which I need to prerender?

I tried the bower approach but I get the non-auto polyfill versión.

I am now including the auto manually, but I wonder what would be the better way of doing this.

Thanks.

**Comment by thoop** [comment]
Which polyfill? If you want to switch to our Chrome rendering engine on the `chrome` branch, then you probably wouldn't need any polyfills since Chrome supports all of the up to date javascript features.
