### ISSUE TITLE
[Angular 4.3.6] URL don't work

### ISSUE THREAD

**Issue by rcsty** [prerender/prerender#439]
Hello,

I'm working on an Angular project on which I tried to implement some SEO. You're well aware of the issue this may cause so I started using Prerender.io.

**What I have**
I created a node server that I use to prerend any website (so I can have http://localhost:3000/https://localhost:4200/).
I then configured my crawler to start on this URL.

- I have this in my _index.html_:
`<base href="/">`
`<meta name="fragment" content="!">`

- My internal links look like this:
`<a role="link" routerLink="/shop">Shop</a>`

**Where I have an isue**
The crawler has no issue to get the home page but when it tries to follow the links, he sees them like that: http://localhost:3000/shop when I want it to be http://localhost:3000/https://localhost:4200/shop.

I read some issues about the fragment and how to fix URL that have a # but I have none in my app.

Does anyone know how I can have my URL to be "prefixed" correctly ? It would help me a lot.

Thanks for the support,

Raphael

**Comment by thoop** [comment]
Hi Raphael,

Sorry for the delay.

Going to `http://localhost:3000/https://localhost:4200/` is great for testing that the page is rendered correctly, but you don't want any crawlers to access that URL directly. Instead, you will want them to access:

`https://localhost:4200/?_escaped_fragment_=`

If you have the Prerender middleware installed, the middleware will be the one that requests the `http://localhost:3000/https://localhost:4200/` URL and serve that HTML back through your server. Then, all of your href links should point to the correct place.

Let me know if you have any questions about that.

**Comment by thoop** [comment]
This shouldn't be an issue when accessing your prerendered page through your middleware instead of accessing the API directly so I'm closing this issue. Please let me know if you have any other questions here!
