### ISSUE TITLE
Page not rendering properly

### ISSUE THREAD

**Issue by bitqistchris** [prerender/prerender#441]
Hey,

I'm using the hosted prerender service. All pages are working properly except for one page. Without the ?_escaped_fragment_= suffix the page loads properly, but unfortunately it does not with the suffix. I've tried to debug the issue, but I'm unable to find the reason. It seems to stop rendering after an array.find call. However I strongly suspect that the reason is in another thread (I'm using AngularJS, async)

An example of an URL where prerender does not work is:
https://bitqist.com/currencies/bitcoin?_escaped_fragment_=
Working version:
https://bitqist.com/currencies/bitcoin

Can anyone help me with this?

Thanks!

**Comment by thoop** [comment]
Seems like our PhantomJS browser is running into an issue (it might not support Array.find). We can enable our Chrome rendering engine for you if you are using our hosted service. Just send us an email. If you are running your own Prerender server, you might want to check out our Chrome branch!

**Comment by bitqistchris** [comment]
Thanks, I set up my own Prerender server with the Chrome branch and that indeed fixed the problem. Can you tell me when inMemoryHtmlCache will be implemented for the chrome branch?

**Comment by thoop** [comment]
Sorry, no ETA yet on the memory cache but should be easy to implement yourself in the meantime.

**Comment by bitqistchris** [comment]
Thanks, I implemented it myself.
