### ISSUE TITLE
504 in 505ms for socket.io/?EIO=3&transport=polling

### ISSUE THREAD

**Issue by shaun-ba** [prerender/prerender#442]
In logs we're receiving 100s of 504s, what is the cause of this?

**Comment by thoop** [comment]
I'm not sure. It could be that PhantomJS doesn't support sockets or something? Can you send a screenshot of your logs with the URLs it's accessing? Can you try out our Chrome branch to see if that makes a difference:

https://github.com/prerender/prerender/tree/chrome

**Comment by thoop** [comment]
Closing issue without some more information. Please reopen with more information if you still run into issues.
