### ISSUE TITLE
 rendering latest react Hello World app

### ISSUE THREAD

**Issue by arpecop** [prerender/prerender#444]
![screen shot 2017-11-12 at 2 46 48 pm](https://user-images.githubusercontent.com/168974/32699103-dd85388c-c7b8-11e7-8596-324488a58ca4.png)

**Comment by thoop** [comment]
Hi there! You might want to try our chrome branch: https://github.com/prerender/prerender/tree/chrome

That should work fine and we'll be merging that into master soon

**Comment by arpecop** [comment]
Thanks for the reply, and sorry if this is not the right place to ask  ,when to expect that chrome renderer in netlify, or at lease accept the X-Prerender-Browser: chrome header (I've changed that)
Regards!

**Comment by thoop** [comment]
Great question. We will try to get in touch with Netlify and see if they are interesting in switching over to Chrome. It probably wouldn't be until we switch all of our users over to Chrome. We don't have a set date yet but we plan for it to be after the new year.

**Comment by thoop** [comment]
Feel free to reopen if the chrome branch didn't fix your issue!
