### ISSUE TITLE
How to change the URL of the post being shared on Facebook. Currently Service.Prerender.io

### ISSUE THREAD

**Issue by JeanHules** [prerender/prerender#447]
Currently, when I share a page from an Apache Angular application, everything works, but the small grey URL of the Facebook post says, "Service.Prerender.io". 

Is there a way to make this say the URL of my website?

**Comment by thoop** [comment]
That sounds like you have the middleware set up incorrectly. If you have it set as a redirect (with the R flag), make sure you change that to a proxy (with the P flag) like this:

`
RewriteRule ^(?!.*?(\.js|\.css|\.xml|\.less|\.png|\.jpg|\.jpeg|\.gif|\.pdf|\.doc|\.txt|\.ico|\.rss|\.zip|\.mp3|\.rar|\.exe|\.wmv|\.doc|\.avi|\.ppt|\.mpg|\.mpeg|\.tif|\.wav|\.mov|\.psd|\.ai|\.xls|\.mp4|\.m4a|\.swf|\.dat|\.dmg|\.iso|\.flv|\.m4v|\.torrent|\.ttf|\.woff))(.*) http://service.prerender.io/http://example.com/$2 [P,L]
`

**Comment by JeanHules** [comment]
I was missing the "P" in [P,L]. Thanks for the help!

**Comment by malkitsingh** [comment]
Hi,
I am using prerender service at my own server with Nginx and here is how I am using it.
my application runs at xyz.com and my prerender server is running at pre.xyz.com
I am facing the same issue (facebook grey bar shows pre.xyz.com instead of xyz.com). Can anyone help how to fix this issue?
Here is the snippet of my configuration file of Nginx server 

```
# self hosted pre render service
server {
	listen 443 ssl;
	ssl on;
    ssl_certificate /home/ubuntu/newssl/ssl-bundle.crt;
    ssl_certificate_key /home/ubuntu/newssl/xyz.key;
	server_name pre.xyz.com;
	location / {
      proxy_pass http://localhost:1337;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
	}
	
}

# xyz.com 
server {
	listen 443 ssl;
	ssl on;
    ssl_certificate /home/ubuntu/newssl/ssl-bundle.crt;
    ssl_certificate_key /home/ubuntu/newssl/xyz.key;
	server_name xyz.com;
	root /home/ubuntu/company-build/;         
	index index.html;
	location / 
	{
         try_files $uri @prerender;
	}
	location @prerender 
	{         
		#proxy_set_header X-Prerender-Token YOUR_TOKEN;          
		set $prerender 0;         
		if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") 
		{             
			set $prerender 1; 
		}         
		if ($args ~ "_escaped_fragment_") 
		{             
			set $prerender 1;
		}         
		if ($http_user_agent ~ "Prerender") 
		{             
		set $prerender 0;
		}         
		if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") 
		{
			set $prerender 0;
		}          
		#resolve using Google's DNS server to force DNS resolution and prevent caching of IPs         
		resolver 8.8.8.8;
		if ($prerender = 1)
		{              
			#setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing             
			set $prerender "pre.xyz.com";             
			rewrite .* /$scheme://$host$request_uri? break;             
			proxy_pass http://$prerender;         
		}         
		if ($prerender = 0)
		{             
			rewrite .* /index.html break;         
		}
	}
}
```
@thoop I am droping you an email as well, see if you can suggest something.
Thanks!

**Comment by vesper8** [comment]
@malkitsingh did you figure it out? would you mind sharing your solution please?
