### ISSUE TITLE
Adding adsense and other scripts it makes things to load unnecessary and wrong

### ISSUE THREAD

**Issue by freereikicourse** [prerender/prerender#448]
For example if I add adsense to the page:

```
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-8900380089861989",
    enable_page_level_ads: true
  });
</script>
```

The problem is that the `render` of the page will load all the scripts that adsenses "wants" and then they will be injected in the rendered html page.

This is a disaster because now I have worthless js requests:

 - https://adservice.google.co.uk/adsid/integrator.js?domain=localhost
 - https://adservice.google.com/adsid/integrator.js?domain=localhost

Notice that the domain is different and also domain is localhost...

I also get this weird request:

 - https://pagead2.googlesyndication.com/pub-config/r20160913/ca-pub-8900380089861989.js

**Comment by thoop** [comment]
Which URL are you accessing and how are you accessing it? Any more information you can provide here would be helpful so I can understand what the issue might be here.

Thanks!

**Comment by freereikicourse** [comment]
Hi! Is this url: https://www.freereikicourse.com/
