### ISSUE TITLE
res.setHeader not working

### ISSUE THREAD

**Issue by rogierslag** [prerender/prerender#449]
`res.sendHeader` in any plugin is no longer working, due to the way `firePluginEvent` is called from `server.js`. As a result, only `res.send` is available.

However I'd like to inject additional headers in the response to the client. How can we do this with the chrome setup?

(Note that official `httpHeaders` plugin is broken as well if the prerender specific headers are present)

**Comment by thoop** [comment]
Thanks for that! Just pushed the fix. We had to wrap that due to how we're using express now. Let me know if you see any issues with `5.0.2` with regards to that.
