### ISSUE TITLE
Dramatic drop in performance after upgrade to phantom-cluster

### ISSUE THREAD

**Issue by eleventigers** [prerender/prerender#45]
Been running pre-phantom-cluster version for a good month with an issue and decided to check out the new version after @dailymuse's merge. Performance dropped significantly:

![screenshot from 2014-01-22 13 44 37](https://f.cloud.github.com/assets/564920/1974240/bff23f76-836b-11e3-8143-cacc931a0c58.png)

Seeing a lot of 504 errors. Any ideas what's happening?

**Comment by eduardomb** [comment]
I had a similar issue. I was able to get rid of the **504** errors by **updating prerender** and **re-instaling node packages** with these commands:
```cd /path/to/prerender```
```git pull```
```rm -rf node_modules```
```npm install```
```node server.js```
