### ISSUE TITLE
Chrome connection closed..

### ISSUE THREAD

**Issue by alexprotoplanpro** [prerender/prerender#450]
Hello there is an error.

> 2017-11-21T12:54:26.835Z Starting Prerender
2017-11-21T12:54:26.836Z Starting Chrome
2017-11-21T12:54:26.840Z Prerender server accepting requests on port 3000
2017-11-21T12:54:26.861Z Chrome connection closed... restarting Chrome
2017-11-21T12:54:26.861Z Chrome died immediately after restart... stopping Prerender

**Comment by alexprotoplanpro** [comment]
add
    chromeFlags: [ '--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars' ]

Nice)

**Comment by paOol** [comment]
@alexprotoplanpro add that where?

in `server.js`?

**Comment by thoop** [comment]
I don't recommend using --no-sandbox. That could be a security risk.

**Comment by xianyuLuo** [comment]
@alexprotoplanpro I try this method, but be not allowed. my OS is Centos 7.2
2018-08-20T08:47:56.325Z Starting Prerender
2018-08-20T08:47:56.327Z Starting Chrome
2018-08-20T08:47:56.335Z Prerender server accepting requests on port 3000
2018-08-20T08:47:56.461Z Chrome connection closed... restarting Chrome
2018-08-20T08:47:56.461Z Chrome died immediately after restart... stopping Prerender

**Comment by thoop** [comment]
Does Chrome run on Centos 7.2? Which version of Chrome are you using?

**Comment by xianyuLuo** [comment]
@thoop  hi, Chrome version is Google Chrome 68.0.3440.106.
I try chromium-browser, but be not allowed. chromium-browser version is Chromium 67.0.3396.79 Fedora Project

**Comment by selfdem** [comment]
I fix it by launching prerender by no-root user。

**Comment by thoop** [comment]
Yes, make sure that Chrome is not running as the root user. Chrome 68 should work fine @xianyuLuo

**Comment by xianyuLuo** [comment]
thanks @thoop

**Comment by kruff** [comment]
I've add 

> chromeFlags: [ '--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars' ]

to server.js and everything works fine. Trying to start it with systemd

> [Unit]
> Description=Prerender
> After=network.target
> After=redis.service
> Requires=redis.service
> 
> [Service]
> ExecStart=/usr/bin/node /opt/prerender/server.js
> Restart=always
> RestartSec=10
> User=prerender
> Group=prerender
> Environment=NODE_ENV=production
> Environment=PATH=/usr/bin:/usr/local/bin PORT=3000
> WorkingDirectory=/opt/prerender
> 
> [Install]
> WantedBy=multi-user.target

and get an error 

> Starting Prerender
> Starting Chrome
>Prerender server accepting requests on port 3000
> Chrome connection closed... restarting Chrome
> Chrome died immediately after restart... stopping Prerender

Changing user to root instead of prerender gives the same. What I'm doing wrong? =(((

**Comment by acgissues** [comment]
>  Environment=PATH=/usr/bin:/usr/local/bin PORT=3000

@kruff Just went through this. Tried starting chrome headless directly from the server and it wasn't finding `mkdir` and other utilities. Remember to add `/bin` to your PATH.

**Comment by thoop** [comment]
I still wouldn't recommend using `--no-sandbox` since that could introduce security issues.
