### ISSUE TITLE
Facebook share link is not working

### ISSUE THREAD

**Issue by akkigaykar** [prerender/prerender#451]
I have added prerender as a Middleware at Nginx level.
for crawler it is working as per expected.
but when i am trying to share link over a facebook then dynamic meta tags are not getting tracked/rendered.

**Comment by thoop** [comment]
Can you send an email to support@prerender.io with the URL you are having issues with? We'll be happy to look into it!

Facebook doesn't like to wait longer than ~5 seconds for a response so you'll want to make sure your pages are cached before Facebook tries to access them.

**Comment by thoop** [comment]
@ducit1995 I just responded to your email so let's continue the conversion there. Thanks!
