### ISSUE TITLE
Redis cache not working at master branch

### ISSUE THREAD

**Issue by dzydzany** [prerender/prerender#452]
Hello,

I see that all caching methods are on hold. When could we expect it back?

**Comment by thoop** [comment]
What's the issue with the redis cache not working? We are working on getting our in-memory and s3 plugins added back but the redis cache was built by someone else. So, that redis cache plugin might just need to be upgraded to support our new plugin event methods.

**Comment by dzydzany** [comment]
I see. Thank you very much.
