### ISSUE TITLE
Prerender takes 20 secounds to return 200 status code

### ISSUE THREAD

**Issue by VladSuciu76** [prerender/prerender#453]
Cloned master branch of prerender on the server and it all works well except that it takes 20 seconds to return 200 status code. The website I am using for it loads fast, even on google page speed it gets 90/100 score. Why it takes 20 on prerender?

**Comment by thoop** [comment]
Our Prerender server counts the number of requests in flight and saves the page a short time after that number reaches zero.

You might want to try turning on the `logRequests` parameter and see if you see an outstanding network request that isn't finishing.

Feel free to share the website if you want me to take a look at it. Or you can email it to me at todd@prerender.io.
