### ISSUE TITLE
Prerender with chrome on Heroku

### ISSUE THREAD

**Issue by hadifarnoud** [prerender/prerender#454]
I found a buildpack for Heroku that has chrome. I tried to use multipack (using both Node and Chrome buildpack)

https://github.com/heroku/heroku-buildpack-google-chrome

I tried the buildpack above. this is my server.js

```js
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender();
var server = prerender({
    chromeLocation: '/usr/bin/google-chrome'
});
server.use(prerender.sendPrerenderHeader());
// server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
// server.use(prerender.inMemoryHtmlCache());
// server.use(prerender.s3HtmlCache());

// server.use(require('prerender-redis-cache'));
server.start();
```

the app keeps crashing and still says chrome not found

we are actually using Flynn.io but it uses Heroku buildpacks so anything that works on Heroku it works on Flynn too

**Comment by thoop** [comment]
You'll want to remove that first call to `var server = prerender();`. That won't cause any issues but it's not needed there in your code.

As for the buildpack, it says:

> You'll need to tell Selenium/chromedriver that the chrome binary is at /app/.apt/usr/bin/google-chrome instead.

So can you try:

```
var server = prerender({
    chromeLocation: '/app/.apt/usr/bin/google-chrome'
});
```
Does that work?

**Comment by hadifarnoud** [comment]
thanks that fixed the issue!

looks like the S3 and in memory cache is still a work in progress. would `server.use(require('prerender-redis-cache'));` still work given the chrome change?

**Comment by thoop** [comment]
Last time I checked it looked like the redis cache plugin had a pull request to get the method names upgraded for the new Prerender chrome change, but I'm not sure if that's gone through yet.

You should be able to pretty easily use the old s3 or in-memory plugins and modify them to work with our new Prerender engine until we get those moved over.

**Comment by hadifarnoud** [comment]
I just wait for official plugins. don't know how to change them to new one
