### ISSUE TITLE
Head tags that should be in the <head> appear in the <body>

### ISSUE THREAD

**Issue by jeffersonpark** [prerender/prerender#455]
We're using:
- Prerender node middleware  @ 2.7.4
- Prerender server @ 5.0.2

In using the previous versions of the server, the link, meta, etc tags were rendering in the head tag as normal when coming through prerendered.  In this latest version, while much snappier, has these tags rendering in the body for us.

This behavior appears when we run through our internal instance of the prerender server as well as through your official url: http://service.prerender.io/<user url\> So at least it's consistent there.

This is what part of the prerendered document looks like in chrome dev tools:
![meta-in-body](https://user-images.githubusercontent.com/2273220/33293634-b6262e80-d38a-11e7-8200-ac6c7719b88f.png)

As you can see, the tags appear in the body tag for some reason -- rendering the page through the browser normally does yield expected results with meta tags in the right place and such. There's no obvious errors in the console or the server logs that I can tell, so debugging has been a challenge.

I'm not sure if it's a specific issue with the server or my code, but perhaps people may have some insights to share here.

**Comment by thoop** [comment]
We've seen this before and it's due to the `<iframe>` there. Chrome (and other browsers) see an `<iframe>` and try to end the `<head>` and start the `<body>` before the `<iframe>`. Are you able to move that iframe down to the body?

**Comment by jeffersonpark** [comment]
Yep!
We were able to change that to use an image tag instead of an iframe and that solved our issues.  Thank you for the help!

**Comment by thoop** [comment]
Great! Happy to help.

**Comment by ngodichat** [comment]
Hi @thoop , I have the same issue here but I don't use any iframe tag.
Here is the screenshot:
![image](https://user-images.githubusercontent.com/11161907/52046325-082dca80-2579-11e9-9c61-0e38682bacc7.png)

Can you please tell me why all the tags in the head are moved into the body? And why is there a "html" plain text at the start of the page? Thank you!

**Comment by thoop** [comment]
@ngodichat this might be related to https://github.com/prerender/prerender/issues/563 where we just pushed a fix. Can you try upgrading to v5.5.1 of Prerender to see if that fixes the issue here?

**Comment by akaSybe** [comment]
@thoop I guess you can close it
