### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by srossross** [prerender/prerender#457]
The instructions in the readme and on https://prerender.io/documentation/test-it don't work like service.prerender.io

For example, the url `http://localhost:3000/https://www.google.ca/?gfe_rd=cr&dcr=0&ei=bTUfWqbnHMXM8gfz57PoCw` does not show the page correctly.

### logs:

```
2017-11-29T22:34:47.556Z invalid URL: logos/doodles/2017/gertrude-jekylls-174th-birthday-6002071852548096-s.png
2017-11-29T22:34:47.558Z got 400 in 2ms for logos/doodles/2017/gertrude-jekylls-174th-birthday-6002071852548096-s.png
2017-11-29T22:34:47.559Z getting logos/doodles/2017/gertrude-jekylls-174th-birthday-6002071852548096-l.png
2017-11-29T22:34:47.559Z invalid URL: logos/doodles/2017/gertrude-jekylls-174th-birthday-6002071852548096-l.png
2017-11-29T22:34:47.560Z got 400 in 1ms for logos/doodles/2017/gertrude-jekylls-174th-birthday-6002071852548096-l.png
2017-11-29T22:34:47.662Z getting images/nav_logo242.png
2017-11-29T22:34:47.662Z invalid URL: images/nav_logo242.png
2017-11-29T22:34:47.663Z got 400 in 1ms for images/nav_logo242.png
2017-11-29T22:34:47.740Z getting images/branding/product/ico/googleg_lodp.ico
2017-11-29T22:34:47.740Z invalid URL: images/branding/product/ico/googleg_lodp.ico
2017-11-29T22:34:47.740Z got 400 in 0ms for images/branding/product/ico/googleg_lodp.ico
```

**Comment by thoop** [comment]
Can you explain a little more what you mean by the instructions not working like service.prerender.io?

The logs you pasted there are your browser trying to load the relative links on the page from the `http://localhost:3000` domain but those relative URLs actually live on `https://www.google.ca/`. So that is the expected behavior because once you proxy your HTML through your middleware, all relative links will work correctly since the `localhost:3000` will no longer be in the URL.

**Comment by srossross** [comment]
> The logs you pasted there are your browser trying to load the relative links on the page from the http://localhost:3000 domain but those relative URLs actually live on https://www.google.ca/. So that is the expected behavior because once you proxy your HTML through your middleware, all relative links will work correctly since the localhost:3000 will no longer be in the URL.

OK, Sorry for the spam. I think I understand how prerender.io works now. Maybe google is serving different sites based on IP? My only followup would be to use `http://localhost:3000/https://www.httpbin.com/`   instead of `http://localhost:3000/https://www.google.com/` google.com has a redirect which immediatly redirects off of `localhost:3000` and once that page is behind `localhost:3000` the page does not look right.

> Can you explain a little more what you mean by the instructions not working like service.prerender.io?

I was seeing different results when I do `http://localhost:3000/https://google.ca/...` v.s. `service.prerender.io/https://google.ca/...` neither of witch looked like the actual site `https://google.ca/...`. 

<img width="916" alt="screen shot 2017-11-29 at 4 14 43 pm" src="https://user-images.githubusercontent.com/741611/33406186-8caa9c2a-d520-11e7-80f3-c1327a663689.png">

<img width="916" alt="screen shot 2017-11-29 at 4 14 51 pm" src="https://user-images.githubusercontent.com/741611/33406189-8fd0cc44-d520-11e7-99e2-c59856ee99b3.png">

**Comment by thoop** [comment]
Yeah Google checks your IP so in your case going to https://www.google.com is redirecting you to https://www.google.ca (assuming your in canada).

I think the different result you are seeing is Google showing an "old" Google page to our PhantomJS browser (currently the default browser used on service.prerender.io if you don't specify an API token) and the "new" Google page shown to a Chrome browser which is what our open source Prerender server uses by default.

So if we had your Prerender.io account switched to using Chrome and you specified your token, then the service.prerender.io link would use Chrome and it would look the same as you see locally.

It looks like everything is working as intended there, and once we switch all of our service.prerender.io users over to Chrome then you won't see any difference.
