### ISSUE TITLE
Allow forcing download of files

### ISSUE THREAD

**Issue by jeerbl** [prerender/prerender#459]
Hi!

It would be nice to be able to send the files generated (PDF or PNG for example) as a download so that it is not displayed in the browser but downloaded on the user computer.

Should I create a plugin or would this be a nice-to-have "native" feature?

Cheers
Jerome

**Comment by thoop** [comment]
Hmm, I'm not sure if that's on our radar for a native feature. If you are accessing the Prerender server like an API from your server, you should be able to retrieve the PDF from the Prerender server and just add a header to the response to force the download.

https://stackoverflow.com/questions/36936605/node-express-force-browser-to-download-file-with-custom-name

**Comment by jeerbl** [comment]
Ok thanks for your answer, better handle it myself then.

Cheers
Jerome
