### ISSUE TITLE
not an issue: news - prerender-redis-cache for prerender 5.0

### ISSUE THREAD

**Issue by simonjoom** [prerender/prerender#460]
I created a fork of prerender-redis-cache working with the last prerender

it's here:
https://github.com/simonjoom/prerender-redis-cache

**Comment by thoop** [comment]
Awesome, thanks for your work! Going to close this issue but anyone searching on our repo should be able to find it :)

Try to get it merged back into the upstream branch that you forked from if possible!

**Comment by simonjoom** [comment]
it wasn t a big work :)
