### ISSUE TITLE
Consider have new API endpoint for checking if URL is already cached since it is queued.

### ISSUE THREAD

**Issue by brickgale** [prerender/prerender#462]
Would be nice if there is a way to check if url is already cached or to control calling of `recache` and also to signal out to apps that it's now available to be shared through different mediums like facebook since it already has SEO tags (ogp for facebook).

**Comment by thoop** [comment]
Since caching can be handled by different plugins with different types of caches (in memory, s3, redis, etc), I don't think we'll want this to be a part of our prerender repo. Each cache would handle that differently.

**Comment by brickgale** [comment]
Hmm isn't this the point of this project to primarily address the issue on how SEO tags to be read by the crawlers? It would be a shame if this feature won't be included, especially for larger apps that will include dynamic pages to be prerendered.

**Comment by thoop** [comment]
Yes but this server is mainly meant to be the rendering server. You can include some basic caching functionality in this server to save pages to the cache but signaling a recache is better done at a higher level and in the Prerender server code.

For our hosted Prerender.io service, we have a recache API endpoint that runs separately from the prerendering server that will queue up recache requests and then request the HTML from a Prerender server, take that HTML and save it over the current item in the cache, and update database records.

We also do the same for our "cache freshness" functionality where any page older than X days is queued up to be recached. So having that functionality live elsewhere works better than if it were all bundled together with the Prerender server.

That being said, feel free to write your own plugin to check the URL in the `requestReceived` event for `/recache` or something and then handle the recache separately. That's entirely possible to accomplish through a custom plugin.
