### ISSUE TITLE
Cache using memcached

### ISSUE THREAD

**Issue by genz10** [prerender/prerender#463]
Hi,

I found that there's already in memory cached implementation, but what exactly I need is memcached implementation, so I decided to try implement memcached on prerender.

It's already running for a couple month, you can try to browse here :

https://id.ckerja.com/?_escaped_fragment_=

If the cache is not available or already expired, it will render and save to memcached, after that, try to hit refresh and it will load directly from memcached.

I don't know if there any corner case or bug at my implementation because I haven't seen it.

I'd be willing to submit PR if you guys allow me to.

**Comment by thoop** [comment]
Cool! We don't want to add any more caching functionality directly to our Prerender repository but feel free to post it on your own github. Prerender plugins can be loaded and used from any github repo. Post back here with a link to it when you upload it somewhere!
