### ISSUE TITLE
Sending of Custom Headers are not working anymore

### ISSUE THREAD

**Issue by carsten-neuendorf** [prerender/prerender#466]
This plugin is not working anymore:
https://github.com/prerender/prerender/blob/c63413ac2359144f16641874dc0a748c075515f1/lib/plugins/sendPrerenderHeader.js#L4

**Comment by thoop** [comment]
Is it just not sending the `'X-Prerender': '1'` header anymore for you? Do you have any other plugins that modify the headers? I'll test this out.

**Comment by carsten-neuendorf** [comment]
Any header value that I set over this method is not sending anymore.

**Comment by thoop** [comment]
It looks like this is a bug with chrome 63.

https://bugs.chromium.org/p/chromium/issues/detail?id=795336&q=setExtraHTTPHeaders&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

When testing an old version of Chrome (v61) or Chrome Canary (v65) on my mac, it's working correctly. Not sure if there's a workaround here.

**Comment by carsten-neuendorf** [comment]
**THX** @thoop for investigating this issue! 
It is also working with v62 again. 

I think this issue can close now.

**Comment by thoop** [comment]
I'll leave this open until v64 comes out and we'll see if this issue is fixed then.

**Comment by xsbchen** [comment]
v64 on Windows still didn't work.

**Comment by thoop** [comment]
I just tested this on v64 on OSX and it looks like it works for me.

@carsten-neuendorf can you try testing with v64 and see if `sendPrerenderHeader` is sending the `x-prerender: 1` header now?

**Comment by cjmling** [comment]
Not working in `HeadlessChrome/72.0.3626.96`

**Comment by thoop** [comment]
When I run a local Prerender server on port 1337 and visit:

```
http://localhost:1337/https://manytools.org/http-html-text/http-request-headers/
```
I see:

![image](https://user-images.githubusercontent.com/1259374/55122038-e6f1e200-50c2-11e9-9f7f-175bf5912186.png)


So this looks to be working as expected by sending the `X-Prerender: 1` header on the browser requests. Feel free to provide more information so we can look into this more but it looks to be working as expected.
