### ISSUE TITLE
Error: {"isTrusted":false}

### ISSUE THREAD

**Issue by mhluska** [prerender/prerender#468]
I see the following error show up pretty frequently in Sentry: https://sentry.io/share/issue/86b593b6e51b4824b74ee5a84032b7b5

The error is `{"isTrusted":false}` and the User Agent indicates the request is coming from Prerender:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/61.0.3163.59 Safari/537.36 Prerender (+https://github.com/prerender/prerender)
```

My frontend code is written with React.

I'm not really sure how to debug this error or if it can be ignored. Any idea why it happens?

**Comment by thoop** [comment]
Hmm, I haven't seen that error before. It could be anything on your page like an ad, third party code, or your code if it checks for certain "bots", or even just the fact that our browser never tries to authenticate as a user.

Are you seeing that cause any errors with page rendering? Are you able to tell what is spitting out that error?

**Comment by mhluska** [comment]
This seems to be related more to [error reporting in JS in general](https://blog.sentry.io/2016/05/17/what-is-script-error.html#the-fix-cors-attributes-and-headers). Going to close.
