### ISSUE TITLE
[Vue.js] Cannot read property 'user-agent' of undefined   

### ISSUE THREAD

**Issue by maurodollinger** [prerender/prerender#472]
Hi! 
I developed an app using Vue and I want to use Prerender service. 
I'm getting this error when trying to run application locally.

> Uncaught TypeError: Cannot read property 'user-agent' of undefined
>     at Function.prerender.shouldShowPrerenderedPage

I run npm install, and then I had to fix a dependency error, adding this to webpack.config

> node: {
>   fs: 'empty',
>   net: 'empty',
>   tls: 'empty'
>   } 

Also, I'm still having this warnings.
I don't know if they are related to the error, but I'm pasting it just in case

> WARNING in ./~/ajv/lib/compile/index.js
> 13:21-34 Critical dependency: the request of a dependency is an expression
> 
> WARNING in ./~/ajv/lib/async.js
> 96:20-33 Critical dependency: the request of a dependency is an expression
> 
> WARNING in ./~/ajv/lib/async.js
> 119:15-28 Critical dependency: the request of a dependency is an expression

**Comment by thoop** [comment]
Which version of Prerender are you using? How are you testing your page through the Prerender server?

From the first error you shared, it looks like you are trying to run prerender-node in your browser. If so, that should be run on the server side instead.

**Comment by maurodollinger** [comment]
Thanks for the quick reply. 
I'm using @2.7.4 . 
and running it on a node server, on localhost (npm run dev).

**Comment by thoop** [comment]
Yeah that sounds like you're using prerender-node. Here's the line that is returning that first error:
```
var userAgent = req.headers['user-agent']
```
And req.headers is what's undefined there, which shouldn't happen if you have this set up correctly with your node server. Can you show me where you are including the prerender-node middleware?

**Comment by maurodollinger** [comment]
Hi, I'm defining 
this:

> //Prerender
> Vue.use(require('prerender-node').set('prerenderToken', '--------------------'));

before creating my vue App, on main.js

I dont'know where else to put it.

**Comment by thoop** [comment]
That should be run on the server side. What type of server are you using to serve your index html file?

**Comment by thoop** [comment]
Were you able to get this running on your server?

**Comment by maurodollinger** [comment]
No. I wasn't able. I tried running it on a Windows Server and on an Apache Server, both without positive results. I'm not sure if Vue let me define prerender in that way:  `Vue.use(require('prerender-node')`

**Comment by thoop** [comment]
The prerender-node middleware is meant to be run on the server side, but you are trying to run it on the front end. If you are using Apache to serve your index.html file, you should try our Apache config: https://gist.github.com/thoop/8072354

We can Prerender Vue websites just fine, but the prerender-node middleware can not be run from within Vue. The middleware is what checks each request to see if the request is from a crawler in order to serve a prerendered page to crawlers instead of the javascript. That means the middleware code has to run on the server.

**Comment by maurodollinger** [comment]
Hi. Just to not leave this thread empty.. A partner of mine, communicated with you for this issue through email. He's working on this now. Thanks a lot for your help

**Comment by thoop** [comment]
Sure! No problem.
