### ISSUE TITLE
Question - Prerender.io and Angular 4 webpack

### ISSUE THREAD

**Issue by SMRockend** [prerender/prerender#475]
Do you have any prerender.io sample with Angular 4 webpack?

**Comment by thoop** [comment]
No but it should work just fine no matter which version of Angular you use. You'll just want to install the correct Prerender.io middleware from the readme depending on which server you are using.

**Comment by SMRockend** [comment]
Thanks mate. If someone can provide prerender.io and angular 2+ webpack sample here that would be great.

**Comment by thoop** [comment]
If you're using a webpack dev server locally, you should be able to modify the middleware to add the [prerender-node](https://github.com/prerender/prerender-node) middleware.
