### ISSUE TITLE
Prerender rails returns empty page

### ISSUE THREAD

**Issue by ravitej177** [prerender/prerender#478]
I have integrated the prerender.io in my react rails application however when I visit the url [http://codelabs.greycampus.com/php/installation_process?_escaped_fragment_=](http://codelabs.greycampus.com/php/installation_process?_escaped_fragment_=) it returns empty body

![screenshot from 2018-01-29 11-46-14](https://user-images.githubusercontent.com/12657841/35495986-12c0da06-04ea-11e8-8d8d-604c87c99cca.png)

I'm using rails 5.1 with react integrated in it. Please help me, if any further steps required for prerender working.

**Comment by thoop** [comment]
Happy to help here. Are you using your own Prerender server? Or are you using our hosted service? If you are using your own Prerender server, which version are you running?

**Comment by ravitej177** [comment]
@thoop  I have figured the issue on my side, I have not created the token in the prerender website, thats why its returning the empty page. Now, its resolved. Thanks.
