### ISSUE TITLE
Why always return 504?

### ISSUE THREAD

**Issue by xsbchen** [prerender/prerender#479]
```js
// server.js
const prerender = require('prerender');
const server = prerender();
server.start();
```

1. run `node server.js`
2. test with `curl http://localhost:3000/render?url=https://www.example.com/`
3. result:
```
< HTTP/1.1 504 Gateway Timeout
< Content-Type: text/html; charset=utf-8
< Content-Length: 1262
< ETag: W/"4ee-FFELfcnWHsSUqMa192lFVYpoep4"
< Vary: Accept-Encoding
< Date: Mon, 29 Jan 2018 11:27:17 GMT
```

**Comment by baterson** [comment]
You need to install chrome I guess. And set headers in a chrome headers.  
`
var server = prerender({
    chromeFlags: [ '--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars' ]
});
`

**Comment by jrockets** [comment]
Prerender is not working with Google Chrome 64. It is working with Chrome 63.

**Comment by csbenjamin** [comment]
I'm having the same issue. Using Google chrome 64 here. For now, as a workaround, I'm setting the following plugin:
```js
server.use({
	beforeSend: function(req, res, next) {
    	return res.send(200, req.prerender.content);
	}
})
```

**Comment by thoop** [comment]
Sorry for the delay here. It looks like Chrome 64 changed `params.loaderId` in the `requestWillBeSent` callback so we changed that to `params.requestId`. It should be working now with Prerender version 5.2.1.

Can someone give it a test and verify before I close this issue?

**Comment by csbenjamin** [comment]
@thoop It works now with Google Chrome 64.0.3282.119

**Comment by xsbchen** [comment]
@thoop It works now with Google Chrome 65.0.3312.0
thanks a lot.
