### ISSUE TITLE
How to debug page errors? (phantomjs)

### ISSUE THREAD

**Issue by thepry** [prerender/prerender#480]
Hi,

I have an angular application with http request intercepter. If request returns 404 - interceptor redirects to 404 page and adds 404 for a prerender-status-code.

The problem is that for some pages prerender returns 500 error, even all of the requests were 200 or 404 (for example item was not found in the api)

No one had 500. So it looks like chrome/phantom js (i'm trying both) has some error. Is it possible to get all the console output from chrome/phantomjs?

For phantom js version I added `console.log` in every place where `statusCode` is set and nowhere it was 500.

However there is this line of code, which perhaps is adding callback to phantomjs engine, and `req.prerender.statusCode` is `500` there:

```
    this._pluginEvent("beforeSend", [req, res], function() {
```

With chrome version I tried `LOG_REQUESTS=true` and only one with 404 is there, nothing with 500 error.

Does anyone have an idea what might be causing this problem and how to debug it?

**Comment by thoop** [comment]
I'd recommend testing Chrome over PhantomJS since Chrome is much more reliable. So you're saying Chrome will return a 500 too? Which plugins do you have enabled?

**Comment by thepry** [comment]
@thoop Yes, chrome returns 500 as well. I've tried the default - latest master.

**Comment by thoop** [comment]
Can you send over what your logs look like when you receive a 500? Is there a URL that this is reproducible on? Or does it happen randomly over time?
