### ISSUE TITLE
Many chrome zombie processes

### ISSUE THREAD

**Issue by Nyoroon** [prerender/prerender#484]
Prerender doesn't kill chrome processes when connection closes (`Chrome connection closed... restarting Chrome`).
![2018-02-02 16 42 41](https://user-images.githubusercontent.com/182203/35736180-2056a352-0838-11e8-8c96-c795ddd82d31.png)
Also is there any way to view chrome logs?

**Comment by thoop** [comment]
This looks similar to https://github.com/prerender/prerender/issues/483

Which version of Prerender, Chrome, and Node are you using? Are you using any custom plugins or code?

You can view Chrome logs by passing parameters to Chrome to set up logging by passing `chromeFlags` to the `spawn` function: https://github.com/prerender/prerender/blob/master/lib/browsers/chrome.js#L24

**Comment by Nyoroon** [comment]
Prerender 5.2.0
Chrome 63.0.3239.132
NodeJS v8.9.4

My server.js is very simple:
```js
const prerender = require('prerender');
const server = prerender();
server.use(prerender.removeScriptTags());
//server.use(prerender.whitelist());
server.use(prerender.blockResources());
server.start();
```

**Comment by thoop** [comment]
I wasn't able to reproduce this locally when testing. Are the URLs that you're rendering causing a code path where our javascript throws an error and leaves the tab open? Do you see any errors in your Prerender logs?

You should be seeing the Prerender server restart Chrome every 10 minutes if there are no requests in flight or every hour if there are always more than 1 request in flight. Are you seeing those restarts happen? The restarts should be killing Chrome with a `SIGINT` which should clean up all open processes for that browser.

**Comment by Nyoroon** [comment]
Forgot to mention that I run prerender with chrome in docker with SYS_ADMIN caps under non-privileged user.
Log:
```
app_1  | 2018-02-03T03:34:41.182Z Starting Chrome
app_1  | 2018-02-03T03:34:41.703Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T07:09:42.788Z getting
app_1  | 2018-02-03T07:09:42.791Z invalid URL:
app_1  | 2018-02-03T07:09:42.793Z Restarting Chrome
app_1  | 2018-02-03T07:09:42.809Z got 400 in 21ms for
app_1  | 2018-02-03T07:09:42.845Z Chrome connection closed... restarting Chrome
app_1  | 2018-02-03T07:09:42.845Z Starting Chrome
app_1  | 2018-02-03T07:09:43.357Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T08:56:18.798Z getting http://example.com/some/path
app_1  | 2018-02-03T08:56:19.495Z Restarting Chrome
app_1  | 2018-02-03T08:56:19.496Z got 307 in 698ms for http://example.com/some/path
app_1  | 2018-02-03T08:56:19.514Z Chrome connection closed... restarting Chrome
app_1  | 2018-02-03T08:56:19.514Z Starting Chrome
app_1  | 2018-02-03T08:56:20.024Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T09:00:27.415Z getting
app_1  | 2018-02-03T09:00:27.417Z invalid URL:
app_1  | 2018-02-03T09:00:27.421Z got 400 in 6ms for
app_1  | 2018-02-03T09:17:50.030Z getting http://example.com/some/path
app_1  | 2018-02-03T09:17:50.705Z Restarting Chrome
app_1  | 2018-02-03T09:17:50.706Z got 307 in 676ms for http://example.com/some/path
app_1  | 2018-02-03T09:17:50.723Z Chrome connection closed... restarting Chrome
app_1  | 2018-02-03T09:17:50.723Z Starting Chrome
app_1  | 2018-02-03T09:17:51.234Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T09:19:10.866Z getting http://example.com/some/path
app_1  | 2018-02-03T09:19:11.519Z got 307 in 653ms for http://example.com/some/path
app_1  | 2018-02-03T09:44:04.207Z getting http://example.com/some/path
app_1  | 2018-02-03T09:44:04.889Z Restarting Chrome
app_1  | 2018-02-03T09:44:04.892Z got 307 in 685ms for http://example.com/some/path
app_1  | 2018-02-03T09:44:04.910Z Chrome connection closed... restarting Chrome
app_1  | 2018-02-03T09:44:04.910Z Starting Chrome
app_1  | 2018-02-03T09:44:05.422Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T09:44:40.288Z getting http://example.com/some/path
app_1  | 2018-02-03T09:44:40.933Z got 307 in 645ms for http://example.com/some/path
app_1  | 2018-02-03T09:56:20.299Z getting http://example.com/some/path
app_1  | 2018-02-03T09:56:20.896Z Restarting Chrome
app_1  | 2018-02-03T09:56:20.898Z got 307 in 598ms for http://example.com/some/path
app_1  | 2018-02-03T09:56:20.921Z Chrome connection closed... restarting Chrome
app_1  | 2018-02-03T09:56:20.921Z Starting Chrome
app_1  | 2018-02-03T09:56:21.431Z Started Chrome: HeadlessChrome/63.0.3239.132
app_1  | 2018-02-03T09:59:28.771Z getting http://example.com/some/path
app_1  | 2018-02-03T09:59:29.450Z got 307 in 679ms for http://example.com/some/path
```

**Comment by thoop** [comment]
Does that docker container run Chrome with --no-sandbox or any other different configs? I've seen some docker projects have to modify the arguments to Chrome to get it working.

**Comment by Nyoroon** [comment]
Ran with `--no-sandbox`, but zombies are still here.
![2018-02-05 18 02 10](https://user-images.githubusercontent.com/182203/35811152-cb309f40-0a9e-11e8-9acf-c99a87c1d17f.png)

**Comment by thoop** [comment]
Sorry I should have been more clear. Usually --no-sandbox is what causes issues so I'm glad you didn't have that set previously. I wouldn't recommend using --no-sandbox.

It might also be helpful if you tried upgrading Chrome to v64 or even the current beta of v65 to see if that changes anything.

We don't see any of these hung processes on our machines and we max out our CPUs with rendering so I'll have to continue looking into this.

**Comment by Nyoroon** [comment]
Using simple init (https://github.com/krallin/tini) solved the problem. Thanks for help!

**Comment by thoop** [comment]
Interesting, can you explain a little more how you used simple init with Prerender? That way we could look into using that with our repo if needed.

**Comment by Nyoroon** [comment]
Just installed tini and changed `CMD ["/usr/local/bin/node", "server.js"]` to `CMD ["/usr/local/bin/tini", "--", "/usr/local/bin/node", "server.js"]` in Dockerfile. Also `--init` option from docker 1.13+ will work too.
