### ISSUE TITLE
Got a lot of 504 lately with valid content...

### ISSUE THREAD

**Issue by vIceBerg** [prerender/prerender#485]
Hi!

I use prerender with on the chrome branch.
Node 6.11.2
Chrome 64.0.3282.140

Prerender was working well until a couple of days. I pulled the latest version from the branch and I test my app locally.

I got 504 errors all the time, even if my page`s content is returned. You can see in the screenshot that the status in Postman is 504, but the size of the content is 54k.

The only "special" feature that I use is Firebase... but I doubt it's the reason why it does not work, because it worked well before.

I'm a bit loss and I don`t know where to look at....

Please help.

Thanks

![prerender](https://user-images.githubusercontent.com/2366606/35813401-8926d890-0a61-11e8-86ce-30918b0e7e62.PNG)

**Comment by vIceBerg** [comment]
After some debugging:

`server._send = function(req, res) {
	req.prerender.statusCode = parseInt(req.prerender.statusCode) || 504;
	[...]
`

the req.prerender.statusCode is undefined, even if I have content... I'll continue my investigation, but if you could gove me some hints on where to check that would be appreciated.

**Comment by thoop** [comment]
Can you use the latest version of the master branch? We merged the chrome branch into master and already pushed out a fix on master for this issue. Or, ideally, use npm to download our latest version of `prerender` which uses Chrome and has the fix in it.

**Comment by vIceBerg** [comment]
Hi!

It worked. Thanks... I'll look into switching to the npm package in the future.

VB

**Comment by thoop** [comment]
Great!
