### ISSUE TITLE
LocalStorage shared between requests

### ISSUE THREAD

**Issue by maciejmrozinski** [prerender/prerender#488]
Hi,

Versions:
Prerender: 5.2.2 (commit: b3aeaca5b3d660aae9eae7dfca39fbc45323d3ff)
Chrome: HeadlessChrome/64.0.3282.167
OS: Ubuntu 16.04

I observed weird behavior about localStorage. In my opinion it's not cleared between requests. I provide simplest script i can imagine to test it:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="test"></div>
<script type="application/javascript">

    var count = localStorage.getItem('ls_test_variable');
    if (count === null) {
        count = 0;
    }
    count++;
    localStorage.setItem('ls_test_variable', count.toString());

    document.getElementById('test').innerHTML = count;

</script>
</body>
</html>
```

Div content should always be `1` since localStorage shouldn't have `ls_test_variable` key, so value is set to `0` and incremented once. If You try to refresh (re-prerender) this page, the div content increments all the time by one. Is there any flag possible to use to "reset" localStorage or this is incorrect behavior at the start?

**Comment by thoop** [comment]
Thanks for sending this over. We use Chrome's `Target.createBrowserContext()` which should be like opening multiple different incognito tabs that don't overlap: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext

Ah, it looks like the Chrome team is aware of the bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=754576

Looks like we might need to put a workaround in place to clear local storage after page load until that is fixed.

**Comment by maciejmrozinski** [comment]
Thx for fast reply :)

**Comment by maciejmrozinski** [comment]
I created a MR #489 that seems to fix this issue.

**Comment by thoop** [comment]
Merged and fixed. Thanks!
