### ISSUE TITLE
Support an option to disable the gzip for the response

### ISSUE THREAD

**Issue by Alex1990** [prerender/prerender#500]
I use the redis to be a cache and need to store the response in string.

**Comment by thoop** [comment]
Are you using redis as a cache as a plugin on the Prerender server or do you mean you are using a redis server upstream from the Prerender server that is caching responses?

We don't compress the response until it's sent (and only if there is an accept-encoding: gzip header) so you should be able to use any Prerender plugin to store the response in a string in redis.

**Comment by Alex1990** [comment]
I use the redis as an express server middleware.

```js
const app = express();
app.get('/', redisCache.getter, proxyToPrerender, redisCache.setter);
```

Thank you for your hint. I will try modifying the `accept-encoding` header.
