### ISSUE TITLE
How to add basic auth for client requests?

### ISSUE THREAD

**Issue by dim-s** [prerender/prerender#502]
I know that basicAuth plugin can add basic auth for prerender server, but I need to pass a basic auth (login and password) to get page content when prerender makes requests. How can I pass a custom Authorization header via code?

P.S. I try to create a plugin for this, but it doesn't work!

```js
requestReceived: (req, res, next) => {
    req.prerender.headers = { authentication: 'Basic **********' };
    return next();
}
```

**Comment by dim-s** [comment]
I found a solution:

```js
server.use({
  tabCreated: (req, res, next) => {
    req.prerender.tab.Network.setExtraHTTPHeaders({
      headers: {
        Authorization: 'Basic *******'
      }
    }).then(() => {
      next();
    }).catch(() => {
      res.send(504);
    });
  }
});
```

**Comment by thoop** [comment]
Awesome, glad that worked! Feel free to let us know if you run into any other issues.

**Comment by VjeraTurk** [comment]
Does this still work?

I got this answer from Support:

You are correct, we do not bypass any authentication.
However, you can only implement it for visitors and disable it when the user agent is Prerender. Unfortunately, we don't have documentation regarding this procedure.


Irina O.
[support@prerender.io](mailto:support@prerender.io)
[Prerender.io](http://prerender.io/) | @prerender
