### ISSUE TITLE
How to speed up // parallelize prerender

### ISSUE THREAD

**Issue by laurentdebricon** [prerender/prerender#506]
Hello,
how do you manage to render a lot html  ?
Do people manage to do it with a gpu ?

Can someone share me his perf // running machine ? So far it's like i can only run two rendering at the same time on a intel i7 cpu. It takes 3 secondes each.

imagine I want to render 100 000 pages quickly ?

Best regards

**Comment by thoop** [comment]
The best thing to do is have multiple servers behind a load balancer so you can scale out horizontally. From our experience, having one big server doesn't work as well as having lots of smaller servers.

**Comment by thoop** [comment]
I'm going to close this but please feel free to reopen if you have any other questions about this.
