### ISSUE TITLE
 unable to set header: Access-Control-Allow-Methods, Access-Control-Allow-Origin,Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by NeethuVishnu** [prerender/prerender#507]
Hai prerender team,

I am getting the below issue after integrating prerender middleware in my sails js application , using my own prerender server and it is working fine with other applications. 
Local environment everything is working fine.

warning: unable to set header: Access-Control-Allow-Methods
warning: unable to set header: Access-Control-Allow-Origin
warning: unable to set header: Access-Control-Allow-Headers

GET requests are working but any of the POST request from my application is not working . 
Getting below error in browser console
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('appdomain') does not match the recipient window's origin ('prerender server domain').

Please reply asap, got stuck with issue

**Comment by thoop** [comment]
I'm going to close this issue since we haven't heard back but please feel free to reopen it if you are still running into issues here! Feel free to get in touch with us at support@prerender.io with your URL if this is an easily reproducible issue.
