### ISSUE TITLE
Callback after the server has started?

### ISSUE THREAD

**Issue by parris** [prerender/prerender#509]
Hello! So I have some plans to use the prerender server in a task runner. I'd like it to spin up and then I want to wait until the prerender server is ready before I make requests to it. I'm noticing that `.start()` doesn't return a promise or have any callbacks. Is there a way to wait until the server has started? Would you accept a PR for that?

**Comment by thoop** [comment]
Sorry for the delay!

So Prerender is a web server that takes requests and sends them to Chrome to render. Once the web server is started, it can receive a request and will wait for Chrome to start before sending it to be rendered. So it should be started and ready for requests as soon as it the web server starts listening.

On my machine, it looks like from starting Prerender, it takes 8 milliseconds for the web server to start accepting requests:

```
2018-05-11T14:13:56.301Z Starting Prerender
2018-05-11T14:13:56.303Z Starting Chrome
2018-05-11T14:13:56.309Z Prerender server accepting requests on port 3000
```

So the timing should work just fine if you are sending requests right away. Is there something else that getting `.start()` to return a promise would help with?

**Comment by parris** [comment]
I guess this is fine - thanks! :)
