### ISSUE TITLE
AngularJS not rendering anymore

### ISSUE THREAD

**Issue by shashankmds** [prerender/prerender#510]
@thoop 
we are using prerender.io for caching our angular website pages, but this is not working anymore.
It is not rendering pages, and removing the scripts tag even before that
https://metadesignsolutions.com is our website.

http://service.prerender.io/https://metadesignsolutions.com returns a blank page...

Can you please help ?

**Comment by shashankmds** [comment]
FYI... the page gets render if i test it through local prerender installation
http://localhost:3000/render?url=https://metadesignsolutions.com

**Comment by thoop** [comment]
Just responded to your email. Let's continue the conversation there!
