### ISSUE TITLE
prerender behind nginx doesn't work with prerender_rails [help needed]

### ISSUE THREAD

**Issue by marcek** [prerender/prerender#512]
Hi there,
I've tried to serve my rails application with prerender in two ways so far: nginx+passenger and nginx+unicorn and in both cases everything works as long as I run prerender locally via node. 

nginx: 1.12.2
passenger: 5.2.3
rails: 4.2.7.1
prerender_rails: 1.5.1
unicorn: 4.5.0
prerender: 5.4.2
chrome: HeadlessChrome/66.0.3359.181

Configuration bellow works. Prerender is simply run using `node server.js` on port 8000
```
# config/application.rb
config.middleware.use Rack::Prerender, prerender_service_url: 'http://127.0.0.1:8000'
```

I have no luck with using prerender with Rails when I put it behind nginx:
```
# config/application.rb
config.middleware.use Rack::Prerender, prerender_service_url: 'http://prerender.local'
```
```
# /opt/nginx/sites-enabled/prerender.conf
server {
  listen                          80;
  server_name                     prerender.local;

  location / {
    proxy_pass http://127.0.0.1:8000;

    proxy_redirect off;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```
Nginx+Unicorn output:
```
2018/05/18 13:27:51 [error] 13251#0: *224 upstream sent invalid chunked response while reading response header from upstream, client: 127.0.0.1, server: app.local, request: "GET /events/example?_escaped_fragment_ HTTP/1.1", upstream: "http://unix:/Users/username/app/shared/sockets/unicorn.sock:/events/example?_escaped_fragment_", host: "app.local"
```

Nginx+passenger output
```
*** Exception RuntimeError in Rack response body object (Response object may not contain both Content-Length and Transfer-Encoding) (process 13829, thread 0x007f7f5b151d00(Worker 1)):
```

It looks like the problem is within prerender_rails middleware because passing an URL directly to prerender with nginx works as well:
```
http://prerender.local/http://app.local/events/example
```

Can you help ?

**Comment by thoop** [comment]
This looks similar to this issue: https://github.com/prerender/prerender/issues/144

And we added this line to fix that issue: https://github.com/prerender/prerender/commit/dba349553a496cc212f6abbaf7354ea54b4c4d08

But it looks like that might not be working. Do you have that Transfer-Encoding header in your response from your server? Are you able to see that being returned from the prerender server if you do:
```
curl -v http://prerender.local/http://app.local/events/example
```

**Comment by marcek** [comment]
No, I don't get that header. Your fix works and gets rid of it

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to prerender.local (127.0.0.1) port 80 (#0)
> GET /http://app.local/events/example HTTP/1.1
> Host: prerender.local
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.12.2
< Date: Mon, 21 May 2018 08:45:08 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 49003
< Connection: keep-alive
< Status: 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< ETag: W/"737290fd785d38a9bf9d27f573aaf98f"
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Runtime: 0.006866
< X-Request-Id: 4d188231-0244-43d2-bf03-583599a4b0bd
< X-Powered-By: Phusion Passenger 5.2.3
< Vary: Accept-Encoding
```

Well, it almost works. First request complains about headers and returns 502 but page is rendered and cached:

```
// First request
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to app.local (127.0.0.1) port 80 (#0)
> GET /events/example?_escaped_fragment_ HTTP/1.1
> Host: app.local
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Content-Type: text/html; charset=UTF-8
< Content-Length: 54
< Connection: keep-alive
< Status: 502 Bad Gateway
< Date: Mon, 21 May 2018 08:49:03 +0100
< cache-control: no-cache, no-store, must-revalidate
< Server: nginx/1.12.2 + Phusion Passenger 5.2.3
<
* Connection #0 to host kk.local left intact
```

```
// Second request
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to app.local (127.0.0.1) port 80 (#0)
> GET /events/example?_escaped_fragment_ HTTP/1.1
> Host: app.local
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 49003
< Connection: keep-alive
< Status: 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< ETag: W/"4592a591ef368e11b47d8b90ea27544b"
< X-Runtime: 0.001884
< X-Request-Id: ce5a56ee-621e-4d53-a0f8-61c553682058
< Date: Mon, 21 May 2018 08:49:46 GMT
< X-Powered-By: Phusion Passenger 5.2.3
< Server: nginx/1.12.2 + Phusion Passenger 5.2.3

+ HTML
```

**Comment by thoop** [comment]
That fix was from back in 2014 and is already a part of the Prerender server. So is it working differently now that you are testing it again?

If you turn on the `logRequests` option by running `export LOG_REQUESTS=true` on the Prerender server, can you tell where that 502 is coming from?

**Comment by thoop** [comment]
Any idea why the `X-Runtime: 5.028436` is so much higher when requesting through rails vs curling the prerender server directly and seeing `X-Runtime: 0.003678` ? Is this a case where rails is blocking the thread on the request out to Prerender so Prerender is unable to render the page on the fly? And is that causing the error through nginx?

**Comment by konukhov** [comment]
Removing `transfer-encoding` header from the rack-response in `prerender_rails` somehow solved the same issue for me. I still don't get how this header gets there though.

https://github.com/konukhov/prerender_rails/commit/febf0e4bdb13eca28a290a39997581b2d418a263

**Comment by thoop** [comment]
Interesting... but the `transfer-encoding` header is not being returned from the Prerender server, right? Is the `prerender_rails` middleware somehow adding that header on its own?

**Comment by konukhov** [comment]
@thoop I thought the same thing but didn't have time to dig into it. It might be Rails itself who's adding the header. I'll look into it.

**Comment by thoop** [comment]
@konukhov were you able to figure out where that `transfer-encoding` header was being added? I want to make sure this is fixed if there's an issue!

**Comment by thoop** [comment]
I haven't heard back in a while so I'm going to close this issue since we haven't heard any other issues here. Feel free to let us know if this is still an issue and we'll reopen.

**Comment by oyamowiec** [comment]
I started to get this issue as well when using Nginx, rails and prerender.

**Comment by oyamowiec** [comment]
Exception RuntimeError in Rack response body object (Response object may not contain both Content-Length and Transfer-Encoding) (process 17686, thread 0x0000559b92a8e700(Worker 1)):
App 17686 output: 	from /home/hosting/.rvm/gems/ruby-2.5.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:210:in `process_body'
[ W 2020-03-31 08:49:31.5475 32118/Tb age/Cor/Con/InternalUtils.cpp:96 ]: [Client 2-53991] Sending 502 response: application did not send a complete response

**Comment by ehlertij** [comment]
This was an issue for us as well. I had to add:

```
    build_rack_response_from_prerender: (Proc.new do |response, prerender_response|
      response.headers.delete('transfer-encoding')
    end)
```

to get it to stop responding with 502 bad gateway.

**Comment by mewa** [comment]
@thoop This is still an issue (or a class of issues). More specifically, this is an issue with the rails middleware (essentially - acting as a proxy) not discarding hop-by-hop headers.
