### ISSUE TITLE
Error: unable to find Chrome install. Please specify with chromeLocation

### ISSUE THREAD

**Issue by nvrossett** [prerender/prerender#513]
Hello, somebody know how i fix this problem??
`unable to find Chrome install. Please specify with chromeLocation`

![image](https://user-images.githubusercontent.com/2110820/40261426-e4a0816a-5ad6-11e8-9bb4-195a16a70618.png)

I'm trying to run the prerender in a server CentOS 6 on MediaTemple

I installed chrome on the server but it still did not work

**Comment by thoop** [comment]
Hi there! It looks like Prerender just isn't able to find your executable in the places it looks by default.

You can pass your Chrome executable location to the Prerender server like this in your server.js: https://github.com/prerender/prerender#chromelocation

After passing that, it should all work correctly.

**Comment by MikinjMistry** [comment]
Hello Guys,
How to fix this issue by installing Chrom in EC2 ubuntu instance and what is the location of it ?

**Comment by josfaber** [comment]
I've solved this one on Debian 10 by installing Chromium and updating the server.js with the chromium location.

Install Chromium
```
sudo apt update
sudo apt install chromium
```

Determine Chromium location
```
which chromium
```

Update `server.js` to pass Chromium location trough the server options
```
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
  chromeLocation: '/usr/bin/chromium'
});

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();
```

**Comment by hovpetrosyan95** [comment]
In the windows pay attention to the slashes, instead of '\' use '/'
e.g. replace var server = prerender() with 
var server = prerender({
    chromeLocation: 'path-to-chrome.exe'
});
path-to-chrome.exe in my case is C:/Users/user/Downloads/chrome-win/chrome.exe (check where is your chrome.exe and set appropriate path)

Good Luck!!!
