### ISSUE TITLE
prevent Mixpanel events from prerender

### ISSUE THREAD

**Issue by nobalmohan** [prerender/prerender#516]
is there a way to avoid triggering mixpanel or any other analytics events when rendering the page via prerender?

**Comment by thoop** [comment]
Hi there. We should already be blocking any mixpanel events as seen here:

https://github.com/prerender/prerender/blob/master/lib/plugins/blockResources.js#L3

**Comment by nobalmohan** [comment]
We were still seeing some events. So we added a param in the URL and won't trigger Mixpanel if the param bot is true.

`rewrite .* /$scheme://$host$request_uri?bot=true break;`
