### ISSUE TITLE
encoded slash is decode by Prerender

### ISSUE THREAD

**Issue by sj82516** [prerender/prerender#518]
In my custom url contains slash /.  
But I have encodeURIComponent twice and "/" would turn to be "%252F".
I test my encoded URI such as "http://example.com/myslash%252F" and it works well in Chrome.  
However the prerender seems to decode the URL and get the wrong result.

**Comment by thoop** [comment]
You say you ran encodeURIComponent twice, how do your users normally access that URL? Like "http://example.com/myslash/" ?

**Comment by sj82516** [comment]
Sorry I make misleading example.  
My real example is like "http://example.com/myslash/somewordshere" => "http://example.com/myslash%252Fsomewordshere".  
The slash is inside the words not the end of url.

**Comment by thoop** [comment]
Sorry for the delay here! Can you send us a real example of your URL so we can make changes, test, and verify that it works as expected? My email is todd@prerender.io if you want to keep your website private.

**Comment by thoop** [comment]
Haven't heard back so I'll close this issue but please send me a real example of your URL so that we can test and make corrections as needed!
