### ISSUE TITLE
Unknown provider: $cookieStoreProvider <- $cookieStore <- sessionService <- authInterceptor <- $http <- $templateRequest <- $route

### ISSUE THREAD

**Issue by dharveshmydeen** [prerender/prerender#526]
HI ,

Just now I have started working on it.I have installed all the modules which you have mentioned in Redme Docs.But Started of the project It show this run Time Error at my browser.

**Comment by thoop** [comment]
Hi there, can you send an email to us with more info or a URL we can test? I don't think that has anything to do with Prerender.io. support@prerender.io
