### ISSUE TITLE
Default host running on IPV6

### ISSUE THREAD

**Issue by murilo-campaner** [prerender/prerender#528]
Hello everyone,

I started my prerender server cloning the example repository with the following code:

````
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender();

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();
````

But by default prerender always listen on IPV6, not IPV4. It works on localhost, but when I upload the code do my server in amazon, I got 502 error on nginx, cause I'm using loadbalancers that redirect my requests to IPV4.

Can I set the host to 0.0.0.0 on app.listen() of the following file for get IPV4 listening? 
https://github.com/prerender/prerender/blob/master/lib/index.js#L13

Thank you

**Comment by thoop** [comment]
Were you able to figure this one out?

**Comment by murilo-campaner** [comment]
@thoop Yes, I updated the code of index.js inside lib folder setting:
`app.listen(port, '0.0.0.0', () => util.log(`Prerender server accepting requests on port ${port}`))`
on line 26. :)

**Comment by thoop** [comment]
Great, thanks for letting us know!
