### ISSUE TITLE
Unknown errror

### ISSUE THREAD

**Issue by ethereal-sandeep** [prerender/prerender#530]
I am getting consistent issue as mentioned below.
```

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Cannot communicate with PhantomJS process: Unknown reason
    at Phantom._afterExit (/home/ec2-user/prerender-phantomjs/prerender/node_modules/phridge/lib/Phantom.js:348:17)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)

```

Kindly help in upstanding this

**Comment by thoop** [comment]
It looks like that's down in the phridge library so I assume that you've lost the connection to your PhantomJS instance somehow. I'd suggest that you upgrade to use our Chrome rendering engine. It performs much better than the old PhantomJS engine.

**Comment by ethereal-sandeep** [comment]
@thoop , Hey thoop, thanks for the clarification but do we have redis cache feature in Chrome rendering engine.

**Comment by thoop** [comment]
Yes you can use this redis plugin for Prerender: https://github.com/jonathanbennett/prerender-redis-cache

**Comment by ethereal-sandeep** [comment]
Hey @thoop, thanks i will check it out.
