### ISSUE TITLE
renderType=jpeg/png/pdf corrupting font choice

### ISSUE THREAD

**Issue by 9607835** [prerender/prerender#538]
The jpeg render is almost perfect except all the text like "thing" will become "γϒ<<<γ<" (approximately, seems to be the same number of characters).
All desktop browsers correctly show the page, it is only headless chrome on centos through prerender that I am having a problem with.  (note: I have never used desktop chrome on centos, so it could be a host issue)

HeadlessChrome/69.0.3497.100
prerender git commit: 2e909d44e9bbb72e1d414d4bfc3d337ef3b01d3b

$ uname -s -r -v -m -o
Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

Thanks for any help.

**Comment by 9607835** [comment]
bug report reported upstream to google's chromium browser:
  https://bugs.chromium.org/p/chromium/issues/detail?id=888069

**Comment by 9607835** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=888069
closed

**Comment by thoop** [comment]
Sorry for the delay here! Looks like this was just a centos issue?

**Comment by 9607835** [comment]
> Sorry for the delay here! Looks like this was just a centos issue?

Yes, not certain what exactly caused it, but a fresh centos install got chrome working again.

**Comment by thoop** [comment]
Interesting. Thanks for the update.
