### ISSUE TITLE
run prerender on windows iis with iisnode module

### ISSUE THREAD

**Issue by torabi7** [prerender/prerender#540]
hi,
i am runing this script on windows server 2012 with iis v.8.5 and chrome v.69 , for this goal i needed to install iisnode module and its runing good for other node.js applications .
but when i install prerender and go to the url :
http://localhost:3000/render?url=https://www.ejarex.com/
i got the error below in log file :
 Starting Prerender
 Starting Chrome
 Prerender server accepting requests on port \\.\pipe\19a6f5d8-52d9-4aed-8147-10e15b64a15f
 getting https://www.ejarex.com/
 Chrome connection closed... restarting Chrome
 Chrome died immediately after restart... stopping Prerender

can anybody help?

**Comment by thoop** [comment]
Sorry for the delay here! Can you run this on the command line:
```
echo $PORT
```
I suspect `PORT` is set to a non-integer value.

**Comment by torabi7** [comment]
thanks @thoop  ,
i did it , now i can render pages ,
the problem is i need to set iis as my middleware  so when a request comes from robots , forward it to localhost:3000 where my prerender server is lunched.
my application is angular js ,  do you have any setting example for iis to do that?

**Comment by torabi7** [comment]
thanks @thoop 
its set and done fine.
i tested my page with _escaped_fragment_= query string and its ok , there is no script in page source.
now the problem is , when i am fetching my page as google in webmaster, still dont render page, any idea?

**Comment by thoop** [comment]
That sounds like googlebot is not being checked by your middleware. Can you check your middleware and confirm that googlebot is being checked? You can find more information on that here: https://prerender.io/documentation/best-practices

Feel free to reopen or create a new issue if you are still running into problems. Happy to help more if needed.
