### ISSUE TITLE
how to verify extraHttpHeaders and Cookies set using plugins

### ISSUE THREAD

**Issue by sarasgh** [prerender/prerender#542]
how to verify the headers and cookies set from plugins using "req.prerender.tab.Network" object functions such as setExtraHttpHeaders & SetCookies?

I am not able to console.log the headers using "req.prerender.tab.prerender.headers", giving me undefined message. Also how do i console.log the cookies set? didn't not succeed trying to inspect/log using "req.prerender.tab.Network.getCookies".

Any help on how to print and verify these headers & cookies would be much appreciated. Thanks!

**Comment by thoop** [comment]
The headers are sent on the network request so you might have to hook into Chrome's `Network.requestWillBeSent` function like:

```
req.prerender.tab.Network.requestWillBeSent((params) => {
    console.log('headers:', params.request.headers)
});
```

As for the cookies, I would assume those would be sent on the network request as a header too, but I'm not seeing any sent. So I think the cookies should be getting cleared every time since we open a new "incognito" context for each browser tab. I know we had a bug with Chrome in the past here so I could be wrong.

**Comment by sarasgh** [comment]
Thanks, i am able to verify the headers using this function "Network.requestWillBeSent" as suggested but not seeing any cookies being sent as u mentioned.. how do we then send/pass cookies in the prerender request to chrome browser tab? Thought, setting "cookiesEnabled: true" flag should allow SetCookie on the prerender request? Any help with this cookie pass through in the prerender request to chrome browser tab is much appreciated. Thanks!

**Comment by thoop** [comment]
We should be clearing cookies on every request. If you are wanting to pass cookies through from a request to the Prerender server, you will need to write a plugin that takes the cookie off of the incoming request and then uses Chrome's API to set that cookie header on the Prerender request before the page is loaded.

**Comment by sarasgh** [comment]
that's exactly what i am trying to do..take the cookie off from incoming request and set the cookie on the prerender request using "req.prerender.tab.Network.setCookie" function and trying to validate whether its being sent correctly in the prerender request to load the page in chrome browser tab.. but i am not seeing the cookie being sent as a header in the network request.. am i missing something here?!

**Comment by thoop** [comment]
Can you share the code that you are using to take the cookie off the incoming request and set it on Chrome? I'll be happy to take a look at what you've got.

**Comment by sarasgh** [comment]
actually setCookie function works and sets the cookie header in the prerender request which i can verify by inspecting the request headers from inside the page which is prerendered...so i think, its just the Network.requestWillBeSent function which is not showing the cookies sent as part of the headers.. not sure why?

**Comment by thoop** [comment]
Sorry for the delay here! Interesting...must be a Chrome thing? We don't mess with that at all.

Going to close this issue if it's working. Feel free to reopen if needed!
