### ISSUE TITLE
add support for different view ports

### ISSUE THREAD

**Issue by dfreudenberger** [prerender/prerender#544]
Hi there,

our website renders different html based on the browsers view port. Are you interested in a pull request to support different viewport sizes? 

Do you know if ```req.prerender.tab.Page.setDeviceMetricsOverride``` would be the correct way to go or is there a better way to resize the viewport on a request base?

Thanks,
Daniel

**Comment by thoop** [comment]
We already set the viewport size based on the `tab.prerender.width` and `tab.prerender.height` as seen [here](https://github.com/prerender/prerender/blob/master/lib/browsers/chrome.js#L430).

So you could set that up with a simple plugin like the following. This checks incoming request headers for the width to use and you could set that width based on any criteria that you choose.

```
module.exports = {
	requestReceived: function(req, res, next) {

		if (req.headers && req.headers['x-viewport-width'] && req.headers['x-viewport-height']) {

			var newWidth = parseInt(req.headers['x-viewport-width']);
			var newHeight = parseInt(req.headers['x-viewport-height']);

			if (!isNaN(newWidth) && !isNaN(newHeight) && newWidth > 0 && newHeight > 0) {

				req.prerender.width = newWidth;
				req.prerender.height = newHeight;
			}

		}

		next();
	}
}
```

And then you would want to include that plugin in the server.js file, similar to the other plugins.

**Comment by dfreudenberger** [comment]
that's great, thank you!
