### ISSUE TITLE
Headless chrome hangs on iframe with X-Frame-Options: SAMEORIGIN

### ISSUE THREAD

**Issue by iliakan** [prerender/prerender#546]
I tried to prerender a page with:
```
<iframe src="https://twitter.com"></iframe>
```

Chrome (and thus prerender) hangs.

But if I remove "--headless" from options in `chrome.js`, then it renders fine.

**Comment by thoop** [comment]
Which version of Chrome are you using? That seems like a bug in Headless Chrome and not in Prerender.

**Comment by iliakan** [comment]
The one prerender downloads by default.

**Comment by iliakan** [comment]
I tried current stable and canary.

**Comment by thoop** [comment]
Sorry for the delay here! That sounds like a bug in Headless mode of Chrome. I don't think we can do anything to fix that from the Prerender side of things.
