### ISSUE TITLE
problem with some agents

### ISSUE THREAD

**Issue by torabi7** [prerender/prerender#552]
hi 
i am using bellow config in iis to prerender my site :
`<rule name="Prerender" stopProcessing="true">
                    <match url="^(?!.*?(\.js|\.css|\.xml|\.less|\.png|\.jpg|\.jpeg|\.gif|\.pdf|\.doc|\.txt|\.ico|\.rss|\.zip|\.mp3|\.rar|\.exe|\.wmv|\.doc|\.avi|\.ppt|\.mpg|\.mpeg|\.tif|\.wav|\.mov|\.psd|\.ai|\.xls|\.mp4|\.m4a|\.swf|\.dat|\.dmg|\.iso|\.flv|\.m4v|\.torrent))(.*)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAny">
					 <add input="{HTTP_USER_AGENT}" pattern="baiduspider|googlebot|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora\ link\ preview|showyoubot|outbrain|pinterest|TelegramBot|telegrambot|TelegramBot (like TwitterBot)|redditbot|Applebot|WhatsApp|flipboard|tumblr|bitlybot|SkypeUriPreview|nuzzel|slackbot|vkShare|W3C_Validator" />
                        <add input="{QUERY_STRING}" pattern="(.*)_escaped_fragment_(.*)" ignoreCase="false" />              
                     </conditions>
                    <action type="Rewrite" url="myserverip/https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" />
                </rule>`

the problem is it does not work with "seositecheckup" and "telegram" robots , any idea?

**Comment by thoop** [comment]
Hi there,

Telegram should work since `TelegramBot` is being checked. Can you try making that a case insensitive check and adding that other user agent to your list? 

You would want to change this:
```
<add input="{HTTP_USER_AGENT}" pattern="baiduspider|googlebot|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora\ link\ preview|showyoubot|outbrain|pinterest|TelegramBot|telegrambot|TelegramBot (like TwitterBot)|redditbot|Applebot|WhatsApp|flipboard|tumblr|bitlybot|SkypeUriPreview|nuzzel|slackbot|vkShare|W3C_Validator" />
```

to this:
```
<add input="{HTTP_USER_AGENT}" pattern="baiduspider|googlebot|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora\ link\ preview|showyoubot|outbrain|pinterest|TelegramBot|telegrambot|TelegramBot (like TwitterBot)|redditbot|Applebot|WhatsApp|flipboard|tumblr|bitlybot|SkypeUriPreview|nuzzel|slackbot|vkShare|W3C_Validator|seositecheckup" ignoreCase="false" />
```
That should fix the issue. Feel free to reopen if that doesn't fix it!
