### ISSUE TITLE
prerender reply no data

### ISSUE THREAD

**Issue by ganchaoyang** [prerender/prerender#554]
i just run an prerender in my local,but it returns an empty page.but i tried to access https://service.prerender.io/my-url, this way returns an page contains all data.And my actual url is https://itweknow.cn

**Comment by thoop** [comment]
Can you show what you are seeing on your Prerender.io server console when you try to render that URL locally?

**Comment by ganchaoyang** [comment]
```
2018-11-20T03:24:19.996Z getting https://itweknow.cn/
2018-11-20T03:24:23.164Z got 200 in 3168ms for https://itweknow.cn/
2018-11-20T03:24:23.220Z getting https://static/editor.md/css/editormd.preview.css
2018-11-20T03:24:43.308Z page timed out https://static/editor.md/css/editormd.preview.css
2018-11-20T03:24:43.316Z got 504 in 20096ms for https://static/editor.md/css/editormd.preview.css
2018-11-20T03:24:43.416Z getting favicon.ico
2018-11-20T03:24:43.417Z invalid URL: favicon.ico
2018-11-20T03:24:43.417Z got 400 in 1ms for favicon.ico
```
This is the logs show on my prerender.io server, i tried to set the waitAfterLastRequest longer, and sometimes the result contains data,but sometimes not.

**Comment by thoop** [comment]
```
2018-11-20T03:24:23.164Z got 200 in 3168ms for https://itweknow.cn/
```
From that, it looks like your page is being returned correctly. It sounds like you might be having a timing issue where the Prerender server is saving the page too early. We've seen this happen sometimes when the main javascript file is a could MB in size. You might want to look into using our `window.prerenderReady` flag to more accurately tell the Prerender server when the page is finished loading. https://prerender.io/documentation/best-practices

**Comment by ganchaoyang** [comment]
It's a vue.js project.And in fact, the window.prerenderReady has been set.
```
router.beforeEach((to, from, next) => {
  window.prerenderReady = false
  next()
})

router.afterEach((to, from) => {
  window.prerenderReady = true
})
```
Is it a wrong way?

**Comment by thoop** [comment]
Ideally you would want window.prerenderReady to be set to false before the javascript is loaded like:
```
<script>
window.prerenderReady = false;
</script>
```
That way, you know it is being set to false right away. If you are setting it to false there in your javascript, that could be one of the final things to run so it might not be set to false yet when we check.

**Comment by thoop** [comment]
Hmm, if you set `window.prerenderReady` like I showed in my comment, prerenderReady should at least show as false. If you load your page in your Chrome browser, open the dev tools and type `window.prerenderReady` into the console, then press Enter, does it show "false"?

**Comment by ganchaoyang** [comment]
I'm set the window.prerenderReady at the wrong position.And now, i have solved this problem.Very thanks.
