### ISSUE TITLE
what if i wanted to share new meta tags for each items form the same url 

### ISSUE THREAD

**Issue by juniordeveloperforlife** [prerender/prerender#558]
your defintion: ->The Prerender.io middleware that you install on your server will check each request to see if it's a request from a crawler. If it is a request from a crawler, the middleware will send a request to Prerender.io for the static HTML of that page. If not, the request will continue on to your normal server routes. The crawler never knows that you are using Prerender.io since the response always goes through your server.

my requirements:
i need to send dynamic meta tags for each items on single page
so first time if i share meta tags for first item form page url say 
http://localhost:3000/#!/framePreview?foo=5a9160da26d5714860be8841&imageType=digital
 and if now i share second items then it will share only last time shared meta tags because that have  been cached because url is same  

but what if i wanted to share new meta tags for each items form the same url 

thanks

**Comment by thoop** [comment]
If you change the meta tags when the Prerender server renders the page the next time, the meta tags will be saved at the time of the rendering. I would highly recommend that you use different URLs if you are wanting to serve different content though. Lots of services cache the HTML returned so they might not always make a request to a URL each time. Separate URLs would fix that issue.
