### ISSUE TITLE
blockResources plugin still does not seem to work

### ISSUE THREAD

**Issue by arrilot** [prerender/prerender#559]
Related #473 

Versions:
Prerender: 5.4.4 (from package-json.lock) - Latest ATM
chrome-remote-interface: 0.25.7 (from package-json.lock)
Started Chrome: HeadlessChrome/69.0.3497.100 (from log)

server.js

```
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
	logRequests: true
});

server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
//server.use(prerender.blockResources());

server.start();
```

After `server.use(prerender.blockResources());` is uncommented I expect to see the following changes in log:
1. No more requests like this 
2018-12-04T11:29:52.210Z - 8 https://<my domin>/assets/build/img/logo.png (same with woff and other blocked patterns), but they still there
2. got 200 in **2159ms** for https://<my domain>/catalogue/ to be lower than before, but it's the same.
So nothing is blocked i suppose.

If I debug in `blockResources.js` changing

```
if (shouldBlock) {
	interceptOptions.errorReason = 'Aborted';
}
```

to

```
if (shouldBlock) {
     console.log('aborting ' + request.url);
     interceptOptions.errorReason = 'Aborted';
} else {
    console.log('not aborting ' + request.url);
}
```

the output is just fine

```
not aborting https://<my domain>/assets/jquery/jquery.min.js
not aborting https://<my domain>/cache/js/s1/main/kernel_main/kernel_main.js?1543922242288581
aborting https://<my domain>/assets/build/img/logo.png
aborting https://<my domain>/upload/iblock/af0/electro.png
```
The problem lays somewhere deeper

Rolling plugin back to `setBlockedURLs` does not help aswell

**Comment by krailler** [comment]
+1 blockResources does not work.

**Comment by thoop** [comment]
Chrome still makes the request in their lifecycle, we just block the requests right way by setting them as `Aborted`. So that's why you still see them in the logs even when they are being blocked.

So you will see in the timestamp that the request is actually being aborted:
with blockResources disabled you can see this image took 408ms to download:
```
2019-01-16T05:50:04.587Z + 14 https://prerender.io/img/vuejs.png
2019-01-16T05:50:04.995Z - 1 https://prerender.io/img/vuejs.png
```
with blockResources enabled you can see this image request took 12ms due to being aborted:
```
2019-01-16T05:47:24.070Z + 10 https://prerender.io/img/vuejs.png
2019-01-16T05:47:24.082Z - 15 https://prerender.io/img/vuejs.png
```
So it looks to be working as expected when I test locally.

**Comment by arrilot** [comment]
Looks like I get the same time because images are already cached/banned in chrome.

Thanks for clarification.
