### ISSUE TITLE
How to use express middleware with prerender?

### ISSUE THREAD

**Issue by akaSybe** [prerender/prerender#567]
I want to add healthcheck express middleware to server.

Is there a way to achieve it?

**Comment by akaSybe** [comment]
I found a workaround. It could be implemented as plugin, but I don't think it is a right way.

**Comment by thoop** [comment]
Sorry for the delay! A plugin is a great way to implement a health check. You might do something like:
```
module.exports = {
  requestReceived: (req, res, next) => {
    if (req.prerender.url == '/healthcheck') {
      //do health check stuff
    } else {
      next();
    }
  }
}
```
Feel free to reopen if you have any questions about that.
