### ISSUE TITLE
Prerendering doesn't work with the domain name

### ISSUE THREAD

**Issue by ayushkhanduri** [prerender/prerender#568]
I have setup prerender on my server, it works well when I test using

the ports
curl localhost:3000/localhost:5000
or 
curl localhost:3000/https://domainNameOfSite.com

but have issues when providing my domain name using 

curl domainNameOfSite.com/?_escaped_fragment_=

there is request timeout issue which gives me back blank html

<html><head></head><body></body></html>

i have just configured my server using 
server.use(require('prerender-node').set('prerenderServiceUrl','http://localhost:3000'));
///all the routes

**Comment by ayushkhanduri** [comment]
this actually wasn't an issue

i was doing this 

server.use(require('prerender-node').set('prerenderToken','').set('protocol','https').set('host','https://domain.com').set('prerenderServiceUrl','http://localhost:3000'));

i needed to set the domain name from set('host','https://domain.com') to set('host','domain.com') as i was already providing the protocol.

**Comment by thoop** [comment]
Ah, ok great! Glad you figured it out and sorry for the delay here!
