### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

### ISSUE THREAD

**Issue by 4456465465-44554** [prerender/prerender#571]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|log-welcome  | Error: Something took too long to do.
0|log-welcome  |     at timeout.client.setTimeout (/root/sbot/node_modules/discord.js/src/client/ClientManager.js:40:57)
0|log-welcome  |     at Timeout.setTimeout [as _onTimeout] (/root/sbot/node_modules/discord.js/src/client/Client.js:433:7)
0|log-welcome  |     at ontimeout (timers.js:498:11)
0|log-welcome  |     at tryOnTimeout (timers.js:323:5)
0|log-welcome  |     at Timer.listOnTimeout (timers.js:290:5)

**Comment by thoop** [comment]
Hi there! I'm not seeing anything related to Prerender in that output. Going to close this due to that but feel free to reopen and provide more information if necessary.
