### ISSUE TITLE
Specify chrome size

### ISSUE THREAD

**Issue by psabharwal123** [prerender/prerender#572]
How do i specify the window size that should be used by chrome headless?

**Comment by Nyoroon** [comment]
You can specify it with `--window-size` chrome option.
For example:
```js
const prerender = require('prerender');
const server = prerender({
    chromeFlags: ['--headless', '--disable-gpu', '--remote-debugging-port=9222',
	    '--hide-scrollbars', '--window-size=1920,1080']
});
```

**Comment by psabharwal123** [comment]
Thanks! The flags above, are they the reccomended ones to pass along with window-size?

**Comment by Nyoroon** [comment]
They are defaults:
https://github.com/prerender/prerender/blob/master/lib/browsers/chrome.js#L24

**Comment by thoop** [comment]
You can also pass in a different screen size on every request by setting `req.prerender.width` and `req.prerender.height` during the `requestReceived` lifecycle event.

Here's an example of what a plugin might look like to set the width and height based on a header you can pass in:
```
module.exports = {
  requestReceived: function(req, res, next) {

    if (req.headers && req.headers['x-prerender-viewport-width'] && req.headers['x-prerender-viewport-height']) {

      var newWidth = parseInt(req.headers['x-prerender-viewport-width']);
      var newHeight = parseInt(req.headers['x-prerender-viewport-height']);

      if (!isNaN(newWidth) && !isNaN(newHeight) && newWidth > 0 && newHeight > 0) {

        req.prerender.width = newWidth;
        req.prerender.height = newHeight;
      }

    }

    next();
  }
}
```

**Comment by psabharwal123** [comment]
Thanks!
