### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by akaSybe** [prerender/prerender#584]
Thank you for awesome tool.

I want to participate in development of this tool. Can I add Prettier to this project to have code formatting standard across the project? I think it will help in further development of prerender.

Prettier is a code formatting tool: https://prettier.io/

**Comment by thoop** [comment]
I wouldn't mind something like that but what's the difference between Prettier and a normal linting tool?

**Comment by akaSybe** [comment]
Prettier isn't linting tool, it's a formatting tool.
ESLint is a linting tool, they could work well side by side.

**Comment by akaSybe** [comment]
Actually, it will be great to add them both

**Comment by thoop** [comment]
Prettier looks interesting but we don't have very strict code formatting standards and adding Prettier would mainly just be for forcing things like semicolons, tabs, tab width, etc. I'm not too worried about that so I don't think we'll add Prettier yet but if we get lots of pull requests in the future with bad formatting I might revisit Prettier. Thanks though!
