### ISSUE TITLE
Rendering for mobile devices

### ISSUE THREAD

**Issue by captainjackrana** [prerender/prerender#587]
I have an Angular app on a Node.js server that is using a self-hosted Prerender service to perform the rendering on the backend server using a middleware, similar to [prerender-node](https://www.npmjs.com/package/prerender-node).

Now, the Angular app has different layout and content based on whether the device is mobile or desktop. However, Prerender always renders the page like a desktop device would, due to the headless chrome mechanism.

Is there any way in which I can tell the Prerender service to run a headless chrome for a mobile device? For eg, selenium allows you to do that by defining a device name property in a headless chrome instance.

**Comment by dberney** [comment]
I would like to know this too

**Comment by captainjackrana** [comment]
For now, I've been able to partially solve this using the `width` & `height` parameters in the prerender documentation. 
Basically simulate a mobile device using width & height values as `375` and `667`

**Comment by thoop** [comment]
Sorry for the delay here! You would want to create a plugin to detect the device type and render the width/height differently. We've done something similar on our hosted service: https://prerender.io/documentation/desktop-vs-mobile
