### ISSUE TITLE
bug fix for latest chrome (74.0.3729.169)

### ISSUE THREAD

**Issue by smills17** [prerender/prerender#591]
I am using prerender in a dockerfile and I install headless chrome like this

```docker
FROM node:latest
RUN apt-get update -y && apt-get install -y \
    libappindicator1 fonts-liberation libasound2 \
    libatk-bridge2.0-0 libatspi2.0-0 libgtk-3-0 \
    libnspr4 libnss3 libx11-xcb1 libxss1 \
    libappindicator3-1  lsb-release xdg-utils

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome*.deb
```
Which installs chrome version, at the time of writing, 74.0.3729.169

If you use this with the default settings you will get an error:

```2019-05-31T18:36:29.662Z Starting Prerender
2019-05-31T18:36:29.666Z Starting Chrome
2019-05-31T18:36:29.673Z Prerender server accepting requests on port 80
2019-05-31T18:36:29.711Z Chrome connection closed... restarting Chrome
2019-05-31T18:36:29.712Z Chrome died immediately after restart... stopping Prerender
```

The fix is to add the chromeFlag `--no-sandbox` and then it works perfectly fine

so if you change `/lib/browsers/chrome.js` line 29 from:

```javascript
this.chromeChild = spawn(location, this.options.chromeFlags || [ '--headless', '--disable-gpu', '--remote-debugging-port=9222'    , '--hide-scrollbars']);
```
to
```javascript
this.chromeChild = spawn(location, this.options.chromeFlags || ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222'    , '--hide-scrollbars']);
```

then it works just fine on default settings without having to manually add chromeFlags which are not a part of the documentation anyway.

**Comment by thoop** [comment]
I do not recommend adding `--no-sandbox` to the config options since that could cause security issues. This seems to be a problem with running Chrome in docker since we don't see that happen when running outside of docker. I think we need a better solution that turning off the security sandbox.

You might consider trying something like adding a new user with different privileges so that you don't need to pass `--no-sandbox`.
