### ISSUE TITLE
Browser does not cache the resources

### ISSUE THREAD

**Issue by manusis** [prerender/prerender#593]
We are using the prerender default implementation with chrome. We expect the browser to cache the page resources but it does not seem to cache. We tried setting --user-data-dir and --disk-cache-dir directories but still does not work.

We are looking at data from req.prerender.pageLoadInfo.entries which always returns 200. 

"responseParams": {
        "requestId": "1000004125.7",
        "loaderId": "FD93582F85E3D017AAE8540DDF455B43",
        "timestamp": 6638.180447,
        "type": "Script",
        "response": {
          "url": "https://myserver.com/js/abc.js",
          "status": 200,
          "statusText": "",
          "headers": {
            "date": "Tue, 28 May 2019 20:37:18 GMT",
            "content-encoding": "gzip",
            "age": "1507292",
            "x-cache": "Hit from cloudfront",
            "status": "200",
            "content-length": "124991",
            "last-modified": "Mon, 29 Oct 2018 11:18:11 GMT",
            "server": "AmazonS3",
          },

**Comment by thoop** [comment]
We open a new incognito-style context for each browser tab so that they explicitly do not share resources between tabs. This was to prevent issues with Cookies from one tab causing issues with another tab.

I'm not aware of a way to share the browser cache but not share things like Cookies.

**Comment by manusis** [comment]
I do not think two tabs with different host anyway share the resources. Not sure why was the need for the incognito-style context.  

How can we disable that?

**Comment by vesper8** [comment]
@thoop Also curious.. I have a SPA with 40k pages.. pre-caching those pages would be so much faster if the js/css files were shared and not redownloaded every time... is there a way to work around this?

**Comment by victorsilent** [comment]
@thoop any glue to @vesper8 ?

**Comment by 23233** [comment]
@manusis hi ~ have you solved this problem ?

**Comment by manusis** [comment]
We ended up using nginx as reverse proxy with cache for our CDN files. That solved the problem for now.
