### ISSUE TITLE
prerender as a library

### ISSUE THREAD

**Issue by cyberhck** [prerender/prerender#594]
Right now it's only a server and it doesn't really let me do much if I want to use prerender a bit differently,

I wanted to keep chrome headless browser open, render urls each time, I can imagine API looking like this:
```ts
const {Renderer, ChromeHeadless} = require("prerender");
const browser: IBrowser = new ChromeHeadless();
const renderer = new Renderer(browser, {plugins: [
  new ScriptsRemover(),
  new SpecialPlugin()
]});
renderer.render("https://....").then(res => {
  // res is the source of that url
})
```

This way I use prerender as a library

**Comment by thoop** [comment]
I think in that case you might want to look at using https://github.com/GoogleChrome/puppeteer

We built Prerender specifically as a server that takes in a request, renders the page (and lets you modify the behavior some with plugins), and sends back the HTML response. We don't want to change how that works currently.

If you need to use Prerender, you could just run it on it's own local server for your custom plugins and send http requests to the Prerender server as needed.
