### ISSUE TITLE
Request header field x-prerender is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by mixalbl4-127** [prerender/prerender#600]
All cross-domain requests fail with that error:
```
Access to font at 'https://fonts.gstatic.com/s/materialicons/v48/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2' from origin 'xxx' has been blocked by CORS policy: Request header field x-prerender is not allowed by Access-Control-Allow-Headers in preflight response.

Access to script at 'https://connect.facebook.net/en_US/sdk.js?hash=&ua=modern_es6' from origin 'xxx' has been blocked by CORS policy: Request header field x-prerender is not allowed by Access-Control-Allow-Headers in preflight response.
```

How to disable `x-prerender` for 3rd domains?

**Comment by thoop** [comment]
We use https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setExtraHTTPHeaders to set that header on all network requests. If you are using a local Prerender server, you can turn off that plugin by commenting out this line in the server.js:
```
server.use(prerender.sendPrerenderHeader());
```

**Comment by kasperstorgaard** [comment]
@thoop What if you are using prerender.com, is there any option to disable that header there?

**Comment by alexdriaguine** [comment]
@thoop Wondering the same as @kasperstorgaard, what if you use the hosted prerender? Will 3rd party requests work?
