### ISSUE TITLE
Problem with chrome 76?

### ISSUE THREAD

**Issue by vIceBerg** [prerender/prerender#601]
Does anyone have problem with the new Chrome version?

So far, with 76, the page does not render correctly. I somehow downgrade to 75 and it works.

My page is an angular 7 SPA. With chrome 76, the prerender output is the first "Loading..." page, even if it looks like it waits correctly for the page to be loaded.

**Comment by vIceBerg** [comment]
What I discovered is if I do not use the sendPrerenderHeader plug-in, it works...

**Comment by thoop** [comment]
Interesting! I don't see this issue with Chrome 76.

If anyone else runs into this issue, please feel free to add information to this issue so we can look into it.

The `sendPrerenderHeader` plugin just uses `Network.setExtraHTTPHeaders` which is still a valid Chrome command: https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setExtraHTTPHeaders

**Comment by thoop** [comment]
Closing this issue since we haven't run into this again.
