### ISSUE TITLE
Prerender server returns white page 

### ISSUE THREAD

**Issue by spirosdi** [prerender/prerender#602]
hi, I am trying to prerender my react app using the my own deployed prerender server. The server and the app are deployed in Openshift. The server renders other pages (such as google.gr) fine. When trying to render my react app, it returns a white page. The logs when requesting my react app using ?_escaped_fragment_= are:

```
2019-09-11T13:46:04.333Z getting http://uds-product-comparison-production.apps.eu.company.com/vergleich/staubsauger
  | 2019-09-11T13:46:14.607Z got 200 in 10274ms for http://uds-product-comparison-production.apps.eu.company.com/vergleich/staubsauger
  | 2019-09-11T13:46:15.526Z getting favicon.ico
  | 2019-09-11T13:46:15.864Z got 504 in 338ms for favicon.ico

```
The server and the app are in a VPN server, so they are not publicly available. I am using the phantomjs version.

**Comment by thoop** [comment]
Sorry for the delay here! Could you send us an email at support@prerender.io with a new URL so we can help test and see if we can find anything? It looks like that URL is no longer available.
