### ISSUE TITLE
styled-components

### ISSUE THREAD

**Issue by jonbjk** [prerender/prerender#609]
There is a problem with css-in-js libraries, such as styled-components or emotion. These libraries use CSSOM to add styling, so the CSS is not set in the DOM and will therefore not be part of the HTML that prerender sends back, resulting in poor rendering result.

The issue can be be fixed with a small script that extracts the CSS and inject it into the DOM. My problem is that this can not be done with a plugin. The "pageLoaded" event is too late in the process.

I have done a fix on chrome.js that solve the problem. It you are interested I can open a pull request.

**Comment by sbalay** [comment]
Hi @jonbjk, there is a discussion going on about this same issue at #574. Would you mind following up there?

BTW, I'm curious about your solution, is your code upload to a branch where I can take a look?

**Comment by jonbjk** [comment]
Hi @sbalay 
Here is my branch https://github.com/jonbjk/prerender/tree/css_in_js
It is a simple way to dump the css. It work for our use case (styled-components 3.5.x).

I would be happy though with an event just before the HTML is extracted so that I could write a plugin that did the job. The "pageLoaded" is too late.
Something like (untested code):
```
.then(() => {
		return this.firePluginEvent('beforeExtractHTML', req, res);
})
```
At line: https://github.com/prerender/prerender/blob/master/lib/server.js#L239

**Comment by wintercounter** [comment]
With https://www.styled-components.com/docs/api#stylesheetmanager you have to option to `disableCSSOMInjection`

**Comment by jonbjk** [comment]
@wintercounter Only on newer versions of styled-components

**Comment by thoop** [comment]
Let's continue the conversation in #574. Thanks everyone!

**Comment by chr4ss12** [comment]
```
import { StyleSheetManager } from 'styled-components';


    <StyleSheetManager disableCSSOMInjection={(navigator.userAgent.includes('Prerender') || navigator.userAgent.includes('prerender'))}>
      
    </StyleSheetManager>

```
