### ISSUE TITLE
how to stop request type in css image 

### ISSUE THREAD

**Issue by 23233** [prerender/prerender#612]
This library is so cool;

But i'm just use the spa seo;

about seo use small and fast request is good idea;

so,i want to know how stop request;

just like puppeteer :

```
    await page.setRequestInterception(true);
    page.on('request', (request) => {
        // stop it
        if (['image', 'stylesheet', 'font'].indexOf(request.resourceType()) !== -1) {
            request.abort();
        } else {
            request.continue();
        }
    });
```
 
thanks ~

**Comment by yayajacky** [comment]
I think in the chrome_controller.js, we can add 

Network.requestIntercepted(({ interceptionId, request }) => {
  // perform a test against the intercepted request
  const blocked = shallNotPass(request);
  console.log(`- ${blocked ? "BLOCK" : "ALLOW"} ${request.url}`);
  // decide whether allow or block the request
  Network.continueInterceptedRequest({
    interceptionId,
    errorReason: blocked ? "Aborted" : undefined
  });
});

To block files based on the request

function shallNotPass(request) {
  const { pathname } = url.parse(request.url);
  return pathname.match(/\.(css|png|svg|woff2)$/);
}

It would be great to add that into chrome_controller, and adjust it base on a middleware.
Let me know if you are interested, I can PR

**Comment by 23233** [comment]
@yayajacky  yes! just do it !  i'm very  intereste , waiting for you PR !!  thanks you ~

**Comment by yayajacky** [comment]
Here's the branch
https://github.com/yayajacky/prerender/tree/add_browserInterceptorCallback
And the PR:
https://github.com/prerender/prerender/pull/613

You use it by passing browserInterceptorCallback into prerender, 

const server = prerender({
  logBrowserRequests: true,
  browserInterceptorCallback: request => {
    // console.log(request.url);
    if (request.url.indexOf(".css") !== -1) {
      return true;
    }
  }
});

Above would block any request that has .css in the name from loading.
