### ISSUE TITLE
Prerender returns a 502 with Content-Security-Policy-Report-Only

### ISSUE THREAD

**Issue by jamesarosen** [prerender/prerender#615]
We added a [`Content-Security-Policy-Report-Only`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only) header to our site yesterday. When we did, Prerender started returning 502s for most pages.

When I go to those pages in my own browser, I see errors like this in the console:

> Content Security Policy: The page’s settings observed the loading of a resource at … (“img-src”). A CSP report is being sent.

But because we're in report-only mode, the browser is still able to load those assets.

It seems like Prerender might be treating `Content-Security-Policy-Report-Only` the same as `Content-Security-Policy`.

**Comment by thoop** [comment]
This was a different issue not related to Content-Security-Policy headers so I'll close this issue.
