### ISSUE TITLE
Custom screen resolution with nginx proxy configuration

### ISSUE THREAD

**Issue by avg07** [prerender/prerender#620]
Hello. I'm using a local prerender server with nginx reverse proxy, like here: https://gist.github.com/thoop/8165802
How I can use custom screen resolution with reverse proxy in requests, like here https://github.com/prerender/prerender#width?
Thanks

**Comment by thoop** [comment]
That might not be possible with the nginx reverse proxy. You might need to do something more custom with some code that adds the width on the URL before sending the request to the Prerender server.

I'm assuming you'd be trying to pass a different width for desktop vs mobile pages so you'd need something detecting the device type to pass a different width.
