### ISSUE TITLE
Reduce TTL time

### ISSUE THREAD

**Issue by victorsilent** [prerender/prerender#622]
There're something that I can do to reduce the time to load the page?
I have the php application on a server and the node on another
![Screenshot from 2020-01-07 18-10-51](https://user-images.githubusercontent.com/8001358/71929763-19179080-3179-11ea-8233-e3986495cf99.png)

**Comment by thoop** [comment]
Hi there. That is heavily dependent on your website and how it's loading the page. Feel free to send a URL of your website to us at support@prerender.io if you'd like us to take a look and see how you might improve the page render time.
