### ISSUE TITLE
Pass params to the rendered page

### ISSUE THREAD

**Issue by pybuche** [prerender/prerender#628]
Hi !

I'm currently using `prerender` with the Express middleware, and I'd like to be able to treat images I have on my pages differently between the crawler and a normal user.

I'm using an image resizing provider that is triggered via a `<script>` tag, that is not executed while prerendering. This script does one simple thing: replace my `src` attribute in my `<img>` tags with the correctly sized image. 

To have a nice "blur" effect, I prefill the `src` attribute with a low-quality image. 

The problem is: prerender only keeps the low-quality image, making Google see ugly images while crawling my website. 
Is there a way to either:
- Make this script execute
- Pass a parameter to the crawled url so my website doesn't load low-quality images (something like a `window.prerender = true` or a request header)

About the request header, I saw there is a plugin to add a `X-Prerender` header to the request. But since I'm using the Express middleware, I'm not sure I can enable it... 

Thanks !

**Comment by thoop** [comment]
Hi there! You could check for the user agent containing "prerender" in order to execute that script. How are you triggering that script? I would expect that would work properly unless it waits for the image to download before replacing the src tag. Our Prerender server tries not to download the image data since it's usually not needed but that can be modified so that the images are downloaded.

**Comment by pybuche** [comment]
Hi!
I'm so sorry for the very late answer, but thanks anyway!

I know this is not mandatory to display images for Google, but I think in the end, the images that GoogleBot will see will end up in the "images" section, right?
Thus, if all the images are of very poor quality (the blur effect), I will end up having only poor quality images in the image results for my website.

For now, I didn't find a suitable solution for this. What I currently do is that I detect if there is a `prerender` header, and then, I force my images to be at least at a suitable size. This way, Google never sees tiny pics.

Indeed, I'm not exactly sure how this script works, since it's a 3rd-party one, but I'll try to investigate more.

Thanks!

**Comment by thoop** [comment]
Ok, great!
