### ISSUE TITLE
Blocking fonts.googleapis.com can cause cloaking penalties

### ISSUE THREAD

**Issue by cngarkar** [prerender/prerender#633]
Currently blockResources plugin is blocking the fonts.googleapis.com, that means some angular sites who use the material icons(`<link
			href="https://fonts.googleapis.com/icon?family=Material+Icons&display=swap"
			rel="stylesheet"
		/>`) won't get the icons rendered correctly(`undefined` is displayed in place of icon when we don't use fonts from googleapis.com), which can potentially add penalty as google can count it as a cloaking.

Should we remove the google fonts from the blockResources plugin?

**Comment by thoop** [comment]
We've never seen this cause any issues with Google seeing this as cloaking across all of our customers. You can feel free to remove that from the blockResources plugin though if you'd like to load those fonts during your page rendering. Loading those fonts won't cause any problems.
