### ISSUE TITLE
What are these big files Prerender Generates?

### ISSUE THREAD

**Issue by acegilz** [prerender/prerender#634]
I use prerender with prerender-memory-cache addon. Everything is ok, except the fact that today I noticed big part of my disk was being consumed by some strange files on the prerender directory.

```
process.env.CACHE_TTL = 65000;
process.env.CACHE_MAXSIZE = 5000;
process.env.PORT = 1337;

const prerender = require('prerender');
//const server = prerender();
var server = prerender({
  //chromeFlags: ['--no-sandbox', '--headless', '--remote-debugging-port=9222', '--hide-scrollbars']
  chromeFlags: ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars']
});
server.use(require('prerender-memory-cache'))

server.start();
```

<img width="646" alt="Screenshot 2020-04-21 22 35 34" src="https://user-images.githubusercontent.com/4284362/79916326-7087f680-8420-11ea-9918-479746675615.png">

**Comment by thoop** [comment]
It looks like these are core dump files that contain information on a program crashing. If the Prerender server seems to be performing properly, you might want to just turn off the generation of those core dump files upon a program crash unless you are going to be inspecting them the reason for the crash.

You can safely delete those.

https://unix.stackexchange.com/questions/125232/what-is-centos-root-core-files-they-eat-my-hard-disk-till-it-is-full
