### ISSUE TITLE
Not able to close chrome tab using the java script

### ISSUE THREAD

**Issue by SanjuJayakumarNair** [prerender/prerender#635]
i have a bot in a specified URL when i try to close the tab using window.close it throwing an error
"Scripts may close only the windows that were opened by it."so i used window.open(window.location, '_self');window.close the tab is not getting closed instead the page is getting refreshed..can any one please help me out how to close a tab in chrome..

**Comment by thoop** [comment]
Do you mean the website that is being rendered wants to close the tab themselves? Because the Prerender server will close the tab for you so you don't need to make any changes there.

Just looking for some clarification on what you're trying to accomplish.

**Comment by SanjuJayakumarNair** [comment]
i have a chat bot so when i type the word "close" i want to close the tab in chrome using script. can you please help me out.

**Comment by thoop** [comment]
I don't think that's a use case that we like to support. The Prerender server should just be rendering the page to return the HTML content to the crawlers. The tab is then closed automatically after the HTML has been returned.
