### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by xuanlv0703** [prerender/prerender#639]
`8|Prerende |     at IncomingMessage.emit (events.js:208:7)
8|Prerende |     at endReadableNT (_stream_readable.js:1064:12)
8|Prerende |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
8|Prerende |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
8|Prerende | node[10077]: pthread_create: Resource temporarily unavailable
8|Prerende | node[10082]: pthread_create: Resource temporarily unavailable
8|Prerende | SyntaxError: Unexpected end of JSON input
8|Prerende |     at JSON.parse (<anonymous>)
8|Prerende |     at /var/www/prerender/node_modules/chrome-remote-interface/lib/devtools.js:23:33
8|Prerende |     at IncomingMessage.<anonymous> (/var/www/prerender/node_modules/chrome-remote-interface/lib/external-request.js:27:21)
8|Prerende |     at emitNone (events.js:111:20)
8|Prerende |     at IncomingMessage.emit (events.js:208:7)
8|Prerende |     at endReadableNT (_stream_readable.js:1064:12)
8|Prerende |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
8|Prerende |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)

/root/.pm2/logs/Prerender-out-8.log last 15 lines:
8|Prerende |   address: '127.0.0.1',
8|Prerende |   port: 9222 }
8|Prerende | 2020-05-14T08:42:18.575Z got 504 in 31513ms for http://139.198.21.19:9212/pay
8|Prerende | 2020-05-14T08:42:18.877Z { Error: connect EMFILE 127.0.0.1:9222 - Local (undefined:undefined)
8|Prerende |     at internalConnect (net.js:964:16)
8|Prerende |     at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
8|Prerende |     at net.js:1062:9
8|Prerende |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
8|Prerende |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
8|Prerende |   errno: 'EMFILE',
8|Prerende |   code: 'EMFILE',
8|Prerende |   syscall: 'connect',
8|Prerende |   address: '127.0.0.1',
8|Prerende |   port: 9222 }
8|Prerende | 2020-05-14T08:42:18.877Z got 504 in 31815ms for http://139.198.21.19:9212/pay

8|Prerende | 2020-05-14T08:42:19.180Z { Error: connect EMFILE 127.0.0.1:9222 - Local (undefined:undefined)
8|Prerende |     at internalConnect (net.js:964:16)
8|Prerende |     at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
8|Prerende |     at net.js:1062:9
8|Prerende |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
8|Prerende |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
8|Prerende |   errno: 'EMFILE',
8|Prerende |   code: 'EMFILE',
8|Prerende |   syscall: 'connect',
8|Prerende |   address: '127.0.0.1',
8|Prerende |   port: 9222 }
8|Prerende | 2020-05-14T08:42:19.180Z got 504 in 32118ms for http://139.198.21.19:9212/pay
8|Prerende | 2020-05-14T08:42:19.402Z { Error: connect EMFILE 127.0.0.1:9222 - Local (undefined:undefined)
8|Prerende |     at internalConnect (net.js:964:16)
8|Prerende |     at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
`
got this error after run a long time, so now i restart and alway got it.
please help me.
Google Chrome 81.0.4044.138
 server code:

`#!/usr/bin/env node
var prerender = require('./lib');
var server = prerender({
chromeLocation:'/usr/bin/google-chrome-stable',
  chromeFlags: ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars']
});

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
server.use(require('prerender-memory-cache'));

server.start();
`

**Comment by thoop** [comment]
Hmm, I haven't run into this error before. Is there a reason you are using `--no-sandbox`? I wouldn't recommend that and I'm not sure if that might be contributing to this issue.

**Comment by xuanlv0703** [comment]
hmm, i don't know, i think some issue with Ubuntu 14.04.6 LTS (GNU/Linux 3.13.0-042stab140.1 x86_64), take a lot of memory
i had run a same source code in unbuntu 18.04 and everything is oke.
this is error in got in ubuntu 14, free ram 16G
![error5](https://user-images.githubusercontent.com/7371516/82424825-ea5ae080-9aaf-11ea-94c3-97dfd1a79d15.PNG)

**Comment by thoop** [comment]
I'm glad that upgrading to Ubuntu 18 fixed the issues! Thank you for reporting back on that. We will keep an eye out for reports of this error in the future.
