### ISSUE TITLE
Run prerender  as lambda function

### ISSUE THREAD

**Issue by adnanmuttaleb** [prerender/prerender#640]
Hello

Is it possible to run the `prerender` service (not the middleware) as aws's lambda function? 

**Edit:** 

I found tool called [claudia](https://claudiajs.com/tutorials/serverless-express.html) that may handle packaging and distribution of NodeJs app, all you need to do is the follow:

```
// app.listen(3000) // <-- find this line and delete it or comment it out
module.exports = app; // add this line

```

But I think the `server` instance here:

`const server = prerender();`

is not the actual ExpressJs instance so I can not simply export it, I am right? if this is the case, is there an easy way to solve this?

**Comment by thoop** [comment]
I'm not sure if there's an easy way to do this with our Prerender repo, but I haven't tried it. You'd need to provide Chrome already in your lambda and then make the necessary changes to get Prerender to play well with the lambda code setup.

With how long websites usually take to fully render, Lambda might be more expensive than a normal server if you aren't able to re-use the long running chrome instance and start multiple tabs in the same browser like our Prerender server does.

**Comment by adnanmuttaleb** [comment]
@thoop thank you for your time, I thought it might be a cheaper to run as lambda.

**Comment by thoop** [comment]
No worries!
