### ISSUE TITLE
Prerender.io's cached html header getting replaced by static header

### ISSUE THREAD

**Issue by TianrenWang** [prerender/prerender#697]
I have a Heroku app that I added a namecheap domain (https://www.platonic.chat/) to. I recently added SEO to the app using Prerender.io, so particular pages on the app have dynamic link preview. However, the namecheap domain does not display the desired dynamic link preview. I can see on my Prerender.io dashboard that it cached the pages correctly, but somehow the `<meta>` tags of the cached htmls got replaced by the `<meta>` tags of the static index.html when the cached htmls get fetched.

Another observation is that the Heroku domain that doesn't use namecheap (https://platonic-prod.herokuapp.com/) doesn’t have this problem. In the Heroku domain (https://platonic-prod.herokuapp.com/c/welcome-to-platonic), the desired title meta tag is:
```
<meta property=“og:title” content=“Welcome to Platonic”>
.
.
.
```

But in the namecheap domain (https://www.platonic.chat/c/welcome-to-platonic), the title meta tag is:
```
<meta property=“og:title” content=“Platonic”>
.
.
.
```
The body of the Prerender.io fetched html in both cases are the same, so it seems to me that something is replacing the header of cached html. The link preview gives the incorrect result when I use Facebook Debugger and metatags.io, but it gives the correct result when I use Googlebot through command line `curl -A Googlebot https://www.example.com/` and displays properly on Discord. So why does adding a namecheap domain to a Heroku app modifies the cached html when it gets fetched?

I am using ExpressJS middleware for Prerender.io, caching Angular pages.

**Comment by TianrenWang** [comment]
The following is my app.js file that generates the express app:
```
const express = require('express');
const path = require('path');
const logger = require('morgan');
const cors = require('cors');
const passport = require('passport');
const errorMiddleware = require('./middleware/error');
const config = require('./config');

// import routes
const userRoutes = require('./routes/user');
const messageRoutes = require('./routes/message');
const channelRoutes = require('./routes/channel');
const subscriptionRoutes = require('./routes/subscription');
const twilioRoutes = require('./routes/twilio');
const emailRoutes = require('./routes/email');
const webpushRoutes = require('./routes/webpush');

// initialize the app
const app = express();

app.use(require('prerender-node').set('prerenderToken', process.env.PRERENDER_TOKEN));

// middleware
app.use(cors());
app.use(logger('dev'));
app.use(express.json({limit: '25mb'}));
app.use(express.urlencoded({limit: '25mb', extended: true}));
app.use(passport.initialize());
require('./config/passport').normal_authentication(passport);
var distDir = __dirname + "/dist/";
app.use(express.static(distDir));

// static folder
app.use(config.root, express.static(path.join(__dirname, 'public')));

// set routes
app.use(`${config.apiPath}/users`, userRoutes);
app.use(`${config.apiPath}/messages`, messageRoutes);
app.use(`${config.apiPath}/channels`, channelRoutes);
app.use(`${config.apiPath}/twilio`, twilioRoutes);
app.use(`${config.apiPath}/email`, emailRoutes);
app.use(`${config.apiPath}/subscription`, subscriptionRoutes);
app.use(`${config.apiPath}/webpush`, webpushRoutes);

// set error handling middleware
app.use(errorMiddleware);

app.get('*', (req, res) => {
  res.sendFile(path.join(distDir, 'index.html'));
});

module.exports = app;
```
Please let me know if you need more information.

**Comment by ym** [comment]
Hi Tianren,

I noticed that `og:tittle` part is updated dynamically by your Angular code, please set `window.prerenderReady = false;` then set `window.prerenderReady` to `true` after the part is updated.

For more details, please check the page below:

https://docs.prerender.io/article/11-best-practices

Regards,
Siyuan

**Comment by TianrenWang** [comment]
I set the index.html file to the following:
```
<!doctype html>
<html>
<head>
  <script>window.prerenderReady = false;</script>
  <meta charset="utf-8">
  <title>Platonic</title>
  <base href="/">

  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://www.platonic.chat/">
  <meta property="og:title" content="Platonic">
  <meta property="og:description" content="Platform for having thoughtful conversations that can be shared.">
  <meta property="og:image" content="https://platonic-dev.s3.ca-central-1.amazonaws.com/channel-photo/60745b1ea686c400172d449d.jpg">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/loader.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&amp;display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="manifest" href="manifest.webmanifest">
  <meta name="theme-color" content="#1976d2">
</head>

<body>

  <app-root>
    <div class="container-fluid text-center loader-container">
      <div class="loader">
      </div>
    </div>
  </app-root>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="..." crossorigin="anonymous"></script>
  <noscript>Please enable JavaScript to continue using this application.</noscript>
</body>
</html>
```
And in my Angular component, I added the following line after dynamically updating the meta tag: `window['prerenderReady'] = true;`

I am still experiencing the same issue.

**Comment by Golyo88** [comment]
I checked your page and in the debug console the window.prerenderReady is undefined...

**Comment by TianrenWang** [comment]
@Golyo88 I updated the code. It should now have `window.prerenderReady`.

**Comment by Golyo88** [comment]
@TianrenWang 
on both pages (https://www.platonic.chat/ and https://platonic-prod.herokuapp.com/) window.prerenderReady is false!

**Comment by Golyo88** [comment]
Yes, I can see that.
In the developer console I added a breakpoint to the part where you set it to true and checked what happens.

This code runs and stops at the break point if the user agent is the default. (browser user agent). And it looks OK.
Although when you change the user agent to e.g.: Googlebot that part of the code not runs! The code is not changing the og metatags and the prerenderReady flag is not set either... 

[Here ](https://developer.chrome.com/docs/devtools/device-mode/override-user-agent/) is the docs on how can you change the user agent in chrome.

**Comment by TianrenWang** [comment]
I am closing this issue because I no longer have this problem after transferring my domain from namecheap to godaddy.
