### ISSUE TITLE
Prerender with CloudFront not working as expected... 

### ISSUE THREAD

**Issue by boogiekim** [prerender/prerender#796]
<img width="1020" alt="Screenshot 2024-07-23 at 1 31 45 PM" src="https://github.com/user-attachments/assets/5a48b1de-9672-4644-abda-64c55508ee40">

Example of what shows up when I run `curl -A "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" and save to output, then open the output.html file in browser. 

Set up is CloudFront w 2 lambda@edge function associations as so: 

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/c521e2fc-8d42-4bb7-b3c3-270b580dffc7">

Any ideas or insight as to what is wrong?

**Comment by pduggi-cf** [comment]
@boogiekim How did you fix this?
