### ISSUE TITLE
window.prerenderReady doesn't seem to work

### ISSUE THREAD

**Issue by lukezheng** [prerender/prerender#85]
Some of my Angular.js pages requires extra ajax requests, so I added

window.prerenderReady = false; 

to my index.html and set

window.prerenderReady = true;

in my angularjs controllers when ajax calls have completed.  However, the resulting page still isn't cached properly even though the caching takes much longer time vs not setting window.prerenderReady.

If i access my pages directly, I can clearly see

window.prerenderReady 

being set to false in the beginning.  Before it's set to true, the bindings I intended have been bound to the html.

Could anyone help out?

**Comment by stewones** [comment]
+1 same here. email sent @thoop 
hope you can help. thx.

**Comment by gytisgreitai** [comment]
I would like to clarify one thing. From the documentation:
> When we see window.prerenderReady set to false, we'll wait until it's set to true to save the HTML. 

though looking at prerender source code, it seems that prerender waits for all requests to finish, and only then starts checking if prerenderReady is set to true.

Am i correct?

**Comment by thoop** [comment]
Correct. We only use window.prerenderReady as a signal to tell us to wait longer than usual and you cannot use it to make us save the page earlier than we normally would. This might change in the future to make it work both ways but that's how it currently works.

**Comment by samvloeberghs** [comment]
@thoop just to check, has the behaviour you described in your latest comment been implemented in any way or not?

**Comment by thoop** [comment]
window.prerenderReady is still just a signal to tell us to wait longer and is used in combination with waiting for all ajax calls to complete. We do not currently have a way to force the page to complete before all ajax calls are complete. Sorry for the inconvenience!

**Comment by ccqgithub** [comment]
how can i do with the issue ???

**Comment by thoop** [comment]
If you set pageDoneCheckTimeout to a very large number then of course the page won't complete because you are never executing the check to see if the page is done loading. window.prerenderReady is working as expected.

**Comment by dingyuliang** [comment]
@ccqgithub, I have built a project which is to solve AJAX call & Timeout in both jQuery & AngularJS.
It may be helpful for you.
Please see https://github.com/dingyuliang/prerenderready-javascript

**Comment by ccqgithub** [comment]
@thoop  why not use a signal to tell that the page is ready and can response 200 ? when the page load, we set the signal false to wait for response, until it is be set to true agin ...before your explain, i think window.prerenderReady is do that thing...

**Comment by dingyuliang** [comment]
Definitely, we can use window.prerenderReady to solve the problem, but with the default window.prerenderReady, there are several things it can't solve efficiently

1. I have too many AJAX calls in my existing project. It's very difficult to change one by one.

2. I have another AJAX call inside an AJAX call.

3. I have timeout.


So, I have built a plugin https://github.com/dingyuliang/prerenderready-javascript, which we don't need to change any existing code. It will automatically check all AJAX calls.

[https://avatars0.githubusercontent.com/u/5062690?v=3&s=400]<https://github.com/dingyuliang/prerenderready-javascript>

dingyuliang/prerenderready-javascript<https://github.com/dingyuliang/prerenderready-javascript>
github.com
prerenderready-javascript - The project provides the functionality to track ajax call and settimeout for window.prerenderReady of prerender.io within jQuery application and angularJS 1.X application.




________________________________

**Comment by thoop** [comment]
Cool! The Prerender server already counts all requests in flight (all requests, not just ajax) and then saves the page a short time after that number reaches zero. So counting all ajax calls in the javascript as well might be a little overboard.

**Comment by dingyuliang** [comment]
Thank you very  much. 
When I was testing last month, I hosted Prerender.io service on my  local, it didn't do like this. 
I agree if Prerender Server already does this, we don't this any JavaScript level logic.

**Comment by ansaries** [comment]
hi @thoop,
I am working on a Meteorjs project where the server calls are mostly through websockets instead of ajax/http. 
I am seeing that some of my pages are rendering properly and some are cached before the window.prerenderReady is set to true

please review http://foctest.meteorapp.com/service/Helper-or-Maid/Dubai?_escaped_fragment_= (not rendered and cached properly)

also review http://foctest.meteorapp.com/p/auntest130?_escaped_fragment_= (which takes more time yet is rendered properly)

**Comment by thoop** [comment]
@ansaries Looks like it's rendering correctly when I test it against our service directly, so it looks like that could have been a timing issue where the page took too long to load. Try recaching that page and see if it looks better. If so, then you'll want to make sure your pages are loading correctly before they timeout.

**Comment by thoop** [comment]
Locking this conversation as it's become a dumping ground for issues. Please create a new issue or email us at support@prerender.io. Thanks!
