### ISSUE TITLE
Timeout on heroku server

### ISSUE THREAD

**Issue by AlexCppns** [prerender/prerender#87]
I am getting timeouts on my test server on heroku:

'Timed out. Sending request with HTML on the page'

I am guessing it cannot find the cached version. I am using the same S3 credentials as our platform servers so it should work.

**Comment by tobias74** [comment]
Same here. It seems to me that static angularJS-Apps are rendered correctly, but as soon as some $http- or $resource-Request comes into play, the timeout occurs.

**Comment by thoop** [comment]
we use $http on https://prerender.io and our pages render correctly. Can you email me the URL that you're testing so I can check things out? Thanks!

**Comment by ericraio** [comment]
anyone fix this?

**Comment by thoop** [comment]
@ericraio can you send me an email at todd@prerender.io? If you're seeing any issues, I'm happy to dig into your specific problem and help fix it. Usually these aren't any problems with our server but with how the website might be set up.
